UPDATE Maps SET GridWidth = GridWidth + 2
WHERE MapSizeType IN ('MAPSIZE_DUEL', 'MAPSIZE_ZYL_RVC_4', 'MAPSIZE_TINY', 'MAPSIZE_SMALL', 'MAPSIZE_STANDARD', 'MAPSIZE_LARGE', 'MAPSIZE_HUGE', 'MAPSIZE_ZYL_RVC_16', 'MAPSIZE_ZYL_RVC_18');
