--开启JNR的Savannah地貌后万神改动
--Pantheon 芦苇和沼泽地里的夫人：平原泛滥平原提供+1食物,草原泛滥平原提供+1生产力。草本沼泽提供+2生产力和+1科技值。
-- update Modifiers set SubjectRequirementSetId = 'PLOT_HAS_MARSH_REQUIREMENTS' where ModifierId = 'LADY_OF_THE_REEDS_PRODUCTION2_MODIFIER';
-- update ModifierArguments set Value = 2 where ModifierId = 'LADY_OF_THE_REEDS_PRODUCTION2_MODIFIER' and Name = 'Amount';
-- insert or replace into BeliefModifiers
-- 	(BeliefType,							            ModifierID)
-- values
-- 	('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES',			'LADY_OF_THE_FLOODPLAINS_GRASSLAND_PRODUCTION'),
--     ('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES',			'LADY_OF_THE_FLOODPLAINS_PLAINS_FOOD');

-- insert or replace into Modifiers
-- 	(ModifierId,														ModifierType,										SubjectRequirementSetId)
-- values
-- 	('LADY_OF_THE_FLOODPLAINS_GRASSLAND_PRODUCTION',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
-- 	('LADY_OF_THE_FLOODPLAINS_GRASSLAND_PRODUCTION_MODIFIER',			'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'HD_PLOT_HAS_FEATURE_FLOODPLAINS_GRASSLAND'),
-- 	('LADY_OF_THE_FLOODPLAINS_PLAINS_FOOD',								'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
-- 	('LADY_OF_THE_FLOODPLAINS_PLAINS_FOOD_MODIFIER',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'HD_PLOT_HAS_FEATURE_FLOODPLAINS_PLAINS');

-- insert or ignore into ModifierArguments
-- 	(ModifierId,													Name,				Value)
-- values
-- 	('LADY_OF_THE_FLOODPLAINS_GRASSLAND_PRODUCTION',				'ModifierId',		'LADY_OF_THE_FLOODPLAINS_GRASSLAND_PRODUCTION_MODIFIER'),
-- 	('LADY_OF_THE_FLOODPLAINS_GRASSLAND_PRODUCTION_MODIFIER',		'YieldType',		'YIELD_PRODUCTION'),
-- 	('LADY_OF_THE_FLOODPLAINS_GRASSLAND_PRODUCTION_MODIFIER',		'Amount',			1),
-- 	('LADY_OF_THE_FLOODPLAINS_PLAINS_FOOD',							'ModifierId',		'LADY_OF_THE_FLOODPLAINS_PLAINS_FOOD_MODIFIER'),
-- 	('LADY_OF_THE_FLOODPLAINS_PLAINS_FOOD_MODIFIER',				'YieldType',		'YIELD_FOOD'),
-- 	('LADY_OF_THE_FLOODPLAINS_PLAINS_FOOD_MODIFIER',				'Amount',			1);

-- update Beliefs set Description = 'LOC_BELIEF_LADY_OF_THE_REEDS_AND_MARSHES_SAVANNAH_DESCRIPTION' where BeliefType = 'BELIEF_LADY_OF_THE_REEDS_AND_MARSHES';
-- update Beliefs set Description = 'LOC_BELIEF_LADY_OF_THE_REEDS_AND_MARSHES_SAVANNAH2_DESCRIPTION' where BeliefType = 'BELIEF_LADY_OF_THE_REEDS_AND_MARSHES' 
-- and exists (select FeatureType from Features where FeatureType = 'FEATURE_HD_SWAMP'); 

--Pantheon 荒原先驱:沙漠泛滥平原和绿洲提供+2生产力，稀树草原提供+1食物和+1生产力。
-- New Pantheon pathfinder of the waste land
-- insert or replace into Types
-- 	(Type,											Kind)
-- values
-- 	('BELIEF_PATHFINDER_OF_THE_WASTELAND',		    'KIND_BELIEF');

-- insert or replace into Beliefs
-- 	(BeliefType,									Name,													Description,														BeliefClassType)
-- values
-- 	('BELIEF_PATHFINDER_OF_THE_WASTELAND',		    'LOC_BELIEF_PATHFINDER_OF_THE_WASTELAND_NAME',		    'LOC_BELIEF_PATHFINDER_OF_THE_WASTELAND_DESCRIPTION',		        'BELIEF_CLASS_PANTHEON');

-- insert or replace into BeliefModifiers
-- 	(BeliefType,							        ModifierID)
-- values
	-- ('BELIEF_PATHFINDER_OF_THE_WASTELAND',			'PATHFINDER_OF_THE_WASTELAND_OASIS_PRODUCTION2'),
    -- ('BELIEF_PATHFINDER_OF_THE_WASTELAND',			'PATHFINDER_OF_THE_WASTELAND_FLOODPLAINS_PRODUCTION2'),
    -- ('BELIEF_PATHFINDER_OF_THE_WASTELAND',			'PATHFINDER_OF_THE_WASTELAND_SAVANNAH_YIELD');

-- insert or replace into Modifiers
-- 	(ModifierId,															ModifierType,										SubjectRequirementSetId)
-- values
	-- ('PATHFINDER_OF_THE_WASTELAND_OASIS_PRODUCTION2',						'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	-- ('PATHFINDER_OF_THE_WASTELAND_OASIS_PRODUCTION2_MODIFIER',				'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'HD_PLOT_HAS_FEATURE_OASIS'),
	-- ('PATHFINDER_OF_THE_WASTELAND_FLOODPLAINS_PRODUCTION2',					'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	-- ('PATHFINDER_OF_THE_WASTELAND_FLOODPLAINS_PRODUCTION2_MODIFIER',		'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'HD_PLOT_HAS_FEATURE_FLOODPLAINS'),
	-- ('PATHFINDER_OF_THE_WASTELAND_SAVANNAH_YIELD',							'MODIFIER_ALL_CITIES_ATTACH_MODIFIER',				'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
  --   ('PATHFINDER_OF_THE_WASTELAND_SAVANNAH_YIELD_MODIFIER',					'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD',		'HD_PLOT_HAS_FEATURE_JNR_SAVANNAH');

-- insert or ignore into ModifierArguments
-- 	(ModifierId,															Name,				Value)
-- values
	-- ('PATHFINDER_OF_THE_WASTELAND_OASIS_PRODUCTION2',						'ModifierId',		'PATHFINDER_OF_THE_WASTELAND_OASIS_PRODUCTION2_MODIFIER'),
	-- ('PATHFINDER_OF_THE_WASTELAND_OASIS_PRODUCTION2_MODIFIER',				'YieldType',		'YIELD_PRODUCTION'),
	-- ('PATHFINDER_OF_THE_WASTELAND_OASIS_PRODUCTION2_MODIFIER',				'Amount',			2),
	-- ('PATHFINDER_OF_THE_WASTELAND_FLOODPLAINS_PRODUCTION2',					'ModifierId',		'PATHFINDER_OF_THE_WASTELAND_FLOODPLAINS_PRODUCTION2_MODIFIER'),
	-- ('PATHFINDER_OF_THE_WASTELAND_FLOODPLAINS_PRODUCTION2_MODIFIER',		'YieldType',		'YIELD_PRODUCTION'),
	-- ('PATHFINDER_OF_THE_WASTELAND_FLOODPLAINS_PRODUCTION2_MODIFIER',		'Amount',			2),
	-- ('PATHFINDER_OF_THE_WASTELAND_SAVANNAH_YIELD',							'ModifierId',		'PATHFINDER_OF_THE_WASTELAND_SAVANNAH_YIELD_MODIFIER'),
	-- ('PATHFINDER_OF_THE_WASTELAND_SAVANNAH_YIELD_MODIFIER',					'YieldType',		'YIELD_FOOD,YIELD_PRODUCTION'),
	-- ('PATHFINDER_OF_THE_WASTELAND_SAVANNAH_YIELD_MODIFIER',					'Amount',			'1,1');