insert or replace into EnglishText
    (Tag,                                                               Text)
values
    ("LOC_DISTRICT_SAVANNAH_GOLD",					                    "+{1_num} [ICON_Gold] Gold from the adjacent Savannah tile(s)."),
    ("LOC_SAVANNAH_AND",                                                "Savannah, "),
    ("LOC_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION",                      "All Districts (except City Centers) do not remove Forest, Rainforest, Savannah and Marsh. Receive the following yields for every building and Districts itself on these features: +2 [ICON_Production] Production in Forest, +2 [ICON_Food] Food in Rainforest, +2 [ICON_Science] Science in Marsh, +2 [ICON_Culture] Culture in Swamp and +2 [ICON_Faith] Faith in Savannah. Woods can be planted with the Mysticism civic."),
    ("LOC_TRAIT_CIVILIZATION_MAORI_MANA_DESCRIPTION",                   "Begin the game with the Sailing and Shipbuilding technologies unlocked and with the ability to enter Deep Ocean tiles. Embarked units gain +2 [ICON_Movement] Movement. Rainforest, Savannah and Marsh gain +1 [ICON_PRODUCTION] Production, and Woods and Swamp gain +1 [ICON_FOOD] Food after progressing 'Astrology' Technology. Fishing Boats provide +1 [ICON_FOOD] Food and a Culture Bomb to adjacent tiles."),
    ("LOC_TECH_MINING_HD_DESCRIPTION",                                  "Allows chopping of Woods, Savannah and Rainforest, and harvesting of resources improved by Mines."),
	("LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",						        "Extra +1 [ICON_Production] Production if built on features after researching Archery Technology (obsolete with Medieval Faires Civic). [NEWLINE][NEWLINE]Can only be built on valid Resources or Savannah. Once Archery is unlocked it can also be built on Forests. Once Guilds is unlocked it can also be built on Rainforest."),
    ("LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",					        "+1 [ICON_PRODUCTION] Production and +0.5 [ICON_HOUSING] Housing. +1 [ICON_PRODUCTION] Production for every adjacent Plantation, +1 [ICON_FOOD] Food for every 2 adjacent Hacienda, additional [ICON_PRODUCTION] Production and [ICON_FOOD] Food as you advance through the Civics and Technology Tree. Plantation receives +1 [ICON_PRODUCTION] Production for every 2 adjacent Haciendas, with extra +2 [ICON_GOLD] Gold after researching 'Banking' Technology. Can only be built on Rainforests, Savannahs, Plains, Plains Hills, Grassland , Grassland Hills and Swamps."),
    ("LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",					        "+1 [Icon_Production] Production. Provides [ICON_CULTURE] Culture equal to 100% of the tile's Appeal. Can only be built on Charming or Breathtaking tiles. Can be built on Woods, Savannah and Swamp."),
    ("LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",						        "+2 [ICON_Faith] Faith and +1 [ICON_Food] Food. Extra +2 [ICON_Faith] Faith and +1 [ICON_Food] Food if built on non-Floodplains Desert tiles. Nubian Pyramid receives corresponding yield from different districts. Yields from being adjacent to these districts are doubled after progressing 'Feudalism' Civic. Can only be built on Savannah, Plains, Grass and Desert (including Hills and Floodplains)."),
    ("LOC_IMPROVEMENT_CVS_BERBER_UI_DESCRIPTION",                       "+1 [ICON_HOUSING] Housing, +1 extra [ICON_HOUSING] Housing after researching 'Engineering' Technology, +1 extra [ICON_HOUSING] Housing after researching 'Apprenticeship' Technology. +1 [ICON_FOOD] Food to adjacent resources, extra +1 [ICON_PRODUCTION] Production after researching 'Engineering' Technology. Provides +2 [ICON_FOOD] to adjacent Aqueduct and +2 [ICON_PRODUCTION] Production adjacency bonus to Industial Zone. Cannot be worked. Can only be built on flat lands not adjacent to another Foggara. Can be built on Hills and Floodplains after researching 'Iron Working' Technology."),
    ("LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",						        "+1 [ICON_PRODUCTION] Production, +2 [ICON_GOLD] Gold and +1 [ICON_HOUSING] Housing. +1 [ICON_FOOD] Food for every adjacent Bonus resource, +1 [ICON_PRODUCTION] Production for every adjacent Luxury or Strategic resource. Additional [ICON_PRODUCTION] Production, [ICON_FOOD] Food and [ICON_HOUSING] Housing as you advance through the Civics and Technology Tree. Must be built adjacent to a Bonus or Luxury resource. Can be built on Woods, Savannah and Swamp after researching 'Mining' Technology. Cannot be built adjacent to another Mekewap."),
    ("LOC_BUILDING_PETRA_DESCRIPTION",                                  "+3 [ICON_Food] Food, +2 [ICON_Gold] Gold, and +1 [ICON_Production] Production to all non-Floodplains and non-Savannahs Desert tiles within 5 tiles. Must be built on Desert tiles (including Mountain and Floodplains).");

-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                Text)
values
    ("zh_Hans_CN",  "LOC_FEATURE_JNR_SAVANNAH_NAME",                                    "稀树草原"),
    ("zh_Hans_CN",  "LOC_FEATURE_JNR_BURNING_SAVANNAH_NAME",                            "正在燃烧的稀树草原"),
    ("zh_Hans_CN",  "LOC_FEATURE_JNR_BURNT_SAVANNAH_NAME",                              "烧毁的稀树草原"),
    ("zh_Hans_CN",  "LOC_DISTRICT_JNR_SAVANNAH_FAITH",                                  "+{1_num} [ICON_Faith] 信仰值来自相邻的稀树草原。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_SAVANNAH_GOLD",                                       "+{1_num} [ICON_Gold] 金币来自相邻的稀树草原。"),
    ("zh_Hans_CN",  "LOC_SAVANNAH_AND",                                                 "稀树草原、"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_VIETNAM_DESCRIPTION",                       "所有区域（除市中心外）不移除树林、雨林、稀树草原、沼泽地貌。建在这些区域中的建筑以及区域本体和奇观将获得以下收益：建在树林上提供+2 [ICON_Production] 生产力、建在雨林上提供+2 [ICON_Food] 食物、建在草本沼泽上提供+2 [ICON_Science] 科技值、建在木本沼泽上提供+2 [ICON_CULTURE] 文化值、建在稀树草原上提供+2 [ICON_FAITH] 信仰值。拥有“神秘主义”市政后即可栽种树林。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_MAORI_MANA_DESCRIPTION",                    "游戏初始便解锁“航行”与“造船术”科技，同时拥有进入深海单元格的能力。水运单位+2 [ICON_Movement] 移动力。解锁“占星术”后，雨林、稀树草原和草本沼泽提供+1 [ICON_PRODUCTION] 生产力，森林和木本沼泽提供+1 [ICON_FOOD] 食物。渔船提供+1 [ICON_FOOD] 食物，并向相邻单元格投放文化炸弹。"),
    ("zh_Hans_CN",  "LOC_TECH_MINING_HD_DESCRIPTION",                                   "允许砍伐树林、雨林、稀树草原和收获由矿山改良的资源。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",						        "研究“箭术”科技后，若建造在地貌上，额外+1 [ICON_Production] 生产力（中世纪集市后失效）。[NEWLINE][NEWLINE]只能在有效资源和稀树草原上建造。解锁“弓箭”科技后也可建造在森林上。解锁“公会”市政后也可建造在雨林上。"),
    ("zh_Hans_CN",	"LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",						        "+1 [ICON_PRODUCTION] 生产力、+0.5 [ICON_HOUSING] 住房。每相邻1个种植园+1 [ICON_PRODUCTION] 生产力，每相邻2个大庄园+1 [ICON_FOOD] 食物，随着科技与市政的研究，还将提供更多 [ICON_FOOD] 食物和 [ICON_PRODUCTION] 生产力。种植园每相邻2个大庄园+1 [ICON_PRODUCTION] 生产力，解锁“银行业”科技后额外+2 [ICON_GOLD] 金币。[NEWLINE][NEWLINE]只能建造在雨林、稀树草原、平原、平原丘陵、草原和草原丘陵或木本沼泽上。"),
    ("zh_Hans_CN",	"LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",					        "+1 [Icon_Production] 生产力。提供等同于所在单元格魅力100%的 [ICON_CULTURE] 文化值。[NEWLINE][NEWLINE]只能建造在迷人或惊艳魅力的单元格上。可以建造在森林、稀树草原或木本沼泽上。"),
    ("zh_Hans_CN",	"LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",						        "+1 [ICON_Food] 食物、+2 [ICON_Faith] 信仰值。如果建造在沙漠单元格（非泛滥平原或稀树草原），额外+2 [ICON_Food] 食物和 [ICON_Faith] 信仰值。获得相邻区域的对应产出；解锁“封建主义”市政后，这些产出翻倍。[NEWLINE][NEWLINE]只能建造在稀树草原、沙漠、草原或平原以及对应的丘陵或泛滥平原上。"),
    ("zh_Hans_CN",  "LOC_IMPROVEMENT_CVS_BERBER_UI_DESCRIPTION",                        "+1 [ICON_HOUSING] 住房，解锁“工程”科技后额外+1 [ICON_HOUSING] 住房，解锁“学徒”科技后额外+1 [ICON_HOUSING] 住房。为相邻资源+1 [ICON_FOOD] 食物，解锁“工程”科技后额外+1 [ICON_PRODUCTION] 生产力。为相邻水渠+2 [ICON_FOOD] 食物，为工业区提供+2 [ICON_PRODUCTION] 生产力相邻加成。不能在此单元格工作。[NEWLINE][NEWLINE]只能建造在平坦单元格，且不能相邻另一个柏柏尔井渠。解锁“炼铁术”科技后，允许修建在泛滥平原和丘陵上。"),
    ("zh_Hans_CN",	"LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",						        "+1 [ICON_PRODUCTION] 生产力、+2 [ICON_GOLD] 金币、+1 [ICON_HOUSING] 住房。每相邻1个加成资源+1 [ICON_FOOD] 食物，每相邻1个奢侈或战略资源+1 [ICON_PRODUCTION] 生产力。随着科技与市政的研究，还将提供更多 [ICON_FOOD] 食物、[ICON_PRODUCTION] 生产力和 [ICON_HOUSING] 住房。[NEWLINE][NEWLINE]必须建在与加成或奢侈资源相邻的单元格上。解锁“采矿”科技后可以建造在森林、稀树草原与木本沼泽上。无法建在另一个棚屋旁。"),
    ("zh_Hans_CN",	"LOC_BUILDING_PETRA_DESCRIPTION",						            "5个单元格内的所有沙漠单元格（非泛滥平原或稀树草原）+3 [ICON_Food] 食物、+1 [ICON_Production] 生产力和+2 [ICON_Gold] 金币。[NEWLINE][NEWLINE]必须建在沙漠单元格（包括山脉和泛滥平原）。");