insert or replace into EnglishText
	(Tag,															    Text)
values
  ("LOC_GREAT_PERSON_INDIVIDUAL_MAO_YAN_SHOU_HD_NAME", "Mao Yanshou"),
  ("LOC_GREATWORK_MAO_YAN_SHOU_HD_1_NAME", "Portrait of a Beautiful Woman"),
  ("LOC_GREATWORK_MAO_YAN_SHOU_HD_2_NAME", "Portrait of Wang Zhaojun"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_CAO_BU_XING_HD_NAME", "Cao Buxing"),
  ("LOC_GREATWORK_CAO_BU_XING_HD_1_NAME", "The Dunhuang Wall Paintings: The Story of the Monk Kang Senghui's Establishment of the Dharma in Jianye"),
  ("LOC_GREATWORK_CAO_BU_XING_HD_2_NAME", "Portraits of Buddha on Hanging Scrolls"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_GU_KAI_ZHI_HD_NAME", "Gu Kaizhi"),
  ("LOC_GREATWORK_GU_KAI_ZHI_HD_1_NAME", "The Picture of the Luo Shen Fu, Part One"),
  ("LOC_GREATWORK_GU_KAI_ZHI_HD_2_NAME", "The Picture of the Luo Shen Fu, Part Two"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_DAI_KUI_HD_NAME", "Dai Kui"),
  ("LOC_GREATWORK_DAI_KUI_HD_1_NAME", "The Amitabha Buddha in the Shape of a Giant Buddha Statue"),
  ("LOC_GREATWORK_DAI_KUI_HD_2_NAME", "Statue of the Jade Buddha"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_ZHANG_SENG_YAO_HD_NAME", "Zhang Sengyao"),
  ("LOC_GREATWORK_ZHANG_SENG_YAO_HD_1_NAME", "The True Shape of the Twenty-Eight Constellations"),
  ("LOC_GREATWORK_ZHANG_SENG_YAO_HD_2_NAME", "The Immortal's Tower and Pavilion"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_PHEIDIAS_HD_NAME", "Phidias"),
  ("LOC_GREATWORK_PHEIDIAS_HD_1_NAME", "Portrait of Athena"),
  ("LOC_GREATWORK_PHEIDIAS_HD_2_NAME", "Athena in Armor"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_MYRON_HD_NAME", "Myron"),
  ("LOC_GREATWORK_MYRON_HD_1_NAME", "The Discus Thrower"),
  ("LOC_GREATWORK_MYRON_HD_2_NAME", "Athena and Marsyas"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_POLYCLITUS_HD_NAME", "Polyclitus"),
  ("LOC_GREATWORK_POLYCLITUS_HD_1_NAME", "The Spear-Bearer"),
  ("LOC_GREATWORK_POLYCLITUS_HD_2_NAME", "The Canon"),
  ("LOC_GREATWORK_POLYCLITUS_HD_2_QUOTE", "The Canon presents the standard ratio of body length to head as 7:1, and discusses the ideal mathematical proportions for human sculpture, as well as the balance, natural harmony, and standards for relaxation and tension."),
  ("LOC_GREAT_PERSON_INDIVIDUAL_ZHAN_ZI_QIAN_HD_NAME", "Zhan Ziqian"),
  ("LOC_GREATWORK_ZHAN_ZI_QIAN_HD_1_NAME", "The Spring Outing Picture"),
  ("LOC_GREATWORK_ZHAN_ZI_QIAN_HD_2_NAME", "The Transmission of the Sutra Picture"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_WU_DAO_ZI_HD_NAME", "Wu Daozi"),
  ("LOC_GREATWORK_WU_DAO_ZI_HD_1_NAME", "The Portrait of the God of Children"),
  ("LOC_GREATWORK_WU_DAO_ZI_HD_2_NAME", "The Scroll of the Eighty-Seven Immortals"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_YANG_HUI_ZHI_HD_NAME", "Yang Huizhi"),
  ("LOC_GREATWORK_YANG_HUI_ZHI_HD_1_NAME", "The Reclining Arhat"),
  ("LOC_GREATWORK_YANG_HUI_ZHI_HD_2_NAME", "The Dharma Arhat"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_JING_HAO_HD_NAME", "Jing Hao"),
  ("LOC_GREATWORK_JING_HAO_HD_1_NAME", "The Picture of Mount Kwanglu"),
  ("LOC_GREATWORK_JING_HAO_HD_2_NAME", "The Snowy Landscape"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_ZHANG_ZE_DUAN_HD_NAME", "Zhang Zeduan"),
  ("LOC_GREATWORK_ZHANG_ZE_DUAN_HD_1_NAME", "Along the River During the Qingming Festival"),
  ("LOC_GREATWORK_ZHANG_ZE_DUAN_HD_2_NAME", "The Contest for the Banner at Jinming Pool"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_LI_TANG_HD_NAME", "Li Tang"),
  ("LOC_GREATWORK_LI_TANG_HD_1_NAME", "The Picture of Picking Wei"),
  ("LOC_GREATWORK_LI_TANG_HD_2_NAME", "The Pine Wind in Ten Thousand Valleys"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_ZHAO_MENG_FU_HD_NAME", "Zhao Mengfu"),
  ("LOC_ZHAO_MENG_FU_ARTIST_GREATWORK_BONUS_DESCRIPTION", "The Great Work of this city produces 1.25 times [ICON_CULTURE] Culture and grants a [ICON_Tourism] Tourism bonus of +50%."),
  ("LOC_GREAT_PERSON_INDIVIDUAL_ZHU_BI_SHAN_HD_NAME", "Zhu Bishan"),
  ("LOC_GREATWORK_ZHU_BI_SHAN_HD_1_NAME", "The Silver Chariot of Yuan Zhu Bishan"),
  ("LOC_GREATWORK_ZHU_BI_SHAN_HD_2_NAME", "The Silver Chariot of Yuan Zhu Bishan"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_GISLEBERTUS_HD_NAME", "Gislebertus"),
  ("LOC_GREATWORK_GISLEBERTUS_HD_1_NAME", "The Last Judgment"),
  ("LOC_GREATWORK_GISLEBERTUS_HD_2_NAME", "The Temptation of Eve"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_GIOTTO_DI_BONDONE_HD_NAME", "Giotto di Bondone"),
  ("LOC_GREATWORK_GIOTTO_DI_BONDONE_HD_1_NAME", "The Kiss of Judas"),
  ("LOC_GREATWORK_GIOTTO_DI_BONDONE_HD_2_NAME", "The Flight into Egypt"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_DONG_QI_CHANG_HD_NAME", "Dong Qichang"),
  ("LOC_GREATWORK_DONG_QI_CHANG_HD_1_NAME", "The Picture of Lofty and Free"),
  ("LOC_GREATWORK_DONG_QI_CHANG_HD_2_NAME", "The Picture of Lin Hejing's Poetic Mood"),
  ("LOC_GREATWORK_DONG_QI_CHANG_HD_3_NAME", "The Picture of Rock Dwelling"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_SHI_TAO_HD_NAME", "Shi Tao"),
  ("LOC_GREATWORK_SHI_TAO_HD_1_NAME", "The Clean Autumn of Huaiyang"),
  ("LOC_GREATWORK_SHI_TAO_HD_2_NAME", "The Clear Sound of Mountain Water"),
  ("LOC_GREATWORK_SHI_TAO_HD_3_NAME", "The Sketches of the Monk with Bitter Melon"),
  ("LOC_GREATWORK_SHI_TAO_HD_3_QUOTE", "To recognize the constraints of resemblance is not broad enough, so the gentleman only borrows from the past to open up the present."),
  ("LOC_GREAT_PERSON_INDIVIDUAL_ZHU_DA_HD_NAME", "Bada Shanren"),
  ("LOC_GREATWORK_ZHU_DA_HD_1_NAME", "The Peacock and Bamboo Stone"),
  ("LOC_GREATWORK_ZHU_DA_HD_2_NAME", "The Lotus and Two Birds"),
  ("LOC_GREATWORK_ZHU_DA_HD_3_NAME", "Self-Portrait of Bada Shanren"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_SHEN_RONG_PU_HD_NAME", "Shen Rongpu"),
  ("LOC_GREATWORK_SHEN_RONG_PU_HD_1_NAME", "The Thirteen Rare Paintings of Tongguang, Part One"),
  ("LOC_GREATWORK_SHEN_RONG_PU_HD_2_NAME", "The Thirteen Rare Paintings of Tongguang, Part Two"),
  ("LOC_GREATWORK_SHEN_RONG_PU_HD_3_NAME", "The Thirteen Rare Paintings of Tongguang, Part Three"),

  ("LOC_GREAT_PERSON_INDIVIDUAL_YU_BO_YA_HD_NAME", "Yu Boya"),
  ("LOC_GREATWORK_YU_BO_YA_HD_1_NAME", "High Mountains and Flowing Water"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_SHI_KUANG_HD_NAME", "Shi Kuang"),
  ("LOC_GREATWORK_SHI_KUANG_HD_1_NAME", "Yangchun Baixue"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_LI_YAN_NIAN_HD_NAME", "Li Yannian"),
  ("LOC_GREATWORK_LI_YAN_NIAN_HD_1_NAME", "The Song of the Beautiful Lady"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_SI_MA_XIANG_RU_HD_NAME", "Sima Xiangru"),
  ("LOC_GREATWORK_SI_MA_XIANG_RU_HD_1_NAME", "Phoenix Seeking the Phoenix"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_LIU_XI_JUN_HD_NAME", "Princess Wusun"),
  ("LOC_GREATWORK_LIU_XI_JUN_HD_1_NAME", "The Song of Sorrow"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_CAI_YONG_HD_NAME", "Cai Yong"),
  ("LOC_GREATWORK_CAI_YONG_HD_1_NAME", "The Five Tunes of Cai"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_CAI_WEN_JI_HD_NAME", "Cai Wenji"),
  ("LOC_GREATWORK_CAI_WEN_JI_HD_1_NAME", "The Eighteen Pauses of the Hu Jia"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_HUAN_YI_HD_NAME", "Huan Yi"),
  ("LOC_GREATWORK_HUAN_YI_HD_1_NAME", "The Three Tunes of Plum Blossoms"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_RUAN_XIAN_HD_NAME", "Ruan Xian"),
  ("LOC_GREATWORK_RUAN_XIAN_HD_1_NAME", "The Flowing Springs of the Three Gorges"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_RUAN_JI_HD_NAME", "Ruan Ji"),
  ("LOC_GREATWORK_RUAN_JI_HD_1_NAME", "The Drunken Madness"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_JI_KANG_HD_NAME", "Ji Kang"),
  ("LOC_GREATWORK_JI_KANG_HD_1_NAME", "Guangling San"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_LIU_KUN_HD_NAME", "Zhao Yeli"),
  ("LOC_GREATWORK_LIU_KUN_HD_1_NAME", "The Five Tunes of the Hu Jia"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_SU_ZHI_PO_HD_NAME", "Su Zhipo"),
  ("LOC_SU_ZHI_PO_EXTRA_GREAT_MUSICIAN_POINTS_DESCRIPTION", "The player's [ICON_GREATMUSICIAN] Great Musician points accumulate 25% faster. [NEWLINE] Each building or wonder in this city that provides [ICON_GreatWork_Music] music Great Work slots grants +2 [ICON_CULTURE] Culture."),
  ("LOC_GREAT_PERSON_INDIVIDUAL_WANG_BAO_CHANG_HD_NAME", "Wang Baochang"),
  ("LOC_WANG_BAO_CHANG_MUSIC_CULTURE_BONUS_DESCRIPTION", "The Great Work of Music in this city generates 1.25 times [ICON_CULTURE] Culture and gives [ICON_Tourism] Tourism performance +50%."),
  ("LOC_GREAT_PERSON_INDIVIDUAL_LI_LONG_JI_HD_NAME", "Li Longji"),
  ("LOC_GREATWORK_LI_LONG_JI_HD_1_NAME", "The Melody of Feathered Garments and Rainbow"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_LI_GUI_NIAN_HD_NAME", "Li Guinian"),
  ("LOC_GREATWORK_LI_GUI_NIAN_HD_1_NAME", "The Melody of Weichuan"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_LEI_HAI_QING_HD_NAME", "Lei Haiqing"),
  ("LOC_GREATWORK_LEI_HAI_QING_HD_1_NAME", "Song of Offering Plum to Toast"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_DONG_TING_LAN_HD_NAME", "Dong Tinglan"),
  ("LOC_GREATWORK_DONG_TING_LAN_HD_1_NAME", "The Little Hu Jia"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_MAO_MIN_ZHONG_HD_NAME", "Mao Minzhong"),
  ("LOC_GREATWORK_MAO_MIN_ZHONG_HD_1_NAME", "Falling Wild Geese over the Sand"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_JIANG_KUI_HD_NAME", "Jiang Kui"),
  ("LOC_GREATWORK_JIANG_KUI_HD_1_NAME", "Slow Song of Yangzhou"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_GUAN_HAN_QING_HD_NAME", "Guan Hanqing"),
  ("LOC_GREATWORK_GUAN_HAN_QING_HD_1_NAME", "The Injustice of Dou E"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_BAI_PU_HD_NAME", "Bai Pu"),
  ("LOC_GREATWORK_BAI_PU_HD_1_NAME", "On the Wall, On Horseback"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_ZHENG_GUANG_ZU_HD_NAME", "Zheng Guangzu"),
  ("LOC_GREATWORK_ZHENG_GUANG_ZU_HD_1_NAME", "The Lady Who Departed with Her Soul"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_MA_ZHI_YUAN_HD_NAME", "Ma Zhiyuan"),
  ("LOC_GREATWORK_MA_ZHI_YUAN_HD_1_NAME", "Autumn in the Han Palace"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_WANG_SHI_FU_HD_NAME", "Wang Shifu"),
  ("LOC_GREATWORK_WANG_SHI_FU_HD_1_NAME", "The Romance of the West Chamber"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_FRANCESCO_LANDINI_HD_NAME", "Francesco Landini"),
  ("LOC_GREATWORK_FRANCESCO_LANDINI_HD_1_NAME", "What is Love"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_TANG_XIAN_ZU_HD_NAME", "Tang Xianzu"),
  ("LOC_GREATWORK_TANG_XIAN_ZU_HD_1_NAME", "The Four Dreams of Linchuan"),
  ("LOC_GREATWORK_TANG_XIAN_ZU_HD_2_NAME", "The Tale of the Purple Flute"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_TANG_YING_ZENG_HD_NAME", "Tang Yingzeng"),
  ("LOC_GREATWORK_TANG_YING_ZENG_HD_1_NAME", "The Ambush of Ten Sides"),
  ("LOC_GREATWORK_TANG_YING_ZENG_HD_2_NAME", "Autumn Thoughts at Dongting Lake"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_XIAO_LUAN_HD_NAME", "Xiao Luan"),
  ("LOC_GREATWORK_XIAO_LUAN_HD_1_NAME", "Questions and Answers from Fishermen and Woodcutters"),
  ("LOC_GREATWORK_XIAO_LUAN_HD_2_NAME", "Reading the Book of Changes on the Stone Bed"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_GAO_ZE_CHENG_HD_NAME", "Gao Zecheng"),
  ("LOC_GREATWORK_GAO_ZE_CHENG_HD_1_NAME", "The Pipa Record"),
  ("LOC_GREATWORK_GAO_ZE_CHENG_HD_2_NAME", "The Story of Min Ziqian and His Single Coat"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_ZHU_ZAI_YU_HD_NAME", "Zhu Zaiyu"),
  ("LOC_ZHU_ZAI_YU_CAMPUS_BONUS_DESCRIPTION", "The city's academy and theater adjacent bonus +100%."),
  ("LOC_GREAT_PERSON_INDIVIDUAL_JU_SHI_LIN_HD_NAME", "Ju Shilin"),
  ("LOC_GREATWORK_JU_SHI_LIN_HD_1_NAME", "Sunset Flute and Drum"),
  ("LOC_GREATWORK_JU_SHI_LIN_HD_2_NAME", "Leisurely Conversations of Subtle Sounds"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_GUILLAUME_DUFAY_HD_NAME", "Guillaume Dufay"),
  ("LOC_GREATWORK_GUILLAUME_DUFAY_HD_1_NAME", "Song of the Knight"),
  ("LOC_GREATWORK_GUILLAUME_DUFAY_HD_2_NAME", "Pale as the Moon"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_JOSQUIN_DES_PREZ_HD_NAME", "Josquin des Prez"),
  ("LOC_GREATWORK_JOSQUIN_DES_PREZ_HD_1_NAME", "Hail Mary"),
  ("LOC_GREATWORK_JOSQUIN_DES_PREZ_HD_2_NAME", "Thousands of Regrets"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_THOMAS_TALLIS_HD_NAME", "Thomas Tallis"),
  ("LOC_THOMAS_TALLIS_HOLY_SITE_TO_CULTURE_DESCRIPTION", "This holy site’s adjacent [ICON_FAITH] Faith bonus also provides [ICON_CULTURE} Culture. The city's [ICON_GreatWork_Music] music Great Work output boosts [ICON_Tourism] Tourism by +50%."),
  ("LOC_GREAT_PERSON_INDIVIDUAL_WILLIAM_BYRD_HD_NAME", "William Byrd"),
  ("LOC_GREATWORK_WILLIAM_BYRD_HD_1_NAME", "Fantasy in G Major"),
  ("LOC_GREATWORK_WILLIAM_BYRD_HD_2_NAME", "The Nevills’ Lady Collection"),
  ("LOC_GREAT_PERSON_INDIVIDUAL_TOMAS_LUIS_DE_VICTORIA_HD_NAME", "Tomás Luis de Victoria"),
  ("LOC_GREATWORK_TOMAS_LUIS_DE_VICTORIA_HD_1_NAME", "Requiem Mass"),
  ("LOC_GREATWORK_TOMAS_LUIS_DE_VICTORIA_HD_2_NAME", "O How Glorious is the Kingdom"),

  ("LOC_UNIT_HD_CODIFIER_NAME",         "Codifier"),
  ("LOC_GREAT_PERSON_CLASS_HD_CODIFIER_NAME",         "Codifier"),
  ("LOC_UNIT_HD_CODIFIER_DESCRIPTION",  "Yi Do overhauled the books during his reign. All books were published after he personally read them."),
  ("LOC_GREATWORK_HD_CODIFIER_1_NAME", "Record of Filial Conduct"),
  ("LOC_GREATWORK_HD_CODIFIER_2_NAME", "Direct Treatise on Agriculture"),
  ("LOC_GREATWORK_HD_CODIFIER_3_NAME", "The Three Principles of Practice and Their Illustrations"),
  ("LOC_GREATWORK_HD_CODIFIER_4_NAME", "Eightfold Geography Chronicles"),
  ("LOC_GREATWORK_HD_CODIFIER_5_NAME", "Annotations to the Record of No Grievances"),
  ("LOC_GREATWORK_HD_CODIFIER_6_NAME", "Compendium of Village Medicines"),
  ("LOC_GREATWORK_HD_CODIFIER_7_NAME", "Explanations of the Comprehensive Mirror for Aid in Governance"),
  ("LOC_GREATWORK_HD_CODIFIER_8_NAME", "Commentary on the Works of Han and Liu"),
  ("LOC_GREATWORK_HD_CODIFIER_9_NAME", "Supplement to the Annals of the States"),
  ("LOC_GREATWORK_HD_CODIFIER_10_NAME", "Imperial Decrees of the Ming Emperor"),
  ("LOC_GREATWORK_HD_CODIFIER_11_NAME", "Complete Works of the Silk Thread"),
  ("LOC_GREATWORK_HD_CODIFIER_12_NAME", "Annotations to the Poems of Du"),
  ("LOC_GREATWORK_HD_CODIFIER_13_NAME", "Translation of Proverbs in Rhyme"),
  ("LOC_GREATWORK_HD_CODIFIER_14_NAME", "Annotations to the Five Rites"),
  ("LOC_GREATWORK_HD_CODIFIER_15_NAME", "The Seven Divisions of Calculation, Inner and Outer Texts"),
  ("LOC_GREATWORK_HD_CODIFIER_16_NAME", "Essential Compendium of Governance"),
  ("LOC_GREATWORK_HD_CODIFIER_17_NAME", "Song of the Dragon Flying to the Sky"),
  ("LOC_GREATWORK_HD_CODIFIER_18_NAME", "Annotations to the Song of the Dragon Flying to the Sky"),
  ("LOC_GREATWORK_HD_CODIFIER_19_NAME", "Collection of Historical Omens from Various Scholars"),
  ("LOC_GREATWORK_HD_CODIFIER_20_NAME", "Collection of Medical Prescriptions"),
  ("LOC_GREATWORK_HD_CODIFIER_21_NAME", "Correct Pronunciation for the Instruction of the People"),
  ("LOC_GREATWORK_HD_CODIFIER_22_NAME", "Correct Rhymes of the Eastern Kingdom"),
  ("LOC_GREATWORK_HD_CODIFIER_23_NAME", "Commentary on the Four Books Proverbs"),
  ("LOC_GREATWORK_HD_CODIFIER_24_NAME", "History of Goryeo");

insert or replace into LocalizedText
  (Language,      Tag,                                                                 Text)
values
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MAO_YAN_SHOU_HD_NAME",  "毛延寿"),
  ("zh_Hans_CN",  "LOC_GREATWORK_MAO_YAN_SHOU_HD_1_NAME",  "《美人图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_MAO_YAN_SHOU_HD_2_NAME",  "《昭君画像》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_CAO_BU_XING_HD_NAME",  "曹不兴"),
  ("zh_Hans_CN",  "LOC_GREATWORK_CAO_BU_XING_HD_1_NAME",  "《敦煌壁画康僧会建业传法图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_CAO_BU_XING_HD_2_NAME",  "《佛像立轴》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_GU_KAI_ZHI_HD_NAME",  "顾恺之"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GU_KAI_ZHI_HD_1_NAME",  "《洛神赋图》其一"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GU_KAI_ZHI_HD_2_NAME",  "《洛神赋图》其二"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_DAI_KUI_HD_NAME",  "戴逵"),
  ("zh_Hans_CN",  "LOC_GREATWORK_DAI_KUI_HD_1_NAME",  "《丈六无量寿佛》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_DAI_KUI_HD_2_NAME",  "《玉躯佛像》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHANG_SENG_YAO_HD_NAME",  "张僧繇"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHANG_SENG_YAO_HD_1_NAME",  "《二十八星宿真形图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHANG_SENG_YAO_HD_2_NAME",  "《仙人楼阁图》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_PHEIDIAS_HD_NAME",  "菲狄亚斯"),
  ("zh_Hans_CN",  "LOC_GREATWORK_PHEIDIAS_HD_1_NAME",  "《雅典娜头像》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_PHEIDIAS_HD_2_NAME",  "《戎装的雅典娜》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MYRON_HD_NAME",  "米隆"),
  ("zh_Hans_CN",  "LOC_GREATWORK_MYRON_HD_1_NAME",  "《掷铁饼者》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_MYRON_HD_2_NAME",  "《雅典娜和玛息阿》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_POLYCLITUS_HD_NAME",  "波利克里托斯"),
  ("zh_Hans_CN",  "LOC_GREATWORK_POLYCLITUS_HD_1_NAME",  "《荷矛者》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_POLYCLITUS_HD_2_NAME",  "《法则》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_POLYCLITUS_HD_2_QUOTE",  "《法则》提出身长与头部的标准比例是7:1，并论述了人体雕塑理想的数理比例关系和张弛平衡、自然和谐的规范。"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHAN_ZI_QIAN_HD_NAME",  "展子虔"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHAN_ZI_QIAN_HD_1_NAME",  "《游春图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHAN_ZI_QIAN_HD_2_NAME",  "《授经图》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_WU_DAO_ZI_HD_NAME",  "吴道子"),
  ("zh_Hans_CN",  "LOC_GREATWORK_WU_DAO_ZI_HD_1_NAME",  "《送子天王图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_WU_DAO_ZI_HD_2_NAME",  "《八十七神仙卷》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_YANG_HUI_ZHI_HD_NAME",  "杨惠之"),
  ("zh_Hans_CN",  "LOC_GREATWORK_YANG_HUI_ZHI_HD_1_NAME",  "《袒腹罗汉》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_YANG_HUI_ZHI_HD_2_NAME",  "《达摩罗汉》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JING_HAO_HD_NAME",  "荆浩"),
  ("zh_Hans_CN",  "LOC_GREATWORK_JING_HAO_HD_1_NAME",  "《匡庐图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_JING_HAO_HD_2_NAME",  "《雪景山水图》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHANG_ZE_DUAN_HD_NAME",  "张择端"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHANG_ZE_DUAN_HD_1_NAME",  "《清明上河图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHANG_ZE_DUAN_HD_2_NAME",  "《金明池争标图》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_LI_TANG_HD_NAME",  "李唐"),
  ("zh_Hans_CN",  "LOC_GREATWORK_LI_TANG_HD_1_NAME",  "《采薇图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_LI_TANG_HD_2_NAME",  "《万壑松风图》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHAO_MENG_FU_HD_NAME",  "赵孟頫"),
  ("zh_Hans_CN",  "LOC_ZHAO_MENG_FU_ARTIST_GREATWORK_BONUS_DESCRIPTION",  "本城的 [ICON_GreatWork_Landscape] 艺术巨作产出1.25倍 [ICON_CULTURE] 文化值，且 [ICON_Tourism] 旅游业绩+50%。"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHU_BI_SHAN_HD_NAME",  "朱碧山"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHU_BI_SHAN_HD_1_NAME",  "《元朱碧山银槎》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHU_BI_SHAN_HD_2_NAME",  "《元朱碧山银槎》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_GISLEBERTUS_HD_NAME",  "吉斯勒贝尔"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GISLEBERTUS_HD_1_NAME",  "《最后的审判》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GISLEBERTUS_HD_2_NAME",  "《诱惑夏娃》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_GIOTTO_DI_BONDONE_HD_NAME",  "乔托·迪·邦多纳"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GIOTTO_DI_BONDONE_HD_1_NAME",  "《犹大之吻》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GIOTTO_DI_BONDONE_HD_2_NAME",  "《逃往埃及》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_DONG_QI_CHANG_HD_NAME",  "董其昌"),
  ("zh_Hans_CN",  "LOC_GREATWORK_DONG_QI_CHANG_HD_1_NAME",  "《高逸图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_DONG_QI_CHANG_HD_2_NAME",  "《林和靖诗意图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_DONG_QI_CHANG_HD_3_NAME",  "《岩居图》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_SHI_TAO_HD_NAME",  "石涛"),
  ("zh_Hans_CN",  "LOC_GREATWORK_SHI_TAO_HD_1_NAME",  "《淮扬洁秋图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_SHI_TAO_HD_2_NAME",  "《山水清音图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_SHI_TAO_HD_3_NAME",  "《苦瓜和尚画语录》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_SHI_TAO_HD_3_QUOTE",  "识拘于似则不广，故君子惟借古以开今也。"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHU_DA_HD_NAME",  "八大山人"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHU_DA_HD_1_NAME",  "《孔雀竹石图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHU_DA_HD_2_NAME",  "《荷花双禽图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHU_DA_HD_3_NAME",  "《八大山人自画像》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_SHEN_RONG_PU_HD_NAME",  "沈蓉圃"),
  ("zh_Hans_CN",  "LOC_GREATWORK_SHEN_RONG_PU_HD_1_NAME",  "《同光十三绝》其一"),
  ("zh_Hans_CN",  "LOC_GREATWORK_SHEN_RONG_PU_HD_2_NAME",  "《同光十三绝》其二"),
  ("zh_Hans_CN",  "LOC_GREATWORK_SHEN_RONG_PU_HD_3_NAME",  "《同光十三绝》其三"),

  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_YU_BO_YA_HD_NAME",  "俞伯牙"),
  ("zh_Hans_CN",  "LOC_GREATWORK_YU_BO_YA_HD_1_NAME",  "《高山流水》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_SHI_KUANG_HD_NAME",  "师旷"),
  ("zh_Hans_CN",  "LOC_GREATWORK_SHI_KUANG_HD_1_NAME",  "《阳春白雪》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_LI_YAN_NIAN_HD_NAME",  "李延年"),
  ("zh_Hans_CN",  "LOC_GREATWORK_LI_YAN_NIAN_HD_1_NAME",  "《佳人曲》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_SI_MA_XIANG_RU_HD_NAME",  "司马相如"),
  ("zh_Hans_CN",  "LOC_GREATWORK_SI_MA_XIANG_RU_HD_1_NAME",  "《凤求凰》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_LIU_XI_JUN_HD_NAME",  "乌孙公主"),
  ("zh_Hans_CN",  "LOC_GREATWORK_LIU_XI_JUN_HD_1_NAME",  "《悲愁歌》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_CAI_YONG_HD_NAME",  "蔡邕"),
  ("zh_Hans_CN",  "LOC_GREATWORK_CAI_YONG_HD_1_NAME",  "《蔡氏五弄》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_CAI_WEN_JI_HD_NAME",  "蔡文姬"),
  ("zh_Hans_CN",  "LOC_GREATWORK_CAI_WEN_JI_HD_1_NAME",  "《胡笳十八拍》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HUAN_YI_HD_NAME",  "桓伊"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HUAN_YI_HD_1_NAME",  "《梅花三弄》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_RUAN_XIAN_HD_NAME",  "阮咸"),
  ("zh_Hans_CN",  "LOC_GREATWORK_RUAN_XIAN_HD_1_NAME",  "《三峡流泉》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_RUAN_JI_HD_NAME",  "阮籍"),
  ("zh_Hans_CN",  "LOC_GREATWORK_RUAN_JI_HD_1_NAME",  "《酒狂》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JI_KANG_HD_NAME",  "嵇康"),
  ("zh_Hans_CN",  "LOC_GREATWORK_JI_KANG_HD_1_NAME",  "《广陵散》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_LIU_KUN_HD_NAME",  "赵耶利"),
  ("zh_Hans_CN",  "LOC_GREATWORK_LIU_KUN_HD_1_NAME",  "《胡笳五弄》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_SU_ZHI_PO_HD_NAME",  "苏祗婆"),
  ("zh_Hans_CN",  "LOC_SU_ZHI_PO_EXTRA_GREAT_MUSICIAN_POINTS_DESCRIPTION",  "玩家的 [ICON_GREATMUSICIAN] 大音乐家点数积累速度+25%。[NEWLINE]本城的每个提供 [ICON_GreatWork_Music] 音乐巨作槽位的建筑或奇观+2 [ICON_CULTURE] 文化值。"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_WANG_BAO_CHANG_HD_NAME",  "万宝常"),
  ("zh_Hans_CN",  "LOC_WANG_BAO_CHANG_MUSIC_CULTURE_BONUS_DESCRIPTION",  "本城的 [ICON_GreatWork_Music] 音乐巨作产出1.25倍 [ICON_CULTURE] 文化值，且 [ICON_Tourism] 旅游业绩+50%。"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_LI_LONG_JI_HD_NAME",  "李隆基"),
  ("zh_Hans_CN",  "LOC_GREATWORK_LI_LONG_JI_HD_1_NAME",  "《霓裳羽衣曲》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_LI_GUI_NIAN_HD_NAME",  "李龟年"),
  ("zh_Hans_CN",  "LOC_GREATWORK_LI_GUI_NIAN_HD_1_NAME",  "《渭川曲》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_LEI_HAI_QING_HD_NAME",  "雷海青"),
  ("zh_Hans_CN",  "LOC_GREATWORK_LEI_HAI_QING_HD_1_NAME",  "《引梅敬酒歌》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_DONG_TING_LAN_HD_NAME",  "董庭兰"),
  ("zh_Hans_CN",  "LOC_GREATWORK_DONG_TING_LAN_HD_1_NAME",  "《小胡笳》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MAO_MIN_ZHONG_HD_NAME",  "毛敏仲"),
  ("zh_Hans_CN",  "LOC_GREATWORK_MAO_MIN_ZHONG_HD_1_NAME",  "《平沙落雁》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JIANG_KUI_HD_NAME",  "姜夔"),
  ("zh_Hans_CN",  "LOC_GREATWORK_JIANG_KUI_HD_1_NAME",  "《扬州慢》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_GUAN_HAN_QING_HD_NAME",  "关汉卿"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GUAN_HAN_QING_HD_1_NAME",  "《窦娥冤》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_BAI_PU_HD_NAME",  "白朴"),
  ("zh_Hans_CN",  "LOC_GREATWORK_BAI_PU_HD_1_NAME",  "《墙头马上》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHENG_GUANG_ZU_HD_NAME",  "郑光祖"),
  ("zh_Hans_CN",  "LOC_GREATWORK_ZHENG_GUANG_ZU_HD_1_NAME",  "《倩女离魂》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MA_ZHI_YUAN_HD_NAME",  "马致远"),
  ("zh_Hans_CN",  "LOC_GREATWORK_MA_ZHI_YUAN_HD_1_NAME",  "《汉宫秋》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_WANG_SHI_FU_HD_NAME",  "王实甫"),
  ("zh_Hans_CN",  "LOC_GREATWORK_WANG_SHI_FU_HD_1_NAME",  "《西厢记》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_FRANCESCO_LANDINI_HD_NAME",  "弗朗切斯科·兰迪尼"),
  ("zh_Hans_CN",  "LOC_GREATWORK_FRANCESCO_LANDINI_HD_1_NAME",  "《什么是爱情》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_TANG_XIAN_ZU_HD_NAME",  "汤显祖"),
  ("zh_Hans_CN",  "LOC_GREATWORK_TANG_XIAN_ZU_HD_1_NAME",  "《临川四梦》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_TANG_XIAN_ZU_HD_2_NAME",  "《紫箫记》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_TANG_YING_ZENG_HD_NAME",  "汤应曾"),
  ("zh_Hans_CN",  "LOC_GREATWORK_TANG_YING_ZENG_HD_1_NAME",  "《十面埋伏》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_TANG_YING_ZENG_HD_2_NAME",  "《洞庭秋思》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_XIAO_LUAN_HD_NAME",  "肖鸾"),
  ("zh_Hans_CN",  "LOC_GREATWORK_XIAO_LUAN_HD_1_NAME",  "《渔樵问答》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_XIAO_LUAN_HD_2_NAME",  "《石床读易》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_GAO_ZE_CHENG_HD_NAME",  "高则诚"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GAO_ZE_CHENG_HD_1_NAME",  "《琵琶记》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GAO_ZE_CHENG_HD_2_NAME",  "《闵子骞单衣记》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHU_ZAI_YU_HD_NAME",  "朱载堉"),
  ("zh_Hans_CN",  "LOC_ZHU_ZAI_YU_CAMPUS_BONUS_DESCRIPTION",  "本城的学院和剧院相邻加成+100%。"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JU_SHI_LIN_HD_NAME",  "鞠士林"),
  ("zh_Hans_CN",  "LOC_GREATWORK_JU_SHI_LIN_HD_1_NAME",  "《夕阳箫鼓》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_JU_SHI_LIN_HD_2_NAME",  "《闲叙幽音》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_GUILLAUME_DUFAY_HD_NAME",  "纪尧姆·迪费"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GUILLAUME_DUFAY_HD_1_NAME",  "《武士歌》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_GUILLAUME_DUFAY_HD_2_NAME",  "《脸儿苍白》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JOSQUIN_DES_PREZ_HD_NAME",  "若斯坎·德普雷"),
  ("zh_Hans_CN",  "LOC_GREATWORK_JOSQUIN_DES_PREZ_HD_1_NAME",  "《圣母颂》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_JOSQUIN_DES_PREZ_HD_2_NAME",  "《千般悔》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_THOMAS_TALLIS_HD_NAME",  "托马斯·塔利斯"),
  ("zh_Hans_CN",  "LOC_THOMAS_TALLIS_HOLY_SITE_TO_CULTURE_DESCRIPTION",  "该圣地的 [ICON_FAITH] 信仰值相邻加成也提供 [ICON_CULTURE] 文化值。[NEWLINE]本城的 [ICON_GreatWork_Music] 音乐巨作产出的 [ICON_Tourism] 旅游业绩+50%。"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_WILLIAM_BYRD_HD_NAME",  "威廉·伯德"),
  ("zh_Hans_CN",  "LOC_GREATWORK_WILLIAM_BYRD_HD_1_NAME",  "《G大调幻想曲》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_WILLIAM_BYRD_HD_2_NAME",  "《内维尔夫人曲集》"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_TOMAS_LUIS_DE_VICTORIA_HD_NAME",  "托马斯·路易斯·德·维多利亚"),
  ("zh_Hans_CN",  "LOC_GREATWORK_TOMAS_LUIS_DE_VICTORIA_HD_1_NAME",  "《悼亡仪式》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_TOMAS_LUIS_DE_VICTORIA_HD_2_NAME",  "《王国多么荣耀》"),

  ("zh_Hans_CN",  "LOC_UNIT_HD_CODIFIER_NAME",  "编撰官"),
  ("zh_Hans_CN",  "LOC_GREAT_PERSON_CLASS_HD_CODIFIER_NAME",  "编撰官"),
  ("zh_Hans_CN",  "LOC_UNIT_HD_CODIFIER_DESCRIPTION",  "李裪在位期间，大修书籍，而且所有书籍均经过他亲览裁定后颁布。"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_1_NAME",  "《孝行录》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_2_NAME",  "《农事直说》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_3_NAME",  "《三纲行实图》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_4_NAME",  "《八道地理志》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_5_NAME",  "《无冤录注解》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_6_NAME",  "《乡药集成方》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_7_NAME",  "《资治通鉴训译》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_8_NAME",  "《韩柳文注释》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_9_NAME",  "《国语补正》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_10_NAME",  "《明皇诫鉴》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_11_NAME",  "《丝纶全集》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_12_NAME",  "《杜诗诸家注释》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_13_NAME",  "《韵会谚译》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_14_NAME",  "《五礼仪注》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_15_NAME",  "《七政算內外篇》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_16_NAME",  "《治平要览》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_17_NAME",  "《龙飞御天歌》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_18_NAME",  "《龙飞御天歌注解》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_19_NAME",  "《诸家历象集》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_20_NAME",  "《医方类聚》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_21_NAME",  "《训民正音》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_22_NAME",  "《东国正韵》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_23_NAME",  "《四书谚解》"),
  ("zh_Hans_CN",  "LOC_GREATWORK_HD_CODIFIER_24_NAME",  "《高丽史》");