--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
	(Tag,															 Text)
values
	-- 圣地
	("LOC_DISTRICT_HOLY_SITE_HD_DESCRIPTION",						 				"A district for religious worship in your city. [NEWLINE]+10% [ICON_Faith] Faith if there exists a third-tier worship building in the district."),
	("LOC_DISTRICT_LAVRA_HD_DESCRIPTION",							 					"A district unique to Russia, replacing the Holy Site district.[NEWLINE]The citizens working in this district also yield Great Writer, Artist and Musician points. Your city border grows by one tile each time a Great Person is expended in this city. +10% [ICON_Faith] Faith if there exists a third-tier worship building in the district."),
	-- 学院
	("LOC_DISTRICT_CAMPUS_DESCRIPTION",													"A district for scientific endeavors in your city."),
	("LOC_DISTRICT_SEOWON_HD_DESCRIPTION",											"A district unique to Korea, replacing the Campus district. +4 [Icon_Science] Science. Has more citizen slots."),
	("LOC_DISTRICT_OBSERVATORY_HD_DESCRIPTION",             		"A district unique to the Maya, replacing the Campus district.[NEWLINE]+1 [ICON_Science] Science for every adjacent Luxury Resource, which becomes +2 after researching 'Astronomy' Technology. +1 [ICON_Science] Science for every 2 adjacent Farms, or for every 1 adjacent farm after progressing 'Feudalism' Civic."),
	-- 剧院
	("LOC_DISTRICT_THEATER_HD_DESCRIPTION",											"A district for cultural activities in your city. [NEWLINE]+1 [ICON_CULTURE] Culture when built on tiles with Charming Appeal. +3 [ICON_CULTURE] Culture when built on tiles with Breathtaking Appeal."),
	("LOC_DISTRICT_ACROPOLIS_HD_DESCRIPTION",						 				"A district unique to Greece, replacing the Theater Square district. [NEWLINE]Awards 1 [ICON_Envoy] Envoy when completed. +1 [ICON_Culture] Culture bonus for each adjacent district and an additional +2 [ICON_Culture] Culture bonus for adjacent City Center. +1 [ICON_CULTURE] Culture when built on tiles with Charming Appeal. +3 [ICON_CULTURE] Culture when built on tiles with Breathtaking Appeal."),
	-- 商业中心
	("LOC_DISTRICT_COMMERCIAL_HUB_HD_DESCRIPTION",							"A district for finance and trade in your city. [NEWLINE]+3 [ICON_Gold] Gold for adjacent Improvements. +2 [ICON_Gold] Gold from [ICON_TradeRoute] Trade Routes starting from this city. Immediately create a [ICON_TRADINGPOST] Trading Post in this city."),
	("LOC_DISTRICT_SUGUBA_HD_DESCRIPTION",											"A district unique to Mali, replacing the Commercial Hub district. [NEWLINE]Gains major adjacency bonus when adjacent to Holy Site Districts. Enable purchasing Districts with [ICON_Gold] Gold in this city. Units, Buildings, and Districts are 15% cheaper to purchase with [ICON_GOLD] Gold and [ICON_FAITH] Faith in this City.[NEWLINE][NEWLINE]+3 [ICON_Gold] Gold for adjacent Improvements. +2 [ICON_Gold] Gold from all [ICON_TradeRoute] Trade Routes originated from this city. Immediately create a [ICON_TRADINGPOST] Trading Post in this city."),
	-- 港口
	("LOC_DISTRICT_HARBOR_HD_DESCRIPTION",											"A district for naval activities and trade in your city. [NEWLINE]+2 [ICON_HOUSING] Housing if this city is adjacent to Shallow Sea and Lake. Improvements on water area provide +3 [ICON_Gold] Gold in this city. Immediately create a [ICON_TRADINGPOST] Trading Post in this city. Removes the [ICON_Movement] Movement penalty for embarking and disembarking to and from this tile. [NEWLINE]Must be built on Shallow Sea and Lake adjacent to land."),
	("LOC_DISTRICT_COTHON_HD_DESCRIPTION",											"A district unique to Phoenicia, replacing the Harbor district. [NEWLINE]+2 [ICON_HOUSING] Housing if this city is adjacent to Shallow Sea and Lake. Improvements on water area provide +3 [ICON_Gold] Gold in this city. Immediately create a [ICON_TRADINGPOST] Trading Post in this city. [NEWLINE]+1 [ICON_TradeRoute] Trade Route capacity when built in same Water Area as [ICON_Capital] Capital's Cothon. All wounded naval units in the city heal +100 HP per turn. [NEWLINE]Must be built on Shallow Sea and Lake adjacent to land."),
	("LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_HD_DESCRIPTION",					"A district unique to England, replacing the Harbor district. [NEWLINE]+2 [ICON_HOUSING] Housing if this city is adjacent to Shallow Sea and Lake. Improvements on water area provide +3 [ICON_Gold] Gold in this city. Immediately create a [ICON_TRADINGPOST] Trading Post in this city. Removes the [ICON_Movement] Movement penalty for embarking and disembarking to and from this tile. [NEWLINE]+1 [ICON_Movement] Movement for all naval units built in Dockyard, and land units built in this city ignore additional [ICON_MOVEMENT] Movement costs from embarking and disembarking. +2 [ICON_Gold] Gold bonus for each adjacent Industrial Zone. Properly improved Strategic resources in the city gain an additional +2 per turn. [NEWLINE]Must be built on Shallow Sea and Lake adjacent to land."),
	-- 工业区
	("LOC_DISTRICT_INDUSTRIAL_ZONE_HD_DESCRIPTION",							"A district for industrial activities in your city. [NEWLINE]For each type of Industrial Production Improvements in this city, +5% [ICON_PRODUCTION] Production toward Renaissance, Medieval, Classical, and Ancient wonders. If has at least +6 adjacency bonus, +5% [ICON_PRODUCTION] Production toward Renaissance, Medieval, Classical, and Ancient wonders."),
	("LOC_DISTRICT_HANSA_HD_DESCRIPTION",							 					"A district unique to Germany, replacing the Industrial Zone district.[NEWLINE]+2 [ICON_PRODUCTION] Production when adjacent to River. +1 [ICON_PRODUCTION] Production bonus for each adjacent Commercial Hub districts and Resources (doubles after researching Apprenticeship). +1 [Icon_Production] Production to adjacent Resources. Provides Major adjacency bonus to Commercial Hub Districts. [NEWLINE]For each type of Industrial Production Improvements in this city, +5% [ICON_PRODUCTION] Production toward Renaissance, Medieval, Classical, and Ancient wonders. If has at least +6 adjacency bonus, +5% [ICON_PRODUCTION] Production toward Renaissance, Medieval, Classical, and Ancient wonders."),
	("LOC_DISTRICT_OPPIDUM_HD_DESCRIPTION",											"A district unique to Gaul, replacing the Industrial Zone district.[NEWLINE]The Oppidum district is defensible with a ranged attack. +2 [ICON_FOOD] Food, and +1 [ICON_FOOD] Food bonus for each adjacent district. [NEWLINE]For each type of Industrial Production Improvements in this city, +5% [ICON_PRODUCTION] Production toward Renaissance, Medieval, Classical, and Ancient wonders. If has at least +6 adjacency bonus, +5% [ICON_PRODUCTION] Production toward Renaissance, Medieval, Classical, and Ancient wonders."),
	-- 军营
	("LOC_DISTRICT_ENCAMPMENT_HD_DESCRIPTION",									"A district for land force facilities in your city. [NEWLINE]+10% [ICON_PRODUCTION] Production towards Land Military Units. +1 [Icon_Science] Science for improved Strategic resources in the city. Properly improved Strategic resources in the city gain an additional +2 per turn."),
	("LOC_DISTRICT_IKANDA_HD_DESCRIPTION",											"A district unique to Zulu, replacing the Encampment district. [NEWLINE]Provides +1 [ICON_Housing] Housing. Once the Civic or Technology prerequisite is met, Corps and Armies can be trained without Military Academy building. Culture bombs adjacent tiles when finished. -25% Corps and Army training cost. Ikanda and Buildings in the Ikanda provide +2 [ICON_Production] Production and +2 [ICON_SCIENCE] Science.[NEWLINE]+30% [ICON_PRODUCTION] Production towards Land Military Units. Improved Strategic resources in the city provide +1 [Icon_Science] Science. Properly improved Strategic resources in the city gain an additional +2 per turn."),
	("LOC_DISTRICT_THANH_HD_DESCRIPTION",							 					"A district unique to Vietnam, replacing the Encampment district. [NEWLINE]+1 [ICON_PRODUCTION] Production for every 2 adjacent Districts. Provides [ICON_CULTURE] Culture equal to its [ICON_PRODUCTION] Production adjacency bonus. After Flight is researched receive [ICON_TOURISM] Tourism equal to the [ICON_PRODUCTION] Production yield. The city can build 1 one more district than the [ICON_CITIZEN] population limit allows. Is cheaper to build, cannot be built adjacent to the city center.[NEWLINE]+10% [ICON_PRODUCTION] Production towards Land Military Units. +1 [Icon_Science] Science for improved Strategic resources in the city. Properly improved Strategic resources in the city gain an additional +2 per turn."),
	-- 政府区
	("LOC_DISTRICT_GOVERNMENT_HD_DESCRIPTION",						 			"A district for political activities and state management in your city. [NEWLINE]Provides +8 Loyalty per turn to this city, and an increase of +1 to the adjacency bonuses being earned by any adjacent district. [NEWLINE][NEWLINE]Awards +1 [ICON_GOVERNOR] Governor Title."),
	-- 外交区
	("LOC_DISTRICT_DIPLOMATIC_QUARTER_HD_DESCRIPTION",					"A district for diplomatic activities and national security in your city. [NEWLINE]Your civilization receives +1 [ICON_FAVOR] Diplomatic Favor for each Delegation or Embassy from a foreign civilization through diplomacy. Awards 1 [ICON_Envoy] Envoy when completed. Enemy Spies operate at 2 levels below normal when targeting this District and adjacent Districts. Grants the ability to construct an additional Spy. Districts receive +1 adjacency bonuses from being adjacent to Diplomatic Quater."),
	-- 水渠
	("LOC_DISTRICT_AQUEDUCT_HD_DESCRIPTION",										"A district providing fresh water from an adjacent River, Lake, Oasis, or Mountain in your city. [NEWLINE]+1 [ICON_FOOD] Food. +1 [ICON_PRODUCTION] Production if adjacent to Mountain tiles. +1 [ICON_SCIENCE] Science if on or adjacent to Geothermal Fissure tiles. [NEWLINE]Cities that do not yet have existing fresh water receive up to 6 [ICON_Housing] Housing. Cities that already have existing fresh water will instead get +2 [ICON_Housing] Housing. Prevents [ICON_Food] Food loss during Drought. [NEWLINE]Must be built adjacent to the City Center. [NEWLINE]Military Engineers can spend a charge to complete 30% of an Aqueduct's production."),
	("LOC_DISTRICT_BATH_HD_DESCRIPTION",												"A district unique to Rome, replacing the Aqueduct district. [NEWLINE]+1 [ICON_FOOD] Food, +2 [ICON_Housing] Housing and +1 [ICON_Amenities] Amenity. +1 [ICON_PRODUCTION] Production if adjacent to Mountain tiles. +1 [ICON_SCIENCE] Science if on or adjacent to Geothermal Fissure tiles. [NEWLINE]It provides this city with a source of fresh water from an adjacent River, Lake, Oasis, or Mountain. Cities that do not yet have existing fresh water receive up to 6 [ICON_Housing] Housing. Cities that already have existing fresh water will instead get +2 [ICON_Housing] Housing. Prevents [ICON_Food] Food loss during Drought. [NEWLINE]Must be built adjacent to the City Center. [NEWLINE]Military Engineers can spend a charge to complete 30% of an Aqueduct's production."),
	-- 运河
	("LOC_DISTRICT_CANAL_HD_DESCRIPTION",							 					"A district for connecting waterways and promoting water transportation in the city.[NEWLINE]+6 [ICON_Gold] Gold for adjacent Improvements. Multiplier of	[ICON_Gold] Gold yield from districts at their destination [ICON_TradeRoute] Trade Routes passing through Canal is set to +100% (max. +100%). [NEWLINE]Must be built on flat land. Canals may either go straight through the hex or bend by 60 degrees, connecting two bodies of water or a body of water to a City Center.. However three-way Canal junctures are not allowed and Canals must have a full land tile on each side of the waterway they create. [NEWLINE]Military Engineers can spend a charge to complete 30% of a Canal's production."),
	-- 堤坝
	("LOC_DISTRICT_DAM_HD_DESCRIPTION",													"A district for improving the comfort of living along a River in the city.[NEWLINE]+1 [ICON_Food] Food and +1 [ICON_PRODUCTION] Production for adjacent Improvements. [NEWLINE]Prevents damage from flooding (though yields from flooding drop by 50%). Prevents [ICON_Food] Food loss during Drought. Only one may be built along each river's floodplain (whichever player completes one first) and the river must traverse at least two sides of the Dam hex. [NEWLINE]Military Engineers can spend a charge to complete 30% of a Dam's production."),
	-- 保护区
	("LOC_DISTRICT_PRESERVE_HD_DESCRIPTION",										"A district for environmental protection and ecological conservation in your city. [NEWLINE]+1 [ICON_FOOD] Food. Triggers a Cultural Bomb on adjacent neutral tiles. Can be built on Forests, Rainforests and Marshes. Feature tiles in this city do not decrease the Appeal of adjacent tiles. [NEWLINE][NEWLINE]Award +1 Wildcard Policy Slot for the first time 4 kinds of Agency buildings are all built."),
	-- 娱乐中心
	("LOC_DISTRICT_ENTERTAINMENT_COMPLEX_HD_DESCRIPTION",			 	"A district for habitability and recreational activities in your city. [NEWLINE]+2 [ICON_Amenities] Amenities. Extra +1 [ICON_Amenities] Amenity if adjacent to Wonder or Neighborhood districts."),
	("LOC_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_HD_DESCRIPTION",	"A district for habitability and recreational activities in your city. [NEWLINE]+2 [ICON_Amenities] Amenities. Extra +1 [ICON_Amenities] Amenity if adjacent to Wonder or Neighborhood districts. Must be built on Shallow Sea and Lake adjacent to land."),
	("LOC_DISTRICT_WATER_STREET_CARNIVAL_HD_DESCRIPTION",			 	"A district unique to Brazil, replacing the Water Park district. [NEWLINE]+2 [ICON_Amenities] Amenities. Extra +1 [ICON_Amenities] Amenity if adjacent to Wonder or Neighborhood districts. +1 [ICON_FOOD] Food to adjacent districts. Receives corresponding yield when the first [ICON_GREATPERSON] Great People of each type is attracted or patronized. May purchase buildings inside with [ICON_FAITH] Faith. Must be built on Shallow Sea and Lake adjacent to land."),
	("LOC_DISTRICT_STREET_CARNIVAL_HD_DESCRIPTION",							"A district unique to Brazil, replacing the Entertainment Complex district. [NEWLINE]+2 [ICON_Amenities] Amenities. Extra +1 [ICON_Amenities] Amenity if adjacent to Wonder or Neighborhood districts. +1 [ICON_FOOD] Food to adjacent districts. Receives corresponding yield when the first [ICON_GREATPERSON] Great People of each type is attracted or patronized. May purchase buildings inside with [ICON_FAITH] Faith."),
	("LOC_DISTRICT_HIPPODROME_HD_DESCRIPTION",									"A district unique to Byzantium, replacing the Entertainment Complex district. [NEWLINE]+2 [ICON_Amenities] Amenities. Extra +1 [ICON_Amenities] Amenity if adjacent to Pastures or Camps. +1 [ICON_Culture] Culture bonus for each adjacent Resources. [NEWLINE][NEWLINE]Unlock Saddle technology after constructed for the first time. When the Hippodrome and buildings in this district are constructed, receive a free Heavy Cavalry unit (no maintenance cost)."),
	-- 社区
	("LOC_DISTRICT_NEIGHBORHOOD_HD_DESCRIPTION",								"A district for civil activities and community services in your city. [NEWLINE]Gives Housing according to the tile's appeal.[NEWLINE]Breathtaking: +5 [ICON_HOUSING] Housing.[NEWLINE]Charming: +4 [ICON_HOUSING] Housing.[NEWLINE]Average: +3 [ICON_HOUSING] Housing.[NEWLINE]Unappealing: +2 [ICON_HOUSING] Housing.[NEWLINE]Disgusting: +1 [ICON_HOUSING] Housing."),
	("LOC_DISTRICT_MBANZA_HD_DESCRIPTION",											"A district unique to the Congo, replacing the Neighborhood district. [NEWLINE]Can only be built in Rainforest or Woods. Provides +3 [ICON_HOUSING] Housing, +2 [ICON_FOOD] Food, and +2 [ICON_GOLD] Gold, regardless of Appeal. +1 [ICON_FOOD] Food to all adjacent tiles. Receives +1 [Icon_Production] Production from every Bonus Resource, +2 [Icon_Gold] Gold from every Luxury Resource and +1 [Icon_Science] Science from every Strategic Resource. Allows the purchasing of Settlers and Builders using [ICON_FAITH] Faith."),
	-- 航空港
	("LOC_DISTRICT_AERODROME_HD_DESCRIPTION",						 				"A district for air force activities and civil air services in your city. [NEWLINE]Cannot be built on Hills. Can be built regardless of [ICON_CITIZEN] population. +25% [Icon_Production] Production towards Air Units.");
	

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
	(Language,		Tag,															 Text)
values
	-- 圣地
	("zh_Hans_CN",	"LOC_DISTRICT_HOLY_SITE_HD_DESCRIPTION",						 				"城市中专注于宗教祭祀活动的区域。[NEWLINE]若该区域内含有三级宗教建筑，则本城+10% [ICON_Faith] 信仰值。"),
	("zh_Hans_CN",	"LOC_DISTRICT_LAVRA_HD_DESCRIPTION",							 					"俄罗斯特色区域，取代“圣地”。[NEWLINE]该区域内的专家也产出大作家、大艺术家、大音乐家点数。此城市每消耗一位伟人，城市边界则扩张一个单元格。若该区域内含有三级宗教建筑，则本城+10% [ICON_Faith] 信仰值。"),
	-- 学院
	("zh_Hans_CN",	"LOC_DISTRICT_CAMPUS_DESCRIPTION",													"城市中专注于科学发展的区域。"),
	("zh_Hans_CN",	"LOC_DISTRICT_SEOWON_HD_DESCRIPTION",												"朝鲜特色区域，取代“学院”。[NEWLINE]+4 [Icon_Science] 科技值。拥有更多的专家槽位。"),
	("zh_Hans_CN",  "LOC_DISTRICT_OBSERVATORY_HD_DESCRIPTION",              		"玛雅特色区域。取代“学院”。[NEWLINE]每相邻1个奢侈品相邻+1 [ICON_Science] 科技值，解锁“天文学”科技后变为+2 [ICON_Science] 科技值。每相邻2个农场+1 [ICON_Science] 科技值，解锁“封建主义”市政后变为每相邻1个农场。"),
	-- 剧院
	("zh_Hans_CN",	"LOC_DISTRICT_THEATER_HD_DESCRIPTION",											"城市中专注于文化活动的区域。[NEWLINE]若位于拥有迷人魅力的单元格+1 [ICON_Culture] 文化值，惊艳单元格则+3 [ICON_Culture] 文化值。"),
	("zh_Hans_CN",	"LOC_DISTRICT_ACROPOLIS_HD_DESCRIPTION",						 				"希腊特色区域，取代“剧院广场”。[NEWLINE]建成后奖励1名 [ICON_Envoy] 使者。每个相邻区域+1 [ICON_Culture] 文化值，每个相邻市中心额外+2 [ICON_Culture] 文化值。若位于拥有迷人魅力的单元格+1 [ICON_Culture] 文化值，惊艳单元格则+3 [ICON_Culture] 文化值。"),
	-- 商业中心
	("zh_Hans_CN",	"LOC_DISTRICT_COMMERCIAL_HUB_HD_DESCRIPTION",								"城市中专注于金融与贸易的区域。[NEWLINE]为相邻的改良设施+3 [ICON_Gold] 金币。本城出发的 [ICON_TradeRoute] 贸易路线+2 [ICON_Gold] 金币。本城建立一个 [ICON_TRADINGPOST] 贸易站。"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUGUBA_HD_DESCRIPTION",												"马里特色区域，取代“商业中心”。[NEWLINE]与圣地相邻获得大相邻加成。允许本城使用金币购买区域。使用 [ICON_GOLD] 金币和 [ICON_FAITH] 信仰值在此城中购买单位、建筑和区域时，费用减少15%。[NEWLINE][NEWLINE]为相邻的改良设施+3 [ICON_Gold] 金币。本城出发的 [ICON_TradeRoute] 贸易路线+2 [ICON_Gold] 金币。本城建立一个 [ICON_TRADINGPOST] 贸易站。"),
	-- 港口
	("zh_Hans_CN",	"LOC_DISTRICT_HARBOR_HD_DESCRIPTION",												"城市中专注于海军活动与海上贸易的区域。[NEWLINE]如此城与浅海与湖泊相邻，则+2 [ICON_HOUSING] 住房。本城建造在水域上的改良+3 [ICON_GOLD] 金币。本城建立一个 [ICON_TRADINGPOST] 贸易站。取消从该单元格上下船的 [ICON_Movement] 移动力消耗。[NEWLINE]必须修建在和陆地相邻的浅海与湖泊单元格上。"),
	("zh_Hans_CN",	"LOC_DISTRICT_COTHON_HD_DESCRIPTION",												"腓尼基特色区域，取代“港口”。[NEWLINE]如此城与浅海与湖泊相邻，则+2 [ICON_HOUSING] 住房。本城建造在水域上的改良+3 [ICON_GOLD] 金币。本城建立一个 [ICON_TRADINGPOST] 贸易站。海军单位在此城驻扎一回合可完全恢复。建成时，其所在水域若与 [ICON_Capital] 首都的U型港相同，则+1 [ICON_TRADEROUTE] 贸易路线容量。取消从该单元格上下船的 [ICON_Movement] 移动力减益。[NEWLINE]必须修建在和陆地相邻的浅海与湖泊单元格上。"),
	("zh_Hans_CN",	"LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_HD_DESCRIPTION",					"英国特色区域，取代“港口”。[NEWLINE]如此城与浅海与湖泊相邻，则+2 [ICON_HOUSING] 住房。本城建造在水域上的改良+3 [ICON_GOLD] 金币。本城建立一个 [ICON_TRADINGPOST] 贸易站。皇家海军船坞中建造的所有海军单位+1 [ICON_Movement] 移动力。本城建造的所有陆地单位忽略来自上船和下船的额外 [ICON_MOVEMENT] 移动力消耗。每相邻1个工业区+2 [ICON_Gold] 金币。本城正确改良的战略每回合积累+2。取消从该单元格上下船的 [ICON_Movement] 移动力减益。[NEWLINE]必须建在与陆地相邻的浅海与湖泊上。"),
	-- 工业区
	("zh_Hans_CN",	"LOC_DISTRICT_INDUSTRIAL_ZONE_HD_DESCRIPTION",							"城市中专注于工业生产的区域。[NEWLINE]本城每拥有一种工业生产改良，本城建造文艺复兴以及之前时代的奇观时+5%建造速度。若基础相邻加成至少+6，本城建造文艺复兴以及之前时代的奇观时+5%建造速度。"), 
	("zh_Hans_CN",	"LOC_DISTRICT_HANSA_HD_DESCRIPTION",							 					"德国特色区域，取代“工业区”。[NEWLINE]相邻河流时获得+2 [ICON_PRODUCTION] 生产力加成。可从每个相邻的商业中心和资源处获得+1 [ICON_PRODUCTION] 生产力加成（研究学徒后变为+2）。为相邻的资源+1 [ICON_PRODUCTION] 生产力，为商业中心提供大量相邻加成。[NEWLINE]本城每拥有一种工业生产改良，本城建造文艺复兴以及之前时代的奇观时+5%建造速度。若基础相邻加成至少+6，本城建造文艺复兴以及之前时代的奇观时+5%建造速度。"), 
	("zh_Hans_CN",	"LOC_DISTRICT_OPPIDUM_HD_DESCRIPTION",											"高卢特色区域，取代“工业区”。[NEWLINE]具有防御力且可执行远程攻击。+2 [ICON_FOOD] 食物，每个相邻区域+1 [ICON_FOOD] 食物。[NEWLINE]本城每拥有一种工业生产改良，本城建造文艺复兴以及之前时代的奇观时+5%建造速度。若基础相邻加成至少+6，本城建造文艺复兴以及之前时代的奇观时+5%建造速度。"),
	-- 军营
	("zh_Hans_CN",	"LOC_DISTRICT_ENCAMPMENT_HD_DESCRIPTION",										"城市中专注于陆军活动的区域。[NEWLINE]对陆地军事单位+10%建造速度。本城改良的战略资源+1 [ICON_Science] 科技值，正确改良的战略每回合积累+2。"),
	("zh_Hans_CN",	"LOC_DISTRICT_IKANDA_HD_DESCRIPTION",												"祖鲁特色区域，取代“军营”。[NEWLINE]+1 [ICON_Housing] 住房。解锁相应的市政或科技后即可生产军团和军队。完成时对相邻的单元格施放文化炸弹。伊坎达和其中的建筑+2 [ICON_PRODUCTION] 生产力、+2 [ICON_SCIENCE] 科技值。创建军团和军队的价格变为标准价格的75%。[NEWLINE]对陆地军事单位+30% 建造速度。此城中训练的所有抗骑兵单位+1 [ICON_Movement] 移动力。本城改良的战略资源+1 [ICON_Science] 科技值，正确改良的战略每回合积累+2。"),
	("zh_Hans_CN",	"LOC_DISTRICT_THANH_HD_DESCRIPTION",							 					"越南特色区域，取代“军营”。[NEWLINE]每与2个区域相邻+1 [ICON_PRODUCTION] 生产力。产出等同于 [ICON_PRODUCTION] 生产力相邻加成的 [ICON_CULTURE] 文化值。研究完“飞行”科技后，将获得与 [ICON_PRODUCTION] 生产力产量相等的 [ICON_TOURISM] 旅游业绩。所在城市可以无视 [ICON_CITIZEN] 人口限制额外建造1个区域。建造花费更低、无法建在市中心周围。[NEWLINE]对陆地军事单位+10%建造速度。本城改良的战略资源+1 [ICON_Science] 科技值，正确改良的战略每回合积累+2。"),
	-- 政府区
	("zh_Hans_CN",	"LOC_DISTRICT_GOVERNMENT_HD_DESCRIPTION",						 				"城市中专注于政治活动与国家管理的区域。[NEWLINE]使此城每回合的忠诚度+8、使相邻区域获得的相邻加成+1。[NEWLINE]奖励1个 [ICON_GOVERNOR] 总督头衔。"),
	-- 外交区
	("zh_Hans_CN",	"LOC_DISTRICT_DIPLOMATIC_QUARTER_HD_DESCRIPTION",						"城市中专注于外交活动与国家安全的区域。[NEWLINE]所有盟友的同盟点数每回合额外增加0.25点。其他文明的每个代表团或大使馆将为您的文明提供+1 [ICON_FAVOR] 外交支持。获得1名 [ICON_ENVOY] 使者。+1间谍容量，允许招募间谍（如果您尚未解锁）。将此区域和相邻区域当做目标的敌方间谍降低2级。使相邻区域获得的相邻加成+1。"),
	-- 水渠
	("zh_Hans_CN",	"LOC_DISTRICT_AQUEDUCT_HD_DESCRIPTION",											"从相邻河流、湖泊、绿洲或山脉引水，为城市提供淡水资源的区域。[NEWLINE]+1 [ICON_FOOD] 食物。若相邻山脉单元格，则+1 [ICON_PRODUCTION] 生产力。若相邻或位于地热裂缝单元格，则+1 [ICON_Science] 科技值。[NEWLINE]没有淡水资源的城市最多获得6个 [ICON_Housing] 住房。相反，已有淡水资源的城市 [ICON_Housing] 住房数量+2。干旱时可防止 [ICON_Food] 食物损失。[NEWLINE]必须修建在与市中心相邻的单元格中。[NEWLINE]军事工程师可消耗1次使用次数来完成水渠30%的修建进度。"),
	("zh_Hans_CN",	"LOC_DISTRICT_BATH_HD_DESCRIPTION",													"罗马特色区域，取代“水渠“。[NEWLINE]提供+1 [ICON_FOOD] 食物、+2 [ICON_Housing] 住房和+1 [ICON_Amenities] 宜居度。若相邻山脉单元格，则+1 [ICON_PRODUCTION] 生产力。若相邻或位于地热裂缝单元格，则+1 [ICON_Science] 科技值。[NEWLINE]从相邻河流、湖泊、绿洲或山脉引水，为该城市提供淡水资源。尚未拥有淡水资源的城市最多获得6个 [ICON_Housing] 住房。已有淡水资源的城市则+2 [ICON_Housing] 住房。干旱时可防止 [ICON_Food] 食物损失。[NEWLINE]必须修建在与市中心相邻的单元格中。[NEWLINE]军事工程师可消耗1次使用次数来完成浴场30%的修建进度。"),
	-- 运河
	("zh_Hans_CN",	"LOC_DISTRICT_CANAL_HD_DESCRIPTION",							 					"城市中专注于沟通水域与促进水运的区域。[NEWLINE]为相邻的单改良设施+6 [ICON_Gold] 金币。如 [ICON_TradeRoute] 贸易路线途径此处，其将从目的地的区域处获得成倍 [ICON_Gold] 金币。[NEWLINE]只能建造在平原上。运河可笔直穿过单元格，也可在其中进行60度转向，连接两块水域单元格或将一块水域单元格与市中心连接。无法建造三向连接运河，且运河在其所建水路的两侧皆必须含有一个完整的陆地单元格。[NEWLINE]军事工程师可消耗1次使用次数来完成运河30%的修建进度。"),
	-- 堤坝
	("zh_Hans_CN",	"LOC_DISTRICT_DAM_HD_DESCRIPTION",													"城市中专注于改善江河流域旁民生质量的区域。[NEWLINE]为相邻的改良设施+1 [ICON_Food] 食物和+1 [ICON_PRODUCTION] 生产力。其可防止江河泛滥带来的损害，但来自洪水的产出减半。还可在干旱时防止 [ICON_Food] 食物损失。[NEWLINE]只能建造在沿河的泛滥平原上，且江河必须至少穿过堤坝格位的两个面。每条江河的泛滥平原中仅能建造1个（有文明建成便视为已建造）。[NEWLINE]军事工程师可消耗1次使用次数来完成堤坝30%的修建进度。"),
	-- 保护区
	("zh_Hans_CN",	"LOC_DISTRICT_PRESERVE_HD_DESCRIPTION",											"城市中专注于环境与生态保护的区域。[NEWLINE]+1 [ICON_FOOD] 食物。[NEWLINE]对相邻的中立单元格施放文化炸弹。可以建造在森林、雨林或沼泽上。本城的地貌不再降低魅力。[NEWLINE][NEWLINE]文明中首次建成4种不同的专局建筑后，+1通配符政策槽位。"),
	-- 娱乐中心
	("zh_Hans_CN",	"LOC_DISTRICT_ENTERTAINMENT_COMPLEX_HD_DESCRIPTION",			 	"城市中专注于宜居性与娱乐活动的区域。[NEWLINE]+2 [ICON_Amenities] 宜居度。相邻奇观或社区时额外+1 [ICON_Amenities] 宜居度。"),
	("zh_Hans_CN",	"LOC_DISTRICT_WATER_ENTERTAINMENT_COMPLEX_HD_DESCRIPTION",	"城市中专注于宜居性与娱乐活动的区域。[NEWLINE]必须修建在和陆地相邻的浅海与湖泊单元格上。+2 [ICON_Amenities] 宜居度。相邻奇观或社区时额外+1 [ICON_Amenities] 宜居度。"),
	("zh_Hans_CN",	"LOC_DISTRICT_WATER_STREET_CARNIVAL_HD_DESCRIPTION",			 	"巴西特色区域，取代“水上乐园”。[NEWLINE]必须修建在和陆地相邻的浅海与湖泊单元格上。+2 [ICON_Amenities] 宜居度。相邻奇观或社区时额外+1 [ICON_Amenities] 宜居度。[NEWLINE][NEWLINE]相邻的区域+1 [ICON_FOOD] 食物。首次招募一种类型的 [ICON_GREATPERSON] 伟人时该区域获得对应产出。可以用 [ICON_FAITH] 信仰值购买其中建筑。"),
	("zh_Hans_CN",	"LOC_DISTRICT_STREET_CARNIVAL_HD_DESCRIPTION",							"巴西特色区域，取代“娱乐中心”。[NEWLINE]+2 [ICON_Amenities] 宜居度。相邻奇观或社区时额外+1 [ICON_Amenities] 宜居度。[NEWLINE][NEWLINE]相邻的区域+1 [ICON_FOOD] 食物。首次招募一种类型的 [ICON_GREATPERSON] 伟人时该区域获得对应产出。可以用 [ICON_FAITH] 信仰值购买其中建筑。"),
	("zh_Hans_CN",	"LOC_DISTRICT_HIPPODROME_HD_DESCRIPTION",										"拜占庭特色区域，取代“娱乐中心”。[NEWLINE]+2 [ICON_Amenities] 宜居度。相邻牧场或营地时额外+1 [ICON_Amenities] 宜居度。从每个相邻的资源获得+1 [ICON_Culture] 文化值。[NEWLINE][NEWLINE]首次建成后解锁“马鞍”科技。建成跑马场及其中的建筑时，将获得一个无需消耗资源维护的重骑兵单位。"),
	-- 社区
	("zh_Hans_CN",	"LOC_DISTRICT_NEIGHBORHOOD_HD_DESCRIPTION",									"城市中专注于公民活动与社区服务的区域。[NEWLINE]基于单元格的魅力提供住房，情况如下：[NEWLINE]惊艳的：+5 [ICON_HOUSING] 住房。[NEWLINE]迷人的：+4 [ICON_HOUSING] 住房。[NEWLINE]普通的：+3 [ICON_HOUSING] 住房。[NEWLINE]无吸引力的：+2 [ICON_HOUSING] 住房。[NEWLINE]令人厌恶的：+1 [ICON_HOUSING] 住房。"),
	("zh_Hans_CN",	"LOC_DISTRICT_MBANZA_HD_DESCRIPTION",												"刚果特色区域，取代“社区”。[NEWLINE]只能建在雨林或树林里。无视魅力值，固定提供+3 [ICON_Housing] 住房、+2 [ICON_Food] 食物和+2 [ICON_Gold] 金币。为相邻的单元格提供 +1 [ICON_FOOD] 食物。从每个相邻的加成资源获得+1 [ICON_PRODUCTION] 生产力；从每个相邻的奢侈品资源获得+2 [ICON_Gold] 金币；从每个相邻的战略资源获得+1 [ICON_Science] 科技值。允许使用 [ICON_Faith] 信仰值购买开拓者和建造者。"),
 	-- 航空港
	("zh_Hans_CN",	"LOC_DISTRICT_AERODROME_HD_DESCRIPTION",						 				"城市中专注于空军活动与民航服务的区域。[NEWLINE]不能建在丘陵上。建造空中单位时，+25%建造速度。");