--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                         Text)
values
    ("LOC_BELIEF_ONE_WITH_NATURE_NAME",                           "One with Nature"),
    ("LOC_BELIEF_ONE_WITH_NATURE_DL_DESCRIPTION",                 "+6 [ICON_GreatProphet] Great Prophet points per turn, and +3 [ICON_AMENITIES] Amenity for cities having at least one natural wonder tile."),
    ("LOC_BELIEF_RIVER_GODDESS_DL_DESCRIPTION",                   "Major adjacency bonus for Holy Site if next to a River. +2 [ICON_Amenities] Amenity and +2 [ICON_Housing] Housing to cities if they have a Holy Site district adjacent to a River. +2 [ICON_GreatProphet] Great Prophet points per turn if a city is located adjacent to a River."),
    ("LOC_BELIEF_GOD_OF_WAR_DL_DESCRIPTION",                      "Combat units receive +2 [ICON_Strength] combat strength when attack. Bonus [ICON_SCIENCE] Scienc equal to 40% of the base strength of each combat unit killed (on Standard Speed). Receive [ICON_GREATGENERAL] Great General points equal to 25% of the opposing unit's base strength (on Standard Speed) when a combat unit defeats a major or minor civilization's unit."),
    ("LOC_ABILITY_GOD_OF_WAR_GREAT_GENERAL_NAME",                 "Great General points"),
    ("LOC_ABILITY_GOD_OF_WAR_GREAT_GENERAL_DESCRIPTION",          "Receive [ICON_GREATGENERAL] Great General points when a combat unit defeats a major or minor civilization's unit equal to 25% of the opposing unit's strength (Standard Speed). (God of War Belief)"),
    ("LOC_GOD_OF_WAR_GREAT_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT","God of War Belief"),
    ("LOC_BELIEF_MONUMENT_TO_THE_GODS_DL_DESCRIPTION",            "When chosen, receive a free Monument in your capital. Monument provides +1 [ICON_CULTURE] Culture and +10% [ICON_Culture] Culture to the city. May purchase Monument with [ICON_Faith] Faith."),
    ("LOC_BELIEF_FERTILITY_RITES_DL_DESCRIPTION",                 "When chosen, receive a free Granary in your capital. Granary provides +1 [ICON_FOOD] Food and +10% growth rate to the city. [ICON_Food] Food consumption of [ICON_Citizen] citizens is reduced by 0.3 in City with Granary. May purchase Granary with [ICON_Faith] Faith."),
    ("LOC_BELIEF_CITY_PATRON_GODDESS_DL_DESCRIPTION",             "When chosen, receive a builder unit in your [ICON_CAPITAL] Capital. +1 [ICON_FOOD] Food, +75% [ICON_Production] Production towards Districts in cities without a Specialty district."),
    ("LOC_BELIEF_MESSENGER_OF_THE_GODS_NAME",                     "Messenger of the Gods"),
    ("LOC_BELIEF_MESSENGER_OF_THE_GODS_DL_DESCRIPTION",           "When chosen, receive a Recon unit with one free promotion in your [ICON_Capital] Capital. +1 [ICON_Movement] Movement for all Recon Units."),
    ("LOC_BELIEF_GOD_OF_THE_OPEN_SKY_DL_DESCRIPTION",             "+1 [ICON_Production] Production and +1 [ICON_Culture] Culture from Pastures."),
    ("LOC_BELIEF_ORAL_TRADITION_DL_DESCRIPTION",                  "+1 [ICON_Food] Food and +1 [ICON_Culture] Culture from Plantations."),
    ("LOC_BELIEF_LADY_OF_THE_REEDS_AND_MARSHES_DL_DESCRIPTION",   "+1 [ICON_Production] Production from Grassland Floodplains. +1 [ICON_FOOD] Food from Plain Floodplains. +2 [ICON_Production] Production and +1 [ICON_Science] Science from Marsh."),-- Floodplain tiles no longer lower adjacent tiles' Appeal.
    ("LOC_BELIEF_GODDESS_OF_THE_HUNT_DL_DESCRIPTION",             "Camps over Luxury and Bonus resources provide +1 [ICON_Food] Food and +1 [ICON_Production] Production."),
    ("LOC_BELIEF_DIVINE_SPARK_DL_DESCRIPTION",                    "+3 corresponding [ICON_GREATPERSON] Great Person Points for each Districts. Your [ICON_CAPITAL] capital can build 1 more district than the [ICON_CITIZEN] Population limit allows."),
    ("LOC_BELIEF_STONE_CIRCLES_DL_DESCRIPTION",                   "Quarries provide +1 [ICON_Faith] Faith and +1 [ICON_SCIENCE] Science. Cities having Quarries provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_RELIGIOUS_IDOLS_DL_DESCRIPTION",                 "+1 [ICON_Faith] Faith and +1 [ICON_CULTURE] Culture from Mines over resources. +2 [ICON_GreatProphet] Great Prophet points per turn for cities having mines over resources."),
    ("LOC_BELIEF_EARTH_GODDESS_DL_DESCRIPTION",                   "+2 [ICON_Faith] Faith from tiles with Breathtaking Appeal. +1 [ICON_Faith] Faith from tiles with Charming Appeal. +2 [ICON_GreatProphet] Great Prophet points per turn if a city is located on a Charming tile, doubles for Breathtaking tile."),
    ("LOC_BELIEF_GODDESS_OF_FIRE_DL_DESCRIPTION",                 "Geothermal Fissures and improved Volcanic Soil provide +1 [ICON_FAITH] Faith and +1 [ICON_CULTURE] Culture. Cities having Geothermal Fissures, Volcanic Soil or Volcano (Volcanic Wonders included) tiles provide +3 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_THE_PEOPLE_OF_POLAR_NAME",                       "The People of Polar"),
    ("LOC_BELIEF_THE_PEOPLE_OF_POLAR_DL_DESCRIPTION",             "+1 [ICON_PRODUCTION] Production, +2 [ICON_GOLD] Gold to Improvements over resource on Tundra."),
    ("LOC_BELIEF_GODDESS_OF_THE_DESERT_NAME",                     "Goddess of the Desert"),
    ("LOC_BELIEF_GODDESS_OF_THE_DESERT_DL_DESCRIPTION",           "City centers provide +1 [ICON_Food] Food and +1 [ICON_Faith] Faith for each adjacent Desert or Desert Hills tile. Cities having Desert or Desert Hills tiles provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_RELIGIOUS_SETTLEMENTS_DL_DESCRIPTION",           "+25% [ICON_PRODUCTION] Production toward Settlers. +1 [ICON_MOVEMENT] Movement to Settlers. Gain 30 [ICON_GREATPROPHET] Great Prophet points and 4 extra tiles upon founding cities."),
    ("LOC_BELIEF_DANCE_OF_THE_AURORA_DL_DESCRIPTION",             "Holy Site districts get minor adjacency bonus from Tundra and Tundra Hills. Holy Site provides +1 [ICON_Food] Food and +1 [ICON_CULTURE] Culture to adjacent Tundra tiles. +2 [ICON_GreatProphet] Great Prophet point per turn if Holy Site is located on Tundra or Tundra Hills tiles."),
    ("LOC_BELIEF_DESERT_FOLKLORE_DL_DESCRIPTION",                 "Holy Site districts get standard adjacency bonus from Desert and Desert Hills. Holy Site provides +1 [ICON_Food] Food and +1 [ICON_Faith] Faith to all adjacent Desert tiles when not pillaged. +2 [ICON_GreatProphet] Great Prophet points per turn if Holy Site is located on Desert or Desert Hills tiles."),
    ("LOC_BELIEF_SACRED_PATH_DL_DESCRIPTION",                     "Holy Site districts get standard adjacency bonus from Rainforest. Holy Site provides +1 [ICON_Culture] Culture to all adjacent Rainforest tiles when not pillaged. +2 [ICON_GreatProphet] Great Prophet points per turn if Holy Site is adjacent to Rainforest tiles."),
    ("LOC_BELIEF_VOODOO_NAME",                                    "Voodoo"),
    ("LOC_BELIEF_VOODOO_DL_DESCRIPTION",                          "City centers provide +1 [ICON_Production] Production for each adjacent Rainforest tile, +1 [ICON_Culture] Culture from every two adjacent Rainforest tiles."),
    ("LOC_BELIEF_GODDESS_OF_FESTIVALS_DL_DESCRIPTION",            "Plantations provide +1 [ICON_Production] Production and +1 [ICON_FAITH] Faith. Cities having Plantations provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_TENGRI_NAME",                                    "Tengri"),
    ("LOC_BELIEF_TENGRI_DL_DESCRIPTION",                          "Pastures provide +1 [ICON_FOOD] Food and +1 [ICON_Faith] Faith. Cities having Pastures provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_GODDESS_OF_THE_HARVEST_DL_DESCRIPTION",          "Farms over resource provide +1 [ICON_Food] Food and +1 [ICON_Production] Production."),
    ("LOC_BELIEF_GOD_OF_THE_SEA_DL_DESCRIPTION",                  "Fishing Boats provide +1 [ICON_Food] Food. +2 [ICON_GOLD] Golds to Fishing Boats that inprove Luxury resources. Cities having Fishing Boats provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_OCEAN_MOTHER_DL_DESCRIPTION",                    "City center receive +1 [ICON_Food] Food and +1 [ICON_Faith] Faith from each adjacent Shallow Sea and Lake tile. +2 [ICON_GreatProphet] Great Prophet point per turn for cities adjacent to Shallow Sea. +1 [ICON_FOOD] Food to Shallow Sea and Lake tiles in city with a Holy Site district."),
    ("LOC_BELIEF_OCEAN_MOTHER_NAME",                              "Ocean Mother"),
    ("LOC_BELIEF_HD_DRUID_NAME",                                  "Druid"),
    ("LOC_BELIEF_HD_DRUID_DL_DESCRIPTION",                        "Forest tiles provide +1 [ICON_Food] Food. Rainforest tiles provide +1 [ICON_Production] Production."),
    ("LOC_BELIEF_PATHFINDER_OF_THE_WASTELAND_NAME",               "Pathfinder of the WasteLand"),
    ("LOC_BELIEF_PATHFINDER_OF_THE_WASTELAND_DESCRIPTION",        "+1 [ICON_Production] Production from flat Desert tiles. Additional +1 [ICON_Production] Production to Oasis. "),
    ("LOC_BELIEF_HD_MAZU_BELIEF_NAME",                            "Mazu Belief"),
    ("LOC_BELIEF_HD_MAZU_BELIEF_DL_DESCRIPTION",                  "Cities adjacent to Coasts get +2 [ICON_Production] Production and +2 [ICON_HOUSING] Housing. Harbor district provides +2 [ICON_PRODUCTION] Production. +1 [ICON_CULTURE] Culture to Fishing Boats adjacent to any district."), 
    ("LOC_BELIEF_FISHING_TRADITION_NAME",                         "Fishing Traidition"),
    ("LOC_BELIEF_FISHING_TRADITION_DL_DESCRIPTION",               "+1 [ICON_Production] Production to Fishing Boats. +1 [ICON_FOOD] Food to Fishing Boats over Bonus resource "),
    ("LOC_BELIEF_HD_GOD_KING_NAME",                               "God King"),
    ("LOC_BELIEF_HD_GOD_KING_DL_DESCRIPTION",                     "Palace provides +1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production, +1 [ICON_CULTURE] Culture, +1 [ICON_SCIENCE] Science, +1 [ICON_FAITH] Faith and +1 [ICON_GOLD] Gold. When chosen, receive a [ICON_CITIZEN] Citizen in your [ICON_CAPITAL] capital and a free [ICON_ENVOY] envoy. +1 [ICON_AMENITIES] Amenity and +1 [ICON_HOUSING] Housing in your capital."),
    ("LOC_BELIEF_GOD_OF_CRAFTSMEN_EXPANSION2_DESCRIPTION",        "+1 [ICON_Production] Production and +3 [ICON_Gold] Gold from improved Strategic resources. Reveals [ICON_RESOURCE_HORSES] Horses and [ICON_RESOURCE_IRON] Iron without the normal technology requirement. Properly improved Strategic resources provide an additional +1 per turn."),
    ("LOC_BELIEF_GOD_OF_THE_FORGE_DESCRIPTION",                   "+50% [ICON_PRODUCTION] Production toward Ancient, Classical and Medieval military units. Unit maintenance reduced by 1 [ICON_GOLD] Gold per turn, per unit. Receive 40% discount on Strategic resource costs for units."),
    ("LOC_BELIEF_HD_HERMES_NAME",                                 "Hermes"),
    ("LOC_BELIEF_HD_HERMES_DL_DESCRIPTION",                       "+1 [ICON_TradeRoute] Trade Route capacity and receive a free Trader in the capital. +1 [ICON_GOLD] Gold to all your Trade Routes."),
    ("LOC_BELIEF_HD_POSTERITY_OF_MOUNTAIN_NAME",                  "Posterity of Mountain"),
    ("LOC_BELIEF_HD_POSTERITY_OF_MOUNTAIN_DL_DESCRIPTION",        "Campus and Holy Site districts receive additional standard adjacency bonus from Mountains. Cities having Mountains provide +2 [ICON_GreatProphet] Great Prophet points per turn. Cities adjacent to Mountains receive +1 [ICON_Amenities] Amenity and +1 [ICON_Housing] Housing."),
    ("LOC_BELIEF_HD_SONG_OF_SIREN_NAME",                          "Song of Siren"),
    ("LOC_BELIEF_HD_SONG_OF_SIREN_DL_DESCRIPTION",                "+2 [ICON_Production] Production, +1 [ICON_GOLD] Gold from Reefs."),
    ("LOC_BELIEF_HD_UTAKI_NAME",                                  "Utaki"),
    ("LOC_BELIEF_HD_UTAKI_DL_DESCRIPTION",                        "+1 [ICON_FOOD] Food and +1 [ICON_PRODUCTION] Production from tiles adjacent to Harbor Districts."),
    ("LOC_BELIEF_HD_WOLF_GOD_NAME",                               "Lupercal"),
    ("LOC_BELIEF_HD_WOLF_GOD_DL_DESCRIPTION",                     "Camps over Luxury and Bonus resources provide +1 [ICON_CULTURE] Culture and +1 [ICON_Faith] Faith. Cities having Camps over Luxury or Bonus resources provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_HD_SUN_GOD_NAME",                                "Apollo"),
    ("LOC_BELIEF_HD_SUN_GOD_DL_DESCRIPTION",                      "Farms provide +1 [ICON_Food] Food. Cities having Farm over resource provide +2 [ICON_GreatProphet] Great Prophet points per turn."),
    ("LOC_BELIEF_SPARTA_SPIRIT_NAME",                             "Militarism"),
    ("LOC_BELIEF_SPARTA_SPIRIT_DESCRIPTION",                      "+50% [ICON_PRODUCTION] Production toward Ancient, Classical and Medieval military units. Receive 40% discount on Strategic resource costs for units."),
    ("LOC_BELIEF_TALE_OF_DWALVES_NAME",                           "El Dorado"),
    ("LOC_BELIEF_TALE_OF_DWALVES_DESCRIPTION",                    "+1 [ICON_FOOD] Food and +1 [ICON_HOUSING] Housing from Mines over resources. +2 [ICON_GOLD] Gold from all Mines."),
    ("LOC_BELIEF_MEGALITHIC_WORSHIP_NAME",                        "Tjukurpa"),
    ("LOC_BELIEF_MEGALITHIC_WORSHIP_DESCRIPTION",                 "Quarries provide +1 [ICON_Food] Food and +1 [ICON_Culture] Culture."),
    ("LOC_BELIEF_ILLUMINATORS_NAME",                              "Illuminators"),
    ("LOC_BELIEF_ILLUMINATORS_DESCRIPTION",                       "When chosen, receive a Recon unit with free promotion in your [ICON_Capital] Capital. +1 [ICON_Movement] Movement for all Recon Units. +5 [ICON_STRENGTH] Combat Strength for all units when fighting Barbarians. Gain 50 [ICON_FAITH] Faith when you clear a Barbarian Outpost. The unit that cleared the Barbarian Outpost heals +100 HP."),
    ("LOC_ABILITY_STARLIGHT_NAVIGATER_DESCRIPTION",              "+1 [ICON_MOVEMENT] Movement. +5 [ICON_STRENGTH] Combat Strength. Escorted units move at the same speed."),
    ("LOC_BELIEF_STARLIGHT_NAVIGATER_NAME",                       "Starlight Navigater"),
    ("LOC_BELIEF_STARLIGHT_NAVIGATER_DESCRIPTION",               "Coastal Capital grain a Nacal Raider unit with a free Promotion. Nacal Raider units +1 [ICON_MOVEMENT] Movement and +5 [ICON_STRENGTH] Combat Strength and share its [ICON_MOVEMENT] Movement with all units in the formation."),
    ("LOC_BELIEF_ITANG_NAME",                                    "Itang"),
    ("LOC_BELIEF_ITANG_DESCRIPTION",                             "City Centers gain +1 [ICON_PRODUCTION] Production for every adjacent Shallow Sea and Lake tile. City Centers gain +1 [ICON_CULTURE] Culture for every 2 adjacent Shallow Sea and Lake tiles. +1 [ICON_AMENITIES] Amenity to coastal cities.");
    -- ("LOC_BELIEF_HD_DIONYSIAN_MYSTERIES_NAME",                   "Dionysian Mysteries"),
    -- ("LOC_BELIEF_HD_DIONYSIAN_MYSTERIES_DESCRIPTION",            "When chosen, receive a free Cellar in your capital. Cellar provides +2 [ICON_FOOD] Food and +1 [ICON_AMENITIES] Amenity to the city. May purchase Cellar with [ICON_Faith] Faith.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                         Text)
values
    ("zh_Hans_CN",  "LOC_BELIEF_ONE_WITH_NATURE_NAME",                           "天人合一"),
    ("zh_Hans_CN",  "LOC_BELIEF_ONE_WITH_NATURE_DL_DESCRIPTION",                 "拥有自然奇观的城市+3 [ICON_AMENITIES] 宜居度，且每回合+6 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_RIVER_GODDESS_DL_DESCRIPTION",                   "与河流相邻时，圣地获得大量相邻加成。如果拥有与河流相邻的圣地区域，则城市+2 [ICON_Amenities] 宜居度、+2 [ICON_Housing] 住房。如城市市中心坐落在河边，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_WAR_DL_DESCRIPTION",                      "战斗单位攻击时+2 [ICON_Strength] 战斗力。每击杀1个战斗单位即可获得等于其战斗力40%的 [ICON_SCIENCE] 科技值（标准速度下）。战斗单位击杀主要和小型文明的单位时，获得等同于对方单位战斗力25%的 [ICON_GREATGENERAL] 大将军点数（标准速度下）。"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOD_OF_WAR_GREAT_GENERAL_NAME",                 "大将军点数"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOD_OF_WAR_GREAT_GENERAL_DESCRIPTION",          "战斗单位击杀主要和小型文明的单位时，获得等同于对方单位战斗力25%的 [ICON_GREATGENERAL] 大将军点数（标准速度下）。（战争之神）"),
    ("zh_Hans_CN",  "LOC_GOD_OF_WAR_GREAT_COMBAT_STRENGTH_MODIFIER_PREVIEW_TEXT","战争之神"),
    ("zh_Hans_CN",  "LOC_BELIEF_MONUMENT_TO_THE_GODS_DL_DESCRIPTION",            "选择后即可在首都中获得一个免费的纪念碑。纪念碑+1 [ICON_CULTURE] 文化值，给所在城市提供+10% [ICON_Culture] 文化值。可以使用 [ICON_Faith] 信仰值购买纪念碑。"),
    ("zh_Hans_CN",  "LOC_BELIEF_FERTILITY_RITES_DL_DESCRIPTION",                 "选择后即可在首都中获得一个免费的粮仓。粮仓+1 [ICON_FOOD] 食物。拥有粮仓的城市+10%余粮。粮仓可使城市每 [ICON_Citizen] 市民消耗的 [ICON_Food] 食物减少0.3。可以使用 [ICON_Faith] 信仰值购买粮仓。"),
    ("zh_Hans_CN",  "LOC_BELIEF_CITY_PATRON_GODDESS_DL_DESCRIPTION",             "选择后在首都中获得1个建造者单位。没有专业化区域的城市所有区域+1 [ICON_FOOD] 食物，建造区域+75%建造速度。"),
    ("zh_Hans_CN",  "LOC_BELIEF_MESSENGER_OF_THE_GODS_NAME",                     "神使"),
    ("zh_Hans_CN",  "LOC_BELIEF_MESSENGER_OF_THE_GODS_DL_DESCRIPTION",           "选择后即可在首都中获得1个有免费晋升的侦察单位。所有侦察类型的单位+1 [ICON_Movement] 移动力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_THE_OPEN_SKY_DL_DESCRIPTION",             "牧场+1 [ICON_Production] 生产力和 +1 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_BELIEF_ORAL_TRADITION_DL_DESCRIPTION",                  "种植园+1 [ICON_Food] 食物和+1 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_BELIEF_LADY_OF_THE_REEDS_AND_MARSHES_DL_DESCRIPTION",   "平原泛滥平原提供+1 [ICON_Food] 食物,草原泛滥平原提供+1 [ICON_Production] 生产力。沼泽提供+1 [ICON_Production] 生产力和+1 [ICON_Science] 科技值。"),-- 泛滥平原不再为相邻单元格-1魅力。
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_THE_HUNT_DL_DESCRIPTION",             "改良奢侈品资源和加成资源的营地+1 [ICON_Food] 食物和 +1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_DIVINE_SPARK_DL_DESCRIPTION",                    "每个区域提供+3对应 [ICON_GreatPerson] 伟人点数。首都可以无视 [ICON_CITIZEN] 人口限制额外建造1个区域。"),
    ("zh_Hans_CN",  "LOC_BELIEF_STONE_CIRCLES_DL_DESCRIPTION",                   "采石场+1 [ICON_SCIENCE] 科技值和+1 [ICON_Faith] 信仰值。如城市中有采石场，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_RELIGIOUS_IDOLS_DL_DESCRIPTION",                 "改良资源的矿山+1 [ICON_CULTURE] 文化值和+1 [ICON_FAITH] 信仰值。如城市拥有改良资源的矿山，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_EARTH_GODDESS_DL_DESCRIPTION",                   "魅力为惊艳的单元格提供的 [ICON_Faith] 信仰值+2。魅力为迷人的单元格提供的 [ICON_Faith] 信仰值+1。如城市市中心坐落在迷人单元格上，则每回合+2 [ICON_GreatProphet] 大预言家点数，惊艳则翻倍。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_FIRE_DL_DESCRIPTION",                 "地热裂缝和已改良的火山土单元格提供+1 [ICON_CULTURE] 文化值和+1 [ICON_FAITH] 信仰值。每座拥有地热裂缝、火山土或火山（包括火山自然奇观）的城市提供+3 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_THE_PEOPLE_OF_POLAR_NAME",                       "极地子民"),
    ("zh_Hans_CN",  "LOC_BELIEF_THE_PEOPLE_OF_POLAR_DL_DESCRIPTION",             "冻土上改良资源的改良设施+1 [ICON_PRODUCTION] 生产力、+2 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_THE_DESERT_NAME",                     "沙之女神"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_THE_DESERT_DL_DESCRIPTION",           "市中心每相邻1个沙漠或沙漠丘陵单元格，获得+1 [ICON_Food] 食物和+1 [ICON_Faith] 信仰值。如城市中有沙漠或沙漠丘陵，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_RELIGIOUS_SETTLEMENTS_DL_DESCRIPTION",           "建造开拓者+25%建造速度。开拓者+1 [ICON_MOVEMENT] 移动力。创建城市时获得+30点 [ICON_GREATPROPHET] 大预言家点数和额外4个单元格。"),
    ("zh_Hans_CN",  "LOC_BELIEF_DANCE_OF_THE_AURORA_DL_DESCRIPTION",             "圣地从冻土和冻土丘陵获得少量相邻加成。圣地给相邻的冻土单元格+1 [ICON_Food] 食物、+1 [ICON_CULTURE] 文化值。若圣地位于冻土或冻土丘陵则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_DESERT_FOLKLORE_DL_DESCRIPTION",                 "圣地从沙漠和沙漠丘陵获得标准相邻加成。未被劫掠过的圣地给相邻的沙漠单元格+1 [ICON_Food] 食物和+1 [ICON_Faith] 信仰值。若圣地位于沙漠或沙漠丘陵则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_SACRED_PATH_DL_DESCRIPTION",                     "圣地从雨林获得标准相邻加成。未被劫掠过的圣地给相邻的雨林单元格+1 [ICON_Culture] 文化。若圣地相邻雨林则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_VOODOO_NAME",                                    "伏都教"),
    ("zh_Hans_CN",  "LOC_BELIEF_VOODOO_DL_DESCRIPTION",                          "市中心每相邻1个雨林单元格，获得+1 [ICON_Production] 生产力；每相邻2个雨林单元格，获得+1 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_FESTIVALS_DL_DESCRIPTION",            "种植园+1 [ICON_Production] 生产力和+1 [ICON_FAITH] 信仰值。如城市中有种植园，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_TENGRI_NAME",                                    "长生天"),
    ("zh_Hans_CN",  "LOC_BELIEF_TENGRI_DL_DESCRIPTION",                          "牧场+1 [ICON_Food] 食物和+1 [ICON_Faith] 信仰值。如城市中有牧场，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GODDESS_OF_THE_HARVEST_DL_DESCRIPTION",          "改良资源的农场+1 [ICON_Food] 食物和+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_THE_SEA_DL_DESCRIPTION",                  "渔船+1 [ICON_FOOD] 食物。开发奢侈品资源的渔船+1 [ICON_SCIENCE] 科技值。如城市中有渔船，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_OCEAN_MOTHER_DL_DESCRIPTION",                    "市中心每相邻1个浅海与湖泊单元格，获得+1 [ICON_Food] 食物和+1 [ICON_Faith] 信仰值。有圣地的城市浅海与湖泊单元格+1 [ICON_FOOD] 粮食。相邻浅海的城市每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_OCEAN_MOTHER_NAME",                              "海洋母亲"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_DRUID_NAME",                                  "德鲁伊"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_DRUID_DL_DESCRIPTION",                        "森林单元格+1 [ICON_Food] 食物，雨林单元格+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_PATHFINDER_OF_THE_WASTELAND_NAME",               "荒原先驱"),
    ("zh_Hans_CN",  "LOC_BELIEF_PATHFINDER_OF_THE_WASTELAND_DESCRIPTION",        "平坦的沙漠提供+1 [ICON_PRODUCTION] 生产力，绿洲额外提供+1 [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_MAZU_BELIEF_NAME",                            "妈祖信仰"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_MAZU_BELIEF_DL_DESCRIPTION",                  "位于海边的城市+2 [ICON_Production] 生产力、+2 [ICON_HOUSING] 住房。港口+2 [ICON_Production] 生产力。相邻区域的渔船+1 [ICON_CULTURE] 文化值。"), 
    ("zh_Hans_CN",  "LOC_BELIEF_FISHING_TRADITION_NAME",                         "捕鱼传统"),
    ("zh_Hans_CN",  "LOC_BELIEF_FISHING_TRADITION_DL_DESCRIPTION",               "渔船+1 [ICON_Production] 生产力，改良加成资源的渔船额外+1 [ICON_FOOD] 食物。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_GOD_KING_NAME",                               "神王"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_GOD_KING_DL_DESCRIPTION",                     "宫殿+1 [ICON_FOOD] 食物、 +1 [ICON_PRODUCTION] 生产力、 +1 [ICON_CULTURE] 文化值、 +1 [ICON_SCIENCE] 科技值、 +1 [ICON_FAITH] 信仰值和 +1 [ICON_GOLD] 金币。选择后获得1 [ICON_ENVOY] 使者，首都获得1 [ICON_CITIZEN] 人口。首都+1 [ICON_AMENITIES] 宜居度、+1 [ICON_HOUSING] 住房。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_CRAFTSMEN_EXPANSION2_DESCRIPTION",        "改良后的战略资源+1 [ICON_Production] 生产力和+3 [ICON_Gold] 金币。忽略科技要求显示  [ICON_RESOURCE_HORSES] 马资源和 [ICON_RESOURCE_IRON] 铁资源。正确改良的战略资源每回合积累+1。"),
    ("zh_Hans_CN",  "LOC_BELIEF_GOD_OF_THE_FORGE_DESCRIPTION",                   "为远古、古典和中世纪军事单位+50% [ICON_PRODUCTION] 生产力。每回合、每单位的单位维护费用减少1 [ICON_GOLD] 金币。生产单位所需战略资源花费减少40%。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_HERMES_NAME",                                 "赫尔墨斯"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_HERMES_DL_DESCRIPTION",                       "选择后即可在首都中获得一个商人，+1 [ICON_TradeRoute] 贸易路线容量。所有 [ICON_TRADEROUTE] 贸易路线+1 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_POSTERITY_OF_MOUNTAIN_NAME",                  "山之苗裔"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_POSTERITY_OF_MOUNTAIN_DL_DESCRIPTION",        "学院和圣地靠山获得的加成翻倍，有山脉的城市+2 [ICON_GreatProphet] 大预言家点数，相邻山脉的市中心+1 [ICON_Housing] 住房，+1 [ICON_Amenities] 宜居度。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_SONG_OF_SIREN_NAME",                          "塞壬之歌"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_SONG_OF_SIREN_DL_DESCRIPTION",                "礁石单元格+2 [ICON_Production] 生产力和+1 [ICON_GOLD]金币。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_UTAKI_NAME",                                  "御岳"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_UTAKI_DL_DESCRIPTION",                        "相邻港口的单元格+1 [ICON_FOOD] 食物，+1 [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_WOLF_GOD_NAME",                               "牧狼神"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_WOLF_GOD_DL_DESCRIPTION",                     "改良奢侈品资源和加成资源的营地+1 [ICON_Culture] 文化值和+1 [ICON_Faith] 信仰值。如城市拥有改良奢侈或加成资源的营地，则每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_SUN_GOD_NAME",                                "太阳神"),
    ("zh_Hans_CN",  "LOC_BELIEF_HD_SUN_GOD_DL_DESCRIPTION",                      "农场+1 [ICON_Food] 粮食。拥有改良资源的农场的城市每回合+2 [ICON_GreatProphet] 大预言家点数。"),
    ("zh_Hans_CN",  "LOC_BELIEF_SPARTA_SPIRIT_NAME",                             "尚武精神"),
    ("zh_Hans_CN",  "LOC_BELIEF_SPARTA_SPIRIT_DESCRIPTION",                      "为远古、古典和中世纪军事单位+50% [ICON_PRODUCTION] 生产力。生产单位所需战略资源花费减少40%。"),
    ("zh_Hans_CN",  "LOC_BELIEF_TALE_OF_DWALVES_NAME",                           "黄金国传说"),
    ("zh_Hans_CN",  "LOC_BELIEF_TALE_OF_DWALVES_DESCRIPTION",                    "改良资源的矿山+1 [ICON_FOOD] 食物，+1 [ICON_HOUSING] 住房。所有矿山+2 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_BELIEF_MEGALITHIC_WORSHIP_NAME",                        "梦创时代"),
    ("zh_Hans_CN",  "LOC_BELIEF_MEGALITHIC_WORSHIP_DESCRIPTION",                 "采石场+1 [ICON_FOOD] 食物和+1 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_BELIEF_ILLUMINATORS_NAME",                              "启蒙会"),
    ("zh_Hans_CN",  "LOC_BELIEF_ILLUMINATORS_DESCRIPTION",                       "选择后在首都中获得1个有免费晋升的侦察单位。所有侦察单位+1 [ICON_Movement] 移动力。所有单位与 [ICON_Barbarian] 蛮族战斗时+5 [ICON_STRENGTH] 战斗力。摧毁 [ICON_Barbarian] 蛮族哨站时获得50点 [ICON_Faith] 信仰值，单位回复100点生命值。"),
    ("zh_Hans_CN",  "LOC_ABILITY_STARLIGHT_NAVIGATER_DESCRIPTION",              "+1 [ICON_MOVEMENT] 移动力。+5 [ICON_STRENGTH] 战斗力。被护送的单位将以同样的速度移动。"),
    ("zh_Hans_CN",  "LOC_BELIEF_STARLIGHT_NAVIGATER_NAME",                      "星光引航者"),
    ("zh_Hans_CN",  "LOC_BELIEF_STARLIGHT_NAVIGATER_DESCRIPTION",               "选择后在首都中获得1个有免费晋升的海军袭击者。海军袭击者+1 [ICON_MOVEMENT] 移动力 +5 [ICON_STRENGTH] 战斗力。被海军袭击者被护送的单位将以同样的速度移动。允许单位进入深海。"),
    ("zh_Hans_CN",  "LOC_BELIEF_ITANG_NAME",                                    "渔巫传统"),
    ("zh_Hans_CN",  "LOC_BELIEF_ITANG_DESCRIPTION",                             "市中心每相邻1个浅海与湖泊单元格，获得+1 [ICON_PRODUCTION] 生产力；市中心每相邻2个浅海与湖泊单元格+1 [ICON_CULTURE] 文化。沿海城市+1 [ICON_AMENITIES] 宜居度。");
    -- ("zh_Hans_CN",  "LOC_BELIEF_HD_DIONYSIAN_MYSTERIES_NAME",                   "酒神秘仪"),
    -- ("zh_Hans_CN",  "LOC_BELIEF_HD_DIONYSIAN_MYSTERIES_DESCRIPTION",            "选择后即可在首都中获得一个免费的酒窖。酒窖+2 [ICON_PRODUCTION] 生产力。拥有酒窖的城市+1 [ICON_AMENITIES] 宜居度。可以使用 [ICON_Faith] 信仰值购买酒窖。");
