--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                                 Text)
values
    ("LOC_GREATPERSON_CHARLES_DARWIN_ACTIVE",                             "Gain +1000 [ICON_Science] Science (on Standard speed) for each Natural Wonder tile here or adjacent."),
    ("LOC_GREATPERSON_GALILEO_GALILEI_ACTIVE",                            "Gain +400 [ICON_Science] Science (on Standard speed) for each adjacent Mountain tile."),
    ("LOC_GREAT_PERSON_GRANT_LOTSO_SCIENCE",                              "Gain +3000 [ICON_SCIENCE] Science and +1000 [ICON_CULTURE] Culture (on Standard speed)."),
    ("LOC_GREATPERSON_DIPLO_VISIBILITY",                                  "+{Amount} {Amount : plural 1?level; other?levels;} of diplomatic visibility with all other civilizations. Enemy Spy level reduced by 1 in your lands."),
    ("LOC_GREATPERSON_REGIONAL_RANGE_BONUS",                              "Regional effects of Industrial Zone buildings reach 3 tile farther.[NEWLINE]Industrial Zone regional buildings provide +2 [ICON_SCIENCE] Science with its regional effect."),
	("LOC_PIERO_DE_BARDI_GOLD",                                           "Gain 300 [ICON_Gold] Gold."),
	("LOC_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_NAME",                   "Sanctus Leo PP. I"),
	-- Great Merchant
	("LOC_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_NAME",						  "Croesus"),
	("LOC_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_NAME",			      "Sang Hongyang"),
	("LOC_GREAT_PERSON_INDIVIDUAL_HD_ALI_MUGHAYAT_SYAH_NAME",			  "Malik al-Saleh"),
	("LOC_COLAEUS_SETTLER_PRODUCTION",									  "+25% construction speed towards Settlers in this city."),
	("LOC_COLAEUS_SETTLER_MOVEMENT",							    	  "+1 [ICON_MOVEMENT] Movement for Settlers."),
	("LOC_MARCUS_LICINIUS_CRASSUS_SWORDSMAN",							  "Grants 1 Swordsman units."),
	("LOC_MARCUS_LICINIUS_CRASSUS_IRON",								  "Grants 1 [ICON_RESOURCE_IRON] Iron per turn."),
	("LOC_ZHANG_QIAN_GRANT_TRADER",								 		  "Grants a free Trader."),
	("LOC_GREATPERSON_FREE_TRADER_UNIT",								  "Grants a free Trader."),
	("LOC_GREATPERSON_HAVE_A_FREE_TRADE_ROUTE",							  "Increases [ICON_TRADEROUTE] Trade Route capacity by 1."),
	("LOC_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_ACTIVE",					  "Instantly builds a Fair and a Market in this district.[NEWLINE]Provides +3 [ICON_GOLD] Gold to Tier 2 buildings in Commercial Hub districts."),
	("LOC_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_ACTIVE",				  "Instantly builds a Fair and a Mint in this district.[NEWLINE]Mint provides +1 [ICON_CULTURE] Culture with its regional effect.[NEWLINE]Regional effects of this Commercial Hub reach 1 tile farther."),
	("LOC_MARCO_POLO_NOTHING",				  			 				  "Triggers the [ICON_CIVICBOOSTED] Inspiration of 'Exploration' Civic."),
	("LOC_ZHOU_DAGUAN_COMMERCIAL_ATTACH",				  			  	  "+1 [ICON_ENVOY] Envoy for each Commercial Hub."),
	("LOC_ALI_MUGHAYAT_SYAH_SETTLER",				  			  		  "Grants a Settler."),
	("LOC_ALI_MUGHAYAT_SYAH_BUILDER",				  			  		  "Grants a Builder."),
	("LOC_JAKOB_FUGGER_GOLD",				  			  		 		  "Gain 400 [ICON_GOLD] Gold."),
	("LOC_JAKOB_FUGGER_COMMERCIAL_ADJACENCY",				  			  "Commercial Hub receives an additional standerd adjacency bonus from districts."),
	("LOC_JOHN_JACOB_ASTOR_INDUSTRIAL_ADJACENCY",				  			  "Industrial Zone receives an additional standerd adjacency bonus from districts."),
    ("LOC_DISTRICT_DISTRICT_1_GOLD",                                      "+{1_num} [ICON_GOLD] Gold from the adjacent Districts."),
    ("LOC_DISTRICT_DISTRICT_1_PRODUCTION",                                "+{1_num} [ICON_PRODUCTION] Production from the adjacent Districts."),
	("LOC_GREATPERSON_INFLUENCE_TOKENS_LARGE",				  			  "Gain 3 [ICON_ENVOY] Envoys."),
	("LOC_JOHN_JACOB_ASTOR_GOLD",				  			 			  "Gain 600 [ICON_GOLD] Gold."),
	("LOC_GREATPERSON_CAMPUS_TOURISM",				  			 		  "Campus districts provide +100 [ICON_TOURISM] Tourism."),
	("LOC_GREATPERSON_INDUSTRIAL_ZONE_TOURISM",				  			  "Industrial Zone districts provide +100 [ICON_TOURISM] Tourism."),
	("LOC_GREATPERSON_GIOVANNI_DE_MEDICI_ACTIVE",                         "Instantly builds a Fair, a Market and a Bank in this city. The Bank gets 2 slots forProducts."),
	("LOC_GREATPERSON_GIOVANNI_DE_MEDICI_ACTIVE_HD",                      "{LOC_GREATPERSON_GIOVANNI_DE_MEDICI_ACTIVE} 25% cheaper to purchase Theater Square buildings."),
	("LOC_GREATPERSON_EXTRA_TRADE_ROUTE_CAPACITY2",                       "Increases [ICON_TRADEROUTE] Trade Route capacity by 2."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_ZHANGHENG",                             "Triggers the [ICON_TECHBOOSTED] Eureka for 'Engineering' Technology. If the [ICON_TECHBOOSTED] Eureka of 'Engineering' Technology is already triggered, instead completes the Technology."),
    ("GREATPERSON_1CLASSICALMEDIEVALTECHBOOSTS",                          "Triggers the [ICON_TECHBOOSTED] Eureka for a random Classical Era Technology."),
    ("LOC_ARYABHATA_CAMPUS_AMENITY",                                      "Chosen Campus provide +2 [ICON_AMENITIES] Amenities."),
    ("LOC_GREATPERSON_ALAN_TURING_ACTIVE",                                "Triggers the [ICON_TechBoosted] Eureka moment for Computers and 1 random technology from the Modern and Atomic era. If Computers is already boosted, instead complete the tech."),
    ("LOC_GREATPERSON_DMITRI_MENDELEEV_ACTIVE",                           "Reveals [ICON_RESOURCE_ALUMINUM] Aluminum without the normal technology requirement. Triggers the [ICON_TechBoosted] Eureka moment for Chemistry. If Chemistry is already boosted, instead complete the tech."),
    ("LOC_GREATPERSON_EUCLID_ACTIVE",                                     "Triggers the [ICON_TechBoosted] Eureka moment for Mathematics and 1 random technology from the Medieval era. If Mathematics is already boosted, instead complete the tech. Let this city build one more district than the population limit allows."),
    ("LOC_GREATPERSON_ISAAC_NEWTON_ACTIVE",                               "Instantly builds a University and Library in this district. Universities provide +4 [ICON_Science] Science."),
    ("LOC_GREATPERSON_JAMES_OF_ST_GEORGE_ACTIVE",                         "Instantly builds Ancient and Medieval Walls in this city. +1 Great Engineer point per turn for each level of wall."),
    ("LOC_HD_BI_SHENG_ACTIVE",                       					  "This city can build one more district than the [ICON_CITIZEN] Population limit allows.[NEWLINE]Adds 30% research progress to 'Printing' Technology."),
    ("LOC_GREATPERSON_2MODERNATOMICTECHBOOST",                            "Triggers the [ICON_TechBoosted] Eureka moment for {Amount} random {Amount : plural 1?technology; other?technologies;} from the Modern or Atomic era."),
    ("LOC_GREAT_PERSON_PLASTICS_TECHBOOST",                               "Triggers the [ICON_TechBoosted] Eureka moment for Plastic."),
    ("LOC_GREAT_PERSON_HD_BOOST_OR_GRANT_REFINING",                       "Triggers the [ICON_TechBoosted] Eureka moment for Refining. If Refining is already boosted, instead complete the tech."),
    ("LOC_GREAT_PERSON_HD_BOOST_OR_GRANT_SANITATION",                     "Triggers the [ICON_TechBoosted] Eureka moment for Sanitation. If Sanitation is already boosted, instead complete the tech."),
    ("LOC_GREATPERSON_ARTIFACT_SCIENCE",                     			  "Gain {Amount} [ICON_Science] Science for every [ICON_GREATWORK_WRITING] Great Works of Writing in this city."),
    ("LOC_GREATPERSON_ARTIFACT_TOURISM_MODIFIER",                     	  "+200% of [ICON_TOURISM] Tourism from [ICON_GREATWORK_WRITING] Great Works of Writing in your cities."),
    ("LOC_GREATPERSON_NATIONAL_DISTRICT_SCIENCE_ADJACENCY_AS_TOURISM",    "All Districts you have built yield [ICON_TOURISM] Tourism equal to their adjacency bonus."),
    ("LOC_GREATPERSON_ELECTRICITY",                                       "Grants all Cities with +3 [ICON_POWER] Power from renewable water sources. +5% [ICON_Production] Production to cities if fully [ICON_POWER] powered."),
    ("LOC_GREATPERSON_INDUSTRY_PRODUCTION_SCIENCE",                       "All Industrial Zone district's [ICON_Production] Production adjacency bonus provides [ICON_Science] Science as well."),
    ("LOC_GREATPERSON_NATIONAL_APPEAL",                                   "+1 Appeal to all tiles within your territoty. "),
    ("LOC_GREATPERSON_SINGLECITY_APPEAL",                                 "+2 Appeal to all tiles in this City. Wonder, Improvment and National Park in this City provide +100% [ICON_TOURISM] Tourism."),
    ("LOC_GREATPERSON_CITY_HOUSING_LARGE",                                "+4 [ICON_HOUSING] Housing in all cities."),
    ("LOC_GREATPERSON_CITY_AMENITIES_LARGE",                              "+3 [ICON_AMENITIES] Amenities in all cities."),
    ("LOC_GREATPERSON_NATIONAL_APPEAL_BIG",                               "+2 Appeal to all tiles within your territory."),
    ("LOC_GREATPERSON_GPP_BOOST",                                         "Your Cities generate +25% Great Person points."),
    ("LOC_GREATPERSON_DISTRICT_CULTURE_BOMB",                             "Immediately complete target District (except Spaceport) in the city if the District is not completed. Culture Bomb adjacent tiles when completing such District in any city afterwards."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_MIMAR_SINAN_ACTIVATION_HINT",           "Must be on a District that is completed or under construction (except Spaceport). [COLOR_RED]If it does not work, try save and load.[ENDCOLOR]"),
    ("LOC_ARTEMISIA_LIGHTHOUSE",                                          "Instantly builds a Lighthouse in this district."),
    ("LOC_ARTEMISIA_LIGHTHOUSE_FOOD",                                     "Lighthouses provide +{Amount} [ICON_Food] Food."),
    ("LOC_GREATPERSON_GRANT_A_SETTLER",                                   "Grants a Settler."),
    ("LOC_GREATPERSON_LEIF_ERIKSON_EXPANSION2_ACTIVE",                    "+1 sight range for all naval units. Allows all Settlers and naval units to move over Deep Ocean tiles without the normal technology requirement."),
    ("LOC_GREATPERSON_NAVLA_RAIDER_BONUS",                                "Naval Raider units receive +2 [ICON_Strength] Combat Strength."),
    ("LOC_GREATPERSON_CHING_SHIH_EXPANSION2_ACTIVE",                      "Gain +500 [ICON_Gold] Gold (on Standard speed). Military units get +100% rewards for plundering sea [ICON_TradeRoute] Trade Routes."),
    ("LOC_HORATIO_NELSON_SHIPYARD_PRODUCTION",                            "Shipyards provide +{Amount} [ICON_Production] Production."),
    ("LOC_GREATPERSON_GRANT_PRODUCTION_IN_CITY_MODERN",                   "Grants {Amount} [ICON_Production] Production towards wonder construction."),
    ("LOC_GREATPERSON_JOAQUIM_MARQUES_LISBOA_SEAPORT",                    "Instantly builds a Seaport, Shipyard, and Lighthouse in this district."),
    ("LOC_GREATPERSON_JOAQUIM_MARQUES_LISBOA_SEAPORT_HOUSING",            "Seaports provide +{Amount} [ICON_Housing] Housing."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_TOGO_HEIHACHIRO_SEA_MOVEMENT",          "+1 [Icon_Movement] Movement for all naval units."),
    ("LOC_GREATPERSON_CLANCY_FERNANDO_AMENITIES",                         "Harbors +{Amount} [ICON_Amenities] Amenity."),
    ("LOC_GREATPERSON_CHESTER_NIMITZ_EXPANSION2_ACTIVE",                  "Instantly creates a Aircraft Carrier unit with 1 promotion level. Grants 1 [ICON_RESOURCE_Oil] Oil per Turn. +20% [ICON_Production] Production towards Naval Raider units."),
    ("LOC_GREATPERSON_CHING_SHIH_EXPANSION2_ACTIVE",                  	  "Gain +1000 [ICON_GOLD] Gold (on Standard speed). Military units get +100% rewards for plundering sea [ICON_TRADEROUTE] Trade Routes."),
    ("LOC_ABILITY_HANNO_DESCRIPTION",       "+2 [ICON_MOVEMENT] Movement. Escorted units move at the same speed."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_HANNO_THE_NAVIGATOR_FREE_UNIT",         "Creates a naval melee unit with +2 [ICON_MOVEMENT] Movement. Escorted units with it move at the same speed."),
	("LOC_GREATPERSON_ALLINFORMATIONTECHBOOSTS",						  "Triggers the [ICON_TECHBOOSTED] Eureka moment for all technologies from the Information era and the Future era."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_HOPPER",                                "Awards 2 freely-chosen free technologies (to choose the Technology to be awarded, please click on the Technology icon on the Tech tree). ");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                 Text)
values
    ("zh_Hans_CN",  "LOC_GREATPERSON_CHARLES_DARWIN_ACTIVE",                             "在标准速度下，从此处或相邻的每个自然奇观单元格获得1000 [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_GALILEO_GALILEI_ACTIVE",                            "在标准速度下，所在单元格每相邻一个山脉单元格获得400 [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_GRANT_LOTSO_SCIENCE",                              "获得3000点 [ICON_SCIENCE] 科技值与1000点 [ICON_CULTURE] 文化值（标准速度下）。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_DIPLO_VISIBILITY",                                  "所有文明的外交能见度+{Amount} {Amount : plural 1?级; other?级;}。在您的领土内，敌方间谍等级降低1级。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_REGIONAL_RANGE_BONUS",                              "工业区辐射建筑的辐射范围增加1个单元格，且额外辐射2 [ICON_SCIENCE] 科技值。"),
	("zh_Hans_CN",  "LOC_PIERO_DE_BARDI_GOLD",                                           "获得 300 [ICON_Gold] 金币。"),
	("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_NAME",                   "圣良一世"),
   	-- Great Merchant
	("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_NAME",						  "克罗索斯"),
	("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_NAME",			      "桑弘羊"),
	("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HD_ALI_MUGHAYAT_SYAH_NAME",			  "马利克·萨勒"),
	("zh_Hans_CN",  "LOC_COLAEUS_SETTLER_PRODUCTION",									  "此城生产开拓者时+25%建造速度。"),
	("zh_Hans_CN",  "LOC_COLAEUS_SETTLER_MOVEMENT",						        		  "开拓者+1 [ICON_MOVEMENT] 移动力。"),
	("zh_Hans_CN",  "LOC_MARCUS_LICINIUS_CRASSUS_SWORDSMAN",							  "获得一个剑士。"),
    ("zh_Hans_CN",  "LOC_MARCUS_LICINIUS_CRASSUS_IRON",                                   "每回合提供1点 [ICON_RESOURCE_IRON] 铁。"),
	("zh_Hans_CN",  "LOC_ZHANG_QIAN_GRANT_TRADER",								 		  "获得一个商人。"),
	("zh_Hans_CN",  "LOC_GREATPERSON_FREE_TRADER_UNIT",								 	  "获得一个商人。"),
	("zh_Hans_CN",  "LOC_GREATPERSON_HAVE_A_FREE_TRADE_ROUTE",							  "增加1条 [ICON_TRADEROUTE] 贸易路线容量。"),
	("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_ACTIVE",					  "立即在该区域建造1座集市和1座市场。[NEWLINE]商业中心二级建筑+3 [ICON_GOLD] 金币。"),
	("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_ACTIVE",				  "立即在该区域建造1座集市和1座铸币厂。[NEWLINE]此城的商业中心的辐射范围增加1个单元格，此城的铸币厂额外辐射1 [ICON_CULTURE] 文化值。"),
	("zh_Hans_CN",  "LOC_MARCO_POLO_NOTHING",				  			 	  			  "触发“探索”市政的 [ICON_CIVICBOOSTED] 鼓舞。"),
	("zh_Hans_CN",  "LOC_ZHOU_DAGUAN_COMMERCIAL_ATTACH",				  			 	  "每个商业中心提供1个 [ICON_ENVOY] 使者。"),
	("zh_Hans_CN",  "LOC_ALI_MUGHAYAT_SYAH_SETTLER",				  			  		  "获得一个开拓者。"),
	("zh_Hans_CN",  "LOC_ALI_MUGHAYAT_SYAH_BUILDER",				  			  		  "获得一个建造者。"),
	("zh_Hans_CN",  "LOC_JAKOB_FUGGER_GOLD",				  			  		 		  "获得400 [ICON_GOLD] 金币。"),
	("zh_Hans_CN",  "LOC_JAKOB_FUGGER_COMMERCIAL_ADJACENCY",				  			  "商业中心从相邻区域额外获得标准相邻加成。"),
	("zh_Hans_CN",  "LOC_JOHN_JACOB_ASTOR_INDUSTRIAL_ADJACENCY",				  		  "工业区从相邻区域额外获得标准相邻加成。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_DISTRICT_1_GOLD",                                       "+{1_num} [ICON_GOLD] 金币来自相邻区域。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_DISTRICT_1_PRODUCTION",                                 "+{1_num} [ICON_PRODUCTION] 生产力来自相邻区域。"),
	("zh_Hans_CN",  "LOC_GREATPERSON_INFLUENCE_TOKENS_LARGE",				  			  "获得3个 [ICON_ENVOY] 使者。"),
	("zh_Hans_CN",  "LOC_JOHN_JACOB_ASTOR_GOLD",				  			 			  "获得600 [ICON_GOLD] 金币。"),
	("zh_Hans_CN",  "LOC_GREATPERSON_CAMPUS_TOURISM",				  			 		  "学院+100 [ICON_TOURISM] 旅游业绩。"),
	("zh_Hans_CN",  "LOC_GREATPERSON_INDUSTRIAL_ZONE_TOURISM",				  			  "工业区+100 [ICON_TOURISM] 旅游业绩。"),
	("zh_Hans_CN",  "LOC_GREATPERSON_GIOVANNI_DE_MEDICI_ACTIVE",                          "立即在该区域建造集市、银行和市场。银行获得两个可以存放产品的巨作槽位。"),
	("zh_Hans_CN",  "LOC_GREATPERSON_GIOVANNI_DE_MEDICI_ACTIVE_HD",                       "{LOC_GREATPERSON_GIOVANNI_DE_MEDICI_ACTIVE} 购买剧院广场建筑的费用降低25%。"),
	("zh_Hans_CN",  "LOC_GREATPERSON_EXTRA_TRADE_ROUTE_CAPACITY2",                        "增加2条 [ICON_TRADEROUTE] 贸易路线容量。"),

    ("zh_Hans_CN",  "LOC_ARYABHATA_CAMPUS_AMENITY",                                      "选定的学院获得2点 [ICON_AMENITIES] 宜居度。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_ALAN_TURING_ACTIVE",                                "为电脑和现代或原子能时代的1个随机科技启动 [ICON_TechBoosted] 尤里卡时刻。若电脑尤里卡已被触发，则完成该科技。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_DMITRI_MENDELEEV_ACTIVE",                           "忽略普通科技要求，显示 [ICON_RESOURCE_ALUMINUM] 铝资源。为化学科技启动 [ICON_TechBoosted] 尤里卡时刻。若化学尤里卡已被触发，则完成该科技。"),
--("zh_Hans_CN",  "LOC_GREATPERSON_EUCLID_ACTIVE",                                     "为数学和中世纪的1个随机科技启动 [ICON_TechBoosted] 尤里卡时刻。若数学尤里卡已被触发，则完成该科技。该城可无视人口限制，多建造一个区域。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_ISAAC_NEWTON_ACTIVE",                               "立即在该区域建造大学和图书馆。大学+4 [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_JAMES_OF_ST_GEORGE_ACTIVE",                         "立即在本城建造远古和中世纪城墙。每级城墙每回合+1大工点。"),
    ("zh_Hans_CN",  "LOC_HD_BI_SHENG_ACTIVE",                       					 "该城市可无视 [ICON_CITIZEN] 人口数量限制再建造一个区域。[NEWLINE]为“印刷术”科技推进30%研究进度。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_2MODERNATOMICTECHBOOST",                            "为随机的{Amount}个现代或原子能时代{Amount : plural 1?科技; other?科技;}启动 [ICON_TechBoosted] 尤里卡时刻。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_PLASTICS_TECHBOOST",                               "为塑料启动 [ICON_TechBoosted] 尤里卡时刻。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_HD_BOOST_OR_GRANT_REFINING",                       "为精炼启动 [ICON_TechBoosted] 尤里卡时刻。若精炼已被触发，则完成该科技。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_HD_BOOST_OR_GRANT_SANITATION",                     "为卫生设备启动 [ICON_TechBoosted] 尤里卡时刻。若卫生设备已被触发，则完成该科技。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_ARTIFACT_SCIENCE",                    				 "激活时，该城市每有1个 [ICON_GREATWORK_WRITING] 著作便获得{Amount} [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_ARTIFACT_TOURISM_MODIFIER",                   		 "所有城市中 [ICON_GREATWORK_WRITING] 著作+200% [ICON_TOURISM] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_NATIONAL_DISTRICT_SCIENCE_ADJACENCY_AS_TOURISM",    "激活时当前全国所有已建成的区域提供等于相邻加成的 [ICON_TOURISM] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_ELECTRICITY",                                       "所有城市提供+3点 [ICON_POWER] 电力。为 [ICON_POWER] 供电充足的城市+5% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_INDUSTRY_PRODUCTION_SCIENCE",                       "所有工业区域的 [ICON_Production] 生产力相邻加成也提供 [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_NATIONAL_APPEAL",                                   "国境内的所有单元格+1魅力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_SINGLECITY_APPEAL",                                 "本城+2魅力。本城来自奇观、改良设施和自然公园的业绩+100%。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_CITY_HOUSING_LARGE",                                "所有城市+4 [ICON_HOUSING] 住房。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_CITY_AMENITIES_LARGE",                              "所有城市+3 [ICON_AMENITIES] 宜居度。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_NATIONAL_APPEAL_BIG",                               "国境内的所有单元格+2魅力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_GPP_BOOST",                                         "所有城市的伟人点积累速率+25%。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_OMAR_KHAYYAM_ACTIVE",                               "为两个中世纪或文艺复兴的随机科技启动 [ICON_TechBoosted] 尤里卡时刻，为中世纪和文艺复兴时期的一个随机市政启动 [ICON_CivicBoosted] 鼓舞时刻。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_DISTRICT_CULTURE_BOMB",                             "令该类型的区域获得文化炸弹的效果。若该区域未完成，则立刻完成该区域（宇航中心除外）。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MIMAR_SINAN_ACTIVATION_HINT",           "必须位于已完成或者正在建造的区域上（宇航中心除外）。[COLOR_RED]若未正常生效，请尝试存档后读档，若仍未生效，请在steam页面联系作者并提供存档。[ENDCOLOR]"),
    ("zh_Hans_CN",  "LOC_ARTEMISIA_LIGHTHOUSE",                                          "立即在该区域建造灯塔。"),
    ("zh_Hans_CN",  "LOC_ARTEMISIA_LIGHTHOUSE_FOOD",                                     "所有灯塔+{Amount} [ICON_Food] 食物。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_GRANT_A_SETTLER",                                   "获得一个开拓者。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_LEIF_ERIKSON_EXPANSION2_ACTIVE",                    "所有海军单位视野范围+1（最多+1）。所有海军单位与开拓者可在满足正常科技要求前进入深海单元格。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_NAVLA_RAIDER_BONUS",                                "海军袭击者+2 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_CHING_SHIH_EXPANSION2_ACTIVE",                      "获得500 [ICON_Gold] 金币（标准速度下）。军事单位掠夺海上 [ICON_TradeRoute] 贸易路线时收益+100%。"),
    ("zh_Hans_CN",  "LOC_HORATIO_NELSON_SHIPYARD_PRODUCTION",                            "所有造船厂+{Amount} [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_GRANT_PRODUCTION_IN_CITY_MODERN",                   "为奇观建设赠予{Amount}点 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_JOAQUIM_MARQUES_LISBOA_SEAPORT",                    "立即在该区域建造码头、造船厂和灯塔。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_JOAQUIM_MARQUES_LISBOA_SEAPORT_HOUSING",            "所有码头+{Amount} [ICON_Housing] 住房。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_TOGO_HEIHACHIRO_SEA_MOVEMENT",          "所有海军单位+{Amount} [Icon_Movement] 移动力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_CLANCY_FERNANDO_AMENITIES",                         "所有港口+{Amount} [ICON_Amenities] 宜居度。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_CHESTER_NIMITZ_EXPANSION2_ACTIVE",                  "立即生产出拥有1次升级的航空母舰单位。每回合提供1点 [ICON_RESOURCE_Oil] 石油。生产海军突袭者类单位时+20% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_CHING_SHIH_EXPANSION2_ACTIVE",                  	 "获得1000 [ICON_GOLD] 金币（标准速度下）。军事单位掠夺海上 [ICON_TRADEROUTE] 贸易路线时收益+100%。"),
    ("zh_Hans_CN",  "LOC_ABILITY_HANNO_DESCRIPTION",                                     "+2 [ICON_MOVEMENT] 移动力。被护送的单位将以同样的速度移动。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HANNO_THE_NAVIGATOR_FREE_UNIT",       "创建1个拥有+2 [ICON_MOVEMENT] 移动力的海军近战单位。被该单位护送的单位将以同样的速度移动。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_ALLINFORMATIONTECHBOOSTS",							"为所有信息时代和未来时代科技提供 [ICON_TECHBOOSTED] 尤里卡。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HOPPER",                               "奖励2项当前可以研究的科技（点击科技树上的科技图标来选择被奖励的科技）。");

--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                           Text)
values
    ("LOC_GREAT_PERSON_INDIVIDUAL_JNR_ARCHIMEDES_NAME",             "Archimedes"),
    ("LOC_JNR_GREATPERSON_EUREKA_STRENGTH",                         "[ICON_TechBoosted] Eurekas provide 3% more progress."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_JNR_LI_BING_NAME",                "Li Bing"),
    ("LOC_JNR_GREATPERSON_DAM_UNLOCK_MATHEMATICS",                  "Can build Dam districts with Mathematics researched. +25% construction speed towards the Dam districts. Tiles next to a River yield +1 [ICON_PRODUCTION] Production for each Dam district in this City."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_JNR_MA_JUN_NAME",                 "Ma Jun"),
    ("LOC_HD_GREATPERSON_GRANT_IZ_TIER1_BUILDING",                  "Instantly builds a Workshop in this district. [NEWLINE]Provides +1 [ICON_PRODUCTION] Production to Tier 1 buildings in Industrial Zone district."),
    ("LOC_GREATPERSON_IMHOTEP_ACTIVE_JNR_UC",                       "Grants 55 [ICON_Production] Production (on Standard Speed) towards wonder construction, doubled if the wonder is from the Ancient or Classical Era."),
    ("LOC_GREATPERSON_JAMES_WATT_ACTIVE",                           "Instantly builds a Workshop and a Factory in this district. [NEWLINE]Provides +3 [ICON_PRODUCTION] Production to Tier 2 buildings in Industrial Zone district."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_JNR_MARTINE_DE_BERTEREAU_NAME",   "Martine de Bertereau"),
    ("LOC_GREATPERSON_EUCLID_ACTIVE",                               "Triggers the [ICON_TECHBOOSTED] Eureka moment for Mathematics technology. Let this city build one more district than the population limit allows."),
    -- history
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_ARCHIMEDES_CHAPTER_HISTORY_PARA_1",    "Archimedes of Syracuse (c. 287 – c. 212 BC) was a Greek mathematician, physicist, engineer, astronomer, and inventor. Although few details of his life are known, he is regarded as one of the leading scientists in classical antiquity. Considered to be the greatest mathematician of ancient history, and one of the greatest of all time, Archimedes anticipated modern calculus and analysis by applying the concept of the infinitely small and the method of exhaustion to derive and rigorously prove a range of geometrical theorems, including: the area of a circle; the surface area and volume of a sphere; area of an ellipse; the area under a parabola; the volume of a segment of a paraboloid of revolution; the volume of a segment of a hyperboloid of revolution; and the area of a spiral."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_ARCHIMEDES_CHAPTER_HISTORY_PARA_2",    "His other mathematical achievements include deriving an accurate approximation of pi; defining and investigating the spiral that now bears his name; and devising a system using exponentiation for expressing very large numbers. He was also one of the first to apply mathematics to physical phenomena, founding hydrostatics and statics. Archimedes' achievements in this area include a proof of the principle of the lever, the widespread use of the concept of center of gravity, and the enunciation of the law of buoyancy. He is also credited with designing innovative machines, such as his screw pump, compound pulleys, and defensive war machines to protect his native Syracuse from invasion."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_LI_BING_CHAPTER_HISTORY_PARA_1",       "Li Bing (Chinese: 李冰; pinyin: Lǐ Bīng; c. 3rd century BC) was a Chinese hydraulic engineer and official of the Warring States period. He served the state of Qin as an administrator and is revered for his work on the Dujiangyan River Control System, which both controlled flooding and provided irrigation water year-round, greatly increasing the productivity of the valley. Li Bing became a cultural icon, known as the vanquisher of the River God and is compared to the Great Yu."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_LI_BING_CHAPTER_HISTORY_PARA_2",       "Dujiangyan is still in use today and is listed as a UNESCO World Heritage Site."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MA_JUN_CHAPTER_HISTORY_PARA_1",        "Ma Jun (fl. 220–265), courtesy name Deheng, was a Chinese mechanical engineer, inventor, and politician who lived in the state of Cao Wei during the Three Kingdoms period of China."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MA_JUN_CHAPTER_HISTORY_PARA_2",        "His most notable invention was that of the south-pointing chariot, a directional compass vehicle which actually had no magnetic function, but was operated by use of differential gears (which applies equal amount of torque to driving wheels rotating at different speeds). It is because of this revolutionary device (and other achievements) that Ma Jun is known as one of the most brilliant mechanical engineers and inventors of his day (alongside Zhang Heng of the earlier Eastern Han dynasty). The device was re-invented by many after Ma Jun, including the astronomer and mathematician Zu Chongzhi (429–500). In the later medieval dynastic periods, Ma Jun's south-pointing chariot was combined in a single device with the distance-measuring odometer."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MA_JUN_CHAPTER_HISTORY_PARA_3",        "One of Ma Jun's early inventions was an improved silk drawloom. He also invented a keel waterwheel to divert water from low to high ground; created a wheel-rotating stone firing machine that could continuously fire stones up to hundreds of paces; He once invented for the Wei emperor Cao Rui an intricate hydraulic-powered, mechanical-operated puppet theatre. Since then, Ma Jun has also modified the Zhuge crossbow, contributing to scientific development and technological progress."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_1",        "Sima Qian (135 or 145 BC-?)  was born in Longmen, Zuoneishi of the Western Han Dynasty, was one of the greatest historians of China and the world."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_2",        "Sima Qian was born in an intellectual family in the reign of Emperor Jing of the Han Dynasty. Under the influence of his father, Sima Tan, who served as the Commander of the Imperial Household History, Sima Qian became familiar with history books at a young age. From the age of twenty, Sima Qian travelled around the world, covering places such as Mount Lu, Huiji, Daliang, Lu, Lidu, Changsha and many others. Two years later, Sima Qian returned to Chang'an and joined the imperial court. Before he died, he entrusted Sima Qian with the task of writing a history book to continue the task of his ancestors, the historians. He was also a student of the Han Confucian scholars Dong Zhongshu and Kong Anguo, and he drew on the strengths of a hundred schools of thought to compile the Book of the Grand Historian, or the Records of the Grand Historian, with the ambition to 'study the boundary of heaven and man and to understand the changes of the past and the present'. In 99 BC, Sima Qian was arrested and imprisoned for defending Li Ling, who had surrendered to the Xiongnu, and when he was faced with the choice between castration and execution, he chose castration to continue his work, even though it would have been 'defiling his ancestors'."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_3",        "His many contributions to historical codification were groundbreaking. He pioneered the genre of biography, which uses biographies as clues, and was adept at restoring historical events to their context by means of deduction. He travelled in all directions and was adept at extracting valuable historical material from folk relics and rumours. He was also one of the first writers in the world to begin writing about the history of peoples, economies, ideas and cultures. He also wrote about the history of the lower and middle classes and foreigners, with a simple idea of equality. Like many other famous historians in history, he was also a good historian who wrote straightforward historical facts."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_4",        "In literature, Sima Qian also led the way. At that time, his literary work was on a par with that of the writer Sima Xiangru, and Lu Xun called his 'The Records of the Grand Historian' 'a masterpiece of the historians, a lisao without rhyme', praising both his historical talent and his literary skills."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_5",        "In addition, Sima Qian was also a master of astronomy and astrology, and his astronomical attainments are mainly reflected in the Shiji - Book of Astronomy, which contains one of the earliest records of Xingguan (the traditional Chinese division of the celestial sphere) in China. However, Sima Qian still had a tendency to correspond celestial activity with social personnel, and was inevitably limited by his time."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_CHAPTER_HISTORY_PARA_1",       "Zhuangzi (c. 369 BC - c. 286 BC), known as Zhou, was born in Meng in the State of Song during the Battling States period (the mainstream saying is northeast of present-day Shangqiu in Henan Province). He was a thinker, philosopher and writer of the mid-Warring States period, and a representative figure of the Taoist school."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_CHAPTER_HISTORY_PARA_2",       "Zhuangzi is generally regarded as one of the sages of Taoism. His philosophical ideas are mainly 'Qiwu' and 'Xiaoyao' ."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_CHAPTER_HISTORY_PARA_3",       "He advocated that man should break away from the limitations of his own body and grasp all things as a whole. Therefore, Zhuangzi believed that all human knowledge systems are superficial and one-sided, and that all things are ultimately the same, with no difference between right and wrong, beauty and ugliness, good and evil, and nobility and lowliness. On the other hand, to be free is a state of leisure and ease, an out-of-this-world complex."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_CHAPTER_HISTORY_PARA_4",       "There have been many interpretations of Zhuangzi's thought. Some see him as a primitive anarchist, while others see his actions as a kind of performance art that mocks the sordid world. Whatever the interpretation, his escapism has remained a cultural symbol representing only spirituality. And he himself was very good at telling stories to express his ideas. His Zhuangzi is not only a philosophical masterpiece in itself, but also an excellent collection of fables and tales. To this day, the fables he created continue to influence generations of Chinese people."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_XU_FU_CHAPTER_HISTORY_PARA_1",             "Xu Fu (birth and death unknown), was a alchemist from the late Warring States period and the Qin Dynasty. His first appearance in history is in the Records of the Grand Historian, where he is said to have sent Xu Fu with 3,000 boys and girls on a voyage to the west to 'seek immortals' in his quest for immortality. But after the first trip, Xu Fu returned without success. On his second trip, Xu Fu found the 'Fertile Plain', so he became king there and did not return to the Middle Kingdom. This is the original version (or at least the closest to the original version) of the story, as described in the Records of the Grand Historian, but, like many famous legends, the story continued to change as it was passed down from generation to generation. By the time of the Sui and Tang dynasties, as Japan began to study the political culture of the Tang dynasty, Xu Fu's destination was also linked to Japan. Since then, the legend of Xu Fu crossing over to Japan and establishing his country has slowly taken shape."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_XU_FU_CHAPTER_HISTORY_PARA_2",             "Did Xu Fu's person and his story really exist? Although the Records of the Grand Historian is more credible, it is incoherent and does not mention exactly where Xu Fu went. The details of the later legends of Xu Fu are mostly attributed to later generations, and the records and memorials of Xu Fu's exploits in Japan were created after the introduction of Chinese literature."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_XU_FU_CHAPTER_HISTORY_PARA_3",             "Whether true or not, the story of Xu Fu's journey to Japan has irrefutably become an important symbol of cultural exchange between China and Japan, and continues to exert influence far beyond the expectations of the people of the time."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_KINICH_KAN_BAHLAM_CHAPTER_HISTORY_PARA_1", "Kʼinich Kan Bahlam II, also known as Chan Bahlum II, (May, 635 - February, 702) was ajaw of the Maya city-state of Palenque. He acceded to the throne in January, 684, several months after the death of his father and predecessor, Kʼinich Janaab Pakal I and ruled until his death."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_KINICH_KAN_BAHLAM_CHAPTER_HISTORY_PARA_2", "He continued the ambitious project of adorning Palenque with fine art and architecture begun by his father; his most important addition to the city of Palenque was the Temple of the Cross which is the center piece of the Temple of the Cross Complex. He was succeeded by his younger brother, Kʼinich Kʼan Joy Chitam II, another brother was probably Tiwol Chan Mat. The monuments and text associated with Kʼinich Kan Bahlam II are: Tablets and Alfardas of the Temples of the Cross, Sun and Foliated Cross; tablets and facade of the Temple of the Inscriptions; Temple 17 Panel; Death's Head; Jonuta Panel; Temple of the Cross Stela."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_CHAPTER_HISTORY_PARA_1",     "Guo Shoujing (1231–1316), courtesy name Ruosi , was a Chinese astronomer, hydraulic engineer, mathematician, and politician of the Yuan dynasty. The later Johann Adam Schall von Bell (1591–1666) was so impressed with the preserved astronomical instruments of Guo that he called him 'the Tycho Brahe of China.'Jamal ad-Din cooperated with him."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_CHAPTER_HISTORY_PARA_2",     "At 20, Guo became a hydraulic engineer. In 1251, as a government official, he helped repair a bridge over the Dahuoquan River. Kublai realized the importance of hydraulic engineering, irrigation, and water transport, which he believed could help alleviate uprisings within the empire, and sent Liu Bingzhong and his student Guo to look at these aspects in the area between Dadu (now Beijing or Peking) and the Yellow River. To provide Dadu with a new supply of water, Guo had a 30 km channel built to bring water from the Baifu spring in the Shenshan Mountain to Dadu, which required connecting the water supply across different river basins, canals with sluices to control the water level. The Grand Canal, which linked the river systems of the Yangtze, the Huai, and the Huang since the early 7th century, was repaired and extended to Dadu in 1292–93 with the use of corvée (unpaid labor). After the success of this project, Kublai Khan sent Guo off to manage similar projects in other parts of the empire. He became the chief advisor of hydraulics, mathematics, and astronomy for Kublai Khan."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_CHAPTER_HISTORY_PARA_3",     "Guo began to construct astronomical observation devices. He has been credited with inventing the gnomon, the square table, the abridged or simplified armilla, and a water powered armillary sphere called the Ling Long Yi. The gnomon is used to measure the angle of the sun, determine the seasons, and is the basis of the sundial, but Guo Shoujing revised this device to become much more accurate and improved the ability to tell time more precisely. The square table was used to measure the azimuth of celestial bodies by the equal altitude method and could also be used as protractor. The abridged or simplified armilla was used to measure the angle of the sun, as well as the position of any celestial body. The Ling Long Yi is similar to an abridged armilla except larger, more complex, and more accurate.Kublai Khan, after observing Guo's mastery of astronomy, ordered that he, Zhang, and Wang Xun make a more accurate calendar. They built 27 observatories throughout China in order to gain thorough observations for their calculations. In 1280, Guo completed the calendar, calculating a year to be 365.2425 days, just 26 seconds off the year's current measurement. In 1283, Guo was promoted to director of the Observatory in Beijing and, in 1292, he became the head of the Water Works Bureau. Throughout his life he also did extensive work with spherical trigonometry. After Kublai Khan's death, Guo continued to be an advisor to Kublai's successors, working on hydraulics and astronomy."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_CHAPTER_HISTORY_PARA_4",     ""),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_CHAPTER_HISTORY_PARA_1",  "Sang Hongyang (c. 152–80 BC) was a Chinese politician. He was a prominent official of the Han Dynasty, who served Emperor Wu of Han and his successor Emperor Zhao. He is famous for his economic policies during the reign of Emperor Wu, the best known of which include the state monopolies over iron and salt - systems which would be imitated by other dynasties throughout Chinese history. Due to political conflict, he was executed in 80 BC by Huo Guang (d. 68 BC)."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_CHAPTER_HISTORY_PARA_2",  ""),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_CHAPTER_HISTORY_PARA_3",  ""),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_CHAPTER_HISTORY_PARA_4",  ""),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_CHAPTER_HISTORY_PARA_1",        "Croesus (585-546 BC), was the last king of the Lydia in western Asia Minor."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_CHAPTER_HISTORY_PARA_2",        "The Lydians were then the most famous merchants in the Eastern Mediterranean. Herodotus says they were the first to mint gold and silver money and the first to run a retail business - of course, given Herodotus' reputation for hearsay, his account is indicative only - and they also invented the game of chess. Croesus is recorded as being the first ruler to order the issue of pure gold and silver currency to regulate the circulation of money. He was thus considered the wealthiest man of his time and became almost a cultural symbol representing the wealthy."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_CHAPTER_HISTORY_PARA_3",        "His reign also saw the expansion of the Lydian territories and the struggle for supremacy with Babylon and Medes in western Asia. When Cyrus the Great rose to power in Fars, he asked the Delphic oracle to divine the outcome of this battle. The result he received was - an empire would be destroyed. He gladly went forth to fight the Persians, however, it was his own empire that was destroyed. The story of Croesus' end varies; some say he was executed by Cyrus, while others say he was hired by Cyrus as advicor of finance."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_1","Joseph-Louis Lagrange (born Giuseppe Luigi Lagrangia or Giuseppe Ludovico De la Grange Tournier;1736-1813), also reported as Giuseppe Luigi Lagrange or Lagrangia, was an Italian mathematician, physicist and astronomer, later naturalized French. He made significant contributions to the fields of analysis, number theory, and both classical and celestial mechanics."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_2","In 1766, on the recommendation of Swiss Leonhard Euler and French d'Alembert, Lagrange succeeded Euler as the director of mathematics at the Prussian Academy of Sciences in Berlin, Prussia, where he stayed for over twenty years, producing volumes of work and winning several prizes of the French Academy of Sciences. Lagrange's treatise on analytical mechanics (Mécanique analytique, 4. ed., 2 vols. Paris: Gauthier-Villars et fils, 1788–89), written in Berlin and first published in 1788, offered the most comprehensive treatment of classical mechanics since Newton and formed a basis for the development of mathematical physics in the nineteenth century."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_3","In 1787, at age 51, he moved from Berlin to Paris and became a member of the French Academy of Sciences. He remained in France until the end of his life. He was instrumental in the decimalisation in Revolutionary France, became the first professor of analysis at the École Polytechnique upon its opening in 1794, was a founding member of the Bureau des Longitudes, and became Senator in 1799."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_4","Lagrange was one of the creators of the calculus of variations, deriving the Euler–Lagrange equations for extrema of functionals. He extended the method to include possible constraints, arriving at the method of Lagrange multipliers. Lagrange invented the method of solving differential equations known as variation of parameters, applied differential calculus to the theory of probabilities and worked on solutions for algebraic equations. He proved that every natural number is a sum of four squares. His treatise Theorie des fonctions analytiques laid some of the foundations of group theory, anticipating Galois. In calculus, Lagrange developed a novel approach to interpolation and Taylor's theorem. He studied the three-body problem for the Earth, Sun and Moon (1764) and the movement of Jupiter's satellites (1766), and in 1772 found the special-case solutions to this problem that yield what are now known as Lagrangian points. Lagrange is best known for transforming Newtonian mechanics into a branch of analysis, Lagrangian mechanics. He presented the mechanical 'principles' as simple results of the variational calculus."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG_CHAPTER_HISTORY_PARA_1",       "Justus Freiherr von Liebig(12 May 1803 – 18 April 1873) was a German scientist who made major contributions to agricultural and biological chemistry, and is considered one of the principal founders of organic chemistry. As a professor at the University of Giessen, he devised the modern laboratory-oriented teaching method, and for such innovations, he is regarded as one of the greatest chemistry teachers of all time. He has been described as the 'father of the fertilizer industry' for his emphasis on nitrogen and trace minerals as essential plant nutrients, and his formulation of the law of the minimum, which described how plant growth relied on the scarcest nutrient resource, rather than the total amount of resources available. He also developed a manufacturing process for beef extracts, and with his consent a company, called Liebig Extract of Meat Company, was founded to exploit the concept; it later introduced the Oxo brand beef bouillon cube. He popularized an earlier invention for condensing vapors, which came to be known as the Liebig condenser."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG_CHAPTER_HISTORY_PARA_2",       ""),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG_CHAPTER_HISTORY_PARA_3",       ""),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_CHAPTER_HISTORY_PARA_1",       "Rosalind Elsie Franklin (25 July 1920–16 April 1958) was a British chemist and X-ray crystallographer whose work was central to the understanding of the molecular structures of DNA (deoxyribonucleic acid), RNA (ribonucleic acid), viruses, coal, and graphite. Although her works on coal and viruses were appreciated in her lifetime, Franklin’s contributions to the discovery of the structure of DNA were largely unrecognized during her life, for which she has been variously referred to as the 'wronged heroine', the 'dark lady of DNA', the 'forgotten heroine', a 'feminist icon', and the 'Sylvia Plath of molecular biology'."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_CHAPTER_HISTORY_PARA_2",       "Franklin graduated in 1941 with a degree in natural sciences from Newnham College, Cambridge, and then enrolled for a PhD in physical chemistry under Ronald George Wreyford Norrish, the 1920 Chair of Physical Chemistry at the University of Cambridge. Disappointed by Norrish's lack of enthusiasm, she took up a research position under the British Coal Utilisation Research Association (BCURA) in 1942. The research on coal helped Franklin earn a PhD from Cambridge in 1945.[9] Moving to Paris in 1947 as a chercheur (postdoctoral researcher) under Jacques Mering at the Laboratoire Central des Services Chimiques de l'État, she became an accomplished X-ray crystallographer. After joining King's College London in 1951 as a research associate, Franklin discovered some key properties of DNA, which eventually facilitated the correct description of the double helix structure of DNA. Owing to disagreement with her director, John Randall, and her colleague Maurice Wilkins, Franklin was compelled to move to Birkbeck College in 1953."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_CHAPTER_HISTORY_PARA_3",       "Franklin is best known for her work on the X-ray diffraction images of DNA while at King's College London, particularly Photo 51, taken by her student Raymond Gosling, which led to the discovery of the DNA double helix for which Francis Crick, James Watson, and Maurice Wilkins shared the Nobel Prize in Physiology or Medicine in 1962. Watson suggested that Franklin would have ideally been awarded a Nobel Prize in Chemistry, along with Wilkins but, although there was not yet a rule against posthumous awards, the Nobel Committee generally did not make posthumous nominations."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_CHAPTER_HISTORY_PARA_4",       "Working under John Desmond Bernal, Franklin led pioneering work at Birkbeck on the molecular structures of viruses. On the day before she was to unveil the structure of tobacco mosaic virus at an international fair in Brussels, Franklin died of ovarian cancer at the age of 37 in 1958. Her team member Aaron Klug continued her research, winning the Nobel Prize in Chemistry in 1982."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARGARET_MEAD_CHAPTER_HISTORY_PARA_1",     "J.Robert Oppenheimer (1904–1967) was an American theoretical physicist. A professor of physics at the University of California, Berkeley, Oppenheimer was the wartime head of the Los Alamos Laboratory and is often credited as the 'father of the atomic bomb' for his role in the Manhattan Project—the World War II undertaking that developed the first nuclear weapons. Oppenheimer was among those who observed the Trinity test in New Mexico, where the first atomic bomb was successfully detonated on July 16, 1945. He later remarked that the explosion brought to mind words from the Bhagavad Gita: 'Now I am become Death, the destroyer of worlds.' In August 1945, the weapons were used in the atomic bombings of Hiroshima and Nagasaki."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARGARET_MEAD_CHAPTER_HISTORY_PARA_2",     "After the war ended, Oppenheimer became chairman of the influential General Advisory Committee of the newly created United States Atomic Energy Commission. He used that position to lobby for international control of nuclear power to avert nuclear proliferation and a nuclear arms race with the Soviet Union. He opposed the development of the hydrogen bomb during a 1949–1950 governmental debate on the question and subsequently took stances on defense-related issues that provoked the ire of some U.S. government and military factions. During the Second Red Scare, those stances, together with past associations Oppenheimer had with people and organizations affiliated with the Communist Party, led to the revocation of his security clearance in a much-written-about hearing in 1954. Effectively stripped of his direct political influence, he continued to lecture, write, and work in physics. Nine years later, President John F. Kennedy awarded (and Lyndon B. Johnson presented) him with the Enrico Fermi Award as a gesture of political rehabilitation. In 2022, five decades after his death, the U.S. government formally nullified its 1954 decision and affirmed Oppenheimer's loyalty."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARGARET_MEAD_CHAPTER_HISTORY_PARA_3",     "Oppenheimer's achievements in physics included the Born–Oppenheimer approximation for molecular wave functions, work on the theory of electrons and positrons, the Oppenheimer–Phillips process in nuclear fusion, and the first prediction of quantum tunneling. With his students he also made important contributions to the modern theory of neutron stars and black holes, as well as to quantum mechanics, quantum field theory, and the interactions of cosmic rays. As a teacher and promoter of science, he is remembered as a founding father of the American school of theoretical physics that gained world prominence in the 1930s. After World War II, he became director of the Institute for Advanced Study in Princeton, New Jersey."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_STEPHANIE_KWOLEK_CHAPTER_HISTORY_PARA_1",  "Linus Carl Pauling (1901 – 1994) was an American chemist, biochemist, chemical engineer, peace activist, author, and educator. He published more than 1,200 papers and books, of which about 850 dealt with scientific topics. New Scientist called him one of the 20 greatest scientists of all time, and as of 2000, he was rated the 16th most important scientist in history. For his scientific work, Pauling was awarded the Nobel Prize in Chemistry in 1954. For his peace activism, he was awarded the Nobel Peace Prize in 1962. He is one of five people to have won more than one Nobel Prize (the others being Marie Curie, John Bardeen, Frederick Sanger and Karl Barry Sharpless). Of these, he is the only person to have been awarded two unshared Nobel Prizes,[9] and one of two people to be awarded Nobel Prizes in different fields, the other being Marie Curie."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_STEPHANIE_KWOLEK_CHAPTER_HISTORY_PARA_2",  "Pauling was one of the founders of the fields of quantum chemistry and molecular biology. His contributions to the theory of the chemical bond include the concept of orbital hybridisation and the first accurate scale of electronegativities of the elements. Pauling also worked on the structures of biological molecules, and showed the importance of the alpha helix and beta sheet in protein secondary structure. Pauling's approach combined methods and results from X-ray crystallography, molecular model building, and quantum chemistry. His discoveries inspired the work of James Watson, Francis Crick, Maurice Wilkins and Rosalind Franklin on the structure of DNA, which in turn made it possible for geneticists to crack the DNA code of all organisms."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_STEPHANIE_KWOLEK_CHAPTER_HISTORY_PARA_3",  "In his later years, he promoted nuclear disarmament, as well as orthomolecular medicine, megavitamin therapy, and dietary supplements, especially ascorbic acid (commonly known as Vitamin C). None of his ideas concerning the medical usefulness of large doses of vitamins have gained much acceptance in the mainstream scientific community. He was married to the American human rights activist Ava Helen Pauling."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_CHAPTER_HISTORY_PARA_1",       "Lev Davidovich Landau (1908 – 1968) was a Soviet physicist who made fundamental contributions to many areas of theoretical physics."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_CHAPTER_HISTORY_PARA_2",       "His accomplishments include the independent co-discovery of the density matrix method in quantum mechanics (alongside John von Neumann), the quantum mechanical theory of diamagnetism, the theory of superfluidity, the theory of second-order phase transitions, the Ginzburg–Landau theory of superconductivity, the theory of Fermi liquids, the explanation of Landau damping in plasma physics, the Landau pole in quantum electrodynamics, the two-component theory of neutrinos, and Landau's equations for S matrix singularities. He received the 1962 Nobel Prize in Physics for his development of a mathematical theory of superfluidity that accounts for the properties of liquid helium II at a temperature below 2.17 K (−270.98 °C)."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_CHAPTER_HISTORY_PARA_3",       ""),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_CHAPTER_HISTORY_PARA_1",    "Pope Leo I, the central figure of the four great popes of the Catholic Church, and the most legendary one. After all, there have been many great popes, but only he seemed to have the courage to face conquerors without backing down."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_CHAPTER_HISTORY_PARA_2",    "In 440 AD, Leo became pope. Before that, he was already a mature bishop (although maturity referred to religious judgment). After becoming pope, he emphasized that the pope is the successor of Saint Peter and has the power to rule the entire church. In 445 AD, he successfully turned his expectations into reality through an edict from the Roman emperor, and from then on, the position of the pope as the highest ruler of the Catholic Church was established. In addition, as an excellent theologian, his 'Great Tome' was also the main document for the formulation of the Council of Chalcedon."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_CHAPTER_HISTORY_PARA_3",    "Of course, his most legendary story is still in 452 AD. That year, the most terrifying conqueror in the world at the time, Attila the Hun, was preparing to take Rome as the jewel in his crown, and the millennium-old city was in danger. However, after a night of meeting with the Pope alone, Attila chose to withdraw his troops. What did Pope Leo say to Attila at the time? No one knows, but such courage and boldness are indeed rare in the world. Three years later, the Vandals also attacked Rome, but this time the Pope did not succeed in stopping them from taking over Rome. After Rome was plundered by the Vandals, the Pope finally persuaded the invaders to stop further destruction, proving himself to be the true protector of Rome."),
    ("LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_CHAPTER_HISTORY_PARA_4",    "In 461 AD, Pope Leo I passed away. After losing Aetius, Majorian, and the 'Protector of Rome,' fewer and fewer people were willing to pay for the Western Roman Empire. Fifteen years later, the Western Roman Empire officially fell, and the Middle Ages began, but at this time, the influence of that 'Protector of Rome' became even stronger...");
--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                 Text)
values
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JNR_ARCHIMEDES_NAME",                  "阿基米德"),
    ("zh_Hans_CN",  "LOC_JNR_GREATPERSON_EUREKA_STRENGTH",                              "[ICON_TechBoosted] 尤里卡提供的科技值额外+3%。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JNR_LI_BING_NAME",                     "李冰"),
    ("zh_Hans_CN",  "LOC_JNR_GREATPERSON_DAM_UNLOCK_MATHEMATICS",                       "解锁科技“数学”即可建造堤坝。建造堤坝时加速25%。堤坝为所在城市的沿河单元格+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JNR_MA_JUN_NAME",                      "马钧"),
    ("zh_Hans_CN",  "LOC_HD_GREATPERSON_GRANT_IZ_TIER1_BUILDING",                       "立即在该区域建造工作坊。[NEWLINE]工业区一级建筑+1 [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_IMHOTEP_ACTIVE_JNR_UC",                            "建造奇观时提供55点 [ICON_Production] 生产力，对于远古和古典时代的奇观加倍。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_JAMES_WATT_ACTIVE",                         		"立即在该区域建造工作坊和工厂。[NEWLINE]工业区二级建筑+3 [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JNR_MARTINE_DE_BERTEREAU_NAME",        "玛蒂娜·德·贝尔特罗"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHANGHENG",                            "触发“工程”科技的 [ICON_TECHBOOSTED] 尤里卡，如果“工程”科技的 [ICON_TECHBOOSTED] 尤里卡已触发，则改为解锁该科技。"),
    ("zh_Hans_CN",  "GREATPERSON_1CLASSICALMEDIEVALTECHBOOSTS",                         "触发一个随机古典时代科技的 [ICON_TECHBOOSTED] 尤里卡。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_EUCLID_ACTIVE",                                    "触发“数学”科技的 [ICON_TECHBOOSTED] 尤里卡。该城可无视人口限制，多建造一个区域。"),
    -- history
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_ARCHIMEDES_CHAPTER_HISTORY_PARA_1",     "阿基米德（公元前287年—公元前212年），伟大的古希腊哲学家、百科式科学家、数学家、物理学家、力学家，静态力学和流体静力学的奠基人，并且享有“力学之父”的美称，阿基米德和高斯、牛顿并列为世界三大数学家。 阿基米德曾说过：“给我一个支点，我就能撬起整个地球。”"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_ARCHIMEDES_CHAPTER_HISTORY_PARA_2",     "阿基米德确立了静力学和流体静力学的基本原理。给出许多求几何图形重心，包括由一抛物线和其网平行弦线所围成图形的重心的方法。阿基米德证明物体在液体中所受浮力等于它所排开液体的重量，这一结果后被称为阿基米德原理。他还给出正抛物旋转体浮在液体中平衡稳定的判据。阿基米德发明的机械有引水用的水螺旋，能牵动满载大船的杠杆滑轮机械，能说明日食，月食现象的地球-月球-太阳运行模型。但他认为机械发明比纯数学低级，因而没写这方面的著作。阿基米德还采用不断分割法求椭球体、旋转抛物体等的体积，这种方法已具有积分计算的雏形。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_LI_BING_CHAPTER_HISTORY_PARA_1",        "李冰（约公元前3世纪）是战国时代秦国水利工程专家。公元前256年—前251年被秦昭王任为蜀郡（今成都一带）郡守，任蜀郡郡守时他主持设计并建造了成都北部的都江堰，泄岷江洪水且用之于灌溉，为成都平原成为天府之国奠定了非常重要的基础。他在蜀郡还主持兴办了其他水利工程，并修筑桥梁，在广都主持开凿盐井等，为开发成都平原、发展农业生产作出了重大贡献。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_LI_BING_CHAPTER_HISTORY_PARA_2",        "都江堰至今仍在使用，并被列为联合国教科文组织的世界遗产地。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MA_JUN_CHAPTER_HISTORY_PARA_1",         "马钧，字德恒，三国时期魏国扶风（今陕西省兴平市）人，机械工程师、发明家和政治家。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MA_JUN_CHAPTER_HISTORY_PARA_2",         "他最引人注目的发明是指向南方的战车，这是一种定向罗盘车，实际上没有磁力功能，而是通过使用差动齿轮（对以不同速度旋转的驱动轮施加等量的扭矩）来操作。正是由于这一革命性的装置（以及其他成就），马钧被称为当时最杰出的机械工程师和发明家之一（与早期东汉的张衡齐名）。在马钧之后，许多人重新发明了这个装置，包括天文学家和数学家祖冲之（429-500）。在后来的中世纪王朝时期，马钧的指向南方的战车与测量距离的里程表合二为一。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JNR_MA_JUN_CHAPTER_HISTORY_PARA_3",         "他还改进了当时操作笨重的织绫机；发明一种由低处向高地引水的龙骨水车；制作出一种轮转式发石机，能连续发射石块，远至数百步；把木制原动轮装于木偶下面，叫做“水转百戏图”。此后，马钧还改制了诸葛连弩，对科学发展和技术进步做出了贡献。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_1",         "司马迁（前135或145-？）字子长，西汉左内史龙门人，是中国乃至世界上最伟大的历史学家之一。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_2",         "司马迁在汉景帝年间生于一个知识分子家庭。其父司马谈曾任太史令，在其影响下，司马迁在年少时就熟读史书。从二十岁开始，司马迁游历天下，足迹遍布庐山、会稽、大梁、鲁、离碓、长沙等等多地。两年后，司马迁回到长安入朝为官。到武帝元封元年，司马谈因病未能参与武帝泰山封禅，遂愤懑而死，死前向司马迁寄托了著作史书，延续司马家祖先太史官的任务。司马迁又曾学于汉儒董仲舒、孔安国，博采百家之长，以“究天人之际，通古今之变”的气魄，著成了《太史公书》，即《史记》，开创了中国史学编纂的纪传体范式，历代官方修史，无不遵循这一体例。武帝天汉二年，司马迁因为投降匈奴的李陵辩解而被捕下狱，在死刑和腐刑之间，他选择了“污及先人”的腐刑以延续著书立说的事业，他的这种品德也为后人所称道。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_3",         "在历史编纂方面，他的诸多贡献是开创性的。他开创了以人物传记作为线索的纪传体体例，善于用演绎的方式还原历史事件的情境。他遍历四方，善于从民间的遗迹和传言中提取有价值的史料。他还是世界上较早的开始书写民族史、经济史、思想文化史的作家。他在历史书写中还书写中下层人物及异国异族的历史，蕴含着朴素的平等思想。跟历史上很多著名的史学家一样，他也是善于秉笔直书历史事实的史家。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_4",         "在文学方面，司马迁也领风骚一时。在当时他的文学与辞赋家司马相如并称，鲁迅称其《史记》为“史家之绝唱，无韵之离骚”，既称赞了其史才，又赞扬了其文采。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_CHAPTER_HISTORY_PARA_5",         "此外，司马迁还精通天文星象，他的天文学造诣主要体现在《史记·天官书》中，其中包含了中国最早的对星官（中国传统的对天球区域的划分）的记载。不过，司马迁还是存在将天体活动和社会人事对应起来的倾向，也无可避免的受到时代的局限。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_CHAPTER_HISTORY_PARA_1",        "庄子（约前369-约286），名周，战国时期宋国蒙（主流说法为今河南商丘东北）人。战国中期思想家、哲学家、文学家，道家学派代表人物，与老子并称“老庄”。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_CHAPTER_HISTORY_PARA_2",        "庄子被普遍的认为是道家先贤之一。他的哲学思想主要是“齐物”“逍遥”。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_CHAPTER_HISTORY_PARA_3",        "齐物主张人应突破自我形躯的局限而对万物加以整体性把握。因此，庄子认为人的各种知识系统都是肤浅片面的，而一切事物归根到底都是相同的，没有什么差别，也没有是非、美丑、善恶、贵贱之分。而逍遥则是一种悠游自在的状态，是一种出世情结。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_CHAPTER_HISTORY_PARA_4",        "对于庄子的思想，历来有着很多解释。有人认为他是原始的无政府主义者，也有人认为他的行为是一种嘲讽污浊世俗的行为艺术。无论怎么解释，他的逍遥依然成为一种代表精神只有的文化符号。而他自己本人也很擅长讲故事来表达他的思想。他的《庄子》本身除了是一部哲学巨著以外，也是一本优秀的寓言故事集。时至今日，他所创造的寓言故事仍然影响着一代代中国人。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_XU_FU_CHAPTER_HISTORY_PARA_1",              "徐福（生卒年不详）又作徐巿（注意不是市场的市），是战国末年和秦朝的方士。他在历史上第一次出现于《史记》，说因为秦始皇想追求长生不老，派徐福带三千童男童女向西航行“入海求仙人”。但是徐福在去了第一次以后无功而返。去第二次时，徐福发现了“平原广泽”，于是在当地称王，不在返回中原。这是《史记》描述，也是徐福故事的原始版本（至少是最接近原始版本的版本），然而，跟很多著名的传说母题一样，在后人不断的流传中，这个故事也在不断地变异。到隋唐时，因为日本开始学习唐朝政治文化，徐福的目的地也被与日本建立起了联系。自此之后，徐福东渡日本，建立国家的传说慢慢成形。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_XU_FU_CHAPTER_HISTORY_PARA_2",              "徐福其人其事是否真的存在？虽然《史记》的可信度较高，但是其语焉不详，并没有确切的提到徐福的明确去向。而后来有关徐福的传说的细节，后人附会的成分居多，日本国内有关徐福事迹的记载和纪念，也都是产生于中国文献传入以后。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_XU_FU_CHAPTER_HISTORY_PARA_3",              "徐福东渡日本之事，无论是否为真，都无可辩驳地成为了中日文化交流的重要符号，仍在发挥远超当时的人们预期的影响力。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_KINICH_KAN_BAHLAM_CHAPTER_HISTORY_PARA_1",  "基尼奇·坎·巴拉姆二世（635-702），也就是昌·巴鲁姆二世，是玛雅帕伦克城邦的阿哈乌（城邦世袭领主），继承了帕卡尔打造帕伦克盛世，利用帕伦克强势的国力建造了许多建筑，时至今日，访客还能从断壁残垣中窥见当年的盛况。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_KINICH_KAN_BAHLAM_CHAPTER_HISTORY_PARA_2",  "他继续着他父亲开始的用精美的艺术和建筑装饰帕伦克的雄心勃勃的项目；他对帕伦克城最重要的补充是十字神庙，这是十字神庙建筑群的中心作品。与基尼奇·坎·巴拉姆二世有关的纪念碑和文字是：十字神庙的石板和角椽上的太阳与带叶十字符号；铭文神庙的石板和门面；17号神庙的面板；死神之首雕像；约努塔面石板；十字神庙石碑。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_CHAPTER_HISTORY_PARA_1",      "郭守敬（1231-1316），字若思。邢州邢台县（今河北省邢台市信都区）人。元朝著名的天文学家、数学家、水利工程专家。早年师从刘秉忠、张文谦，官至太史令、昭文馆大学士、知太史院事，世称“郭太史”。元仁宗延祐三年（1316年），郭守敬逝世，享年八十六岁。著有《推步》《立成》等十四种天文历法著作。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_CHAPTER_HISTORY_PARA_2",      "郭守敬在天文、历法、水利和数学等方面都取得了卓越的成就。自至元十三年（1276年）起，他与许衡、王恂等奉命修订新历法，历时四年，制订出《授时历》，成为当时世界上最先进的一种历法，通行三百六十多年。为修订历法，郭守敬还改制、发明了简仪、高表等十二种新仪器。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_CHAPTER_HISTORY_PARA_3",      "至元元年（1264年），郭守敬奉命修浚西夏境内的古渠，更立闸堰，使当地农田得到灌溉。至元二十八年（1291年），郭守敬任都水监，负责修治元大都至通州的运河，耗时一年，完成了全部工程，定名通惠河，发展了南北交通和漕运事业。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_CHAPTER_HISTORY_PARA_4",      "1970年，国际天文学会以郭守敬的名字为月球上的一座环形山命名为“郭守敬环形山”。  1977年，国际小行星中心将小行星2012命名为“郭守敬小行星” 。中科院国家天文台也将国家重大科技基础设施LAMOST望远镜命名为“郭守敬天文望远镜”。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_CHAPTER_HISTORY_PARA_1",   "桑弘羊（前155年？-前80年），河南洛阳人，西汉时期政治家、经济学家、汉武帝的顾命大臣之一，官至御史大夫。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_CHAPTER_HISTORY_PARA_2",   "帝国运转需要巨额的财政开支，光靠农业税根本不够，如果不执行制度，问钱从哪里来？一旦遇到战争、灾荒等紧急事务，国库却空空如也，怎么办？如果中央在财政等各个方面不对地方形成压倒性的优势，一旦地方势力膨胀起兵造反，怎么办？这是汉代大臣桑弘羊留给一切政府的问题。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_CHAPTER_HISTORY_PARA_3",   "汉景帝前元中叶（一说前155年），桑弘羊出生于商业大都会洛阳的一户富商家庭。他13岁就开始在经济部门做官吏。到30多岁（汉武帝元狩三年，前120）时，桑弘羊就被汉武帝召见，之后就成为了汉朝政府一个重要的经济政策制定者。他几乎参与了所有汉武帝时汉朝重要的经济决策，主要包括盐铁官营、铸五铢钱、屯田西北等等。而他的行为基本上就是在实践地回答他提出的问题。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANG_HONGYANG_CHAPTER_HISTORY_PARA_4",   "随着时间推移，他在武帝政府的地位越来越高，最后成为了托孤重臣之一，后来他跟历史上大多数权臣一样被控告谋反而处死了。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_CHAPTER_HISTORY_PARA_1",         "克罗索斯（前585-前546），是小亚细亚西部吕底亚国的最后一位国王。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_CHAPTER_HISTORY_PARA_2",         "吕底亚人当时是东地中海最著名的商人。希罗多德说他们是最早铸造金银货币的人，也是最早经营零售商业的人——当然，考虑到希罗多德向来因为道听途说而名声不嘉，他的记载仅供参考——他们还发明了棋类游戏。克罗索斯据记载是第一个下令发行纯金和纯银货币来规范货币流通的统治者。他也因此被认为是当时最富裕的人，几乎成为了代表有钱人的一个文化符号。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_CROESUS_CHAPTER_HISTORY_PARA_3",         "他在位时期也扩张了吕底亚领土，与巴比伦、米底在西亚争霸。当雅利安人居鲁士在法尔斯崛起时，他向德尔菲神谕请求占卜这次战役的结果。他得到的结果是——一个帝国将毁灭。他欣然前去与波斯人作战，然而，毁灭的却是他自己的帝国。克罗索斯的结局说法不一，有人说他被居鲁士处死了，也有人说他被居鲁士聘为财政大臣。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_1", "约瑟夫·路易·拉格朗日（1736-1813），出生时名为朱塞佩·路易吉·拉格朗吉亚或朱塞佩·洛德维科·德·拉·格朗日·图尼尔，是一位法国籍意大利裔数学家和天文学家。拉格朗日曾为普鲁士的腓特烈大帝在柏林工作了20年，被腓特烈大帝称做“欧洲最伟大的数学家”，后受法国国王路易十六的邀请定居巴黎直至去世。拉格朗日一生才华横溢，在数学、物理和天文等领域做出了很多重大的贡献。他的成就包括著名的拉格朗日中值定理，创立了拉格朗日力学等等。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_2", "拉格朗日是18世纪一位十分重要的科学家，在数学、力学和天文学三个学科中都有历史性的重大贡献，但他主要是数学家。他最突出的贡献是在把数学分析的基础脱离几何与力学方面起了决定性的作用，使数学的独立性更为清楚，而不仅是其他学科的工具。同时在使天文学力学化、力学分析化上也起了历史性作用，促使力学和天文学（天体力学）更深入发展。在他的时代，分析学等分支刚刚起步，欠缺严密性和标准形式，但这不足以妨碍他取得大量的成果。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_3", "拉格朗日是变化微积分的创造者之一，他推导出了函数极值的欧拉-拉格朗日方程。他将这一方法扩展到包括可能的约束，得出了拉格朗日乘数。拉格朗日发明了被称为参数变化的微分方程求解方法，将微分计算应用于概率理论，并致力于代数方程的解决。他证明每个自然数都是四个平方的总和。他的论文《解析函数论》奠定了群论的一些基础，对伽罗瓦的理论起先导作用。在微积分方面，拉格朗日开发了一种新的插值g公式和泰勒定理。他研究了地球、太阳和月亮的三体问题（1764年）和木星卫星的运动（1766年），并于1772年发现了这个问题的特例解，产生了现在被称为拉格朗日的点。拉格朗日因将牛顿力学转变为分析学的一个分支——拉格朗日力学而最为著名。他将力学 “原理”作为变分微积分的简单结果提出。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_CHAPTER_HISTORY_PARA_4", ""),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG_CHAPTER_HISTORY_PARA_1",        "尤斯图斯·冯·李比希男爵（1803年-1873）出生于今日德国黑森州前身黑森大公爵国的达姆施塔特，德国化学家，和吉森大学和慕尼黑大学的大学教授。李比希最重要的贡献在于农业和生物化学，他创立了有机化学。李比希认识到植物以盐的形式吸收重要的无机养分，通过他的研究，他创立了现代矿物肥料和农业化学的开端。作为大学教授他发明了现代实验室导向的教学方法，因为这一创新，他被誉为历史上最伟大的化学教育家之一。他发现了氮对于植物营养的重要性，因此也被称为“肥料工业之父”。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG_CHAPTER_HISTORY_PARA_2",        "李比希是19世纪最著名和最有成果的化学家，是有机化学、农业化学和营养生理学的奠基人。他的写作他对化学的发展的影响非常大。从1831年开始他与汉瑞默克一起编辑出版一份重要的化学和药学年报。他与他人一起出版了一本化学手册和一本有机化学手册。他还发表了许多关于改善农业操作的书籍。1840年他发表了他最重要的关于农业化学的书。为了普及化学知识，他从1841年开始不定期地在《奥格斯堡汇报》上发表科普性的、名为《化学邮件》的小文，获得很大欢迎。李比希是较早的将试验引入自然科学教学的人。通过他的研究他改善了化学中的分析方法，使得化学成为一门精确的学术。在最早的60名诺贝尔化学奖获得者中有42人是他的学生的学生。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG_CHAPTER_HISTORY_PARA_3",        "李比希的各种发明包罗万象，影响巨大。他的提出了无机化学中的根理论，建立了同分异构体概念。他发明了五球瓶等化学仪器、过磷酸钙等肥料、银制镜子、几种成本低廉的穷人营养品、发酵粉。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_CHAPTER_HISTORY_PARA_1",        "罗莎琳·爱尔西·富兰克林（1920-1958），是一位英国物理化学家与晶体学家。她所做的研究，专注于DNA、病毒、煤炭与石墨等物质的结构。其中她所拍摄的DNA晶体绕射图片“照片51号”，以及关于此物质的相关数据，成为詹姆斯·华生与佛朗西斯·克里克解出DNA结构的关键线索。此后她也领导了关于烟草镶嵌病毒与小儿麻痹病毒的研究。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_CHAPTER_HISTORY_PARA_2",        "在她所处的时代，人们对女性在学术上的能力仍然是轻视的，然而她却贡献颇丰。她对煤炭晶体结构的研究促进了煤化工进步，对烟草花叶病毒和脊髓灰质炎病毒的观测也促进了医学的发展。她做出的最大的贡献，是对DNA结构的发掘。她的观测为DNA双螺旋结构的发现奠定了基础，然而，她却因为长期接触X光观测仪器，年仅38岁就死于癌症，未能亲自发表DNA结构的发现。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_CHAPTER_HISTORY_PARA_3",        ""),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_CHAPTER_HISTORY_PARA_4",        ""),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARGARET_MEAD_CHAPTER_HISTORY_PARA_1",      "尤里乌斯·罗伯特·奥本海默（1904-1967），美国理论物理学家，曾于加利福尼亚大学伯克利分校任教物理。第二次世界大战期间，奥本海默领导洛斯阿拉莫斯实验室，其参与的曼哈顿计划最终研发出用于轰炸广岛与长崎的首批核武器，因此他被誉为“原子弹之父”。奥本海默曾经感叹道，人类史上首次核试验——1945年7月16日在新墨西哥州进行的三位一体核试验——让他不禁想到《薄伽梵歌》中的一句：“我现在成了死神，世界的毁灭者。”"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARGARET_MEAD_CHAPTER_HISTORY_PARA_2",      "战后，奥本海默在新成立的美国原子能委员会中担任总顾问委员会主席。他利用这一身份游说国际社会对核能进行管控，从而避免美国与苏联发生核军备竞赛以及防止核扩散。第二次红色恐慌期间，他公开发表的观点激怒了不少政治人士，他的安全许可也因此在1954年被撤销，意味着他无法再直接影响政治。奥本海默仍继续演讲、写作及研究物理。九年之后，美国总统约翰·肯尼迪授予奥本海默恩里科·费米奖（由继任总统林登·约翰逊颁发），奥本海默就此被平反。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_MARGARET_MEAD_CHAPTER_HISTORY_PARA_3",      "在物理方面，奥本海默的研究成果包括分子波函数的波恩–奥本海默近似法、电子和正子理论、核聚变中的奥本海默-菲利浦斯过程以及首次预测量子隧穿效应。他和学生的共同研究还对现代中子星和黑洞理论、量子力学、量子场论及宇宙射线相互作用等范畴有重大贡献。奥本海默作为一名老师，普及科学、一生志业，他在加州大学伯克利分校所建立的伯克利理论物理学中心是数一数二的理论物理学中心。二战后，他长期担任新泽西州普林斯顿高等研究院院长。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_STEPHANIE_KWOLEK_CHAPTER_HISTORY_PARA_1",   "莱纳斯·卡尔·鲍林（1901年－1994）是美国化学家，量子化学和结构生物学的先驱者之一。1954年因在化学键方面的工作取得诺贝尔化学奖，1963年因反对核弹在地面测试的行动获得1962年度的诺贝尔和平奖。 由于在1962年的决选过程中，挪威诺贝尔委员会认为当年的提名者均不符合阿尔弗雷德·诺贝尔遗嘱中所概述的标准。根据诺贝尔基金会的章程，在这种情况下，可以将诺贝尔奖保留到第二年，然后再应用该章程。 因此，一年后的1963年，莱纳斯·鲍林获得1962年诺贝尔和平奖，成为获得不同诺贝尔奖项的两人之一（另一人为玛丽·居里）；也是唯一的一位每次都是独立地获得诺贝尔奖的获奖人。其后他主要的行动为支持维他命C在医学的功用。鲍林被认为是20世纪对化学科学影响最大的人之一，他所撰写的《化学键的本质》被认为是化学史上最重要的著作之一。他以量子力学入手分析化学问题，结论却以直观、浅白的概念重新阐述，即便未受量子力学训练的化学家亦可利用准确的直观图像研究化学问题，影响至为深远，比如他所提出的许多概念：电负度、共振论、价键理论、混成轨域、蛋白质二级结构等概念和理论，如今已成为化学领域最基础和最广泛使用的观念。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_STEPHANIE_KWOLEK_CHAPTER_HISTORY_PARA_2",   ""),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_STEPHANIE_KWOLEK_CHAPTER_HISTORY_PARA_3",   ""),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_CHAPTER_HISTORY_PARA_1",        "列夫·达维多维奇·朗道（1908－1968年），前苏联著名物理学家，凝聚态物理学的奠基人，苏联科学领军人之一，同时擅长理论物理多个分支领域，在理论物理里多个领域都有重大贡献。以惊人的物理直觉、杰出的物理研究成果、扎实的基本功、精炼的著作风格和严格的性格而为人熟知。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_CHAPTER_HISTORY_PARA_2",        "他的成就包括独立地共同发现了量子力学中的密度矩阵法（与约翰d·冯s·诺依曼一起）、二磁体的量子力学理论、超流性理论、二阶相变理论、金兹堡-朗道超导理论、费米液体理论、解释等离子体物理中的朗道阻尼、量子电动力学中的朗道极、中微子的双组分理论、以及朗道的S矩阵奇点方程。他发展了超流性的数学理论，解释了温度低于2.17K（-270.98℃）的液态氦II的特性。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_CHAPTER_HISTORY_PARA_3",        "他由于“关于凝聚态物质的开创性理论，特别是液氦”获得1962年的诺贝尔物理学奖，朗道当时由于身体原因，不能前往国外领奖。结果诺贝尔奖基金会打破了惯例，在历史上第一次不是在瑞典首都由国王授奖，而是由瑞典大使在莫斯科授予了朗道这一物理学研究的最高荣誉。1962年，仍活跃于研究前沿的朗道发生严重车祸，工作能力受损，身体状况大不如前，6年后去世。朗道去世多年后，阿列克谢·阿布里科索夫及维塔利·金兹堡凭借早年与朗道共同建立的超导体和超流体理论也于2003年获得诺贝尔物理学奖。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_CHAPTER_HISTORY_PARA_1",     "圣利奥一世，天主教四大教宗中的第一位--也是最具有传奇色彩的一位。毕竟，伟大的教宗不在少数，可是，敢于直面征服者而不落下风的，似乎只有这么一位。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_CHAPTER_HISTORY_PARA_2",     "440年，圣利奥接任教皇，在这之前，他已经是一个成熟的主教（虽然，成熟指的是宗教审判方面）。在接任教宗后，他强调教宗是圣彼得的继承者，自己有统治全教会的权力。而在445年，他通过罗马皇帝的敕令成功将自己的期盼变成现实，从此，教宗作为天主教最高统治者的地位基本确立。此外，作为一位优秀的神学家，他的《大卷》也是订立迦克敦信经的主要文件。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_CHAPTER_HISTORY_PARA_3",     "当然，他最传奇的故事还是在452年，那一年，当时世界上最恐怖的征服者--匈奴王阿提拉正准备着摘下罗马作为他王冠上的明珠，千年古城岌岌可危。但是，在教宗单刀赴会的一夜之后，阿提拉却选择了撤军。当时，圣利奥到底对阿提拉说了什么？没人知道，但这等胆识和气魄，恐怕确实是天下少有。又过了三年，汪达尔也对罗马进行了进攻，这次，教宗却并没有成功阻止他们攻下罗马。在罗马被汪达尔劫掠两周后，教宗最终还是说服了侵略者阻止了更进一步的破坏，用实际行动证明了自己是罗马名副其实的保护者。"),
    ("zh_Hans_CN",  "LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_HD_SANCTUS_LEO_CHAPTER_HISTORY_PARA_4",     "461年，圣利奥一世去世。失去了埃提乌斯，马约里安，以及“罗马城的保护者”后，愿意为西罗马帝国付出的人越来越少，十五年后，西罗马帝国正式灭亡，中世纪开始，但这时，那位“罗马保护者”的影响才变得愈发壮大……");
--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                        Text)
values
    ("LOC_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_NAME",             "Zhuang Zhou"),
    ("LOC_GREATWORK_ZHUANG_ZHOU_1_NAME",                         "The Journey to Freedom"),
    ("LOC_GREATWORK_ZHUANG_ZHOU_1_QUOTE",                        "The supreme man has no self, the divine man has no merit, the sage has no name."),
    ("LOC_GREATWORK_ZHUANG_ZHOU_2_NAME",                         "The Essay on Qiwu"),
    ("LOC_GREATWORK_ZHUANG_ZHOU_2_QUOTE",                        "I wonder if Zhou's dream was of a butterfly? Is the dream of the butterfly Zhou's dream?"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_NAME",              "Si Maqian"),
    ("LOC_GREATWORK_SI_MA_QIAN_1_NAME",                          "Shiji"),
    ("LOC_GREATWORK_SI_MA_QIAN_1_QUOTE",                         "All the world is bustling with profit."),
    ("LOC_GREATWORK_SI_MA_QIAN_2_NAME",                          "The Letter to Ren'an"),
    ("LOC_GREATWORK_SI_MA_QIAN_2_QUOTE",                         "To study the world of heaven and man, to understand the changes of the past and the present, and to form a family of words.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                             Text)
values
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHUANG_ZHOU_NAME",                  "庄周"),
    ("zh_Hans_CN",  "LOC_GREATWORK_ZHUANG_ZHOU_1_NAME",                              "《逍遥游》"),
    ("zh_Hans_CN",  "LOC_GREATWORK_ZHUANG_ZHOU_1_QUOTE",                             "至人无己，神人无功，圣人无名。"),
    ("zh_Hans_CN",  "LOC_GREATWORK_ZHUANG_ZHOU_2_NAME",                              "《齐物论》"),
    ("zh_Hans_CN",  "LOC_GREATWORK_ZHUANG_ZHOU_2_QUOTE",                             "不知周之梦为胡蝶与？胡蝶之梦为周与？"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_SI_MA_QIAN_NAME",                   "司马迁"),
    ("zh_Hans_CN",  "LOC_GREATWORK_SI_MA_QIAN_1_NAME",                               "《史记》"),
    ("zh_Hans_CN",  "LOC_GREATWORK_SI_MA_QIAN_1_QUOTE",                              "天下熙熙皆为利来，天下攘攘皆为利往。"),
    ("zh_Hans_CN",  "LOC_GREATWORK_SI_MA_QIAN_2_NAME",                               "《报任安书》"),
    ("zh_Hans_CN",  "LOC_GREATWORK_SI_MA_QIAN_2_QUOTE",                              "究天人之际，通古今之变，成一家之言。");

--大军改动 by先驱

-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                        Text)
values
    ("LOC_GREATPERSON_SUN_ZTU_ACTIVE",                           "All combat units gain +25% experience when attacking."),
    ("LOC_GREATPERSON_AETHELFLAED_ACTIVE",                       "Instantly builds a Barracks in this District. +3 [ICON_STRENGTH] Combat Strength when fighting Barbarians."),
    ("LOC_GREATPERSON_EL_CID_ACTIVE",                            "Forms a Corps out of a military land unit, and grants it 1 promotion level."),
    ("LOC_GREATPERSON_NAPOLEON_BONAPARTE_ACTIVE",                "Forms an Army out of a military land unit, and grants it 1 promotion level."),
    ("LOC_GREATPERSON_TIMUR_ACTIVE",                             "+1 [ICON_TRADEROUTE] Trade Route capacity. Grants a trader unit. "),
    ("LOC_GREATPERSON_GUSTAVUS_ADOLPHUS_ACTIVE",                 "Instantly creates a Bombard unit."),
    ("LOC_GREATPERSON_SIMON_BOLIVAR_ACTIVE",                     "Instantly creates a Cuirassier unit.");
    -- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                 Text)
values
    ("zh_Hans_CN",  "LOC_GREATPERSON_SUN_ZTU_ACTIVE",                                    "所有战斗单位的攻击经验+25%。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_AETHELFLAED_ACTIVE",                                "立即在该区域建造一座兵营。与 [ICON_Barbarian] 蛮族战斗时+3 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_EL_CID_ACTIVE",                                     "把一个军事陆地单位变成军团，并为该单位提供1次升级。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_NAPOLEON_BONAPARTE_ACTIVE",                         "把一个军事陆地单位变成军队，并为该单位提供1次升级。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_TIMUR_ACTIVE",                                      "增加1条 [ICON_TradeRoute] 贸易路线容量。获得一个商人单位。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_GUSTAVUS_ADOLPHUS_ACTIVE",                          "立即创建1个射石炮单位。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_SIMON_BOLIVAR_ACTIVE",                              "立即创建1个胸甲骑兵单位。");

    --客卿
insert or replace into EnglishText
    (Tag,                                                        Text)
values
    ("LOC_GREATPERSON_MOVEMENT_AOE_KEQING",                      "+1 [ICON_MOVEMENT] Movement to all land units (except cavalries) within 2 tiles."),
    ("LOC_GREATPERSON_STRENGTH_AOE_KEQING",                      "+5 [ICON_STRENGTH] Combat Strength to all land military units (except cavalries) within 2 tiles."),
    ("LOC_UNIT_KEQING_NAME",                                     "Ke Qing"),
    ("LOC_GREAT_PERSON_CLASS_KEQING_NAME",                       "Ke Qing"),
    ("LOC_ABILITY_KEQING_AOE_MOVEMENT_DESCRIPTION",              "+1 [ICON_Movement] Movement from Ke Qing"),
    ("LOC_ABILITY_KEQING_AOE_STRENGTH_DESCRIPTION",              "+5 [ICON_STRENGTH] Combat Strength from Ke Qing"),
    ("LOC_ABILITY_WANGJIAN_IGNORE_HILLS_DESCRIPTION",            "Wang Jian: ignore [ICON_MOVEMENT] movement penalty from Hills."),
    ("LOC_ABILITY_MENGWU_MOVEMENT_DESCRIPTION",                  "Meng Wu: gain +1 [ICON_MOVEMENT] Movement if starting in enemy's territory."),
    ("LOC_ABILITY_WANGBEN_WALL_DESCRIPTION",                     "Wang Ben: +5 [ICON_STRENGTH] Combat Strength against district defenses."),
    ("LOC_ABILITY_GREATWORK_WEILIAO_HD_DESCRIPTION",             "Wei Liao Zi: +2 [ICON_STRENGTH] Combat Strength."),
    ("LOC_KEQING_STRENGTH",                                      "from KeQing"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_MENGTIAN_NAME",                "Meng Tian"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_MENGYI_NAME",                  "Meng Yi"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_WANGJIAN_NAME",                "Wang Jian"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_WANGBEN_NAME",                 "Wang Ben"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_HANFEI_NAME",                  "Han Fei"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_MENGAO_NAME",                  "Meng Ao"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_GANLUO_NAME",                  "Gan Luo"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_MENGWU_NAME",                  "Meng Wu"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_LISI_NAME",                    "Li Si"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_LVBUWEI_NAME",                 "Lv Buwei"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_WEILIAO_NAME",                 "Wei Liao"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_ZHAOTUO_NAME",                 "Zhao Tuo"),
    ("LOC_UNIT_KEQING_DESCRIPTION",                              "A special type of Great Person only available to Qin Shi Huang. Each has unique abilities, including a passive effect, and a Retire effect."),
    ("LOC_MENGTIAN_GREATWALL_CULTURE",                           "+1 [ICON_CULTURE] Culture for the Great Wall."),
    ("LOC_MENGYI_GOVERNORS",                                     "Grant 1 [ICON_GOVERNOR] Governor Title."),
    ("LOC_WANGJIAN_HILLS",                                       "All land units (except cavalries) ignore [ICON_MOVEMENT] movement penalty from Hills."),
    ("LOC_WANGBEN_WALL_TEXT",                                    "from Wang Ben"),
    ("LOC_WEILIAO_STRENGTH",                                     "from Wei Liao Zi"),
    ("LOC_WANGBEN_WALL",                                         "All land units (except cavalries) gain +5 [ICON_STRENGTH] Combat Strength against district defenses."),
    ("LOC_MENGAO_LEVEL",                                         "Grants 1 promotion level to a military land unit."),
    ("LOC_GANLUO_ENVOY",                                         "Gain 3 [ICON_ENVOY] Envoys.Palace +3 influence points."),
    ("LOC_MENGWU_MOVEMENT",                                      "All land units (except cavalries) gain +1 [ICON_MOVEMENT] Movement if starting in enemy's territory."),
    ("LOC_LISI_TEXT",                                            "Awards 1 freely-chosen free civics.(to choose the Civic to be awarded, please click on the Civic icon on the Civic tree.)"),
    ("LOC_LVBUWE_TEXT",                                          "Increases [ICON_TRADEROUTE] Trade Route capacity by 1. Grants a free Trader. Palace+1 [ICON_AMENITIES] Amenity."),
    ("LOC_ZHAOTUO_TEXT",                                         "Settlers and Builders receive +1 [ICON_MOVEMENT] Movement."),
    ("LOC_GREATWORK_HANFEI_NAME",                                "Han Fei Zi[NEWLINE]+25% production speed towards Settlers and Builders in this city.[NEWLINE](Requires a move of the masterpiece to take effect)"),
    ("LOC_GREATWORK_WEILIAO_NAME",                               "Wei Liao Zi[NEWLINE]All land military units (except cavalries) gain +2 [ICON_STRENGTH] Combat Strength.[NEWLINE](Requires a move of the masterpiece to take effect)"),
    ("LOC_GREATWORK_HANFEI_QUOTE",                               "In a country ruled by a wise ruler, the classics written in books are abolished, and laws are used as the content of education."),
    ("LOC_GREATWORK_WEILIAO_QUOTE",                              "Proficiency in warfare is based on a clear mind and keen vision, and mastering the combat initiative is dependent on a deep understanding of the laws of war."),
    ("LOC_GREAT_PERSON_CLASS_KEQING_NAME",                       "Ke Qing"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_SHAH_JAHAN_NAME",              "Ustad Ahmad Lahori"),
    ("LOC_GREAT_PERSON_HD_BOOST_ASTRONOMY",                      "Triggers [ICON_TECHBOOSTED] Eureka for Astronomy. Campus gain extra standard adjacency bonus from Hills Tiles."),
    ("LOC_GREAT_PERSON_HD_DISTRICT_INDUSTRIAL_ZONE_YIELD",       "Industrial Zone provides +1 [ICON_PRODUCTION] Production and +1 [ICON_GOLD] Gold to adjacent improved tiles."),
    ("LOC_DISTRICT_TERRAIN_CLASS_MOUNTAIN_SCIENCE",              "+{1_num} [ICON_SCIENCE] Science from adjacent Mountain tiles."),
    ("LOC_DISTRICT_TERRAIN_CLASS_HILLS_SCIENCE",                 "+{1_num} [ICON_SCIENCE] Science from adjacent Hills tiles."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_NAME",           "Guo Shoujing"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_KINICH_KAN_BAHLAM_NAME",       "K'inich Kan Bahlam II"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_SONGTSAN_GAMPO_NAME",          "Zhang Daoling"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_NAME",      "Joseph Lagrange"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG_NAME",             "Justus Von Liebig"),
    ("LOC_GREAT_PERSON_HD_BOOST_OR_GRANT_NUCLEAR_FISSION",       "Triggers the [ICON_TECHBOOSTED] Eureka moment for Nuclear Fission technology. If Nuclear Fission is already boosted, instead complete the tech."),
    ("LOC_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_NAME",             "Rosalind Elsie Franklin"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_NAME",             "Lev Davidovich Landau"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_STEPHANIE_KWOLEK_NAME",        "Linus Carl Pauling"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_DANDARA_NAME",                 "Karl Von Clausewitz"),
    ("LOC_GREAT_PERSON_HD_COMBAT_STRENGTH",                      "All land units gain +2 [ICON_STRENGTH] Combat Strength."),
    ("LOC_GREAT_PERSON_HD_COMBAT_STRENGTH_MODIFIER",             "From Great Person"),
    ("LOC_GREATPERSON_SAMORI_TURE_ACTIVE",                       "Instantly creates a Line Infantry unit with 1 promotion level."),
    ("LOC_GREAT_PERSON_MILITARY_POLICY_SLOT",                    "+1 Military policy slot in any government."),
    ("LOC_GREATWORK_QU_YUAN_1_NAME",                             "Heavenly Questions"),
    ("LOC_GREATWORK_QU_YUAN_2_NAME",                             "Li Sao"),
    ("LOC_GREAT_PERSON_INDIVIDUAL_XU_FU_NAME",                   "Xu Fu"),
    ("LOC_GREAT_PERSON_HD_EMBARKED_EXTRA_MOVEMENT",              "Embarked units gain +1 [ICON_MOVEMENT] Movement. [NEWLINE]This Harbor district's [ICON_GOLD] Gold adjacency bonus provides [ICON_FAITH] Faith as well."),
    ("LOC_GREATWORK_SUN_TZU_NAME",                               "The Art of War[NEWLINE]All combat units gain +25% experience when attacking.(Requires a move of the masterpiece to take effect)[NEWLINE]");

insert or replace into LocalizedText
    (Language,      Tag,                                                                 Text)
values
    ("zh_Hans_CN",  "LOC_GREATPERSON_MOVEMENT_AOE_KEQING",                               "在两个单元格以内，为所有非骑兵陆地单位+1 [ICON_MOVEMENT] 移动力。"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_STRENGTH_AOE_KEQING",                               "在两个单元格以内，为所有非骑兵陆地军事单位+5 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_UNIT_KEQING_NAME",                                              "客卿"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_CLASS_KEQING_NAME",                                "客卿"),
    ("zh_Hans_CN",  "LOC_ABILITY_KEQING_AOE_MOVEMENT_DESCRIPTION",                       "客卿：+1 [ICON_Movement] 移动力。"),
    ("zh_Hans_CN",  "LOC_ABILITY_KEQING_AOE_STRENGTH_DESCRIPTION",                       "客卿：+5 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_ABILITY_WANGJIAN_IGNORE_HILLS_DESCRIPTION",                     "王翦：无视丘陵对 [ICON_MOVEMENT] 移动力的减益。"),
    ("zh_Hans_CN",  "LOC_ABILITY_MENGWU_MOVEMENT_DESCRIPTION",                           "蒙武：在敌方领土开始回合时+1 [ICON_MOVEMENT] 移动力。"),
    ("zh_Hans_CN",  "LOC_ABILITY_WANGBEN_WALL_DESCRIPTION",                              "王贲：攻击区域防御时+5 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_ABILITY_GREATWORK_WEILIAO_HD_DESCRIPTION",                      "《尉缭子》：+2 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_KEQING_STRENGTH",                                               "来自客卿"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MENGTIAN_NAME",                         "蒙恬"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MENGYI_NAME",                           "蒙毅"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_WANGJIAN_NAME",                         "王翦"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_WANGBEN_NAME",                          "王贲"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_HANFEI_NAME",                           "韩非"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MENGAO_NAME",                           "蒙骜"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_GANLUO_NAME",                           "甘罗"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MENGWU_NAME",                           "蒙武"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_LISI_NAME",                             "李斯"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_LVBUWEI_NAME",                          "吕不韦"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_WEILIAO_NAME",                          "尉缭"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ZHAOTUO_NAME",                          "赵佗"),
    ("zh_Hans_CN",  "LOC_UNIT_KEQING_DESCRIPTION",                                       "仅限秦始皇使用的特殊伟人。每个皆拥有特色能力，包括被动效果和“隐退”技能。"),
    ("zh_Hans_CN",  "LOC_MENGTIAN_GREATWALL_CULTURE",                                    "为长城改良单元格+1 [ICON_CULTURE] 文化值。"),
    ("zh_Hans_CN",  "LOC_MENGYI_GOVERNORS",                                              "提供1个 [ICON_GOVERNOR] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_WANGJIAN_HILLS",                                                "所有非骑兵陆地单位无视丘陵对 [ICON_MOVEMENT] 移动力的减益。"),
    ("zh_Hans_CN",  "LOC_WANGBEN_WALL_TEXT",                                             "来自王贲"),
    ("zh_Hans_CN",  "LOC_WEILIAO_STRENGTH",                                              "来自《尉缭子》"),
    ("zh_Hans_CN",  "LOC_WANGBEN_WALL",                                                  "攻击区域防御时，所有非骑兵陆地军事单位+5 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_MENGAO_LEVEL",                                                  "赠予陆地军事单位1次强化等级。"),
    ("zh_Hans_CN",  "LOC_GANLUO_ENVOY",                                                  "获得3位 [ICON_ENVOY] 使者，宫殿+3影响力。"),
    ("zh_Hans_CN",  "LOC_MENGWU_MOVEMENT",                                               "所有非骑兵陆地单位在敌方领土开始回合时+1 [ICON_MOVEMENT] 移动力。"),
    ("zh_Hans_CN",  "LOC_LISI_TEXT",                                                     "奖励一项当前可以研究的市政。（点击市政树上的市政图标来选择被奖励的市政。）"),
    ("zh_Hans_CN",  "LOC_LVBUWE_TEXT",                                                   "增加1条 [ICON_TRADEROUTE] 贸易路线容量。获得一个商人。宫殿+1 [ICON_AMENITIES] 宜居度。"),
    ("zh_Hans_CN",  "LOC_ZHAOTUO_TEXT",                                                  "开拓者和建造者获得+1 [ICON_MOVEMENT] 移动力。"),
    ("zh_Hans_CN",  "LOC_GREATWORK_HANFEI_NAME",                                         "《韩非子》[NEWLINE]此城生产开拓者和建造者时+25%建造速度。[NEWLINE]（需要移动展示槽位后生效）"),
    ("zh_Hans_CN",  "LOC_GREATWORK_WEILIAO_NAME",                                        "《尉缭子》[NEWLINE]为所有非骑兵陆地军事单位+2 [ICON_STRENGTH] 战斗力。[NEWLINE]（需要移动展示槽位后生效）"),
    ("zh_Hans_CN",  "LOC_GREATWORK_HANFEI_QUOTE",                                        "明主之国，无书简之文，以法为教。"),
    ("zh_Hans_CN",  "LOC_GREATWORK_WEILIAO_QUOTE",                                       "夫精诚在乎神明，战权在乎道之所极。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_CLASS_KEQING_NAME",                                "客卿"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_SHAH_JAHAN_NAME",                       "乌斯塔德·艾哈迈德·拉赫里"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_WONDER_PURCHASE",                                   "花费 [ICON_GOLD] 金币为一个正在建造的奇观提供 [ICON_PRODUCTION] 生产力，数量等同于花费 [ICON_PRODUCTION] 生产力的两倍，上限为当前国库储量的一半。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_HD_BOOST_ASTRONOMY",                               "为天文学科技启动 [ICON_TECHBOOSTED] 尤里卡时刻。学院从丘陵单元格获得额外标准相邻加成。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_HD_DISTRICT_INDUSTRIAL_ZONE_YIELD",                "工业区为相邻的已改良单元格+1 [ICON_PRODUCTION] 生产力、+1 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_TERRAIN_CLASS_MOUNTAIN_SCIENCE",                       "+{1_num} [ICON_SCIENCE] 科技值来自相邻山脉单元格。"),
    ("zh_Hans_CN",  "LOC_DISTRICT_TERRAIN_CLASS_HILLS_SCIENCE",                          "+{1_num} [ICON_SCIENCE] 科技值来自相邻丘陵单元格。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_GUO_SHOU_JING_NAME",                    "郭守敬"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_KINICH_KAN_BAHLAM_NAME",                "昌·巴鲁姆二世"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_SONGTSAN_GAMPO_NAME",                   "张道陵"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM_NAME",                     "莪默·伽亚谟"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET_NAME",               "约瑟夫·拉格朗日"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG_NAME",                      "尤斯图斯·冯·李比希"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MARGARET_MEAD_NAME",                    "尤里乌斯·奥本海默"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_HD_BOOST_OR_GRANT_NUCLEAR_FISSION",                "为核裂变科技启动 [ICON_TECHBOOSTED] 尤里卡时刻。若核裂变尤里卡已被触发，则完成该科技。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY_NAME",                      "罗莎琳德·富兰克林"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM_NAME",                      "列夫·朗道"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_STEPHANIE_KWOLEK_NAME",                 "莱纳斯·卡尔·鲍林"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_DANDARA_NAME",                          "卡尔·冯·克劳塞维茨"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_HD_COMBAT_STRENGTH",                               "所有陆地单位+2 [ICON_STRENGTH] 战斗力。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_HD_COMBAT_STRENGTH_MODIFIER",                      "来自伟人"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_SAMORI_TURE_ACTIVE",                                "立即创建1个带有1次强化等级的线列步兵单位。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_MILITARY_POLICY_SLOT",                             "所有政体军事政策槽位+1。"),
    ("zh_Hans_CN",  "LOC_GREATWORK_QU_YUAN_1_NAME",                                      "《天问》"),
    ("zh_Hans_CN",  "LOC_GREATWORK_QU_YUAN_2_NAME",                                      "《离骚》"),
    ("zh_Hans_CN",  "LOC_GREATPERSON_EXTRA_TRADE_ROUTE_CAPACITY",                        "增加1条 [ICON_TRADEROUTE] 贸易路线容量。"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_INDIVIDUAL_XU_FU_NAME",                            "徐福"),
    ("zh_Hans_CN",  "LOC_GREAT_PERSON_HD_EMBARKED_EXTRA_MOVEMENT",                       "水运单位+1 [ICON_MOVEMENT] 移动力。[NEWLINE]该港口的 [ICON_GOLD] 金币相邻加成也提供 [ICON_FAITH] 信仰值。"),
    ("zh_Hans_CN",  "LOC_GREATWORK_SUN_TZU_NAME",                                        "《孙子兵法》[NEWLINE]所有战斗单位的攻击经验+25%。（需要移动展示槽位后生效）[NEWLINE]");