--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
	(Tag,														Text)
values
	("LOC_IMPROVEMENT_BUTTRESS_ON_FLOODLANDS",									"[NEWLINE][NEWLINE]Once Buttress is unlocked it can also be built on Floodplains."),
	-- Base Improvements
	("LOC_IMPROVEMENT_FARM_HD_DESCRIPTION",											"Can only be built on Grassland or Plains. After Civil Engineering is unlocked, it can also be built on Grassland Hills or Plains Hills."),
	("LOC_IMPROVEMENT_MINE_HD_DESCRIPTION",											"Can be built on Hills or valid Resources. Once Engineering is unlocked it can also be built on Geothermal Fissures. Extra +1 [ICON_Production] Production if built adjacent to Mountains after researching Bronze Working Technology (obsolete with Apprenticeship Tech)."),
	("LOC_IMPROVEMENT_QUARRY_HD_DESCRIPTION",										"Can only be built on valid resources. Extra +1 [ICON_Production] Production if built on Hills after researching Masonry Technology (obsolete with Metal Casting Tech)."),
	("LOC_IMPROVEMENT_PLANTATION_HD_DESCRIPTION",								"Extra +1 [ICON_FOOD] Food if adjacent to fresh water or Aqueduct after researching Irrigation Technology (obsolete with Feudalism Civic). [NEWLINE][NEWLINE]Can only be built on valid resources."),
	("LOC_IMPROVEMENT_PASTURE_HD_DESCRIPTION",									"Extra +1 [ICON_Production] Production if built on Hills after researching Wheel Technology (obsolete with Heraldry Civic). [NEWLINE][NEWLINE]Can only be built on valid Resources."),
	("LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",											"Extra +1 [ICON_Production] Production if built on features after researching Archery Technology (obsolete with Medieval Faires Civic). [NEWLINE][NEWLINE]Can only be built on valid Resources. Once Archery is unlocked it can also be built on Forests. Once Guilds is unlocked it can also be built on Rainforest."),
	("LOC_IMPROVEMENT_LUMBER_MILL_HD_DESCRIPTION",							"Extra +1 [ICON_Production] Production if adjacent to river after researching Wheel Technology (obsolete with Machinery Technology). [NEWLINE][NEWLINE]Can only be built on Woods. Once Guilds is unlocked it can also be built on Rainforest."), -- Once Bronze Working is unlocked, Extra +1 [ICON_Production] Production if adjacent to a River.
	("LOC_IMPROVEMENT_FISHING_BOATS_HD_DESCRIPTION",						"Extra +1 [ICON_FOOD] Food if adjacent to passable land tile or Harbor district (obsolete with Compass Technology). [NEWLINE][NEWLINE]Can only be built on valid Resources."),
	("LOC_IMPROVEMENT_FISHERY_HD_DESCRIPTION",									"+1 [ICON_Production] Production from every adjacent Fishing Boat. +1 [ICON_FOOD] Food from every adjacent Fishery after researching Celestial Navigation Technology.[NEWLINE][NEWLINE]Must be built on a Water Area tile. Must be built adjacent to Water Area Resource or on features of water area."),
	("LOC_IMPROVEMENT_BEACH_RESORT_HD_DESCRIPTION",							"Provides [ICON_GOLD] Gold equal to 400% of the tile's Appeal. +3 [ICON_GOLD] Gold from each building of Harbor or Water Park district in this city. [NEWLINE][NEWLINE]Can only be built on flat Desert, Plains, or Grassland tiles adjacent to Shallow Sea. Minimum Appeal of Breathtaking."),
	("LOC_IMPROVEMENT_SKI_RESORT_HD_DESCRIPTION",								"+1 [ICON_AMENITIES] Amenity.[NEWLINE][NEWLINE]If adjacent to any Improvement which provide [ICON_TOURISM] Tourism, +50% [ICON_TOURISM] Tourism to Improvements in all cities.[NEWLINE]If adjacent to any Wonder, +50% [ICON_TOURISM] Tourism to Wonders in all cities.[NEWLINE][NEWLINE]Can only be built on a Mountain. Cannot be built adjacent to another Ski Resort. Cannot be pillaged, worked or removed. One per City."),
	("LOC_IMPROVEMENT_SKI_RESORT_HD_MONOPOLY_DESCRIPTION",			"+1 [ICON_AMENITIES] Amenity.[NEWLINE][NEWLINE]If adjacent to any Improvement which provide [ICON_TOURISM] Tourism, +50% [ICON_TOURISM] Tourism to Improvements in all cities.[NEWLINE]If adjacent to any Wonder, +50% [ICON_TOURISM] Tourism to Wonders in all cities.[NEWLINE]If adjacent to Entertainment Complex or Water Park districs, +50% [ICON_TOURISM] Tourism to [ICON_GreatWork_Product] Products in all cities.[NEWLINE][NEWLINE]Can only be built on a Mountain. Cannot be built adjacent to another Ski Resort. Cannot be pillaged, worked or removed. One per City."),
	-- UI of Majors	
	("LOC_IMPROVEMENT_OUTBACK_STATION_DESCRIPTION",							"+1 [ICON_PRODUCTION] Production and +0.5 [ICON_HOUSING] Housing. +1 [ICON_FOOD] Food from every adjacent Pasture, +1 [ICON_PRODUCTION] from every adjacent Outback Station. Provide additional yields to adjacent Pasture and Outback Station as you advance through the Civics and Technology Tree. [NEWLINE]Trigger a Culture Bomb. When built on a tile for the first time, randomly import a copy of the adjacent {LOC_OUTBACK_STATION_BREED_IMPORT}Pasture Resource on an adjacent {LOC_SAVANNAH_AND}Desert, Desert Hill, Grassland, Grassland Hill, Plain or Plain Hill tile. [NEWLINE][NEWLINE]Can only be built on {LOC_SAVANNAH_AND}Desert, Desert Hill, Grassland, Grassland Hill, Plain and Plain Hill tiles."),
	("LOC_OUTBACK_STATION_BREED_IMPORT",       									""),
	("LOC_OUTBACK_STATION_COPY_RESOURCE",       								"Outback Station: Import "),
	("LOC_IMPROVEMENT_TERRACE_FARM_DESCRIPTION",								"+1 [ICON_FOOD] Food, +1 [ICON_HOUSING] Housing. +1 [ICON_PRODUCTION] Production if adjacent to Fresh Water or Aqueduct district. +1 [ICON_FOOD] Food from every adjacent Mountain Tile. [NEWLINE][NEWLINE]Built on tiles adjacent to the builder. Must be built on Hills or Mountain tiles in Grassland, Plains, Desert or Tundra (including Volacanos). Can be built on farm and pasture resources on Grassland, Plains or Desert Hills."),
	("LOC_IMPROVEMENT_MOUNTAIN_ROAD_DESCRIPTION",								"Equivalent to a Mountain Tunnel. 2 [Icon_Production] Production, +3 [ICON_GOLD] Gold. Receive +1 [Icon_Production] Production and [ICON_GOLD] Gold from transportation facilities in this city (except Qhapaq Ñan). [NEWLINE][NEWLINE]Can only be built on an adjacent Mountain tile. Cannot be pillaged or removed."),
	("LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",										"+1 [Icon_Production] Production. Provides [ICON_CULTURE] Culture equal to 100% of the tile's Appeal. Can only be built on Charming or Breathtaking tiles. Can be built on Woods and Swamp."),
	("LOC_IMPROVEMENT_SPHINX_EXPANSION2_DESCRIPTION",						"+1 [ICON_Culture] Culture, +2 [ICON_FAITH] Faith. Extra +1 [ICON_CULTURE] Culture if built on Floodplains. Provides yields equal to 1 times the basic yield of all adjacent Wonders. +2 Appeal to adjacent tiles. Cannot be built next to another Sphinx. Cannot be built on Snow or Snow Hills."),
	("LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",											"Provides +1 [ICON_PRODUCTION] Production +2 [ICON_GOLD] Gold and +1 [ICON_HOUSING] Housing. +1 [ICON_FOOD] Food from every adjacent Bonus resource, +1 [ICON_PRODUCTION] Production from every adjacent Luxury or Strategic resource. Additional [ICON_PRODUCTION] Production, [ICON_FOOD] Food and [ICON_HOUSING] Housing as you advance through the Civics and Technology Tree. Must be built adjacent to a Bonus or Luxury resource. Can be built on Woods and Swamp after researching 'Mining' Technology. Cannot be built adjacent to another Mekewap."),
	("LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",										"+1 [ICON_PRODUCTION] Production and +0.5 [ICON_HOUSING] Housing. +1 [ICON_PRODUCTION] Production from every adjacent Plantation, +1 [ICON_FOOD] Food from every 2 adjacent Hacienda, additional [ICON_PRODUCTION] Production and [ICON_FOOD] Food as you advance through the Civics and Technology Tree. Plantation receives +1 [ICON_PRODUCTION] Production from every 2 adjacent Haciendas, with extra +3 [ICON_GOLD] Gold after researching 'Banking' Technology. Can only be built on Rainforests, Plains, Plains Hills, Grassland , Grassland Hills and Swamps."),
	("LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",									"+1 [ICON_CULTURE] Culture, +2 [ICON_GOLD] Gold. +1 [ICON_CULTURE] Culture from every adjacent Holy Site or Theater Square. +2 [ICON_GOLD] Gold from every adjacent Commercial Hub. +1 [ICON_FOOD] Food from every adjacent City Center. Receives +1 [ICON_CULTURE] Culture from each Government Plaza or Government Plaza building in your civilization. +1 [ICON_CULTURE] Culture after progressing 'Civil Service' Civic. +2 Appeal to adjacent tiles. Cannot be built on Snow, Tundra, Snow Hills, or Tundra Hills or adjacent to another Pairidaeza."),
	("LOC_IMPROVEMENT_KURGAN_DESCRIPTION",											"+1 [ICON_Faith] Faith and +3 [ICON_Gold] Gold. +1 [ICON_Faith] Faith from every adjacent Pasture, which becomes +2 [ICON_Faith] Faith after researching 'Stirrups' Technology. +2 [ICON_FAITH] Faith from every retired [ICON_GREATGENERAL] Great General. +2 [ICON_FAITH] Faith from every promotion level of your Cavalry and Saka Horse Archer units killed in cambat. Provides +1 [ICON_Faith] Faith to adjacent Pasture. Allow the purchase of Cavalry units using [ICON_FAITH] Faith in this city. Cannot be built on Hills."),
	("LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",											"+2 [ICON_Faith] Faith and +1 [ICON_Food] Food. Extra +2 [ICON_Faith] Faith and +1 [ICON_Food] Food if built on non-Floodplains Desert tiles. Nubian Pyramid receives corresponding yield from different districts. Yields from being adjacent to these districts are doubled after progressing 'Feudalism' Civic. Can only be built on Plains, Grass and Desert (including Hills and Floodplains)."),
	("LOC_IMPROVEMENT_ZIGGURAT_DESCRIPTION",										"+1 [ICON_SCIENCE] Science. +1 [ICON_FAITH] Faith and +1 [ICON_Culture] Culture if adjacent to River. +2 [ICON_GREATPROPHET] Great Prophet Points if adjacent to City Center. When you complete a special quest for each type of city-state for the first time, receives corresponding yields of the city-state`s type. [NEWLINE][NEWLINE]Cannot be built on Hills. Can be built on Floodplains. One per City; after respectively founding Pantheon and Religion, [ICON_Capital] capital can build an additional Ziggurat; for every building of Holy Site district, city can build an additional Ziggurat."),
	("LOC_IMPROVEMENT_CHATEAU_EXPANSION2_DESCRIPTION",					"+2 [ICON_FOOD] Food, +1 [ICON_Culture] Culture and +1 [ICON_HOUSING] Housing. +1 [ICON_FOOD] Food from every adjacent Bonus resource. +2 [ICON_CULTURE] Culture from every adjacent Luxury resource and Wonder. Provide an extra copy for each adjacent improved Plantation, Farm or Lumber Mill Luxury resource. +1 Appeal to adjacent tiles. Can only be built one per city. Must be placed adjacent to a Bonus or Luxury resource."),
	("LOC_IMPROVEMENT_STEPWELL_EXPANSION2_DESCRIPTION",					"+2 [ICON_Food] Food and +1 [ICON_Housing] Housing. +2 [ICON_FAITH] Faith from every Holy Site district. +1 [ICON_FAITH] Faith from each adjacent Farm or Plantation tile. +1 [ICON_Food] Food to adjacent Farm and Plantation tiles. Additional [ICON_FAITH] Faith as you advance through the Civics Tree. After researching 'Masonry' Technology, cities with a Stepwell receive +1 [ICON_AMENITIES] Amenity, [ICON_CITIZEN] citizens in these cities provide +0.5 [ICON_FOOD]. Prevents [ICON_Food] Food loss during Drought. Can be built on flat terrains or floodplains. After researching 'Masonry' Technology, can be built on Hills. Cannot be built adjacent to another Stepwell."),
	("LOC_IMPROVEMENT_KAMPUNG_DESCRIPTION",											"+1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production and +1 [ICON_Housing] Housing. After researching Steam Power Technology, +1 [ICON_Housing] Housing. After researching Urbanization Civic, +1 [ICON_Housing] Housing. [NEWLINE]+1 [ICON_FOOD] Food and +1 [ICON_PRODUCTION] Production to every adjacent Shallow Sea and Lake tile, doubled after researching Oceanography Technology. If adjacent to Specialized districts, provide corresponding yields to Shallow Sea and Lake tiles in this city (limit once of each type), doubled after researching Urbanization Civic. [NEWLINE][NEWLINE]Must be placed on a Shallow Sea and Lake tile. Can be built on Reef{LOC_AND_KELP}. Cannot be built adjacent to another Kampung."),
	("LOC_IMPROVEMENT_GOLF_COURSE_XP2_DESCRIPTION",							"+1 [ICON_AMENITIES] Amenity. Extra +1 [ICON_AMENITIES] Amenity after progressing 'Humanism' Civic. +1 [ICON_CULTURE] Culture to every adjacent District. If adjacent to a district which provides adjacency bonus, Golf Course provides +50% adjacency bonuses towards all districts of this type, and provides +30% [ICON_Production] Production towards district of this type in all your cities; each type of district can only receive this bonus once. [NEWLINE][NEWLINE]Cannot be built on Desert or Desert Hills. One per city. This tile cannot be worked."),
	("LOC_IMPROVEMENT_GREAT_WALL_EXPANSION2_DESCRIPTION",				"+1 [ICON_Food] Food, +2 [ICON_GOLD] Gold. Provides an increase to [ICON_Strength] Defense. Enemy military units receive -2 [ICON_Strength] Strength from each adjacent Great Wall. +2 [ICON_Culture] Culture from each adjacent Great Wall. +2 [ICON_Gold] Gold from each adjacent Great Wall after researching 'Castles' Technology. Built on tiles adjacent to the builder. Must be built in a line along the borders of your empire. Can be built on Mountain or Forest{LOC_OR_SWAMP_NAME} tiles. Can only be pillaged (never destroyed) by natural disasters."),
	("LOC_IMPROVEMENT_ROCK_HEWN_CHURCH_EXPANSION2_DESCRIPTION",	"+1 [ICON_FAITH] Faith and +1 [ICON_FOOD] Food. +1 [ICON_FAITH] Faith from every adjacent Hills and Mountain tile. +1 [ICON_FAITH] Faith from every adjacent Resources. May purchase Builders and Settlers with [ICON_FAITH] Faith in this city. +1 Appeal to adjacent tiles. Can only be built on Hills. Cannot be built adjacent to another Rock-Hewn Church."),
	("LOC_IMPROVEMENT_ICE_HOCKEY_RINK_DESCRIPTION",							"+2 [ICON_AMENITIES] Amenity. +1 [ICON_CULTURE] Culture from every city on Tundra or Snow tiles in your civilization. +1 [ICON_PRODUCTION] Production from every type of Specialized district on Tundra or Snow tiles in your civilization. +2 Appeal to adjacent tiles. Can be built on Tundra, Tundra Hills, Snow, and Snow Hills. One per City."),
	("LOC_IMPROVEMENT_ICE_HOCKEY_RINK_DESCRIPTION_JNR_UC",			"+2 [ICON_AMENITIES] Amenity. +1 [ICON_CULTURE] Culture from every city on Tundra or Snow tiles in your civilization. +1 [ICON_PRODUCTION] Production from every type of Specialized district on Tundra or Snow tiles in your civilization. +2 Appeal to adjacent tiles. Can be built on Tundra, Tundra Hills, Snow, and Snow Hills. One per City."),
	("LOC_IMPROVEMENT_MISSION_EXPANSION2_DESCRIPTION",					"+1 [ICON_SCIENCE] Science, +3 [ICON_Faith] Faith. +1 [ICON_Science] Science from every adjacent Campus or Holy Site. +1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production if adjacent to City Center; doubled if it is built not on your [ICON_CAPITAL] Capital's continent. +1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production from every adjacent Neighborhood. Provide additional yields as you advance through the Civics and Technology Tree. [NEWLINE][NEWLINE]If you have founded a Religion, spread +150 Religious Pressure to all Cities within 3 tiles. Can be built on unowned territory."),
	("LOC_IMPROVEMENT_POLDER_NAME",															"Coastal Polder"),
	("LOC_IMPROVEMENT_POLDER_DESCRIPTION",											"+1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production and +0.5 [ICON_HOUSING] Housing. +1 [ICON_FOOD] Food from every 2 adjacent Coastal Polder or Floodplain Polder tiles. Additional [ICON_FOOD] Food and [ICON_PRODUCTION] Production as you advance through the Civics and Technology Tree. Must be placed on a Shallow Sea and Lake tile adjacent to passable land tile.Can be built on Reef. Increases [ICON_MOVEMENT] Movement Cost by 1."),
	("LOC_IMPROVEMENT_LAND_POLDER_NAME",												"Floodplain Polder"),
	("LOC_IMPROVEMENT_LAND_POLDER_DESCRIPTION",									"+1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production and +0.5 [ICON_HOUSING] Housing. +1 [ICON_FOOD] Food from every 2 adjacent Coastal Polder or Floodplain Polder tiles. Additional [ICON_FOOD] Food and [ICON_PRODUCTION] Production as you advance through the Civics and Technology Tree. Must be placed on a Floodplain or Marsh tile. Can be built on farm and plantation resources on Floodplain or Marsh tiles. Increases [ICON_MOVEMENT] Movement Cost by 1."),
	("LOC_IMPROVEMENT_OPEN_AIR_MUSEUM_DESCRIPTION",							"+1 [ICON_CULTURE] Culture from every type of Terrain in your territory. +1 [ICON_SCIENCE] Science from every type of Feature or Natural Wonder in your territory. One per city."),
	("LOC_MARSH_AND_SWAMP",																			"Marsh"),
	("LOC_MARSH_OR_SWAMP",																			"Marsh"),
	("LOC_AND_KELP",																						""),
	("LOC_SAVANNAH_AND",                                    		""),
	("LOC_IMPROVEMENT_FEITORIA_DESCRIPTION",									  "Provides +4 [ICON_GOLD] Gold and +1 [ICON_PRODUCTION] Production. Trade routes sent to this city from Portugal gain +4 [ICON_GOLD] Gold and +1 [ICON_PRODUCTION] Production. Can only be built adjacent to Luxury or Bonus resources in territory belonging to other Civilizations or City-States that you have Open Borders with. Must be built on a Shallow Sea and Lake tile adjacent to land and not adjacent to another Feitoria. Feitorias cannot be removed."),
	-- UI of Minors	
	("LOC_IMPROVEMENT_MAHAVIHARA_DESCRIPTION",									"+2 [ICON_SCIENCE] Science, +1 [Icon_Housing] Housing. +1 [ICON_Science] Science from every adjacent Campus or Holy Site district, which becomes +2 [ICON_Science] Science after progressing 'Divine Right' Civic. +1 [ICON_Science] Science from every adjacent Neighborhood. Must be built on flat terrain. Cannot be built adjacent to another Mahavihara."),
	("LOC_IMPROVEMENT_TRADING_DOME_DESCRIPTION",								"Provides the basic yield of all Luxury resource types improved by your Trading Dome. After researching 'Currency' Technology, your [ICON_TradeRoute] Trade Routes start from this city provide the basic yields of the Luxury resource improved by this Trading Dome, which is doubled after researching 'Economics' Technology. +2 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] if built on non-Floodplains Desert tile. Can only be built on land Luxury resource. One per city."),
	("LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",				"+2 [ICON_Faith] Faith, +1 [ICON_HOUSING] Housing. +15 HP healing for friendly religious unit on this tile that has not attacked this turn. +2 [ICON_FAITH] Faith from every adjacent District, which becomes +3 [ICON_FAITH] Faith after progressing 'Reformed Church' Civic. Extra +1 [ICON_HOUSING] Housing after progressing 'Colonialism' Civic. Cannot be built adjacenct to another Monastery. One per city."),
	("LOC_IMPROVEMENT_ALCAZAR_EXPANSION2_DESCRIPTION",					"+2 [ICON_Culture] Culture. Provides [ICON_SCIENCE] Science equal to the tile's Appeal. Occupying unit receives +4 [ICON_Strength] Defense Strength, and automatically gains 2 turns of fortification. Cannot be built next to another Alcázar."),
	("LOC_IMPROVEMENT_BATEY_DESCRIPTION",												"+1 [ICON_Culture] Culture. +1 [ICON_Culture] Culture from every adjacent Bonus Resource, Luxury Resource, Entertainment Complex or Neighborhood, which becomes +2 after progressing 'Humanism' Civic. Cannot be built on Hills or adjacent to another Batey."),
	("LOC_IMPROVEMENT_COLOSSAL_HEAD_EXPANSION2_DESCRIPTION",		"+2 [ICON_Faith] Faith. +1 [ICON_Faith] Faith from every adjacent Rainforest or Woods tile. Can be built on Rainforest , Woods and Swamp tiles."),
	("LOC_IMPROVEMENT_COLOSSAL_HEAD_NAME",											"Olmec Colossal Head"),
	("LOC_IMPROVEMENT_MOUND_DESCRIPTION",												"+3 [ICON_GOLD] Gold, +1 [ICON_HOUSING] Housing. Cities with Cahokia Mounds receive +1 [ICON_AMENITIES] Amenity, extra +1 for cities with at least 2 Cahokia Mounds. +1 [ICON_FOOD] Food from every adjacent District, which becomes +2 [ICON_FOOD] Food after progressing 'Historical Philosophy' Civic. Cannot be built adjacent to another Cahokia Mounds."),
	("LOC_IMPROVEMENT_NAZCA_LINE_DESCRIPTION",									"+1 [ICON_FOOD] Food to adjacent tiles. Extra +1 [ICON_FOOD] after researching 'Engineering' Technology, +1 [ICON_PRODUCTION] Production after researching 'Mass Production' Technology. Cities Adjacent to Nazca Line receive +2 [ICON_HOUSING] Housing. Provides standard adjacency bonus for Campus, Holy Site and Theater Square districts, which becomes major adjacency bonus after progressing 'Archaeology' Civic. Can only be built on flat Desert. Cannot be built adjacent to another Nazca Line. This tile cannot be worked."),
	("LOC_NAZCA_LINE_HOLY_SITE_ADJACENCY_DESCRIPTION",					"+{1_num} [ICON_FAITH] Faith from adjacent Nazca Line {1_Num : plural 2?Tiles; other?Tile;}."),
	("LOC_NAZCA_LINE_CAMPUS_ADJACENCY_DESCRIPTION",							"+{1_num} [ICON_SCIENCE] Science from adjacent Nazca Line {1_Num : plural 2?Tiles; other?Tile;}."),
	("LOC_NAZCA_LINE_THEATER_ADJACENCY_DESCRIPTION",						"+{1_num} [ICON_CULTURE] Culture from adjacent Nazca Line {1_Num : plural 2?Tiles; other?Tile;}."),
	("LOC_IMPROVEMENT_MOAI_DESCRIPTION",												"+2 [ICON_Culture] Culture. +2 [ICON_Culture] Culture if on or adjacent to a Volcanic Soil. +1 [ICON_Culture] Culture if adjacent to Shallow Sea and Lake. +1 [ICON_Culture] Culture from every 2 adjacent Moai or from every adjacent Moai after progress 'Medieval Faires' Civic. Can be built on Plains, Plains Hills, Grassland, Grassland Hills, or Volcanic Soil."),
	-- UI of Governor
	("LOC_IMPROVEMENT_CITY_PARK_DESCRIPTION",										"Provides +2 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production, +1 [ICON_Culture] Culture and +3 [ICON_GOLD]. Adjacent tiles receive +2 Appeal. Receives corresponding yield from different Specialized districts in its city and buildings in these districts. Cannot be placed adjacent to another City Park.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
	(Language,		Tag,														Text)
values
	("zh_Hans_CN",	"LOC_IMPROVEMENT_BUTTRESS_ON_FLOODLANDS",										"[NEWLINE][NEWLINE]解锁“扶壁”科技后，可以建造在泛滥平原上。"),
	-- 基础改良
	("zh_Hans_CN",	"LOC_IMPROVEMENT_FARM_HD_DESCRIPTION",											"只能建在草原或平原上。解锁“灌溉”科技后，允许建造在相邻淡水或水渠的平原和草原丘陵。解锁“土木工程”市政后，允许建造在所有草原丘陵或平原丘陵上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MINE_HD_DESCRIPTION",											"解锁“铸铜术”科技后，若靠近山脉单元格，额外+1 [ICON_Production] 生产力；解锁“学徒”科技后失效。[NEWLINE][NEWLINE]只能在丘陵或有效资源上建造，研究“工程”科技后也可以建造在地热裂缝上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_QUARRY_HD_DESCRIPTION",										"解锁“砌砖”科技后，若建造在丘陵上，额外+1 [ICON_Production] 生产力；解锁“金属铸造”科技后失效。[NEWLINE][NEWLINE]只能在有效资源上建造。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_PLANTATION_HD_DESCRIPTION",								"解锁“灌溉”科技后，若相邻淡水或水渠，额外+1 [ICON_FOOD] 食物；解锁“封建主义”市政后失效。[NEWLINE][NEWLINE]只能在有效资源上建造。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_PASTURE_HD_DESCRIPTION",										"解锁“轮子”科技后，若建造在丘陵上，额外+1 [ICON_Production] 生产力；解锁“纹章学”市政后失效。[NEWLINE][NEWLINE]只能在有效资源上建造。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_CAMP_HD_DESCRIPTION",											"解锁“箭术”科技后，若建造在地貌上，额外+1 [ICON_Production] 生产力；解锁“中世纪集市”后失效。[NEWLINE][NEWLINE]只能在有效资源上建造。解锁“弓箭”科技后也可建造在森林上。解锁“公会”市政后也可建造在雨林上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_LUMBER_MILL_HD_DESCRIPTION",								"解锁“轮子”科技后，若沿河，额外+1 [ICON_Production] 生产力；解锁“机械”科技后失效。[NEWLINE][NEWLINE]只能建在树林上。解锁“公会”市政后也能建造在雨林上。"), 
	("zh_Hans_CN",	"LOC_IMPROVEMENT_FISHING_BOATS_HD_DESCRIPTION",							"若相邻可通行陆地或港口，额外+1 [ICON_FOOD] 食物；解锁“罗盘”科技后失效。[NEWLINE][NEWLINE]只能在有效资源上建造。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_FISHERY_HD_DESCRIPTION",										"每与1个渔船相邻+1 [ICON_Production] 生产力。解锁“天文导航”科技后，每与1个渔场相邻+1 [ICON_FOOD] 食物。[NEWLINE][NEWLINE]必须建造在水域地貌或靠近水域资源的水域单元格上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_BEACH_RESORT_HD_DESCRIPTION",							"城市中每个港口和水上乐园建筑为海滨度假区+3 [ICON_GOLD] 金币。[NEWLINE][NEWLINE]只能建造在惊艳魅力的与浅海相邻的平原、草原、沙漠或火山土上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_SKI_RESORT_HD_DESCRIPTION",								"+1 [ICON_AMENITIES] 宜居度。[NEWLINE][NEWLINE]若相邻任何提供 [ICON_TOURISM] 旅游业绩的改良设施，则所有城市提供 [ICON_TOURISM] 旅游业绩的改良设施的 [ICON_TOURISM] 旅游业绩+50%。[NEWLINE]若相邻奇观，则所有城市奇观提供的 [ICON_TOURISM] 旅游业绩+50%。[NEWLINE][NEWLINE]只能建造在山脉单元格上。不能建造在与其他滑雪场相邻的单元格上。每个城市仅限建造一座。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_SKI_RESORT_HD_MONOPOLY_DESCRIPTION",				"+1 [ICON_AMENITIES] 宜居度。[NEWLINE][NEWLINE]若相邻任何提供 [ICON_TOURISM] 旅游业绩的改良设施，则所有城市提供 [ICON_TOURISM] 旅游业绩的改良设施的 [ICON_TOURISM] 旅游业绩+50%。[NEWLINE]若相邻奇观，则所有城市奇观提供的 [ICON_TOURISM] 旅游业绩+50%。[NEWLINE]若相邻娱乐中心或水上乐园，则分别为所有城市 [ICON_GreatWork_Product] 产品提供的 [ICON_TOURISM] 旅游业绩+50%。[NEWLINE][NEWLINE]只能建造在山脉单元格上。不能建造在与其他滑雪场相邻的单元格上。每个城市仅限建造一座。"),
	-- 文明特色改良
	("zh_Hans_CN",	"LOC_IMPROVEMENT_OUTBACK_STATION_DESCRIPTION",							"+1 [ICON_PRODUCTION] 生产力、+0.5 [ICON_HOUSING] 住房。每相邻1个牧场+1 [ICON_FOOD] 食物，每相邻1个内陆牧场+1 [ICON_PRODUCTION] 生产力。随着科技与市政的研究将为相邻的牧场和内陆牧场提供更多产出。[NEWLINE]建造后触发文化炸弹。在每个单元格上首次建成内陆牧场后，随机在一个相邻的{LOC_SAVANNAH_AND}沙漠、草原或平原或对应丘陵的单元格上引进一份相邻的{LOC_OUTBACK_STATION_BREED_IMPORT}牧场资源。[NEWLINE][NEWLINE]只能建造在{LOC_SAVANNAH_AND}沙漠、草原或平原以及对应的丘陵单元格上。"),
	("zh_Hans_CN",  "LOC_OUTBACK_STATION_BREED_IMPORT",       									""),
	("zh_Hans_CN",  "LOC_OUTBACK_STATION_COPY_RESOURCE",       									"内陆牧场：引进 "),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_TERRACE_FARM_DESCRIPTION",									"+1 [ICON_FOOD] 食物, +1 [ICON_HOUSING] 住房。如果相邻淡水或水渠则+1 [ICON_PRODUCTION] 生产力。每相邻一座山脉+1 [ICON_FOOD] 食物。[NEWLINE][NEWLINE]建造在与建造者相邻的单元格上。只能建在草原、平原、沙漠或冻土的丘陵或山脉上（包括火山）。可以改良草原、平原或沙漠的丘陵单元格上的农场或牧场资源。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MOUNTAIN_ROAD_DESCRIPTION",								"效果等同于穿山隧道。+2 [Icon_Production] 生产力、+3 [ICON_GOLD] 金币。从城市中的每个交通设施（不包括印加路网）获得+1 [Icon_Production] 生产力和 [ICON_GOLD] 金币。[NEWLINE][NEWLINE]只能建在山脉单元格上。无法被掠夺或移除。"),
  ("zh_Hans_CN",	"LOC_IMPROVEMENT_CHEMAMULL_DESCRIPTION",										"+1 [Icon_Production] 生产力。提供等同于所在单元格魅力100%的 [ICON_CULTURE] 文化值。只能建造在迷人或惊艳魅力的单元格上。可以建造在森林或木本沼泽上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_SPHINX_EXPANSION2_DESCRIPTION",						"+1 [ICON_Culture] 文化值、+2 [ICON_FAITH] 信仰值。若位于泛滥平原上，额外+1 [ICON_CULTURE] 文化值。提供等同于所有相邻奇观的基础产出总和的产出。为相邻单元格+2魅力。无法建在另一个狮身人面像旁。无法建在雪地或雪地丘陵上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MEKEWAP_DESCRIPTION",											"+1 [ICON_PRODUCTION] 生产力、+2 [ICON_GOLD] 金币、+1 [ICON_HOUSING] 住房。每相邻1个加成资源+1 [ICON_FOOD] 食物，每相邻1个奢侈或战略资源+1 [ICON_PRODUCTION] 生产力。随着科技与市政的研究将提供更多产出和住房。必须建在与加成或奢侈资源相邻的单元格上。解锁“采矿”科技后可以建造在森林与木本沼泽上。无法建在另一个棚屋旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_HACIENDA_DESCRIPTION",											"+1 [ICON_PRODUCTION] 生产力、+0.5 [ICON_HOUSING] 住房。每相邻1个种植园+1 [ICON_PRODUCTION] 生产力，每相邻2个大庄园+1 [ICON_FOOD] 食物。随着科技与市政的研究将提供更多产出。种植园每相邻2个大庄园+1 [ICON_PRODUCTION] 生产力，解锁“银行业”科技后额外+3 [ICON_GOLD] 金币。只能建造在雨林、平原、平原丘陵、草原和草原丘陵或木本沼泽上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",										"+1 [ICON_CULTURE] 文化值、+2 [ICON_GOLD] 金币。每相邻1个圣地或剧院广场+1 [ICON_CULTURE] 文化值。每相邻1个商业中心+2 [ICON_GOLD] 金币。每相邻1个市中心+1 [ICON_FOOD] 食物。您每拥有1个市政广场和市政广场建筑+1 [ICON_CULTURE] 文化值。解锁“行政部门”市政后+1 [ICON_Culture] 文化值。为相邻单元格+2魅力。无法建在雪地、冻土、雪地丘陵或冻土丘陵上，也无法建在另一座波斯庭院旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_KURGAN_DESCRIPTION",												"+1 [ICON_Faith] 信仰值、+3 [ICON_Gold] 金币。每相邻1个牧场+1 [ICON_Faith] 信仰值，解锁“马镫”科技后变为+2 [ICON_Faith] 信仰值。每隐退一个 [ICON_GREATGENERAL] 大将军+2 [ICON_FAITH] 信仰值。在战斗中被击杀的每个骑兵和萨卡弓骑手单位每有1级晋升便+1 [ICON_FAITH] 信仰值。为相邻的牧场+1 [ICON_Faith] 信仰值。允许城市用 [ICON_FAITH] 信仰值购买骑兵单位。不能建在丘陵上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_PYRAMID_DESCRIPTION",											"+1 [ICON_Food] 食物、+2 [ICON_Faith] 信仰值。如果建造在沙漠单元格（非泛滥平原），额外+2 [ICON_Food] 食物和 [ICON_Faith] 信仰值。获得相邻区域的对应产出；解锁“封建主义”市政后，这些产出翻倍。[NEWLINE][NEWLINE]只能建造在沙漠、草原或平原以及对应的丘陵或泛滥平原上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_ZIGGURAT_DESCRIPTION",											"+1 [ICON_SCIENCE] 科技值。如果相邻河流，+1 [ICON_Culture] 文化值和 [ICON_FAITH] 信仰值。如果相邻市中心建造，+2 [ICON_GREATPROPHET] 大预言家点数。首次完成每种城邦的特殊任务后，获得该城邦类型的对应产出。[NEWLINE][NEWLINE]不能建造在丘陵上，可以建造在泛滥平原上。每个城市仅限建造一座；创建万神殿和宗教后，[ICON_Capital] 首都可以分别额外建造一座金字形神塔；城市中每拥有一座圣地建筑，可以额外建造一座金字形神塔。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_CHATEAU_EXPANSION2_DESCRIPTION",						"+2 [ICON_FOOD] 食物、+1 [ICON_Culture] 文化值、+1 [ICON_HOUSING] 住房。每相邻1个加成资源+1 [ICON_FOOD] 食物，每相邻1个奢侈资源或奇观+2 [ICON_Culture] 文化值。额外提供一份相邻的且已改良的种植园、农场或伐木场奢侈资源。为相邻单元格+1魅力。每个城市仅限建造一座，且必须建在加成或奢侈品资源旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_STEPWELL_EXPANSION2_DESCRIPTION",					"+2 [ICON_Food] 食物、+1 [ICON_Housing] 住房。每相邻1个圣地区域，+2 [ICON_FAITH] 信仰值。每相邻1个农场或种植园，+1 [ICON_FAITH] 信仰值。给相邻的农场和种植园+1 [ICON_FOOD] 食物。随着科技与市政的研究将提供更多产出。解锁“砌砖”科技后，有梯井的城市+1 [ICON_AMENITIES] 宜居度，每位 [ICON_CITIZEN] 公民+0.5 [ICON_FOOD] 食物。干旱期间可防止 [ICON_Food] 食物损失。可以建造在平坦地形或泛滥平原上，解锁“砌砖”科技后可以建在丘陵上。不能建在另一个梯井旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_KAMPUNG_DESCRIPTION",											"+1 [ICON_FOOD] 食物、+1 [ICON_Production] 生产力和+1 [ICON_Housing] 住房；解锁“蒸汽动力”科技后+1 [ICON_Housing] 住房；解锁“城市化”市政后+1 [ICON_Housing] 住房。[NEWLINE]为相邻的浅海与湖泊单元格+1 [ICON_FOOD] 食物和 [ICON_PRODUCTION] 生产力，解锁“海洋学”科技后收益翻倍。相邻专业化区域时，为本城的浅海与湖泊单元格提供该区域的对应产出，对每种区域仅能生效一次；解锁“城市化”市政后产出翻倍。[NEWLINE][NEWLINE]必须建造在浅海与湖泊单元格上，可以建造在礁石{LOC_AND_KELP}上。无法建在另一个甘榜屋旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_GOLF_COURSE_XP2_DESCRIPTION",							"+1 [ICON_AMENITIES] 宜居度。解锁人文主义市政后，额外+1 [ICON_AMENITIES] 宜居度。相邻的区域+1 [ICON_Culture] 文化值。若建造在提供相邻产出的区域旁，则使所有该区域+50%相邻加成，且所有城市建造该区域+30%建造速度；每种区域仅能获得一次该加成。[NEWLINE][NEWLINE]无法建在沙漠或沙漠丘陵上。每个城市仅限建造一座。此单元格无法被工作。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_GREAT_WALL_EXPANSION2_DESCRIPTION", 				"+1 [ICON_Food] 食物，+2 [ICON_GOLD] 金币。每相邻1个长城+2 [ICON_Culture] 文化值。解锁“城堡”科技后，每相邻1个长城+2 [ICON_GOLD] 金币。进驻单位+4 [ICON_STRENGTH] 防御力，自动进入驻扎状态并获得两回合的驻扎加成（无论他们本回合是否行动过）。敌方军事单位每相邻一段长城-2 [ICON_Strength] 战斗力。[NEWLINE][NEWLINE]建造在与建造者相邻的单元格上。必须沿着帝国的边界线建造。可以建造在山脉、树林{LOC_OR_SWAMP_NAME}上。不会被自然灾害摧毁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_ROCK_HEWN_CHURCH_EXPANSION2_DESCRIPTION",	"+1 [ICON_FAITH] 信仰值，+1 [ICON_FOOD] 食物。每相邻1个丘陵或山脉+1 [ICON_FAITH] 信仰值。每相邻1个资源+1 [ICON_FAITH] 信仰值。可以在此城市中用 [ICON_FAITH] 信仰值购买建造者和开拓者。为相邻单元格+1魅力。只能建造在丘陵上。无法建在另一座独石教堂旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_ICE_HOCKEY_RINK_DESCRIPTION",							"+2 [ICON_AMENITIES] 宜居度。您的文明每有1个在冻土或雪地上的城市便+1 [ICON_CULTURE] 文化值。您的文明每有一种在冻土或雪地上的专业化区域便+1 [ICON_PRODUCTION] 生产力。给相邻单元格+2魅力。可以建造在冻土、冻土丘陵、雪地和雪地丘陵之上。每个城市仅限建造一座。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_ICE_HOCKEY_RINK_DESCRIPTION_JNR_UC",				"+2 [ICON_AMENITIES] 宜居度。您的文明每有1个在冻土或雪地上的城市便+1 [ICON_CULTURE] 文化值。您的文明每有一种在冻土或雪地上的专业化区域便+1 [ICON_PRODUCTION] 生产力。给相邻单元格+2魅力。可以建造在冻土、冻土丘陵、雪地和雪地丘陵之上。每个城市仅限建造一座。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MISSION_EXPANSION2_DESCRIPTION",						"+1 [ICON_SCIENCE] 科技值，+3 [ICON_Faith] 信仰值。相邻市中心建造+1 [ICON_FOOD] 食物和 [ICON_PRODUCTION] 生产力；如果建造在异大陆上，则该加成翻倍。每相邻1个学院或圣地+1 [ICON_Science] 科技值。每相邻1个社区+1 [ICON_FOOD] 食物和 [ICON_PRODUCTION] 生产力。随着科技与市政的研究将提供更多产出。[NEWLINE][NEWLINE]若您已经创立了一个宗教，则向3个单元格内的所有城市施加150点您所创立宗教的宗教压力。可以建造在无主单元格上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_POLDER_NAME",															"滨海圩田"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_POLDER_DESCRIPTION",												"+1 [ICON_FOOD] 食物、+1 [ICON_Production] 生产力、+0.5 [ICON_Housing] 住房。每相邻2个滨海圩田或淤滩圩田+1 [ICON_FOOD] 食物。随着科技与市政的研究将提供更多产出。必须建在相邻可通行陆地单元格的浅海与湖泊上，可以建在礁石上。[ICON_Movement] 移动力消耗增加1点。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_LAND_POLDER_NAME",													"淤滩圩田"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_LAND_POLDER_DESCRIPTION",									"+1 [ICON_FOOD] 食物、+1 [ICON_Production] 生产力、+0.5 [ICON_Housing] 住房。每相邻2个滨海圩田或淤滩圩田+1 [ICON_FOOD] 食物。随着科技与市政的研究将提供更多产出。必须建在泛滥平原或沼泽单元格上。可以改良泛滥平原或沼泽单元格上的农场或种植园资源。[ICON_Movement] 移动力消耗增加1点。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_OPEN_AIR_MUSEUM_DESCRIPTION",							"您的领土中每有一种地形便+1 [ICON_CULTURE] 文化值，解锁“博物馆学”市政后翻倍。您的领土中每有一种地貌或自然奇观便+1 [ICON_SCIENCE] 科技值，解锁“生物”科技后翻倍。每个城市仅限建造一座。"),
	("zh_Hans_CN",	"LOC_MARSH_AND_SWAMP",																			"沼泽"),
	("zh_Hans_CN",	"LOC_MARSH_OR_SWAMP",																				"沼泽"),
	("zh_Hans_CN",	"LOC_AND_KELP",																							""),
	("zh_Hans_CN",  "LOC_SAVANNAH_AND",                                    			""),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_FEITORIA_DESCRIPTION",											"提供+4 [ICON_GOLD] 金币、+1 [ICON_PRODUCTION] 生产力。从葡萄牙通往此城的贸易路线+4 [ICON_GOLD] 金币，+1 [ICON_PRODUCTION] 生产力。仅能建造在其他文明或城邦领土（已与其开放边境）上的奢侈品或加成资源旁。必须建造在与陆地相邻的浅海与湖泊单元格上，且无法与另一个商站相邻。无法移除商站。"),
	-- 城邦改良	
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MAHAVIHARA_DESCRIPTION",										"+2 [ICON_SCIENCE] 科技值、+1 [Icon_Housing] 住房。每相邻1个学院或圣地区域+1 [ICON_Science] 科技值，解锁“王权神授”市政后变为+2 [ICON_Science] 科技值。每相邻1个社区+1 [ICON_SCIENCE] 科技值。必须建在平坦地貌上。无法建在另一个大寺旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_TRADING_DOME_DESCRIPTION",									"获得等同于您的圆顶集市改良的每一种奢侈资源基础产出相同的产出。研究“货币”科技后，此城出发的 [ICON_TRADEROUTE] 贸易路线获得此圆顶集市所改良奢侈资源的基础产出，研究“经济”科技后翻倍。若建造在沙漠单元格（非泛滥平原），则+2 [ICON_FOOD] 食物，+1 [ICON_PRODUCTION] 生产力。只能建造在陆地奢侈品资源上。每个城市仅限建造一座。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MONASTERY_EXPANSION2_DESCRIPTION",					"+2 [ICON_Faith] 信仰值，+1 [ICON_HOUSING] 住房。此单元格上的友方宗教单位生命值恢复+15（前提是其当前回合未发动攻击）。每相邻1个区域+2 [ICON_FAITH] 信仰值，解锁“归正会”市政后变为+3 [ICON_FAITH] 信仰值。解锁“殖民主义”市政后额外 +1 [ICON_HOUSING] 住房。不能建在另一个修道院旁。每个城市仅限建造一座。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_ALCAZAR_EXPANSION2_DESCRIPTION",						"+2 [ICON_Culture] 文化值。提供等同于单元格魅力的 [ICON_SCIENCE] 科技值。占领单位 [ICON_Strength] 防御力+4，并自动获得2回合驻扎加成。无法建在另一座阿卡萨城堡旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_BATEY_DESCRIPTION",												"+1 [ICON_Culture] 文化值。每相邻1个加成资源、奢侈资源、娱乐中心或社区+1 [ICON_Culture] 文化值，完成“人文主义”市政后变为+2 [ICON_Culture] 文化值。不能建造在丘陵上或建造在另一座巴特依旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_COLOSSAL_HEAD_EXPANSION2_DESCRIPTION", 		"+2 [ICON_Faith] 信仰值。每相邻1个森林或雨林+1 [ICON_Faith] 信仰值。可以建造在雨林、森林或木本沼泽上。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_COLOSSAL_HEAD_NAME",												"奥尔梅克头像"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MOUND_DESCRIPTION",												"+3 [ICON_GOLD] 金币、+1 [Icon_Housing] 住房。有卡霍基亚土墩的城市获得+1 [ICON_AMENITIES] 宜居度，有至少2个卡霍基亚土墩的城市额外+1 [ICON_AMENITIES] 宜居度。每相邻1个区域+1 [ICON_FOOD] 食物，解锁“历史哲学”市政后变为+2 [ICON_FOOD] 食物。无法建造在另一个卡霍基亚土墩旁。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_NAZCA_LINE_DESCRIPTION",										"相邻的单元格+1 [ICON_FOOD] 食物。解锁“工程”科技后额外+1 [ICON_FOOD] 食物，解锁“批量生成”科技后额外+1 [ICON_PRODUCTION] 生产力。相邻的资源+1 [ICON_Faith] 信仰值。相邻纳斯卡巨画的城市+2 [ICON_HOUSING] 住房。给学院、圣地和剧院广场提供标准相邻加成，解锁“考古学”市政后变为大量相邻加成。仅能建在平坦的沙漠上。无法建在另一个纳斯卡巨画旁。此单元格无法被工作。"),
	("zh_Hans_CN",	"LOC_NAZCA_LINE_HOLY_SITE_ADJACENCY_DESCRIPTION",						"+{1_num} [ICON_FAITH] 信仰值来自相邻的纳斯卡巨画。"),
	("zh_Hans_CN",	"LOC_NAZCA_LINE_CAMPUS_ADJACENCY_DESCRIPTION",							"+{1_num} [ICON_SCIENCE] 科技值来自相邻的纳斯卡巨画。"),
	("zh_Hans_CN",	"LOC_NAZCA_LINE_THEATER_ADJACENCY_DESCRIPTION",							"+{1_num} [ICON_CULTURE] 文化值来自相邻的纳斯卡巨画。"),
	("zh_Hans_CN",	"LOC_IMPROVEMENT_MOAI_DESCRIPTION",													"+2 [ICON_Culture] 文化值。在火山土上或与其相邻时+2 [ICON_Culture] 文化值。相邻浅海与湖泊时+1 [ICON_Culture] 文化值。每相邻2个摩艾石像+1 [ICON_Culture] 文化值，解锁“中世纪集市”后变为每相邻1个摩艾石像。获得等同于 [ICON_Culture] 文化值产出的 [ICON_Tourism] 旅游业绩。只可建在平原、平原丘陵、草原、草原丘陵或火山土单元格之上。"),
	-- 总督改良
	("zh_Hans_CN",	"LOC_IMPROVEMENT_CITY_PARK_DESCRIPTION",										"+2 [ICON_FOOD] 食物、+1 [ICON_PRODUCTION] 生产力、+1 [ICON_Culture] 文化值和+3 [ICON_GOLD] 金币。为相邻单元格+2魅力。市立公园从所在城市的专业化区域和其中的建筑获得对应产出。无法建在另一个市立公园旁。"); 

-- Ethiopia DLC support
insert or replace into EnglishText
	(Tag,														Text)
select
	"LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",					"+1 [ICON_CULTURE] Culture, +2 [ICON_GOLD] Gold. +1 [ICON_CULTURE] Culture from each adjacent Holy Site or Theater Square. +2 [ICON_GOLD] Gold from each adjacent Commercial Hub. +1 [ICON_FOOD] Food from each adjacent City Center. Receives +1 [ICON_CULTURE] Culture from each Government Plaza or Government Plaza building in your civilization, +2 [ICON_GOLD] Gold from each Diplomatic Quater or Diplomatic Quater building in your civilization. +1 [ICON_CULTURE] Culture after progressing 'Civil Service' Civic. +2 Appeal to adjacent tiles. Cannot be built on Snow, Tundra, Snow Hills, or Tundra Hills or adjacent to another Pairidaeza."
where exists (select Tag from LocalizedText where Tag = 'LOC_CIVILIZATION_ETHIOPIA_NAME');
insert or replace into LocalizedText
	(Language,		Tag,												Text)
select
	"zh_Hans_CN",	"LOC_IMPROVEMENT_PAIRIDAEZA_DESCRIPTION",			"+1 [ICON_CULTURE] 文化值、+2 [ICON_GOLD] 金币。每相邻1个圣地或剧院广场+1 [ICON_CULTURE] 文化值。每相邻1个商业中心+2 [ICON_GOLD] 金币。每相邻1个市中心+1 [ICON_FOOD] 食物。您每拥有1个市政广场和市政广场建筑+1 [ICON_CULTURE] 文化值，每拥有一个外交区和外交区建筑+2 [ICON_GOLD] 金币。解锁“行政部门”市政后+1 [ICON_Culture] 文化值。为相邻单元格+2魅力。无法建在雪地、冻土、雪地丘陵或冻土丘陵上，也无法建在另一座波斯庭院旁。"
where exists (select Tag from LocalizedText where Tag = 'LOC_CIVILIZATION_ETHIOPIA_NAME');

-- Suk's Ocean Mode & WetLands support
insert or replace into EnglishText
	(Tag,														Text)
select
	"LOC_MARSH_AND_SWAMP",										"Marsh and Swamp"
where exists (select Tag from LocalizedText where Tag = 'LOC_RESOURCE_JNR_PEAT_NAME');

insert or replace into EnglishText
	(Tag,														Text)
select
	"LOC_AND_KELP",												" and Kelp Forest"
where exists (select Tag from LocalizedText where Tag = 'LOC_FEATURE_SUK_KELP_NAME');

insert or replace into LocalizedText
	(Language,		Tag,										Text)
select
	"zh_Hans_CN",	"LOC_MARSH_AND_SWAMP",						"草本沼泽和木本沼泽"
where exists (select Tag from LocalizedText where Tag = 'LOC_RESOURCE_JNR_PEAT_NAME');

insert or replace into LocalizedText
	(Language,		Tag,												Text)
select
	"zh_Hans_CN",	"LOC_AND_KELP",								"和海藻森林"
where exists (select Tag from LocalizedText where Tag = 'LOC_FEATURE_SUK_KELP_NAME');

insert or replace into EnglishText
	(Tag,														Text)
select
	"LOC_MARSH_OR_SWAMP",										"Marsh or Swamp"
where exists (select Tag from LocalizedText where Tag = 'LOC_RESOURCE_JNR_PEAT_NAME');

insert or replace into LocalizedText
	(Language,		Tag,										Text)
select
	"zh_Hans_CN",	"LOC_MARSH_OR_SWAMP",						"草本沼泽或木本沼泽"
where exists (select Tag from LocalizedText where Tag = 'LOC_RESOURCE_JNR_PEAT_NAME');