--------------------------------------------------------------------------------
-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                         Text)
values
    -- City Center Buildings
    ("LOC_BUILDING_MONUMENT_EXPANSION1_DESCRIPTION",              "Provides +1 Loyalty per turn in this city. After Calendar is researched, provides an additional +1 [ICON_CULTURE] Culture."),
    ("LOC_BUILDING_WALLS_EARLY_NAME",                             "Simple Ancient Wall"),
    ("LOC_BUILDING_WALLS_EARLY_DESCRIPTION",                      "A building unique to your original capital. A Simple Wall that provides 25 outer defense."),
    ("LOC_BUILDING_GRANARY_DESCRIPTION",                          "Camps, Pastures, Lumber Mills and Fishing Boats over bonus resources in this City provide +1 [ICON_Food] Food, doubled after Mathematics is researched."),
    ("LOC_BUILDING_NILOMETER_HD_NAME",                            "Nilometer"),
    ("LOC_BUILDING_NILOMETER_HD_DESCRIPTION",                     "+1 [ICON_Science] Science if the City Center is adjacent to Flood Plains, Oasis or {LOC_MARSH_OR_SWAMP}. After Geomatics is researched, provides an additional +1 [ICON_Science] Science."),
    ("LOC_BUILDING_TSIKHE_DESCRIPTION_XP2",                       "A building unique to Georgia. Lower [ICON_Production] Production cost and higher outer defenses than Medieval Walls it replaces. Provides +5 [ICON_TOURISM] Tourism after advancing to the Conservation Civic. Provides +4 [ICON_Faith] Faith. When in a Golden Age, +300% [ICON_TOURISM] Tourism and +300% [ICON_FAITH] Faith."),
    ("LOC_BUILDING_SEWER_DESCRIPTION",                            "+20% Growth rate in this city."),
    ("LOC_BUILDING_WATER_MILL_NAME",                              "Mill"),
    ("LOC_BUILDING_WATER_MILL_DESCRIPTION",                       "Farms, Plantations, Mines and Quarries over bonus resources in this City provide +1 [ICON_PRODUCTION] Production, doubled after Engineering is researched."),
    ("LOC_BUILDING_FLOOD_BARRIER_NAME",                           "Seawall"),
    ("LOC_BUILDING_PALGUM_DESCRIPTION",                           "A building unique to Babylon. Replaces Mill. Freshwater tiles receive +1 [ICON_FOOD] Food; then receive [ICON_PRODUCTION] Production after Engineering is researched. [NEWLINE][NEWLINE]City must be adjacent to a River. "),
    ("LOC_BUILDING_HD_POLICE_STATION_NAME",                       "Police Station"),
    ("LOC_BUILDING_HD_POLICE_STATION_DESCRIPTION",                "Receive corresponding yield of two copies from each type of districts in this city."),
    -- Campus
    ("LOC_BUILDING_LIBRARY_DESCRIPTION",                          "After Paper Making is researched, [ICON_Citizen] Citizens in this city provide +0.3 [ICON_SCIENCE] Science."),
    ("LOC_BUILDING_UNIVERSITY_DESCRIPTION",                       "[ICON_CITIZEN] Citizens in this city provide +0.5 [ICON_SCIENCE] Science."),
    ("LOC_BUILDING_MADRASA_NAME",                                 "Al-Azhar University"),
    ("LOC_BUILDING_MADRASA_DESCRIPTION",                          "A building unique to Arabia. This building can only be built once per civilization. [NEWLINE][NEWLINE]Campus and Theater Square districts within 6 tiles provide [ICON_Faith] Faith equal to the adjacency bonus. [NEWLINE]For each city follows your Religion, Campus district in this city receives +1 adjacency bonus. If at least 20 cities follow your Religion, your cities can purchase buildings in Campus districts with [ICON_FAITH] Faith. [NEWLINE]For each cultural policy slot in your government, Theater Square district in this city receives +2 adjacency bonus. If your governmrnt has at least 6 cultural policy slots, your cities can purchase buildings in Theater Square districts with [ICON_FAITH] Faith."),
    ("LOC_BUILDING_NAVIGATION_SCHOOL_DESCRIPTION",                "A building unique to Portugal. +25% [ICON_PRODUCTION] Production towards naval units in this city. +1 [ICON_SCIENCE] Science for every 2 Shallow Sea and Lake tiles in this city. +2 [ICON_GreatAdmiral] Great Admiral points. [ICON_CITIZEN] Citizens in this city provide +0.5 [ICON_SCIENCE] Science."),
    ("LOC_BUILDING_RESEARCH_LAB_DESCRIPTION",                     "+5% [ICON_SCIENCE] Science in this city. +10% [ICON_SCIENCE] Science if this city is fully powered. "),
    ("LOC_BUILDING_SEOWON_NAME",                                  "Bibliothecary"),
    ("LOC_BUILDING_HD_DATA_CENTER_NAME",                          "Data Center"),
    ("LOC_BUILDING_HD_DATA_CENTER_DESCRIPTION",                   "+1 Wildcard Policy Slot. After finishing construction, Gain +1600 [ICON_SCIENCE] Science and +1600 [ICON_CULTURE] Culture from each level 3 Alliance. [NEWLINE]Can only be built once in a civilization."),
    -- Theater
    ("LOC_BUILDING_MARAE_DESCRIPTION",                            "A building unique to the Māori. +2 [ICON_CULTURE] Culture and +2 [ICON_FAITH] Faith to all of this city's tiles with a passable feature or natural wonder. +1 [ICON_CULTURE] Culture for every 3 Shallow Sea and Lake tiles in this city. After Flight is researched, receive +1 [ICON_TOURISM] Tourism to all of this city's tiles with a feature or natural wonder. Has no Great Work slots."),
    ("LOC_BUILDING_MUSEUM_ARTIFACT_DESCRIPTION",                  "Holds [ICON_GreatWork_Artifact] Artifacts. May not be built in a Theater Square district that already has an Art Museum. +5% [ICON_CULTURE] Culture in this city."),
    ("LOC_BUILDING_MUSEUM_ART_DESCRIPTION",                       "Holds [ICON_GreatWork_Landscape] Great Works of Art. May not be built in a Theater Square district that already has an Archaeological Museum. +5% [ICON_CULTURE] Culture in this city."),
    ("LOC_BUILDING_FILM_STUDIO_EXPANSION2_DESCRIPTION",           "A building unique to America. +50% [ICON_Tourism] Tourism pressure from this city. +5% [ICON_CULTURE] Culture in this city. +5% [ICON_CULTURE] culture if this city is fully [ICON_POWER] powered."),
    ("LOC_BUILDING_BROADCAST_CENTER_DESCRIPTION",                 "+5% [ICON_CULTURE] Culture in this city. +5% [ICON_CULTURE] Culture if this city is fully [ICON_POWER] powered. "),
    ("LOC_BUILDING_JNR_DOJO_HD_DESCRIPTION",                      "A building unique to the Japan. +25% combat experience for all military units trained in this city. +2 [ICON_Production] Production, +50% [ICON_CULTURE] Culture and [ICON_Tourism] Tourism to Great Works in this city."),
    ("LOC_ABILITY_JNR_DOJO_TRAINED_UNIT_XP_DESCRIPTION",          "+25% Earned experience from Dojo"),
    -- Industrial Zone
    ("LOC_BUILDING_WORKSHOP_DESCRIPTION",                         "Improved tiles in the City have +1 [ICON_Production] Production"), -- , Quarries and Lumber Mills -- Mines in this city gain +1 [ICON_PRODUCTION] Production. +5% [ICON_Production] Production towards wonders, districts and buildings in this city.
    ("LOC_BUILDING_FACTORY_DL_DESCRIPTION",                       "Provide [ICON_Production] Production to cities within 6 tiles."),
    ("LOC_BUILDING_HD_ELECTRONICS_FACTORY_NAME",                  "Electronics Factory"),
    ("LOC_BUILDING_HD_ELECTRONICS_FACTORY_DESCRIPTION",           "+1 [ICON_PRODUCTION] Production for all District in this city, [ICON_CITIZEN] Citizens in this city provide +0.5 [ICON_PRODUCTION] Production. The bonuses are doubled after Integrated Circuit is researched."),
    ("LOC_BUILDING_HD_INTERNET_COMPANY_NAME",                     "Internet Company"),
    ("LOC_BUILDING_HD_INTERNET_COMPANY_DESCRIPTION",              "Campus and Industrial Zone district's adjacency bonus provides [ICON_TOURISM] Tourism as well. +5% [ICON_TOURISM] Tourism across your empire when city is powered."),
    ("LOC_BUILDING_HD_INTERNET_COMPANY_MONOPOLY_DESCRIPTION",     "Campus and Industrial Zone district's adjacency bonus provides [ICON_TOURISM] Tourism as well. +100% [ICON_SCIENCE] Science, [ICON_CULTURE] Culture and [ICON_TOURISM] Tourism to [ICON_Greatwork_Product] Products in this City. +5% [ICON_TOURISM] Tourism across your empire when city is powered."),
    ("LOC_BUILDING_COAL_POWER_PLANT_DL_DESCRIPTION",              "Automatically converts any amount of [ICON_RESOURCE_COAL] Coal into [ICON_Power] Power for cities within 6 tiles that need it each turn, at the rate of:[NEWLINE][ICON_Bullet]1 [ICON_RESOURCE_COAL] Coal [ICON_PowerRight] 4 [ICON_Power] Power[NEWLINE][ICON_Bullet] Heavy CO2 into the atmosphere.[NEWLINE]+10% [ICON_Production] Production towards wonders, districts and buildings in this city."),
    ("LOC_BUILDING_FOSSIL_FUEL_POWER_PLANT_DL_DESCRIPTION",       "Automatically converts any amount of [ICON_RESOURCE_OIL] Oil into [ICON_Power] Power for cities within 6 tiles that need it each turn, at the rate of:[NEWLINE][ICON_Bullet]1 [ICON_RESOURCE_OIL] Oil [ICON_PowerRight] 4 [ICON_Power] Power[NEWLINE][ICON_Bullet] Moderate CO2 into the atmosphere.[NEWLINE]+10% [ICON_Production] Production towards wonders, districts and buildings in this city."),
    ("LOC_BUILDING_POWER_PLANT_DL_DESCRIPTION",                   "Automatically converts any amount of [ICON_RESOURCE_URANIUM] Uranium into [ICON_Power] Power for cities within 6 tiles that need it each turn, at the rate of:[NEWLINE][ICON_Bullet]1 [ICON_RESOURCE_URANIUM] Uranium [ICON_PowerRight] 16 [ICON_Power] Power[NEWLINE][ICON_Bullet]Miniscule CO2 into the atmosphere[NEWLINE]Once built, as a Nuclear Power Plant ages, there is an increased chance for a Nuclear Accident to occur.[NEWLINE]+10% [ICON_Production] Production towards wonders, districts and buildings in this city."),
    -- Holy Site
    ("LOC_BUILDING_SHRINE_DESCRIPTION",                           "Allows the purchasing of Builders using [ICON_Faith] Faith. Allows the purchasing of Missionaries (can only be purchased with [ICON_Faith] Faith)."),
    ("LOC_BUILDING_TEMPLE_DESCRIPTION",                           "Allows the purchasing of Settlers using [ICON_Faith] Faith. Allows the purchasing of Apostles, Gurus, Inquisitors, and with the proper belief, Warrior Monks (these units can only be purchased with [ICON_Faith] Faith)."),
    ("LOC_BUILDING_PRASAT_EXPANSION2_DESCRIPTION",                "A building unique to Khmer. Replaces the Temple. Allows the purchasing of Settlers using [ICON_Faith] Faith. Allows the purchasing of Apostles, Gurus, Inquisitors, and with the proper belief, Warrior Monks (these units can only be purchased with [ICON_Faith] Faith). [ICON_CITIZEN] Citizens in this is provide +0.5 [ICON_Culture] Culture."),
    ("LOC_BUILDING_STAVE_CHURCH_DESCRIPTION",                     "A building unique to Norway. Replaces Temple. Allows the purchasing of Settlers using [ICON_Faith] Faith. Allows the purchasing of Apostles, Gurus, Inquisitors, and with the proper belief, Warrior Monks (these units can only be purchased with [ICON_Faith] Faith). Holy Site districts get an additional standard adjacency bonus from Woods. +1 [ICON_Food] Food to each Forest tile in this city."), --+1 [ICON_TradeRoute] Trade Route capacity. 
    ("LOC_BUILDING_MOSQUE_DL_DESCRIPTION",                        "Missionary and Apostles created here have +1 spread. All Religious units created in this city receive +3 [ICON_Religion] Religious Strength in Theological Combat."),
    ("LOC_BUILDING_PAGODA_DL_NAME",                               "Pagodas"),
    ("LOC_BUILDING_PAGODA_DL_DESCRIPTION",                        "Can hold 2 [ICON_GreatWork_Writing] Great Work of Writing. [NEWLINE] +20% accumulation rate for [ICON_GREATWRITER] Great Writer Points. +4 [ICON_FAITH] Faith, +25% [ICON_CULTURE] Culture and +50% [ICON_Tourism] Tourism for Great Works of Writing in this city."),
    ("LOC_BUILDING_WAT_DL_DESCRIPTION",                           "+10% [ICON_SCIENCE] Science in this city."),
    ("LOC_BUILDING_SYNAGOGUE_DL_DESCRIPTION",                     "+10% [ICON_FAITH] Faith in this city."),
    ("LOC_BUILDING_GURDWARA_DL_DESCRIPTION",                      "+10% [ICON_Food] Food in this city."),
    ("LOC_BUILDING_MEETING_HOUSE_DL_DESCRIPTION",                 "+10% [ICON_PRODUCTION] Production in this city."),
    ("LOC_BUILDING_STUPA_DL_DESCRIPTION",                         "+1 [ICON_AMENITIES] Amenity for every type of Luxury resource this city has improved."),
    ("LOC_BUILDING_CATHEDRAL_DL_DESCRIPTION",                     "Can hold 2 [ICON_GreatWork_Landscape] Great Work of Art and 1 [ICON_GreatWork_Music] Great Work of Music.[NEWLINE] +10% accumulation rate for [ICON_GREATARTIST] Great Artist and [ICON_GREATMUSICIAN] Great Musician Points. +25% [ICON_CULTURE] Culture and +100% [ICON_Tourism] Tourism for Great Works of Art and Music in this city."),
    ("LOC_BUILDING_DAR_E_MEHR_DL_DESCRIPTION",                    "+2 additional [ICON_FAITH] Faith for each era since constructed or last repaired. +10% [ICON_Culture] Culture in this city."),
    ("LOC_BUILDING_HD_ALCHEMY_ROOM_NAME",                         "Alchemy Room"),
    ("LOC_BUILDING_HD_ALCHEMY_ROOM_DESCRIPTION",                  "[ICON_CITIZEN] Citizens in this city provide +0.3 [ICON_SCIENCE] Science. Allows the purchasing of Settlers using [ICON_FAITH] Faith. Allows the purchasing of Apostles, Gurus, Inquisitors, and with the proper belief, Warrior Monks (these units can only be purchased with [ICON_FAITH] Faith)."),
    -- Encampment
    ("LOC_BUILDING_BARRACKS_EXPANSION2_DESCRIPTION",              "+25% combat experience for all melee, anti-cavalry, ranged, and ranged cavalry land units trained in this city.[NEWLINE][NEWLINE]May not be built in an Encampment district that already has a Stable.[NEWLINE][NEWLINE]+2 [ICON_PRODUCTION] Production to each improved [ICON_RESOURCE_IRON] Iron in this city. +2 [ICON_Strength] Combat strength for all melee, ranged, anti-cavalry units trained in this city."),
    ("LOC_BUILDING_BASILIKOI_PAIDES_EXPANSION2_DESCRIPTION",      "A building unique to Macedon. Replaces the Barracks and is unlocked earlier. +25% combat experience for all melee, ranged land units, and Hetairoi trained in this city. Gain [ICON_SCIENCE] Science equal to 25% of the unit's cost when a non civilian unit is created in this city.[NEWLINE][NEWLINE]+2 [ICON_PRODUCTION] Production to each improved [ICON_RESOURCE_IRON] Iron in this city. +3 [ICON_Strength] Combat strength for all land combat, ranged and Hetairoi trained in this city."), -- [NEWLINE][NEWLINE]May not be built in an Encampment district that already has a Stable.
    ("LOC_BUILDING_STABLE_EXPANSION2_DESCRIPTION",                "+25% combat experience for all cavalry and siege class units trained in this city.[NEWLINE][NEWLINE]May not be built in an Encampment district that already has a Barracks.[NEWLINE][NEWLINE]+2 [ICON_PRODUCTION] Production to each improved [ICON_RESOURCE_HORSES] Horses in this city. +2 [ICON_Strength] Combat strength for all cavalry and siege units trained in this city."),
    ("LOC_BUILDING_ORDU_EXPANSION2_DESCRIPTION",                  "A building unique to Mongolia. Replaces Stable. Grants an ability that gives +1 [ICON_MOVEMENT] Movement to Heavy and Light Cavalry trained in this city. +25% combat experience for all cavalry and siege class units trained in this city.[NEWLINE][NEWLINE]May not be built in an Encampment district that already has a Barracks. [NEWLINE][NEWLINE]+2 [ICON_PRODUCTION] Production to each improved [ICON_RESOURCE_HORSES] Horses. +3 [ICON_Strength] Combat strength for all cavalry and siege units, and Keshig trained in this city."),
    ("LOC_BUILDING_ARMORY_EXPANSION2_DESCRIPTION",                "+25% combat experience for all land units trained in this city.[NEWLINE]Strategic Resource Stockpiles increased +30 (on Standard Speed). [NEWLINE][NEWLINE]+1 [ICON_Production] Production to all [ICON_Resource_Niter] Niter and [ICON_Resource_Oil] Oil in this city. Military units trained in this city start with a free promotion (does not overlap)."),
    ("LOC_BUILDING_MILITARY_ACADEMY_EXPANSION2_DESCRIPTION",      "+25% combat experience for all land units trained in this city.[NEWLINE]Allows Corps and Armies to be trained directly. Corps and Army training costs reduced 25%. [NEWLINE][NEWLINE]+1 [ICON_Production] Production to all [ICON_Resource_Aluminum] Aluminum and [ICON_Resource_Uranium] Uranium in this city. +10% accumulation rate for [ICON_GREATGENERAL] Great General Points across the nation. +3 [ICON_STRENGTH] Combat Strength for all land units trained in this city."),
    -- Commercial Hub
    ("LOC_BUILDING_FAIR_NAME",                                    "Fair"),
    ("LOC_BUILDING_MARKET_EXPANSION1_DESCRIPTION",                "+1 [ICON_TradeRoute] Trade Route capacity."),
    ("LOC_BUILDING_SUKIENNICE_NAME",                              "Krakow Sukiennice"),
    ("LOC_BUILDING_SUKIENNICE_EXPANSION1_DESCRIPTION",            "A building unique to Poland. This building can only be built once per civilization. [NEWLINE][NEWLINE]Culture Bomb adjacent tiles when completing a Commercial Hub district. [NEWLINE]For each +8 adjacency bonus of Commercial Hub district in this city, provides +1 [ICON_TradeRoute] Trade Route capacity. Provides [ICON_PRODUCTION] Production equal to 25% adjacency of Commercial Hub district in this city to Domestic [ICON_TRADEROUTE] Trade Routes to this city. Provides [ICON_GOLD] Gold equal to 75% adjacency of Commercial Hub district in this city to International [ICON_TRADEROUTE] Trade Routes starting from this city. [NEWLINE][NEWLINE] When you build International [ICON_TradeRoute] Trade Routes, receive a random luxury resource and its yields in the destination city. This effect can only be obtained once from each destination city."),
    ("LOC_BUILDING_GRAND_BAZAAR_DESCRIPTION",                     "A building unique to the Ottomans. Accumulate 1 extra Strategic resource for every different type of Strategic resource this city has improved. +1 [ICON_AMENITIES] Amenity for every Luxury resource this city has improved. +5% [ICON_gold] Gold yield in this city."),
    ("LOC_BUILDING_BANK_DESCRIPTION",                             "+5% [ICON_gold] Gold in this city."),
    ("LOC_BUILDING_STOCK_EXCHANGE_DESCRIPTION",                   "+10% [ICON_gold] Gold and +10% accumulation rate for [ICON_GREATMERCHANT] Great Merchant Points from all cities within 6 tiles that do not already have a bonus from another Stock Exchange. These bonuses are doubled if the city is fully powered."),
    -- Harbor
    ("LOC_BUILDING_LIGHTHOUSE_EXPANSION2_DESCRIPTION",            "+25% combat experience for all naval units trained in this city. +1 [ICON_Food] Food to all Shallow Sea and Lake tiles in this city. +1 [ICON_TradeRoute] Trade Route capacity."), -- each [ICON_Resource_Fish] Fish, [ICON_Resource_Crabs] Crabs, [ICON_Resource_Whales] Whales, [ICON_Resource_Pearls] Pearls
    ("LOC_BUILDING_SHIPYARD_EXPANSION2_DESCRIPTION",              "+25% combat experience for all naval units trained in this city. Bonus [ICON_Production] Production equal to adjacency bonus of the Harbor district. +1 [ICON_Production] Production on all Shallow Sea and Lake tiles for this city. +25% [ICON_PRODUCTION] production towards all naval units."),
    ("LOC_BUILDING_SEAPORT_DESCRIPTION",                          "+25% combat experience for all naval units trained in this city. Allows Fleets and Armadas to be trained directly. Fleet and Armada training costs reduced by 25%. +1 [ICON_FOOD] Gold on all Shallow Sea and Lake tiles for this city. Bonus [ICON_FOOD] Food equal to adjacency bonus of the Harbor district.[NEWLINE]+10% accumulation rate for [ICON_GREATADMIRAL] Great Admiral Points. +3 [ICON_STRENGTH] Combat Strength for all navy units trained in this city."),
    -- Government
    ("LOC_BUILDING_GOV_WIDE_NAME",                                "Ekklesiasterion"),
    ("LOC_BUILDING_GOV_WIDE_DESCRIPTION",                         "+50% [ICON_PRODUCTION] Production toward Settlers in this City. New cities receive a free Builder. +50% [ICON_Production] Production towards buildings in City Center which are already built in this city."),
    ("LOC_BUILDING_GOV_TALL_DESCRIPTION",                         "+2 [ICON_Housing] Housing in all cities.[NEWLINE]+20% construction speed towards wonders, districts and buildings in this city, and can build 1 more district than the [ICON_CITIZEN] Population limit allows.[NEWLINE]Awards +1 [ICON_Governor] Governor Title."),
    ("LOC_BUILDING_GOV_CONQUEST_DESCRIPTION",                     "Capturing an enemy City grants 15% bonus [ICON_Production] Production in all Cities for 5 turns.[NEWLINE]+20% [ICON_Production] Production towards training military units in this city. [NEWLINE]+100% Yields gained from pilaging and coastal raids.[NEWLINE]Awards +1 [ICON_Governor] Governor Title."),
    ("LOC_BUILDING_GOV_SPIES_NAME",                               "Secretariat"),
    ("LOC_BUILDING_GOV_SPIES_HD_DESCRIPTION",                     "Your cities +10% [ICON_Food] Food and +10% [ICON_Production] Production. Double these bonus for Cities with a [ICON_Governor] Governor established.[NEWLINE]Awards +1 [ICON_Governor] Governor Title."),
    ("LOC_BUILDING_GOV_FAITH_NAME",                               "Episcopal Church"),
    ("LOC_BUILDING_GOV_FAITH_HD_DESCRIPTION",                     "+10% [ICON_Faith] Faith to cities with Holy Site district. Receive [ICON_Science] Science and [ICON_Culture] Culture equal to 10% of your [ICON_Faith] Faith output in all cities.[NEWLINE]Religious units are 20% cheaper to purchase in all cities. +5 [ICON_Religion] Religious Strength in Theological Combat.[NEWLINE]Awards +1 [ICON_Governor] Governor Title."),
    ("LOC_BUILDING_GOV_CITYSTATES_NAME",                          "Trade Capital"),
    ("LOC_BUILDING_GOV_CITYSTATES_HD_DESCRIPTION",                "+1 [ICON_TRADEROUTE] Trade Route capacity. Grants a free Traders. -10% cost when purchasing a Trader. Starting a [ICON_TRADEROUTE] Trade Route immediately creates a [ICON_TRADINGPOST] Trading Post in the destination city. Your [ICON_TRADEROUTE] Trade Routes provide additional +1 [ICON_GOLD] Gold for passing through each of your [ICON_TRADINGPOST] Trading Post in foreign city. City with a [ICON_GOVERNOR] Governor +15% [ICON_GOLD] Gold. [NEWLINE]Awards +1 [ICON_GOVERNOR] Governor Title."),
    ("LOC_BUILDING_GOV_CITYSTATES_MONOPOLY_DESCRIPTION",          "+1 [ICON_TRADEROUTE] Trade Route capacity. Grants a free Traders. -10% cost when purchasing a Trader. Starting a [ICON_TRADEROUTE] Trade Route immediately creates a [ICON_TRADINGPOST] Trading Post in the destination city. Your [ICON_TRADEROUTE] Trade Routes provide additional +1 [ICON_GOLD] Gold for passing through each of your [ICON_TRADINGPOST] Trading Post in foreign city. City with a [ICON_GOVERNOR] Governor +15% [ICON_GOLD] Gold. Grants a Tycoon and a Investor after researching their required Technologies. [NEWLINE]Awards +1 [ICON_GOVERNOR] Governor Title."),
    ("LOC_BUILDING_GOV_SCIENCE_DESCRIPTION",                      "Campus Buildings provide [ICON_Production] Production equal to their basic [ICON_Science] Science yield.[NEWLINE]Industrial Zone Buildings provide [ICON_Science] Science equal to their basic [ICON_Production] Production yield.[NEWLINE]Awards +1 [ICON_Governor] Governor Title."),
    --("LOC_BUILDING_GOV_SCIENCE_DESCRIPTION",                      "Builders gain the ability to use all of their charges to provide bonus [ICON_Production] Production to a District Project (2% per charge). Once per city per turn.[NEWLINE]Awards +1 [Icon_Governor] Governor Title."),
    ("LOC_BUILDING_GOV_MILITARY_DESCRIPTION",                     "All military units gain +1 [ICON_Movement] Movement and +3 [ICON_Strength] Combat Strength.[NEWLINE]Unit maintenance cost reduced by 2 [ICON_Gold] Gold per turn, per unit.[NEWLINE]25% [ICON_Gold] Gold and Resource discount on all unit upgrades.[NEWLINE]Awards +1 [ICON_Governor] Governor Title."),
    ("LOC_BUILDING_GOV_CULTURE_DESCRIPTION",                      "Provides 6 slots for any Great Work. +100% and [ICON_Tourism] Tourism to all Great Works, extra +100% in this city. +20% [ICON_TOURISM] Tourism across your empire. +25% [ICON_CULTURE] Culture to cities with an Art Museum or an Artifact Museum. [NEWLINE]Awards +1 [Icon_Governor] Governor Title."),
    ("LOC_ABILITY_GOV_FAITH_COMBAT_STRENGTH_DESCRIPTION",         "+5 [ICON_Religion] Religious Combat Strength from Episcopal Church."),
    ("LOC_ABILITY_GOV_MILITARY_MOVEMENT_DESCRIPTION",             "+1 [ICON_Movement] Movement from War Department."),
    ("LOC_ABILITY_GOV_MILITARY_COMBAT_STRENGTH_DESCRIPTION",      "+3 [ICON_Strength] Combat Strength from War Department."),
    ("LOC_BUILDING_QUEENS_BIBLIOTHEQUE_DESCRIPTION",              "A building unique to Sweden. Provides 6 slots for any Great Work. +100% [ICON_Tourism] Tourism to Great Works in this city, extra +100% [ICON_Tourism] Tourism to [ICON_GreatWork_Writing] Great Work of Writing. Provides extra 3% [ICON_CULTURE] Culture for Inspiration. Grant boost [ICON_CIVICBOOSTED] to 'Opera and Ballet' (complete 'Opera and Ballet' if already boosted). [NEWLINE]Awards +1 [ICON_GOVERNOR] Governor Title."),
    ("LOC_BUILDING_EL_ESCORIAL_PALACE_NAME",                      "El Escorial Palace"),
    ("LOC_BUILDING_EL_ESCORIAL_PALACE_DESCRIPTION",               "A building unique to Philip II. Each time you ""Explore City of Gold"", provide the basic yields or adjacency yields of this natural wonder to your Palace and this building, and provide +2 [ICON_GreatProphet] Great Prophet points, +2 [ICON_GreatWriter] Great Writer points and +2 [ICON_GreatArtist] Great Artist points per turn to this building. +50% [ICON_CULTURE] Culture and [ICON_Faith] Faith to [ICON_GreatWork_Relic] Great Work of Relic, [ICON_GreatWork_Writing] Great Work of Writing and [ICON_GreatWork_Landscape] Great Work of Art."),
    -- Diplomatic Quarter
    ("LOC_BUILDING_CONSULATE_DESCRIPTION",                        "+2 Influence Points per turn. Gain +1 [ICON_ENVOY] Envoy. Leveraging City States costs 20% less [ICON_Gold] Gold. +50% construction speed towards Spy in this city. Your Spy units can choose from any possible promotion."),
    ("LOC_BUILDING_CHANCERY_DESCRIPTION",                         "+3 Influence Points per turn. Gain +1 [ICON_ENVOY] Envoy. +1 [ICON_VISLIMITED] Visibility level on all other Civs. +50% [ICON_PRODUCTION] toward Spies in all Cities. Receive one Spy and +1 Spy capacity. Spys start with a free promotion. All Spy Operations have a higher chance of success. Spy mission time reduces by 15%. When this civilization captures or kills an enemy Spy, receive 50 [ICON_SCIENCE] Science for every level of the enemy Spy."),
    ("LOC_BUILDING_HD_REGIONAL_COUNCIL_CENTER_NAME",              "Regional Council Centre"),
    ("LOC_BUILDING_HD_REGIONAL_COUNCIL_CENTER_DESCRIPTION",       "+1 Cultural Policy Slot. +1 Dipolomatic Victory Point. +25% Influence points. +1 Diplomatic visibility towards all civilizations. Accumulates 5 extra Alliance Points per turn. Double bonus of [ICON_TRADEROUTE] Trade Routes from alliances. Enemy Spy level reduced by 1 in your lands. [NEWLINE]Awards +1 [ICON_Governor] Governor Title. [NEWLINE]Can only be built once in a civilization."),
    ("LOC_BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS_NAME",        "World Parliament Headquarters"),
    ("LOC_BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS_DESCRIPTION", "Building unique to America. +1 Cultural Policy Slot. +3 Dipolomatic Victory Point. +50% Influence points. +1 Diplomatic visibility towards all civilizations. Accumulates 5 extra Alliance Points per turn. Double bonus of [ICON_TRADEROUTE] Trade Routes from alliances. If you are the suzerain of at least 1 City States of the same type, all of your cities receive +10% of the respective yield. Your Spy level is increased by 1 for all offensive operations，enemy Spy level reduced by 1 in your lands. [NEWLINE]Awards +1 [ICON_Governor] Governor Title. [NEWLINE]Can only be built once in a civilization."),
    ("LOC_TRAIT_CIVILIZATION_BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS_NAME",               "American unique building: World Parliament Headquarters"),
    ("LOC_BUILDING_HD_HUMAN_RIGHTS_COUNCIL_NAME",                 "Human Rights Council"),
    ("LOC_BUILDING_HD_HUMAN_RIGHTS_COUNCIL_DESCRIPTION",          "+1 Economic Policy Slot. Each type of Districts provides +4 corresponding [ICON_GREATPERSON] Great Person points to each Neighborhood district in the city. [NEWLINE]Awards +1 [ICON_Governor] Governor Title. [NEWLINE]Can only be built once in a civilization."),
    ("LOC_BUILDING_HD_MINISTRY_OF_NATIONAL_DEFENSES_NAME",        "Ministry of National Defenses"),
    ("LOC_BUILDING_HD_MINISTRY_OF_NATIONAL_DEFENSE_DESCRIPTION",  "+1 Military Policy Slot. +5 [ICON_STRENGTH] Combat Strength to all military units. +50% accumulation rate for [ICON_GREATGENERAL] Great General Points. +3 [ICON_SCIENCE] Science and +3 [ICON_Production] Production from each type of trained military units. [NEWLINE]Awards +1 [ICON_Governor] Governor Title. [NEWLINE]Can only be built once in a civilization."),
    ("LOC_ABILITY_MND_UNIT_STRENGTH_DESCRIPTION",                 "Ministry of National Defenses: +5 [ICON_STRENGTH] Combat Strength."),
    -- Entertainment Complex
    ("LOC_BUILDING_ARENA_EXPANSION1_DESCRIPTION",                 "Provides 1 [ICON_TOURISM] Tourism after advancing to the Conservation Civic. "),
    ("LOC_BUILDING_TLACHTLI_XP1_DESCRIPTION",                     "A building unique to the Aztecs. +1 [ICON_Amenities] Amenity, +2 [ICON_Culture] Culture, +2 [ICON_Faith] Faith. +1 [ICON_GreatGeneral] Great General Point per turn. +1 [ICON_TOURISM] Tourism after advancing to the Conservation Civic. "),
    ("LOC_BUILDING_STADIUM_DL_DESCRIPTION",                       "+2 [ICON_Tourism] Tourism if the city [ICON_CITIZEN] population is 10 or higher. +5 [ICON_Tourism] Tourism if the city [ICON_CITIZEN] population is 20 or higher."),
    ("LOC_BUILDING_ZOO_EXPANSION1_DESCRIPTION",                   "+1 [ICON_Culture] Culture and +3 [ICON_Gold] Gold from every type of Camp or Pasture Resource you controlled."),
    ("LOC_BUILDING_THERMAL_BATH_DESCRIPTION",                     "Building unique to Hungary. All Geothermal Fissures in this city gain +2 [ICON_FAITH] Faith and +2 [ICON_CULTURE] Culture; gain +2 [ICON_SCIENCE] Science after Chemisty is researched. Districts in this city gain an additional major adjacency bonus from Geothermal Fissures."),
    ("LOC_THERMAL_BATH_FAITH",                                    "+{1_num} [ICON_FAITH] Faith from the adjacent geothermal fissure {1_Num : plural 1?tile; other?tiles;}."),
    ("LOC_THERMAL_BATH_GOLD",                                     "+{1_num} [ICON_GOLD] Gold from the adjacent geothermal fissure {1_Num : plural 1?tile; other?tiles;}."),
    ("LOC_THERMAL_BATH_SCIENCE",                                  "+{1_num} [ICON_SCIENCE] Science from the adjacent geothermal fissure {1_Num : plural 1?tile; other?tiles;}."),
    ("LOC_THERMAL_BATH_CULTURE",                                  "+{1_num} [ICON_CULTURE] Culture from the adjacent geothermal fissure {1_Num : plural 1?tile; other?tiles;}."),
    ("LOC_THERMAL_BATH_PRODUCTION",                               "+{1_num} [ICON_PRODUCTION] Production from the adjacent geothermal fissure {1_Num : plural 1?tile; other?tiles;}."),
    -- Water Entertainment Complex
    ("LOC_BUILDING_FERRIS_WHEEL_DESCRIPTION_HD",                  "+3 [ICON_Tourism] Tourism."),
    ("LOC_BUILDING_AQUATICS_CENTER_DL_DESCRIPTION",               "+2 [ICON_Tourism] Tourism for each Wonder built in this city on or adjacent to a Shallow Sea tile."),
    ("LOC_BUILDING_AQUARIUM_DL_DESCRIPTION",                      "+1 [ICON_SCIENCE] Science and [ICON_Culture] Culture from every type of Fishing Boat Resource you controlled."),
    -- Aerodrome
    ("LOC_BUILDING_HANGAR_DESCRIPTION",                           "+25% combat experience for air units trained in this city. +2 air unit slot in Aerodrome district. +50% [Icon_Production] Production towards Air Units."),
    ("LOC_BUILDING_AIRPORT_DESCRIPTION",                          "+100% [ICON_TOURISM] Tourism from Wonders, and +50% [ICON_TOURISM] Tourism from Improvements, Great Works in this city if is fully [ICON_POWER] Powered. This bonus is extended to all cities within 5 tiles that do not already have a bonus from another Airport. [NEWLINE] +50% combat experience for air units trained in this city. Allows the ability to airlift land units between Aerodrome districts with Airports after the Rapid Deployment civic is unlocked."),
    ("LOC_BUILDING_AIRPORT_DESCRIPTION_PRODUCT",                  "If the City is fully [ICON_POWER] Powered, +100% [ICON_TOURISM] Tourism to Wonders, +50% [ICON_TOURISM] Tourism to Improvements, Great Works and [ICON_GREATWORK_PRODUCT] Products. This bonus is extended to all Cities within 5 tiles that do not already have a bonus from another Airport. [NEWLINE]+50% combat experience for air units trained in this city. Allows the ability to airlift land units between Aerodrome districts with Airports after the Rapid Deployment civic is unlocked."),
    -- Neighborhood.
    ("LOC_BUILDING_FOOD_MARKET_NAME",                             "Farmer's Market"),
    ("LOC_BUILDING_FOOD_MARKET_DESCRIPTION",                      "+10% accumulation rate for {LOC_BUILDING_FOOD_MARKET_BUFF_OBJECT} Points, this bonus is doubled after Modern Agriculture is researched. Provide +1 [ICON_GOLD] Gold to your cities from each type of Farm, Plantation, Pasture or Fishing Boat Resource you controlled. [NEWLINE][NEWLINE]Can only be built once in a civilization."),
    ("LOC_BUILDING_FOOD_MARKET_DESCRIPTION_CORP",                 "+10% accumulation rate for {LOC_BUILDING_FOOD_MARKET_BUFF_OBJECT} Points, this bonus is doubled after Modern Agriculture is researched. Provide +1 [ICON_GOLD] Gold to your cities from each type of Farm, Plantation, Pasture or Fishing Boat Resource you controlled. [NEWLINE][NEWLINE]When the city is [ICON_POWER] powered, +50% [ICON_FOOD] Food and [ICON_PRODUCTION] Production and +100% [ICON_TOURISM] Tourism from [ICON_GreatWork_Product] Products. [NEWLINE][NEWLINE]Can only be built once in a civilization."),
    ("LOC_BUILDING_FOOD_MARKET_BUFF_OBJECT",                      "[ICON_GREATMERCHANT] Great Merchant"),
    ("LOC_BUILDING_SHOPPING_MALL_NAME",                           "Department Store"),
    ("LOC_BUILDING_SHOPPING_MALL_DESCRIPTION",                    "+10% accumulation rate for [ICON_GREATMERCHANT] Great Merchant Points, this bonus is doubled after Finance is researched. Provide +1 [ICON_GOLD] Gold to your cities from each type of Mine, Quarry, Camp or Lumber Mill Resource you controlled. [NEWLINE][NEWLINE]Can only be built once in a civilization."),
    ("LOC_BUILDING_SHOPPING_MALL_DESCRIPTION_CORP",               "+10% accumulation rate for [ICON_GREATMERCHANT] Great Merchant Points, this bonus is doubled after Finance is researched. Provide +1 [ICON_GOLD] Gold to your cities from each type of Mine, Quarry, Camp or Lumber Mill Resource you controlled. [NEWLINE][NEWLINE]When the city is [ICON_POWER] powered, +50% [ICON_Gold] Gold and [ICON_Faith] Faith and +100% [ICON_TOURISM] Tourism from [ICON_GreatWork_Product] Products. [NEWLINE][NEWLINE]Can only be built once in a civilization."),
    ("LOC_BUILDING_HD_VILLA_NAME",                                "Villa"),
    ("LOC_BUILDING_HD_VILLA_DESCRIPTION",                         "+1 [ICON_Food] Food and +3 [ICON_GOLD] Gold to Neighborhood and Residential Facilities Improvements in this city."),
    ("LOC_BUILDING_HD_MANSION_NAME",                              "Official Mansion"),
    ("LOC_BUILDING_HD_MANSION_DESCRIPTION",                       "Cities with a [ICON_GOVERNOR] Governor and Neighborhood distirct can receive 1.5 times of regional yield from Buildings and Wonders. [NEWLINE]Awards +1 [ICON_Governor] Governor Title. [NEWLINE][NEWLINE]Must be built in [ICON_CAPITAL] Capital. Can only be built once in a civilization."),
    ("LOC_BUILDING_HD_BUS_STOP_NAME",                             "Bus Stop"),
    ("LOC_BUILDING_HD_BUS_STOP_DESCRIPTION",                      "Provide corresponding yield to districts within 3 tiles. +3 [ICON_GOLD] Gold to improvements within 3 tiles. +100% Commercial Hub and Harbor district adjacency bonuses in this city."),
    -- Dam
    ("LOC_BUILDING_HYDROELECTRIC_DAM_DESCRIPTION",                "Provides the city +6 [ICON_Power] Power from renewable water sources. +1 [ICON_Production] Production to all tiles that are adjacent to river in this city. "),
    -- 保护区
    ("LOC_BUILDING_GROVE_NAME",                                   "Oracle Stele"),
    ("LOC_BUILDING_GROVE_DESCRIPTION",                            "+1 [ICON_CULTURE] Culture to adjacent Charming tiles, and additionally extra +1 [ICON_SCIENCE] Science to adjacent Breathtaking tiles."),
    ("LOC_BUILDING_SANCTUARY_NAME",                               "Environmental Conservation Department"),
    ("LOC_BUILDING_SANCTUARY_DESCRIPTION",                        "Upon completion, it will cause the population of one randomly Biological Resource on features in this city to expand nearby. [NEWLINE][NEWLINE]Rainforest, Marsh and Floodplains tiles in this city grant +1 Appeal to adjacent tiles. [NEWLINE][NEWLINE]+1 [ICON_FOOD] Food to all Feature tiles in this city; extra +1 [ICON_PRODUCTION] Production if with any resource; extra +3 [ICON_GOLD] Gold if with Charming appeal; extra +1 [ICON_CULTURE] Culture if with Breathtaking appeal. [NEWLINE]+2 [ICON_FOOD] Food, +2 [ICON_CULTURE] Culture and +6 [ICON_GOLD] Gold Natural Wonder tiles in this city."),
    ("LOC_BUILDING_SANCTUARY_TEXT",                               "{1_Name} population has expanded"),
    ("LOC_BUILDING_HD_CULTURE_HERITAGE_PRESERVE_NAME",            "Cultural Heriate Conservation Department"),
    ("LOC_BUILDING_HD_CULTURE_HERITAGE_PRESERVE_DESCRIPTION",     "+1 [ICON_CULTURE] Culture and +3 [ICON_GOLD] Gold to World Wonder or Unique Improvement tiles with Charming Appeal in this city, doubled if these tiles have Breathtaking Appeal. +100% Tourism from World Wonders and Unique Improvements in this city."),
    ("LOC_BUILDING_HD_LANDFORM_EPO_NAME",                         "Landscape Ecology Protection Agency"),
    ("LOC_BUILDING_HD_LANDFORM_EPO_DESCRIPTION",                  "+8 [ICON_SCIENCE] Science [ICON_CULTURE] Culture for every type of Feature within your empire (not including Natural Wonders). [NEWLINE][NEWLINE]Can only be built once in a civilization."),
    ("LOC_BUILDING_HD_RESOURCE_EPO_NAME",                         "Non-renewable Resources Administration Agency"),
    ("LOC_BUILDING_HD_RESOURCE_EPO_DESCRIPTION",                  "+4 [ICON_PRODUCTION] Production and [ICON_SCIENCE] Science for every type of Minearl Resource you controlled. [NEWLINE][NEWLINE]Can only be built once in a civilization."),
    ("LOC_BUILDING_HD_SPECIES_EPO_NAME",                          "Species Diversity Conservation Agency"),
    ("LOC_BUILDING_HD_SPECIES_EPO_DESCRIPTION",                   "+4 [ICON_FOOD] Food and [ICON_CULTURE] Culture for every type of Biological Resource you controlled. [NEWLINE][NEWLINE]Can only be built once in a civilization."),
    ("LOC_BUILDING_HD_SCENIC_EPO_NAME",                           "Natural Attractions Tourism Agency"),
    ("LOC_BUILDING_HD_SCENIC_EPO_DESCRIPTION",                    "Triples the yield of Natural Wonders across your empire. +5% all yields in cities with a Natural Wonder or a National Park, quadrupled if you have every Natural Wonder inside your empire. Immediately gain a Naturalist. Naturalists are 50% cheaper to purchase with Faith. [NEWLINE][NEWLINE]Can only be built once in a civilization.");

--------------------------------------------------------------------------------
-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                         Text)
values
    -- 市中心建筑
    ("zh_Hans_CN",  "LOC_BUILDING_MONUMENT_EXPANSION1_DESCRIPTION",              "使此城每回合的忠诚度+1。解锁“历法”科技后，纪念碑额外+1 [ICON_Culture] 文化值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_WALLS_EARLY_NAME",                             "简易远古城墙"),
    ("zh_Hans_CN",  "LOC_BUILDING_WALLS_EARLY_DESCRIPTION",                      "只提供25点外部防御的简易城墙，无法建造，只会被赠送在原始首都。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GRANARY_DESCRIPTION",                          "本城改良加成资源的牧场、营地、伐木场和渔船+1 [ICON_Food] 食物，解锁“数学”科技后该效果翻倍。"),
    ("zh_Hans_CN",  "LOC_BUILDING_NILOMETER_HD_NAME",                            "测量仪"),
    ("zh_Hans_CN",  "LOC_BUILDING_NILOMETER_HD_DESCRIPTION",                     "如果市中心靠近泛滥平原、绿洲或{LOC_MARSH_OR_SWAMP}，则额外+1 [ICON_Science] 科技值。解锁“测绘学”科技后，测量仪额外+1 [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_SEWER_DESCRIPTION",                            "本城+20%余粮。"),
    ("zh_Hans_CN",  "LOC_BUILDING_TSIKHE_DESCRIPTION_XP2",                       "格鲁吉亚特色建筑。[ICON_Production] 生产力花费低于中世纪城墙，并拥有更强的外部防御力。获得“保护地球”市政后提供+5点 [ICON_TOURISM] 旅游业绩。提供+4 [ICON_Faith] 信仰值。进入黄金时代后 [ICON_TOURISM] 旅游业绩与 [ICON_FAITH] 信仰值均+300%。"),
    ("zh_Hans_CN",  "LOC_BUILDING_WATER_MILL_NAME",                              "磨坊"),
    ("zh_Hans_CN",  "LOC_BUILDING_WATER_MILL_DESCRIPTION",                       "本城改良加成资源的农场、种植园、矿山和采石场+1 [ICON_Production] 生产力，解锁“工程”科技后该效果翻倍。"),
    ("zh_Hans_CN",  "LOC_BUILDING_FLOOD_BARRIER_NAME",                           "拦海堤"),
    ("zh_Hans_CN",  "LOC_BUILDING_PALGUM_DESCRIPTION",                           "巴比伦特色建筑。取代磨坊。本城淡水单元格+1 [ICON_FOOD] 食物。解锁“工程”科技后，本城淡水单元格+1 [ICON_Production] 生产力。[NEWLINE][NEWLINE]城市必须建在河流旁。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_POLICE_STATION_NAME",                       "警署"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_POLICE_STATION_DESCRIPTION",                "从本城的每个区域获得2份对应产出。"),
    -- 学院
    ("zh_Hans_CN",  "LOC_BUILDING_LIBRARY_DESCRIPTION",                          "解锁“造纸术”科技后，城市中每位 [ICON_Citizen] 公民 +0.3 [ICON_SCIENCE] 科技值产出。"),
    ("zh_Hans_CN",  "LOC_BUILDING_UNIVERSITY_DESCRIPTION",                       "每位 [ICON_CITIZEN] 市民+0.5 [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_MADRASA_NAME",                                 "艾孜哈尔伊斯兰大学"),
    ("zh_Hans_CN",  "LOC_BUILDING_MADRASA_DESCRIPTION",                          "阿拉伯特色建筑，文明中一次仅限建造一座该建筑。[NEWLINE][NEWLINE]6个单元格内的学院和剧院广场的相邻加成也提供 [ICON_FAITH] 信仰值。[NEWLINE][NEWLINE]每座信仰你创立的宗教的城市为本城的学院+1相邻加成；若至少有20座城市信仰你创立的宗教，则你的所有城市可以用 [ICON_FAITH] 信仰值购买学院建筑。[NEWLINE]你的政体中的每个文化政策槽位为本城的剧院广场+2相邻加成；若你的政体至少有6个文化政策槽位，则你的所有城市可以用 [ICON_FAITH] 信仰值购买剧院广场建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_NAVIGATION_SCHOOL_DESCRIPTION",                "葡萄牙特色建筑。在此城中生产海军单位时+25%生产力。此城中每拥有2个浅海与湖泊单元格，则+1 [ICON_SCiENCE] 科技值。+2 [ICON_GreatAdmiral] 海军统帅点数。每位 [ICON_CITIZEN] 市民+0.5 [ICON_Science] 科技值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_RESEARCH_LAB_DESCRIPTION",                     "本城 [ICON_SCIENCE] 科技值+5%。通电后额外为本城+10% [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_SEOWON_NAME",                                  "编书馆"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_DATA_CENTER_NAME",                          "数据中心"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_DATA_CENTER_DESCRIPTION",                   "+1通配符政策槽位。建成时，每个3级同盟提供1600 [ICON_SCIENCE] 科技值和1600 [ICON_CULTURE] 文化值。[NEWLINE]文明中一次仅限建造一座该建筑。"),
    -- 剧院
    ("zh_Hans_CN",  "LOC_BUILDING_MARAE_DESCRIPTION",                            "毛利特色建筑。城市中所有包含可通行地貌或自然奇观的单元格+2 [ICON_CULTURE] 文化值与 [ICON_FAITH] 信仰值。此城中每拥有3个浅海与湖泊单元格，则+1 [ICON_CULTURE] 文化值。解锁“飞行”科技后，城市中所有包含地貌或自然奇观的单元格+1 [ICON_TOURISM] 旅游业绩。无巨作槽位。"),
    ("zh_Hans_CN",  "LOC_BUILDING_MUSEUM_ARTIFACT_DESCRIPTION",                  "可存放 [ICON_GreatWork_Artifact] 文物。如果在剧院广场区域已经有一座艺术博物馆则无法修建。[NEWLINE]本城 [ICON_CULTURE] 文化值+5%。"),
    ("zh_Hans_CN",  "LOC_BUILDING_MUSEUM_ART_DESCRIPTION",                       "可存放 [ICON_GreatWork_Landscape] 艺术巨作。如果在剧院广场区域已经有一座考古博物馆则无法修建。[NEWLINE]本城 [ICON_CULTURE] 文化值+5%。"),
    ("zh_Hans_CN",  "LOC_BUILDING_BROADCAST_CENTER_DESCRIPTION",                 "本城 [ICON_CULTURE] 文化值+5%，通电后额外为本城+5% [ICON_CULTURE] 文化值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_FILM_STUDIO_EXPANSION2_DESCRIPTION",           "美国特色建筑。本城+50% [ICON_Tourism] 旅游业绩。本城 [ICON_CULTURE] 文化值+5%，通电后额外为本城+5% [ICON_CULTURE] 文化值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_JNR_DOJO_NAME",                                "道场"),
    ("zh_Hans_CN",  "LOC_BUILDING_JNR_DOJO_HD_DESCRIPTION",                      "日本特色建筑。此城中生产的所有军事单位+25%经验值。本城的巨作+2 [ICON_Production] 生产力。本城的巨作产出1.5倍的 [ICON_CULTURE] 文化值，且 [ICON_Tourism] 旅游业绩+50%。"),
    ("zh_Hans_CN",  "LOC_ABILITY_JNR_DOJO_TRAINED_UNIT_XP_DESCRIPTION",          "从道场获得的经验值+25%"),
    -- 工业
    ("zh_Hans_CN",  "LOC_BUILDING_WORKSHOP_DESCRIPTION",                         "本城已改良单元格+1 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_FACTORY_DL_DESCRIPTION",                       "为6个单元格内的城市或社区提供 [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_ELECTRONICS_FACTORY_NAME",                  "电子厂"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_ELECTRONICS_FACTORY_DESCRIPTION",           "本城每个区域 +1 [ICON_PRODUCTION] 生产力，每位 [ICON_CITIZEN] 市民+0.5 [ICON_PRODUCTION] 生产力；解锁“集成电路”科技后收益翻倍。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_INTERNET_COMPANY_NAME",                     "互联网公司"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_INTERNET_COMPANY_DESCRIPTION",              "学院和工业区的相邻加成也产生等量 [ICON_Tourism] 旅游业绩。此城 [ICON_POWER] 供电充足时，全境内+5% [ICON_TOURISM] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_INTERNET_COMPANY_MONOPOLY_DESCRIPTION",     "学院和工业区的相邻加成也产生等量 [ICON_Tourism] 旅游业绩。此城市的 [ICON_GreatWork_Product] 产品提供2倍的 [ICON_SCIENCE] 科技和 [ICON_CULTURE] 文化产出，且提供的 [ICON_Tourism] 旅游业绩+100%。此城 [ICON_POWER] 供电充足时，全境内+5% [ICON_TOURISM] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_BUILDING_COAL_POWER_PLANT_DL_DESCRIPTION",              "将任意数额的 [ICON_RESOURCE_COAL] 煤自动转换为 [ICON_Power] 电力，每回合可为周围6个单元格内的城市提供其所需电力：[NEWLINE][ICON_Bullet]1点 [ICON_RESOURCE_COAL] 煤 [ICON_PowerRight] 4点 [ICON_Power] 电力[NEWLINE][ICON_Bullet]会向大气层排放大量二氧化碳。[NEWLINE]本城建造区域、建筑和奇观+10% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_FOSSIL_FUEL_POWER_PLANT_DL_DESCRIPTION",       "将任意数额的 [ICON_RESOURCE_OIL] 石油自动转换为 [ICON_Power] 电力，每回合可为周围6个单元格内的城市提供其所需电力：[NEWLINE][ICON_Bullet]1点 [ICON_RESOURCE_OIL] 石油 [ICON_PowerRight] 4点 [ICON_Power] 电力[NEWLINE][ICON_Bullet]会向大气层排放中量二氧化碳。[NEWLINE]本城建造区域、建筑和奇观+10% [ICON_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_POWER_PLANT_DL_DESCRIPTION",                   "将任意数额的 [ICON_RESOURCE_URANIUM] 铀自动转换为 [ICON_Power] 电力，每回合可为周围6个单元格内的城市提供其所需电力：[NEWLINE][ICON_Bullet]1点 [ICON_RESOURCE_URANIUM] 铀 [ICON_PowerRight] 16点 [ICON_Power] 电力[NEWLINE][ICON_Bullet]会向大气层排放少量二氧化碳。[NEWLINE]本城建造区域、建筑和奇观+10% [ICON_Production] 生产力。"),
    -- 圣地
    ("zh_Hans_CN",  "LOC_BUILDING_SHRINE_DESCRIPTION",                           "允许使用 [ICON_FAITH] 信仰值购买建造者和传教士。"),
    ("zh_Hans_CN",  "LOC_BUILDING_TEMPLE_DESCRIPTION",                           "允许使用 [ICON_FAITH] 信仰值购买开拓者、使徒、上师、审判官，拥有特定信仰还可购买武僧。本城的 [ICON_Faith] 信仰值+5%。"),
    ("zh_Hans_CN",  "LOC_BUILDING_PRASAT_EXPANSION2_DESCRIPTION",                "高棉特色建筑。替代寺庙。允许使用 [ICON_FAITH] 信仰值购买开拓者、使徒、上师、审判官，拥有特定信仰还可购买武僧。此城中每有1点 [ICON_CITIZEN] 人口，便+0.5 [ICON_Culture] 文化值。本城的 [ICON_Faith] 信仰值+5%。"),
    ("zh_Hans_CN",  "LOC_BUILDING_STAVE_CHURCH_DESCRIPTION",                     "挪威特色建筑。取代寺庙。允许使用 [ICON_FAITH] 信仰值购买开拓者、使徒、上师、审判官，拥有特定信仰还可购买武僧。圣地可从树林获得额外的标准相邻加成。城市中每个森林单元格+1 [ICON_Food] 食物。本城的 [ICON_Faith] 信仰值+5%。"), --+1 [ICON_TradeRoute] 贸易路线容量。
    ("zh_Hans_CN",  "LOC_BUILDING_MOSQUE_DL_DESCRIPTION",                        "此处创建的传教士和使徒+1传教次数。所有从本城创建的宗教单位在宗教战争中+3力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_PAGODA_DL_NAME",                               "藏经阁"),
    ("zh_Hans_CN",  "LOC_BUILDING_PAGODA_DL_DESCRIPTION",                        "可放置2个 [ICON_GreatWork_Writing] 著作巨作。玩家的 [ICON_GREATWRITER] 大作家点数积累速度+20%。本城的 [ICON_GreatWork_Writing] 著作巨作+4 [ICON_FAITH] 信仰值，产出1.25倍的 [ICON_CULTURE] 文化值和+50% [ICON_TOURISM] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_BUILDING_WAT_DL_DESCRIPTION",                           "本城+10% [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_SYNAGOGUE_DL_DESCRIPTION",                     "本城+10% [ICON_FAITH] 信仰值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GURDWARA_DL_DESCRIPTION",                      "本城+10% [ICON_Food] 食物。"),
    ("zh_Hans_CN",  "LOC_BUILDING_MEETING_HOUSE_DL_DESCRIPTION",                 "本城+10% [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_STUPA_DL_DESCRIPTION",                         "本城每种已改良的奢侈品 +1 [ICON_AMENITIES] 宜居度。"),
    ("zh_Hans_CN",  "LOC_BUILDING_CATHEDRAL_DL_DESCRIPTION",                     "可放置2个 [ICON_GreatWork_Landscape] 艺术巨作和1个 [ICON_GreatWork_Music] 音乐巨作。玩家的 [ICON_GREATARTIST] 大艺术家和 [ICON_GREATMUSICIAN] 大音乐家点数积累速度+10%。本城的 [ICON_GreatWork_Landscape] 艺术和 [ICON_GreatWork_Music] 音乐巨作产出1.25倍的 [ICON_CULTURE] 文化值和+100% [ICON_TOURISM] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_BUILDING_DAR_E_MEHR_DL_DESCRIPTION",                    "建造或上次修复后的每个时代均额外+2 [ICON_FAITH] 信仰值。本城+10% [ICON_CULTURE] 文化值。 "),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_ALCHEMY_ROOM_NAME",                         "丹房"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_ALCHEMY_ROOM_DESCRIPTION",                  "本城每位 [ICON_CITIZEN] 公民 +0.3 [ICON_SCIENCE] 科技值产出。允许使用 [ICON_FAITH] 信仰值购买开拓者、使徒、上师、审判官，拥有特定信仰还可购买武僧。"),
    -- 军营
    ("zh_Hans_CN",  "LOC_BUILDING_BARRACKS_EXPANSION2_DESCRIPTION",              "该城市中训练的所有近战、抗骑兵、远程和远程骑兵类陆地单位+25%战斗经验值。[NEWLINE][NEWLINE]无法建造在已有马厩的军营区域中。[NEWLINE][NEWLINE]本城的所有已开发的 [ICON_RESOURCE_IRON] 铁资源+2 [ICON_Production] 生产力。为在本城训练的近战、远程、抗骑兵单位提供永久+2 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_BASILIKOI_PAIDES_EXPANSION2_DESCRIPTION",      "马其顿特色建筑，取代兵营且解锁更早。该城中训练的陆地近战、远程单位和伙友骑兵+25%战斗经验值。非平民单位在此城中创建时，获得等同于单位花费25%的 [ICON_SCIENCE] 科技值。[NEWLINE][NEWLINE]无法建造在已拥有马厩的军营区域中。[NEWLINE][NEWLINE]本城的所有已开发的 [ICON_RESOURCE_IRON] 铁+2 [ICON_Production] 生产力。为在本城训练的近战、远程、抗骑兵、攻城单位和伙友骑兵提供永久+3 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_STABLE_EXPANSION2_DESCRIPTION",                "该城市中训练的所有骑兵类和攻城类单位+25%战斗经验值。[NEWLINE][NEWLINE]不能建造在已有兵营的军营区域中。[NEWLINE][NEWLINE]本城的所有已开发的 [ICON_RESOURCE_HORSES] 马+2 [ICON_Production] 生产力。为在本城训练的轻重骑兵和攻城类单位提供永久+2 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_ORDU_EXPANSION2_DESCRIPTION",                  "蒙古特色建筑。其所在城市中训练的轻重骑兵单位 [ICON_MOVEMENT] 移动力+1。其所在城市中训练的所有骑兵类和攻城类单位+25%战斗经验值。[NEWLINE][NEWLINE]无法建造在已拥有兵营的军营区域中。[NEWLINE][NEWLINE]本城的所有已开发的 [ICON_RESOURCE_HORSES] 马资源+2 [ICON_Production] 生产力。为在本城训练的轻重骑兵、攻城类单位、怯薛歹提供永久+3 [ICON_Strength] 战斗力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_ARMORY_EXPANSION2_DESCRIPTION",                "该城市中训练的所有陆地单位+25%战斗经验值。[NEWLINE]战略资源储备+30（标准速度下）。为本城所有的 [ICON_Resource_Niter] 硝石、 [ICON_Resource_Oil] 石油资源+1 [ICON_Production] 生产力。此城中生产的所有军事单位若初始未拥有免费晋升，则其初始可获得免费晋升。"),
    ("zh_Hans_CN",  "LOC_BUILDING_MILITARY_ACADEMY_EXPANSION2_DESCRIPTION",      "该城市中训练的所有陆地单位+25%战斗经验值。[NEWLINE]可直接训练军团和军队。军团和军队的训练费用降低25%。为本城的 [ICON_Resource_Aluminum] 铝、 [ICON_Resource_Uranium] 铀资源+1 [ICON_Production] 生产力。玩家的 [ICON_GREATGENERAL] 大将军点数积累速度+10%，且所有训练的陆地单位+3 [ICON_STRENGTH] 战斗力。"),
    -- 商业
    ("zh_Hans_CN",  "LOC_BUILDING_FAIR_NAME",                                    "集市"),
    ("zh_Hans_CN",  "LOC_BUILDING_MARKET_EXPANSION1_DESCRIPTION",                "+1 [ICON_TradeRoute] 贸易路线容量。"),
    ("zh_Hans_CN",  "LOC_BUILDING_SUKIENNICE_NAME",                              "克拉科夫纺织会馆"),
    ("zh_Hans_CN",  "LOC_BUILDING_SUKIENNICE_EXPANSION1_DESCRIPTION",            "波兰特色建筑，文明中一次仅限建造一座该建筑。[NEWLINE][NEWLINE]建成商业中心后对相邻单元格释放文化炸弹。[NEWLINE]本城的商业中心每拥有+8相邻加成，提供+1 [ICON_TradeRoute] 贸易路线容量。以本城为目的地的国内 [ICON_TRADEROUTE] 贸易路线获得25%本城商业中心相邻加成的 [ICON_PRODUCTION] 生产力；本城出发的国际 [ICON_TRADEROUTE] 贸易路线获得75%本城商业中心相邻加成的 [ICON_GOLD] 金币。[NEWLINE][NEWLINE]本城建立国际 [ICON_TRADEROUTE] 贸易路线时，随机获得一份目的地城市的奢侈资源以及其产出，仅能从每座目的地城市获得一次该效果。"),
    ("zh_Hans_CN",  "LOC_BUILDING_BANK_DESCRIPTION",                             "本城 [ICON_GOLD] 金币产出+5%。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GRAND_BAZAAR_DESCRIPTION",                     "奥斯曼特色建筑。城市中改良的每种不同战略资源均可额外增加1点。城市改良的每个奢侈品资源均可提供1点 [ICON_AMENITIES] 宜居度。本城 [ICON_GOLD] 金币产出+5%。"),
    ("zh_Hans_CN",  "LOC_BUILDING_STOCK_EXCHANGE_DESCRIPTION",                   "6个单元格内的城市+10% [ICON_GOLD] 金币，玩家的 [ICON_GREATMERCHANT] 大商人点数积累速度+10%（前提是其尚未从其他的“证券交易所”建筑获得加成）；通电后效果翻倍。"),
    -- 港口
    ("zh_Hans_CN",  "LOC_BUILDING_LIGHTHOUSE_EXPANSION2_DESCRIPTION",            "此城生产的所有海军单位+25%战斗经验值。此城的所有浅海与湖泊单元格+1 [ICON_Food] 食物。+1 [ICON_TradeRoute] 贸易路线容量。"), -- [ICON_Resource_Fish] 鱼、 [ICON_Resource_Crabs] 螃蟹、 [ICON_Resource_Whales] 鲸鱼、 [ICON_Resource_Pearls] 珍珠
    ("zh_Hans_CN",  "LOC_BUILDING_SHIPYARD_EXPANSION2_DESCRIPTION",              "此城中生产的所有海军单位+25%战斗经验值。[ICON_Production] 生产力加成等于港口区域的相邻加成。此城所有浅海与湖泊单元格+1 [ICON_PRODUCTION] 生产力。对所有海军单位+25% [ICON_PRODUCTION] 生产力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_SEAPORT_DESCRIPTION",                          "此城中生产的所有海军单位+25%经验值。可直接生产舰队和无敌舰队。舰队和无敌舰队的生产费用降低25%。此城所有浅海与湖泊单元格+1 [ICON_FOOD] 食物。额外产出相当于港口相邻加成的 [ICON_FOOD] 食物。 [NEWLINE]玩家的 [ICON_GREATADMIRAL] 海军统帅点数积累速度+10%，且所有训练的海军单位+3 [ICON_STRENGTH] 战斗力。"),
    -- 政府区
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_WIDE_NAME",                                "会议堂"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_WIDE_DESCRIPTION",                         "在此城中生产开拓者时+50%建造速度。新建立的城市获得1个免费的建造者。建造本城拥有的市中心建筑+50%建造速度。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_TALL_DESCRIPTION",                         "所有城市+2 [ICON_Housing] 住房。[NEWLINE]本城建造奇观、区域和建筑时+20%建造速度，可以无视 [ICON_CITIZEN] 人口限制额外建造1个区域。[NEWLINE]奖励1个 [ICON_Governor] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_CONQUEST_DESCRIPTION",                     "占领一座敌方城市后，所有城市将获得15%的 [ICON_Production] 生产力加成，效果持续5回合。[NEWLINE]本城建造军事单位时+20% [ICON_Production] 生产力。[NEWLINE]掠夺和海岸扫荡的收益+100%。[NEWLINE]奖励1个 [ICON_Governor] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_SPIES_NAME",                               "中书省"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_SPIES_HD_DESCRIPTION",                     "所有城市+10% [ICON_Food] 食物和 [ICON_Production] 生产力。总督所在的城市这些效果翻倍。[NEWLINE]奖励1个 [ICON_Governor] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_FAITH_NAME",                               "主教座堂"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_FAITH_HD_DESCRIPTION",                     "有圣地的城市+10% [ICON_Faith] 信仰值。所有城市获得等同于 [ICON_Faith] 信仰值产出10%的 [ICON_Science] 科技值和 [ICON_Culture] 文化值。[NEWLINE]所有城市购买宗教单位的花费减少20%。宗教单位在神学战斗中+5 [ICON_Religion] 宗教力量。[NEWLINE]奖励1个 [ICON_Governor] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_CITYSTATES_NAME",                          "贸易本埠"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_CITYSTATES_HD_DESCRIPTION",                "+1 [ICON_TRADEROUTE] 贸易路线容量。获得1个商人。购买商人时-10%花费。创建 [ICON_TRADEROUTE] 贸易路线后，[ICON_TRADINGPOST] 贸易站将立刻出现在目标城市。您的 [ICON_TRADEROUTE] 贸易路线每经过一个您在国外城市的 [ICON_TRADINGPOST] 贸易站便+1 [ICON_GOLD] 金币。有 [ICON_GOVERNOR] 总督就职的城市+15% [ICON_GOLD] 金币产出。[NEWLINE]奖励1个 [Icon_Governor] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_CITYSTATES_MONOPOLY_DESCRIPTION",          "+1 [ICON_TRADEROUTE] 贸易路线容量。获得1个商人。购买商人时-10%花费。创建 [ICON_TRADEROUTE] 贸易路线后，[ICON_TRADINGPOST] 贸易站将立刻出现在目标城市。您的 [ICON_TRADEROUTE] 贸易路线每经过一个您在国外城市的 [ICON_TRADINGPOST] 贸易站便+1 [ICON_GOLD] 金币。有 [ICON_GOVERNOR] 总督就职的城市+15% [ICON_GOLD] 金币产出。解锁对应科技后，分别获得一个大亨和投资人。[NEWLINE]奖励1个 [Icon_Governor] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_SCIENCE_DESCRIPTION",                      "学院建筑提供等同于基础 [ICON_Science] 科技值产出的 [ICON_Production] 生产力。[NEWLINE]工业区建筑提供等同于基础 [ICON_Production] 生产力产出的 [ICON_Science] 科技值。[NEWLINE]奖励1个 [ICON_Governor] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_MILITARY_DESCRIPTION",                     "所有军事单位+1 [ICON_Movement] 移动力和+3 [ICON_Strength] 战斗力。[NEWLINE]每个单位每回合维护费减少2 [ICON_Gold] 金币。[NEWLINE]升级单位所需的 [ICON_Gold] 金币和资源减少25%。[NEWLINE]奖励1个 [ICON_Governor] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_BUILDING_GOV_CULTURE_DESCRIPTION",                      "提供6个可保存任意类型的巨作槽位。所有城市来自巨作的 [ICON_Tourism] 旅游业绩+100%；该效果对本城的巨作翻倍。全境内+20% [ICON_TOURISM] 旅游业绩。建有艺术博物馆或考古博物馆的城市+25% [ICON_CULTURE] 文化值。[NEWLINE]奖励1个 [Icon_Governor] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOV_FAITH_COMBAT_STRENGTH_DESCRIPTION",         "+5 [ICON_Religion] 宗教力量来自主教座堂。"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOV_MILITARY_MOVEMENT_DESCRIPTION",             "+1 [ICON_Movement] 移动力来自作战部。"),
    ("zh_Hans_CN",  "LOC_ABILITY_GOV_MILITARY_COMBAT_STRENGTH_DESCRIPTION",      "+3 [ICON_Strength] 战斗力来自作战部。"),
    ("zh_Hans_CN",  "LOC_BUILDING_QUEENS_BIBLIOTHEQUE_DESCRIPTION",              "克里斯蒂娜的特色建筑。提供6个可保存任意类型的巨作槽位。本城巨作产出的 [ICON_Tourism] 旅游业绩+100%； [ICON_GreatWork_Writing] 著作产出的 [ICON_Tourism] 旅游业绩额外+100%。[ICON_CivicBoosted] 鼓舞额外提供3% [ICON_CULTURE] 文化值。建成后触发“歌剧与芭蕾” [ICON_CivicBoosted] 鼓舞，若“歌剧与芭蕾” [ICON_CivicBoosted] 鼓舞已触发，则直接完成“歌剧与芭蕾”市政。[NEWLINE]奖励1个 [ICON_GOVERNOR] 总督头衔。"),
    ("zh_Hans_CN",  "LOC_BUILDING_EL_ESCORIAL_PALACE_NAME",                      "埃斯科里亚尔王宫"),
    ("zh_Hans_CN",  "LOC_BUILDING_EL_ESCORIAL_PALACE_DESCRIPTION",               "菲利普二世的特色建筑。你每探索过的一座“黄金城”，该建筑和你的宫殿获得等同于该自然奇观的基础产出或相邻产出的加成，且该建筑每回合提供+2 [ICON_GreatProphet] 大预言家点数、[ICON_GreatWriter] 大作家点数和 [ICON_GreatArtist] 大艺术家点数。本城的 [ICON_GreatWork_Relic] 遗物、 [ICON_GreatWork_Writing] 著作和 [ICON_GreatWork_Landscape] 艺术巨作产出1.5倍的 [ICON_CULTURE] 文化值和 [ICON_Faith] 信仰值。"),
    -- 外交区
    ("zh_Hans_CN",  "LOC_BUILDING_CONSULATE_DESCRIPTION",                        "每回合影响力点数+2。获得1名 [ICON_ENVOY] 使者。征兵花费的 [ICON_GOLD] 金币减少20%。此城市训练间谍时+50%建造速度。您的间谍可以选择任何可用升级。"),
    ("zh_Hans_CN",  "LOC_BUILDING_CHANCERY_DESCRIPTION",                         "每回合影响力点数+3。获得1名 [ICON_ENVOY] 使者。对所有文明+1 [ICON_VISLIMITED] 外交能见度。所有城市训练间谍时+50%建造速度。获得一个间谍并+1间谍容量。所有间谍初始便拥有1次免费升级，出击时+1级成功率，执行任务的时间缩短15%。此文明俘获或杀死敌方间谍时，敌方间谍每拥有一级升级，文明便获得50点 [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_REGIONAL_COUNCIL_CENTER_NAME",              "区域议会中心"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_REGIONAL_COUNCIL_CENTER_DESCRIPTION",       "+1文化政策槽位。+1外交胜利点数。+25%影响力点数。对所有文明+1 [ICON_VISLIMITED] 外交能见度。所有盟友的同盟点数每回合额外增加5点。来自同盟的 [ICON_TRADEROUTE] 贸易路线收益翻倍。领土内的敌方间谍下降1级。[NEWLINE]奖励1个 [ICON_GOVERNOR] 总督头衔。[NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS_NAME",        "世界议会总部"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS_DESCRIPTION", "美国特色建筑。+1文化符政策槽位。+3外交胜利点数。+50%影响力点数。对所有文明+1 [ICON_VISLIMITED] 外交能见度。所有盟友的同盟点数每回合额外增加5点。来自同盟的 [ICON_TRADEROUTE] 贸易路线收益翻倍。对于每一类城邦，若你是其中至少1个的宗主国，所有城市此类城邦对应的产出+10%。我方间谍出击时+1级成功率，领土内的敌方间谍下降1级。[NEWLINE]奖励1个 [ICON_GOVERNOR] 总督头衔。[NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_TRAIT_CIVILIZATION_BUILDING_HD_WORLD_PARLIAMENT_HEADQUARTERS_NAME",               "美国特色建筑：世界议会总部"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_HUMAN_RIGHTS_COUNCIL_NAME",                 "人权理事会"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_HUMAN_RIGHTS_COUNCIL_DESCRIPTION",          "+1经济政策槽位。城市每有一种提供 [ICON_GREATPERSON] 伟人点的区域，该城市的每座社区提供+4对应 [ICON_GREATPERSON] 伟人点。[NEWLINE]奖励1个 [ICON_GOVERNOR] 总督头衔。[NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_MINISTRY_OF_NATIONAL_DEFENSES_NAME",        "国防部"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_MINISTRY_OF_NATIONAL_DEFENSE_DESCRIPTION",  "+1军事政策槽位。所有单位+5 [ICON_STRENGTH] 战斗力。玩家的 [ICON_GREATGENERAL] 大将军的点数积累速度+50%。每训练过一种军事单位，提供+3 [ICON_SCIENCE] 科技值和 [ICON_Production] 生产力。[NEWLINE]奖励1个 [ICON_GOVERNOR] 总督头衔。[NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_ABILITY_MND_UNIT_STRENGTH_DESCRIPTION",                 "国防部：+5 [ICON_STRENGTH] 战斗力。"),
    -- 娱乐区
    ("zh_Hans_CN",  "LOC_BUILDING_ARENA_EXPANSION1_DESCRIPTION",                 "拥有“保护地球”市政后提供1点 [ICON_TOURISM] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_BUILDING_TLACHTLI_XP1_DESCRIPTION",                     "阿兹特克特色建筑。提供1点 [ICON_Amenities] 宜居度、+2 [ICON_Culture] 文化值、+2 [ICON_Faith] 信仰值，并提供2点 [ICON_GreatGeneral] 大将军点数。拥有“保护地球”市政后提供1点 [ICON_TOURISM] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_BUILDING_STADIUM_DL_DESCRIPTION",                       "如城市 [ICON_CITIZEN] 人口大于等于10，则+2 [ICON_Tourism] 旅游业绩；如城市 [ICON_CITIZEN] 人口大于等于20，则+5 [ICON_Tourism] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_BUILDING_ZOO_EXPANSION1_DESCRIPTION",                   "你每拥有一种牧场或营地资源，额外+1 [ICON_CULTURE] 文化值，+3 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_BUILDING_THERMAL_BATH_DESCRIPTION",                     "匈牙利特色建筑。本城中地热裂缝+2 [ICON_FAITH] 信仰值，+2 [ICON_CULTURE] 文化值；解锁“化学”科技后，额外获得+2 [ICON_SCIENCE] 科技值。本城的区域从地热裂缝获得大量相邻加成。"),
    ("zh_Hans_CN",  "LOC_THERMAL_BATH_FAITH",                                    "+{1_num} [ICON_FAITH] 信仰来自相邻地热裂缝{1_Num : plural 1?单元格; other?单元格;}。"),
    ("zh_Hans_CN",  "LOC_THERMAL_BATH_GOLD",                                     "+{1_num} [ICON_GOLD] 金币来自相邻地热裂缝{1_Num : plural 1?单元格; other?单元格;}。"),
    ("zh_Hans_CN",  "LOC_THERMAL_BATH_SCIENCE",                                  "+{1_num} [ICON_SCIENCE] 科技值来自相邻地热裂缝{1_Num : plural 1?单元格; other?单元格;}。"),
    ("zh_Hans_CN",  "LOC_THERMAL_BATH_CULTURE",                                  "+{1_num} [ICON_CULTURE] 文化值自相邻地热裂缝{1_Num : plural 1?单元格; other?单元格;}。"),
    ("zh_Hans_CN",  "LOC_THERMAL_BATH_PRODUCTION",                               "+{1_num} [ICON_PRODUCTION] 生产力来自相邻地热裂缝{1_Num : plural 1?单元格; other?单元格;}。"),
    -- 水上娱乐
    ("zh_Hans_CN",  "LOC_BUILDING_FERRIS_WHEEL_DESCRIPTION_HD",                  "+3 [ICON_Tourism] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_BUILDING_AQUATICS_CENTER_DL_DESCRIPTION",               "此城中沿海或海上的奇观+2 [ICON_Tourism] 旅游业绩。"),
    ("zh_Hans_CN",  "LOC_BUILDING_AQUARIUM_DL_DESCRIPTION",                      "你每拥有一种渔船资源，额外+1 [ICON_SCIENCE] 科技值和 [ICON_CULTURE] 文化值。"),
    -- 航空港
    ("zh_Hans_CN",  "LOC_BUILDING_HANGAR_DESCRIPTION",                           "当前城市训练的空中单位+25%战斗经验值。航空港区域+2空中单位槽位。建造空中单位时，+50% [Icon_Production] 生产力。"),
    ("zh_Hans_CN",  "LOC_BUILDING_AIRPORT_DESCRIPTION",                          "若此城 [ICON_POWER] 供电充足，则城市中来自改良、巨作的 [ICON_Tourism] 旅游业绩+50%，来自奇观的 [ICON_Tourism] 旅游业绩+100%；该加成效果延伸到5个单元格内的所有城市（前提是其尚未从其他的“机场”建筑获得加成）。 [NEWLINE] 该城市训练的空中单位+50%战斗经验值。紧急部署市政解锁后，可以在带有机场的航空港之间空运陆地单位。"),
    ("zh_Hans_CN",  "LOC_BUILDING_AIRPORT_DESCRIPTION_PRODUCT",                  "若此城 [ICON_POWER] 供电充足，则城市中来自改良、巨作、 [ICON_GreatWork_Product] 产品的 [ICON_Tourism] 旅游业绩+50%，来自奇观的 [ICON_Tourism] 旅游业绩+100%；该加成效果延伸到5个单元格内的所有城市（前提是其尚未从其他的“机场”建筑获得加成）。 [NEWLINE] 该城市训练的空中单位+50%战斗经验值。紧急部署市政解锁后，可以在带有机场的航空港之间空运陆地单位。"),
    -- 社区
    ("zh_Hans_CN",  "LOC_BUILDING_FOOD_MARKET_NAME",                             "农贸市场"),
    ("zh_Hans_CN",  "LOC_BUILDING_FOOD_MARKET_DESCRIPTION",                      "玩家的{LOC_BUILDING_FOOD_MARKET_BUFF_OBJECT}点数积累速度+10%，解锁“现代农业”科技后翻倍。你拥有的每种农场、种植园、牧场或渔船资源，为所有城市+1 [ICON_GOLD] 金币。[NEWLINE][NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_FOOD_MARKET_DESCRIPTION_CORP",                 "玩家的{LOC_BUILDING_FOOD_MARKET_BUFF_OBJECT}点数积累速度+10%，解锁“现代农业”科技后翻倍。你拥有的每种农场、种植园、牧场或渔船资源，为所有城市+1 [ICON_GOLD] 金币。[NEWLINE][NEWLINE]若此城 [ICON_POWER] 供电充足，全国 [ICON_GreatWork_Product] 产品提供1.5倍的 [ICON_FOOD] 食物和 [ICON_PRODUCTION] 生产力，且 [ICON_TOURISM] 旅游业绩+100%。[NEWLINE][NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_FOOD_MARKET_BUFF_OBJECT",                      " [ICON_GREATMERCHANT] 大商人"),
    ("zh_Hans_CN",  "LOC_BUILDING_SHOPPING_MALL_NAME",                           "百货大楼"),
    ("zh_Hans_CN",  "LOC_BUILDING_SHOPPING_MALL_DESCRIPTION",                    "玩家的 [ICON_GREATMERCHANT] 大商人点数积累速度+10%，解锁“金融学”市政后翻倍。你拥有的每种矿山、采石场、营地或伐木场资源，为所有城市+1 [ICON_GOLD] 金币。[NEWLINE][NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_SHOPPING_MALL_DESCRIPTION_CORP",               "玩家的 [ICON_GREATMERCHANT] 大商人点数积累速度+10%，解锁“金融学”市政后翻倍。你拥有的每种矿山、采石场、营地或伐木场资源，为所有城市+1 [ICON_GOLD] 金币。[NEWLINE][NEWLINE]若此城 [ICON_POWER] 供电充足，全国 [ICON_GreatWork_Product] 产品提供1.5倍的 [ICON_Gold] 金币和 [ICON_Faith] 信仰，且 [ICON_TOURISM] 旅游业绩+100%。[NEWLINE][NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_VILLA_NAME",                                "别墅"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_VILLA_DESCRIPTION",                         "本城的社区和住宅设施改良+1 [ICON_FOOD] 食物和+3 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_MANSION_NAME",                              "官邸"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_MANSION_DESCRIPTION",                       "有 [ICON_GOVERNOR] 总督就职且有社区的城市从建筑和奇观获得1.5倍的辐射产出。[NEWLINE]奖励1个 [ICON_GOVERNOR] 总督头衔。[NEWLINE][NEWLINE]必须建造在 [ICON_CAPITAL] 首都。文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_BUS_STOP_NAME",                             "公交站"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_BUS_STOP_DESCRIPTION",                      "3个单元格内的区域获得一份对应产出。3个单元格内的改良+3 [ICON_GOLD] 金币。本城的商业中心和港口+100%相邻加成。"),
    -- 堤坝
    ("zh_Hans_CN",  "LOC_BUILDING_HYDROELECTRIC_DAM_DESCRIPTION",                "可再生水力发电向城市提供+6点 [ICON_Power] 电力。本城所有的沿河单元格+1 [ICON_Production] 生产力。"),
    -- 保护区
    ("zh_Hans_CN",  "LOC_BUILDING_GROVE_NAME",                                   "神谕碑"),
    ("zh_Hans_CN",  "LOC_BUILDING_GROVE_DESCRIPTION",                            "相邻的迷人单元格+1 [ICON_CULTURE] 文化值。相邻的惊艳单元格额外+1 [ICON_SCIENCE] 科技值。"),
    ("zh_Hans_CN",  "LOC_BUILDING_SANCTUARY_NAME",                               "自然环境保护部"),
    ("zh_Hans_CN",  "LOC_BUILDING_SANCTUARY_DESCRIPTION",                        "建成后，使本城的随机一种地貌上的生物类资源在附近种群扩张。[NEWLINE][NEWLINE]本城的雨林、草本沼泽和泛滥单元格为周围单元格+1魅力。[NEWLINE][NEWLINE]本城的地貌单元格+1 [ICON_FOOD] 食物；若拥有资源，则额外+1 [ICON_PRODUCTION] 生产力；若位于迷人单元格，则额外+3 [ICON_GOLD] 金币；若位于惊艳单元格，则额外+1 [ICON_CULTURE] 文化值。[NEWLINE]本城的自然奇观单元格+2 [ICON_FOOD] 食物，+2 [ICON_CULTURE] 文化值和+6 [ICON_GOLD] 金币。"),
    ("zh_Hans_CN",  "LOC_BUILDING_SANCTUARY_TEXT",                               "{1_Name}的种群扩张了"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_CULTURE_HERITAGE_PRESERVE_NAME",            "人文遗产保护部"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_CULTURE_HERITAGE_PRESERVE_DESCRIPTION",     "本城位于迷人单元格的世界奇观和特色改良设施+1 [ICON_CULTURE] 文化值、+3 [ICON_GOLD] 金币；若位于惊艳单元格，则收益翻倍。本城的世界奇观和特色改良设施提供的 [ICON_TOURISM] 旅游业绩+100%。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_LANDFORM_EPO_NAME",                         "地貌生态环保专局"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_LANDFORM_EPO_DESCRIPTION",                  "境内每拥有一种地貌（不包括自然奇观），则获得+8 [ICON_SCIENCE] 科技值、+8 [ICON_CULTURE] 文化值。[NEWLINE][NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_RESOURCE_EPO_NAME",                         "不可再生资源管理专局"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_RESOURCE_EPO_DESCRIPTION",                  "你每拥有一种矿产类资源，获得+4 [ICON_PRODUCTION] 生产力、+4 [ICON_SCIENCE] 科技值。[NEWLINE][NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_SPECIES_EPO_NAME",                          "物种多样性维护专局"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_SPECIES_EPO_DESCRIPTION",                   "你每拥有一种生物类资源，获得+4 [ICON_FOOD] 食物、+4 [ICON_CULTURE] 文化值。[NEWLINE][NEWLINE]文明中一次仅限建造一座该建筑。"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_SCENIC_EPO_NAME",                           "自然名胜旅游专局"),
    ("zh_Hans_CN",  "LOC_BUILDING_HD_SCENIC_EPO_DESCRIPTION",                    "境内的自然奇观提供的产出翻三倍。拥有自然奇观或国家公园的城市+5%所有产出。国家公园提供的 [ICON_TOURISM] 旅游业绩+100%。建成时获得1个自然学家。购买自然学家的费用降低50%。[NEWLINE][NEWLINE]文明中一次仅限建造一座该建筑。");