insert or replace into EnglishText (Tag, Text) values
  ("LOC_TOOLTIP_HD_COMMA_TEXT",                     ", "),
  ("LOC_TOOLTIP_HD_OR_TEXT",                        " or "),

  ("LOC_TOOLTIP_HD_TRAITS_TEXT",                    "Traits:"),
  ("LOC_TOOLTIP_HD_APPEAL_TEXT",                    "{1_Amount: number +#,###.#;-#,###.#} Appeal to adjacent tiles"),
  ("LOC_TOOLTIP_HD_TOURISM_FROM_YIELD_TEXT",        "Provide [ICON_TOURISM] Tourism equal to {1_ScalingFactor}% of {2_Icon} {3_Name}. Requires {4_TechCivicName}."),
  ("LOC_TOOLTIP_HD_TOURISM_FROM_APPEAL_TEXT",       "Provide [ICON_TOURISM] Tourism equal to {1_ScalingFactor}% of Appeal. Requires {2_TechCivicName}."),
  ("LOC_TOOLTIP_HD_TOURISM_FROM_YIELD_NOREQ_TEXT",  "Provide [ICON_TOURISM] Tourism equal to {1_ScalingFactor}% of {2_Icon} {3_Name}."),
  ("LOC_TOOLTIP_HD_TOURISM_FROM_APPEAL_NOREQ_TEXT", "Provide [ICON_TOURISM] Tourism equal to {1_ScalingFactor}% of Appeal."),

  ("LOC_TOOLTIP_HD_CLASSIFICATIONS_TEXT",           "Classifications:"),
  ("LOC_TOOLTIP_HD_GENERAL_DISTRICT_TEXT",          "General District"),
  ("LOC_TOOLTIP_HD_UNIQUE_DISTRICT_TEXT",           "Unique District"),
  ("LOC_TOOLTIP_HD_REPLACE_DISTRICT_TEXT",          "Unique District (Replacing {1_Name})"),
  ("LOC_TOOLTIP_HD_WORLD_WONDER_TEXT",              "World Wonder"),
  ("LOC_TOOLTIP_HD_NATIONAL_WONDER_TEXT",           "National Wonder"),
  ("LOC_TOOLTIP_HD_GENERAL_BUILDING_TEXT",          "General Building"),
  ("LOC_TOOLTIP_HD_UNIQUE_BUILDING_TEXT",           "Unique Building"),
  ("LOC_TOOLTIP_HD_REPLACE_BUILDING_TEXT",          "Unique Building (Replacing {1_Name})"),
  ("LOC_TOOLTIP_HD_RESOURCE_CLASSIFICATIONS_TEXT",  "Usages:"),

  ("LOC_TOOLTIP_HD_REQUIRES_TEXT",                  "Requires:"),
  ("LOC_TOOLTIP_HD_TERRAIN_REQUIRES_TEXT",          "Terrains:"),
  ("LOC_TOOLTIP_HD_FEATURE_REQUIRES_TEXT",          "Features:"),
  ("LOC_TOOLTIP_HD_COAST_DISTRICT_TEXT",            "Shallow Sea and Lake tile adjacent to land"),
  ("LOC_TOOLTIP_HD_REQUIRE_NOT_ADJACENT_TO_CITY",   "Cannot be adjacent to a City Center"),
  ("LOC_TOOLTIP_HD_MAX_PER_PLAY_TEXT",              "Up to {1_Amount} can be built within territory"),
  ("LOC_TOOLTIP_HD_MUST_COAST_TEXT",                "Must adjacent to Sea"),
  ("LOC_TOOLTIP_HD_MUST_ADJACENT_LAND_TEXT",        "Must adjacent to Land"),
  ("LOC_TOOLTIP_HD_MUST_SEA_TEXT",                  "Must be built on Shallow Sea"),
  ("LOC_TOOLTIP_HD_MUST_LAKE_TEXT",                 "Must be built on Lake"),

  ("LOC_TOOLTIP_HD_YIELD_CHANGES_TEXT",             "Yield Changes:"),
  ("LOC_TOOLTIP_HD_BASIC_YIELDS_TEXT",              "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName}."),
  ("LOC_TOOLTIP_HD_YIELD_CHANGES_REQUIRES_TEXT",    "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName}. Requires {4_TechOrCivicName}."),
  ("LOC_TOOLTIP_HD_YIELD_FROM_APPEAL_TEXT",         "Provide {2_Icon} {3_Name} equal to {1_ScalingFactor}% of Appeal."),

  ("LOC_TOOLTIP_HD_ADJACENCIES_TEXT",               "Adjacencies:"),
  ("LOC_TOOLTIP_HD_ADJACENCIES_SELF_TEXT",          "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName} from itself."),
  ("LOC_TOOLTIP_HD_ADJACENCIES_RIVER_TEXT",         "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName} from adjacent river plots."),
  ("LOC_TOOLTIP_HD_ADJACENCIES_OBJECT_TEXT",        "{LOC_TYPE_TRAIT_ADJACENT_BONUS}"),
  ("LOC_TOOLTIP_HD_ADJACENCIES_OBJECT_PER_TEXT",    "{LOC_TYPE_TRAIT_ADJACENT_BONUS_PER}"),
  ("LOC_TOOLTIP_HD_ADJACENCIES_REQUIRES_TEXT",      " {LOC_TYPE_TRAIT_ADJACENT_BONUS_REQUIRES_TECH_OR_CIVIC}"),
  ("LOC_TOOLTIP_HD_ADJACENCIES_OBSOLETE_TEXT",      " {LOC_TYPE_TRAIT_ADJACENT_BONUS_OBSOLETE_WITH_TECH_OR_CIVIC}"),
  ("LOC_TYPE_TRAIT_ADJACENT_OBJECT_SEA_RESOURCE",   "Water Area Resources"),

  ("LOC_TOOLTIP_HD_IMPROVEMENT_UNIT_TEXT",          "Built By:"),

  ("LOC_TOOLTIP_COST_PROGRESSION_PARAM",						"Cost Progression Param: {1_num}"),
  ("LOC_TOOLTIP_ACTUAL_COST_TEXT",						      "Actual Cost: {1_Num} {2_Icon} {3_Name}"),

	("LOC_TOOLTIP_BUILDING_CITIZEN_YIELDS_HEADER",		"Citizen Yields change:"),
	("LOC_TOOLTIP_DISTRICT_CITIZEN_YIELDS_HEADER",		"Citizen Yields:"),

	("LOC_TOOLTIP_RESOURCE_IMPROVED_BY",							"Improved by: "),
	("LOC_TOOLTIP_RESOURCE_CORP_CATEGORY",						"Industry & Corporation: "),
  
  ("LOC_TOOLTIP_REGIONAL_EFFECT_RANGE",							"{1_num}-tile Regional Effect: The basic yields of this Wonder are extend to other cities within {1_num} tiles."),
	("LOC_TOOLTIP_REGIONAL_EFFECT_RANGE_MODIFIER",		"{1_num}-tile Regional Effect: Cities with City Center or Neighborhood within {1_num} tiles of this building receive the following bonuses, except those cities that have already received this bonus from the same building:"),
	("LOC_TOOLTIP_REGIONAL_EFFECT_REQ",								"(requires {1_TechOrCivicName})"),

  ("LOC_TOOLTIP_GREATWORK_SOLT_TEXT",							  "Great Work Slot: "),
	("LOC_TOOLTIP_THEMING_REQ_TITLE",							    "Theming Requirements: "),
	("LOC_TOOLTIP_THEMING_UNIQUE_PERSON_REQ",					"Display Great Works from different creators"),
	("LOC_TOOLTIP_THEMING_UNIQUE_PRODUCT_REQ",				"Display [ICON_GreatWork_Product] Products of different classes"),
	("LOC_TOOLTIP_THEMING_UNIQUE_CIVS_REQ",					  "Display Great Works from different civilizations"),
	("LOC_TOOLTIP_THEMING_SAME_OBJECT_TYPE_REQ",			"Display Great Works of the same kind"),
	("LOC_TOOLTIP_THEMING_SAME_ERAS_REQ",							"Display Great Works of the same era"),
	("LOC_TOOLTIP_THEMING_ALL_FILLED_REQ",						"All slots are filled"),
	("LOC_TOOLTIP_THEMING_BONUS_TITLE",							  "Theming Bonus: "),
	("LOC_TOOLTIP_THEMING_YIELD_BONUS_TEXT",					"+{1_Amount}% Yields"),
	("LOC_TOOLTIP_THEMING_TOURISM_BONUS_TEXT",				"+{1_Amount}% [ICON_TOURISM] Tourism");

insert or replace into LocalizedText (Language, Tag, Text) values
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_COMMA_TEXT",                     "、"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_OR_TEXT",                        "或"),

  ("zh_Hans_CN", "LOC_TOOLTIP_HD_TRAITS_TEXT",                    "特点："),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_APPEAL_TEXT",                    "为相邻单元格{1_Amount: number +#,###.#;-#,###.#}魅力"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_TOURISM_FROM_YIELD_TEXT",        "提供等同于 {2_Icon} {3_Name}{1_ScalingFactor}%的 [ICON_TOURISM] 旅游业绩；需要{4_TechCivicName}"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_TOURISM_FROM_APPEAL_TEXT",       "提供等同于单元格魅力{1_ScalingFactor}%的 [ICON_TOURISM] 旅游业绩；需要{4_TechCivicName}"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_TOURISM_FROM_YIELD_NOREQ_TEXT",  "提供等同于 {2_Icon} {3_Name}{1_ScalingFactor}%的 [ICON_TOURISM] 旅游业绩"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_TOURISM_FROM_APPEAL_NOREQ_TEXT", "提供等同于单元格魅力{1_ScalingFactor}%的 [ICON_TOURISM] 旅游业绩"),

  ("zh_Hans_CN", "LOC_TOOLTIP_HD_CLASSIFICATIONS_TEXT",           "分类："),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_GENERAL_DISTRICT_TEXT",          "通用区域"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_UNIQUE_DISTRICT_TEXT",           "特色区域"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_REPLACE_DISTRICT_TEXT",          "特色区域（取代{1_Name}）"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_WORLD_WONDER_TEXT",              "世界奇观"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_NATIONAL_WONDER_TEXT",           "国家奇观"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_GENERAL_BUILDING_TEXT",          "通用建筑"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_UNIQUE_BUILDING_TEXT",           "特色建筑"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_REPLACE_BUILDING_TEXT",          "特色建筑（取代{1_Name}）"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_RESOURCE_CLASSIFICATIONS_TEXT",  "用途："),

  ("zh_Hans_CN", "LOC_TOOLTIP_HD_REQUIRES_TEXT",                  "需求："),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_TERRAIN_REQUIRES_TEXT",          "地形需求："),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_FEATURE_REQUIRES_TEXT",          "地貌需求："),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_COAST_DISTRICT_TEXT",            "与陆地相邻的浅海与湖泊单元格"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_REQUIRE_NOT_ADJACENT_TO_CITY",   "不能靠近市中心"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_MAX_PER_PLAY_TEXT",              "境内最多可建造{1_Amount}座"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_MUST_COAST_TEXT",                "必须相邻海洋"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_MUST_ADJACENT_LAND_TEXT",        "必须相邻陆地"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_MUST_SEA_TEXT",                  "必须建在浅海上"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_MUST_LAKE_TEXT",                 "必须建在湖泊上"),

  ("zh_Hans_CN", "LOC_TOOLTIP_HD_YIELD_CHANGES_TEXT",             "加产节点："),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_BASIC_YIELDS_TEXT",              "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName}"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_YIELD_CHANGES_REQUIRES_TEXT",    "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName}；需要{4_Name}"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_YIELD_FROM_APPEAL_TEXT",         "提供等同于单元格魅力{1_ScalingFactor}%的 {2_Icon} {3_Name}"),

  ("zh_Hans_CN", "LOC_TOOLTIP_HD_ADJACENCIES_TEXT",               "相邻加成："),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_ADJACENCIES_SELF_TEXT",          "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName}，来自自身特质"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_ADJACENCIES_RIVER_TEXT",         "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName}，来自相邻河流"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_ADJACENCIES_OBJECT_TEXT",        "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName}，来自每个相邻{5_AdjacentObject}"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_ADJACENCIES_OBJECT_PER_TEXT",    "{1_Amount: number +#,###.#;-#,###.#} {2_YieldIcon} {3_YieldName}，来自每{4_Count}个相邻{5_AdjacentObject}"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_ADJACENCIES_REQUIRES_TEXT",      "；需要{1_Name}"),
  ("zh_Hans_CN", "LOC_TOOLTIP_HD_ADJACENCIES_OBSOLETE_TEXT",      "；{1_Name}后失效"),
  ("zh_Hans_CN", "LOC_TYPE_TRAIT_ADJACENT_OBJECT_SEA_RESOURCE",   "水域资源"),

  ("zh_Hans_CN", "LOC_TOOLTIP_HD_IMPROVEMENT_UNIT_TEXT",          "改良单位："),

  ("zh_Hans_CN", "LOC_TOOLTIP_COST_PROGRESSION_PARAM",						"涨价系数：{1_num}"),
  ("zh_Hans_CN", "LOC_TOOLTIP_ACTUAL_COST_TEXT",						      "实际花费：{1_Num} {2_Icon} {3_Name}"),

	("zh_Hans_CN", "LOC_TOOLTIP_BUILDING_CITIZEN_YIELDS_HEADER",		"专家收益变动："),
	("zh_Hans_CN", "LOC_TOOLTIP_DISTRICT_CITIZEN_YIELDS_HEADER",		"专家收益："),

	("zh_Hans_CN", "LOC_TOOLTIP_RESOURCE_IMPROVED_BY",							"改良设施："),
	("zh_Hans_CN", "LOC_TOOLTIP_RESOURCE_CORP_CATEGORY",						"行业与公司："),

	("zh_Hans_CN", "LOC_TOOLTIP_REGIONAL_EFFECT_RANGE",						  "{1_num}环辐射：此奇观的基础产出延伸到{1_num}个单元格内的其它城市。"),
	("zh_Hans_CN", "LOC_TOOLTIP_REGIONAL_EFFECT_RANGE_MODIFIER",		"{1_num}环辐射：拥有在此建筑{1_num}个单元格内的市中心或社区的城市获得以下加成，但不包括已经从相同建筑获得过此加成的城市："),
	("zh_Hans_CN", "LOC_TOOLTIP_REGIONAL_EFFECT_REQ",							  "（需要{1_TechOrCivicName}）"),

  ("zh_Hans_CN", "LOC_TOOLTIP_GREATWORK_SOLT_TEXT",							  "巨作槽位："),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_REQ_TITLE",							    "主题化条件："),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_UNIQUE_PERSON_REQ",					"展示不同作者的巨作"),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_UNIQUE_PRODUCT_REQ",				"展示不同类别的 [ICON_GreatWork_Product] 产品"),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_UNIQUE_CIVS_REQ",					  "展示不同文明的巨作"),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_SAME_OBJECT_TYPE_REQ",			"展示相同类型的巨作"),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_SAME_ERAS_REQ",							"展示相同时代的巨作"),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_ALL_FILLED_REQ",						"填满所有槽位"),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_BONUS_TITLE",							  "主题化收益："),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_YIELD_BONUS_TEXT",					"+{1_Amount}%产出"),
	("zh_Hans_CN", "LOC_TOOLTIP_THEMING_TOURISM_BONUS_TEXT",				"+{1_Amount}% [ICON_TOURISM] 旅游业绩");