--- Language: en_US
insert or replace into EnglishText
  (Tag,                                                     Text)
values
  ("LOC_LEADER_CATHERINE_DE_MEDICI_ALT_NAME", "Catherine de Medici (Magnificences)"),
  ("LOC_TRAIT_LEADER_MAGNIFICENCES_NAME", "Masquerade Ball"),
  ("LOC_TRAIT_LEADER_MAGNIFICENCES_DESCRIPTION", "If a city has improved luxury resources, units produced gain +1 [ICON_MOVEMENT] Movement. Each time a wonder is constructed, gain 2 copies of the corresponding luxury resource. Can undertake the 'Court Festival' project in any city with a Theater Square."),
  ("LOC_ABILITY_CITY_HAS_LUXURY_TRAIN_UNIT_MOVEMENT_DESCRIPTION", "{LOC_TRAIT_LEADER_MAGNIFICENCES_NAME}: Permanently grants +1 [ICON_MOVEMENT] Movement."),
  ("LOC_PROJECT_COURT_FESTIVAL_HD_DESCRIPTION", "Upon completion of this project: All Château Estates gain +1 [ICON_CULTURE] Culture; this city can construct one additional Château Estate; for each surplus luxury resource, gain 10 [ICON_CULTURE] Culture and 10 [ICON_TOURISM] Tourism."),

  ("LOC_RESOURCE_HD_BUILDING_BAMYAN_NAME", "Karakul Sheep"),
  ("LOC_RESOURCE_HD_BUILDING_BURJ_KHALIFA_NAME", "Arabic Gum"),
  ("LOC_RESOURCE_HD_BUILDING_KILWA_KISIWANI_NAME", "Frankincense"),
  ("LOC_RESOURCE_HD_BUILDING_HUEY_TEOCALLI_NAME", "Cochineal"),
  ("LOC_RESOURCE_HD_BUILDING_PYRAMIDS_NAME", "Fennel"),
  ("LOC_RESOURCE_HD_BUILDING_GREAT_LIGHTHOUSE_NAME", "Coriander"),
  ("LOC_RESOURCE_HD_BUILDING_GREAT_LIBRARY_NAME", "Nile Tilapia"),
  ("LOC_RESOURCE_HD_BUILDING_ABU_SIMBEL_NAME", "Long-Staple Cotton"),
  ("LOC_RESOURCE_HD_BUILDING_SYDNEY_OPERA_HOUSE_NAME", "Macadamia"),
  ("LOC_RESOURCE_HD_BUILDING_HANGING_GARDENS_NAME", "Garlic"),
  ("LOC_RESOURCE_HD_BUILDING_ETEMENANKI_NAME", "Onion"),
  ("LOC_RESOURCE_HD_BUILDING_PANAMA_CANAL_NAME", "Palm Oil"),
  ("LOC_RESOURCE_HD_BUILDING_CRISTO_REDENTOR_NAME", "Açaí Berry"),
  ("LOC_RESOURCE_HD_BUILDING_ESTADIO_DO_MARACANA_NAME", "Brazil Nut"),
  ("LOC_RESOURCE_HD_BUILDING_HAGIA_SOPHIA_NAME", "Ankara Sheep"),
  ("LOC_RESOURCE_HD_BUILDING_APADANA_NAME", "Pistachio"),
  ("LOC_RESOURCE_HD_BUILDING_HALICARNASSUS_MAUSOLEUM_NAME", "Persian Carpet"),
  ("LOC_RESOURCE_HD_BUILDING_RUHR_VALLEY_NAME", "Hops"),
  ("LOC_RESOURCE_HD_BUILDING_NEUSCHWANSTEIN_NAME", "Rye"),
  ("LOC_RESOURCE_HD_BUILDING_BRANDENBURG_GATE_NAME", "European Catfish"),
  ("LOC_RESOURCE_HD_BUILDING_BOLSHOI_THEATRE_NAME", "Amethyst"),
  ("LOC_RESOURCE_HD_BUILDING_HERMITAGE_NAME", "King Crab"),
  ("LOC_RESOURCE_HD_BUILDING_ST_BASILS_CATHEDRAL_NAME", "Emerald"),
  ("LOC_RESOURCE_HD_BUILDING_MOTHERLAND_CALLS_NAME", "Kefir"),
  ("LOC_RESOURCE_HD_BUILDING_MONT_ST_MICHEL_NAME", "Foie Gras"),
  ("LOC_RESOURCE_HD_BUILDING_EIFFEL_TOWER_NAME", "Lavender"),
  ("LOC_RESOURCE_HD_BUILDING_SUK_NOTRE_DAME_DE_PARIS_NAME", "Oyster"),
  ("LOC_RESOURCE_HD_BUILDING_AL_STPETERSBASILICA_NAME", "Unleavened Bread"),
  ("LOC_RESOURCE_HD_BUILDING_ANGKOR_WAT_NAME", "Garcinia"),
  ("LOC_RESOURCE_HD_CL_BUILDING_CN_TOWER_NAME", "Canola"),
  ("LOC_RESOURCE_HD_BUILDING_GREAT_ZIMBABWE_NAME", "Crocodile"),
  ("LOC_RESOURCE_HD_BUILDING_UNIVERSITY_SANKORE_NAME", "Shea Butter"),
  ("LOC_RESOURCE_HD_BUILDING_CHICHEN_ITZA_NAME", "Scarlet Macaw"),
  ("LOC_RESOURCE_HD_BUILDING_BROADWAY_NAME", "Cola"),
  ("LOC_RESOURCE_HD_BUILDING_STATUE_LIBERTY_NAME", "Bald Eagle"),
  ("LOC_RESOURCE_HD_BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION_NAME", "Cranberry"),
  ("LOC_RESOURCE_HD_BUILDING_GOLDEN_GATE_BRIDGE_NAME", "Almond"),
  ("LOC_RESOURCE_HD_BUILDING_BIOSPHERE_NAME", "Colonel's Chicken Nuggets"),
  ("LOC_RESOURCE_HD_WON_CL_BUILDING_ARECIBO_NAME", "Thanksgiving Turkey"),
  ("LOC_RESOURCE_HD_WON_CL_EMPIRE_STATES_NAME", "Cherry"),
  ("LOC_RESOURCE_HD_BUILDING_JEBEL_BARKAL_NAME", "Agate"),
  ("LOC_RESOURCE_HD_BUILDING_TORRE_DE_BELEM_NAME", "Cork"),
  ("LOC_RESOURCE_HD_BUILDING_ITSUKUSHIMA_NAME", "Wagyu Beef"),
  ("LOC_RESOURCE_HD_BUILDING_KOTOKU_IN_NAME", "Winter Yellowtail"),
  ("LOC_RESOURCE_HD_WON_CL_KINKAKU_NAME", "Red Fuji Apple"),
  ("LOC_RESOURCE_HD_BUILDING_SUK_WAT_ARUN_NAME", "Mangosteen"),
  ("LOC_RESOURCE_HD_BUILDING_VENETIAN_ARSENAL_NAME", "Squid Ink"),
  ("LOC_RESOURCE_HD_BUILDING_ALHAMBRA_NAME", "Iberian Ham"),
  ("LOC_RESOURCE_HD_BUILDING_CASA_DE_CONTRATACION_NAME", "Guitar"),
  ("LOC_RESOURCE_HD_BUILDING_ORACLE_NAME", "Oregano"),
  ("LOC_RESOURCE_HD_BUILDING_COLOSSUS_NAME", "Thyme"),
  ("LOC_RESOURCE_HD_BUILDING_TEMPLE_ARTEMIS_NAME", "Greek Yogurt"),
  ("LOC_RESOURCE_HD_BUILDING_STATUE_OF_ZEUS_NAME", "Fig"),
  ("LOC_RESOURCE_HD_P0K_BUILDING_TEMPLE_POSEIDON_NAME", "Octopus"),
  ("LOC_RESOURCE_HD_BUILDING_ORSZAGHAZ_NAME", "Paprika"),
  ("LOC_RESOURCE_HD_BUILDING_COLOSSEUM_NAME", "Pasta"),
  ("LOC_RESOURCE_HD_BUILDING_LEANING_TOWER_NAME", "Bluefin Tuna"),
  ("LOC_RESOURCE_HD_BUILDING_UFFIZI_NAME", "Sardine"),
  ("LOC_RESOURCE_HD_BUILDING_MAHABODHI_TEMPLE_NAME", "Pepper"),
  ("LOC_RESOURCE_HD_BUILDING_TAJ_MAHAL_NAME", "Turmeric"),
  ("LOC_RESOURCE_HD_BUILDING_GREAT_BATH_NAME", "Rosewood"),
  ("LOC_RESOURCE_HD_BUILDING_MEENAKSHI_TEMPLE_NAME", "Cardamom"),
  ("LOC_RESOURCE_HD_BUILDING_BOROBUDUR_NAME", "Durian"),
  ("LOC_RESOURCE_HD_BUILDING_MACHU_PICCHU_NAME", "Llama"),
  ("LOC_RESOURCE_HD_BUILDING_STONEHENGE_NAME", "Stargazy Pie"),
  ("LOC_RESOURCE_HD_BUILDING_OXFORD_UNIVERSITY_NAME", "Black Pudding"),
  ("LOC_RESOURCE_HD_BUILDING_BIG_BEN_NAME", "Scone"),
  ("LOC_RESOURCE_HD_BUILDING_TOWER_BRIDGE_NAME", "Scottish Highland Cattle"),
  ("LOC_RESOURCE_HD_BUILDING_GLOBE_THEATRE_NAME", "Blue Cheese"),
  ("LOC_RESOURCE_HD_BUILDING_PETRA_NAME", "Myrrh"),
  ("LOC_RESOURCE_HD_BUILDING_TERRACOTTA_ARMY_NAME", "Yew"),
  ("LOC_RESOURCE_HD_BUILDING_FORBIDDEN_CITY_NAME", "Ginseng"),
  ("LOC_RESOURCE_HD_BUILDING_POTALA_PALACE_NAME", "Goji Berry"),
  ("LOC_RESOURCE_HD_BUILDING_PORCELAIN_TOWER_NAME", "Sea Cucumber"),
  ("LOC_RESOURCE_HD_BUILDING_TEMPLE_OF_HEAVEN_NAME", "Musk"),
  ("LOC_RESOURCE_HD_BUILDING_PHANTA_BRONZE_BIRD_TERRACE_NAME", "Shrimp"),
  ("LOC_RESOURCE_HD_BUILDING_THREE_GORDES_DAM_NAME", "Cordyceps"),
  ("LOC_RESOURCE_HD_BUILDING_YELLOW_CRANE_HD_NAME", "Lychee");


insert or replace into LocalizedText
  (Language,      Tag,                                                              Text)
values
  ("zh_Hans_CN",  "LOC_LEADER_CATHERINE_DE_MEDICI_ALT_NAME",                        "凯瑟琳·德·美第奇（金碧辉煌）"),
  ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MAGNIFICENCES_NAME",                            "假面舞会"),
  ("zh_Hans_CN",  "LOC_TRAIT_LEADER_MAGNIFICENCES_DESCRIPTION",                     "如果城市拥有改良的奢侈资源，生产的单位+1 [ICON_MOVEMENT] 移动力。每建造一座奇观，获得2份该奇观对应的特色奢侈资源。可在拥有剧院广场区域的任意城市中开展“宫廷盛会”项目。"),
  ("zh_Hans_CN",  "LOC_ABILITY_CITY_HAS_LUXURY_TRAIN_UNIT_MOVEMENT_DESCRIPTION",    "{LOC_TRAIT_LEADER_MAGNIFICENCES_NAME}：永久+1 [ICON_Movement] 移动力。"),
  ("zh_Hans_CN",  "LOC_PROJECT_COURT_FESTIVAL_HD_DESCRIPTION",                      "此项目完成时：所有城堡庄园+1 [ICON_CULTURE] 文化值；本城可以额外建造一座城堡庄园；每拥有一个多余的奢侈品资源，提供10点 [ICON_CULTURE] 文化值和10点 [ICON_TOURISM] 旅游业绩。"),

  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_BAMYAN_NAME",                           "卡拉库尔羊"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_BURJ_KHALIFA_NAME",                     "阿拉伯胶"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_KILWA_KISIWANI_NAME",                   "乳香"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_HUEY_TEOCALLI_NAME",                    "胭脂虫"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_PYRAMIDS_NAME",                         "茴香"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_GREAT_LIGHTHOUSE_NAME",                 "芫荽"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_GREAT_LIBRARY_NAME",                    "尼罗罗非鱼"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_ABU_SIMBEL_NAME",                       "长绒棉"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_SYDNEY_OPERA_HOUSE_NAME",               "夏威夷果"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_HANGING_GARDENS_NAME",                  "大蒜"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_ETEMENANKI_NAME",                       "洋葱"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_PANAMA_CANAL_NAME",                     "棕榈油"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_CRISTO_REDENTOR_NAME",                  "阿萨伊浆果"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_ESTADIO_DO_MARACANA_NAME",              "巴西栗"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_HAGIA_SOPHIA_NAME",                     "安卡拉羊"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_APADANA_NAME",                          "开心果"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_HALICARNASSUS_MAUSOLEUM_NAME",          "波斯地毯"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_RUHR_VALLEY_NAME",                      "啤酒花"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_NEUSCHWANSTEIN_NAME",                   "黑麦"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_BRANDENBURG_GATE_NAME",                 "欧鲇"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_BOLSHOI_THEATRE_NAME",                  "紫金"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_HERMITAGE_NAME",                        "帝王蟹"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_ST_BASILS_CATHEDRAL_NAME",              "祖母绿"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_MOTHERLAND_CALLS_NAME",                 "开菲尔酸奶"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_MONT_ST_MICHEL_NAME",                   "鹅肝"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_EIFFEL_TOWER_NAME",                     "薰衣草"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_SUK_NOTRE_DAME_DE_PARIS_NAME",          "牡蛎"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_AL_STPETERSBASILICA_NAME",              "无酵饼"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_ANGKOR_WAT_NAME",                       "藤黄果"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_CL_BUILDING_CN_TOWER_NAME",                      "油菜籽"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_GREAT_ZIMBABWE_NAME",                   "鳄鱼"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_UNIVERSITY_SANKORE_NAME",               "乳木果"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_CHICHEN_ITZA_NAME",                     "金刚鹦鹉"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_BROADWAY_NAME",                         "可乐"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_STATUE_LIBERTY_NAME",                   "白头海雕"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION_NAME",  "蔓越莓"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_GOLDEN_GATE_BRIDGE_NAME",               "杏仁"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_BIOSPHERE_NAME",                        "上校鸡块"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_WON_CL_BUILDING_ARECIBO_NAME",                   "感恩节火鸡"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_WON_CL_EMPIRE_STATES_NAME",                      "车厘子"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_JEBEL_BARKAL_NAME",                     "玛瑙"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_TORRE_DE_BELEM_NAME",                   "软木"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_ITSUKUSHIMA_NAME",                      "和牛"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_KOTOKU_IN_NAME",                        "寒鰤"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_WON_CL_KINKAKU_NAME",                            "红富士"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_SUK_WAT_ARUN_NAME",                     "山竹"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_VENETIAN_ARSENAL_NAME",                 "墨鱼汁"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_ALHAMBRA_NAME",                         "伊比利亚火腿"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_CASA_DE_CONTRATACION_NAME",             "吉他"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_ORACLE_NAME",                           "牛至"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_COLOSSUS_NAME",                         "百里香"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_TEMPLE_ARTEMIS_NAME",                   "希腊酸奶"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_STATUE_OF_ZEUS_NAME",                   "无花果"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_P0K_BUILDING_TEMPLE_POSEIDON_NAME",              "章鱼"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_ORSZAGHAZ_NAME",                        "红椒粉"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_COLOSSEUM_NAME",                        "意大利面"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_LEANING_TOWER_NAME",                    "蓝鳍金枪鱼"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_UFFIZI_NAME",                           "沙丁鱼"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_MAHABODHI_TEMPLE_NAME",                 "胡椒"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_TAJ_MAHAL_NAME",                        "姜黄"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_GREAT_BATH_NAME",                       "紫檀"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_MEENAKSHI_TEMPLE_NAME",                 "小豆蔻"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_BOROBUDUR_NAME",                        "榴梿"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_MACHU_PICCHU_NAME",                     "骆马"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_STONEHENGE_NAME",                       "仰望星空派"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_OXFORD_UNIVERSITY_NAME",                "黑布丁"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_BIG_BEN_NAME",                          "司康饼"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_TOWER_BRIDGE_NAME",                     "苏格兰高地牛"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_GLOBE_THEATRE_NAME",                    "蓝纹奶酪"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_PETRA_NAME",                            "没药"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_TERRACOTTA_ARMY_NAME",                  "红豆杉"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_FORBIDDEN_CITY_NAME",                   "人参"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_POTALA_PALACE_NAME",                    "枸杞"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_PORCELAIN_TOWER_NAME",                  "海参"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_TEMPLE_OF_HEAVEN_NAME",                 "麝香"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_PHANTA_BRONZE_BIRD_TERRACE_NAME",       "对虾"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_THREE_GORDES_DAM_NAME",                 "冬虫夏草"),
  ("zh_Hans_CN",  "LOC_RESOURCE_HD_BUILDING_YELLOW_CRANE_HD_NAME",                  "荔枝");