-- Language: en_US
insert or replace into EnglishText
    (Tag,                                                                       Text)
values
    ("LOC_UNIT_ORAL_SCHOLAR_NAME",                                              "Oral Scholar"),
    ("LOC_UNIT_TRAVEL_THEATRE_NAME",                                            "Travel Theatre"),
    ("LOC_UNIT_ORAL_SCHOLAR_DESCRIPTION",                                       "Oral Scholar"),
    ("LOC_UNIT_TRAVEL_THEATRE_DESCRIPTION",                                     "Travel Theatre"),
    ("LOC_PROMOTION_MYSTICISM_HD_NAME",                                         "Mysticism"),
    ("LOC_PROMOTION_CLASSICISM_HD_NAME",                                        "Classicism"),
    ("LOC_PROMOTION_ROMANTICISM_HD_NAME",                                       "Romanticism"),
--    ("LOC_PROMOTION_HEDONISM_HD_NAME",                                          "Hedonism"),
    ("LOC_PROMOTION_REALISM_HD_NAME",                                           "Realism"),
    ("LOC_PROMOTION_ACADEMISM_HD_NAME",                                         "Academism"),
    ("LOC_PROMOTION_POPULARISM_HD_NAME",                                        "Popularism"),
    ("LOC_PROMOTION_PLURALISM_HD_NAME",                                         "Pluralism"),
    ("LOC_PROMOTION_FISHER_SONG_HD_NAME",                                       "Fisher Song"),

	("LOC_PROMOTION_MYSTICISM_PRE_HD_NAME",                                     "Mysticism"),
    ("LOC_PROMOTION_CLASSICISM_PRE_HD_NAME",                                    "Classicism"),
    ("LOC_PROMOTION_ROMANTICISM_PRE_HD_NAME",                                   "Romanticism"),
    ("LOC_PROMOTION_REALISM_PRE_HD_NAME",                                       "Realism"),
    ("LOC_PROMOTION_ACADEMISM_PRE_HD_NAME",                                     "Academism"),
    ("LOC_PROMOTION_POPULARISM_PRE_HD_NAME",                                    "Popularism"),
    ("LOC_PROMOTION_PLURALISM_PRE_HD_NAME",                                     "Pluralism"),
    ("LOC_PROMOTION_FISHER_SONG_PRE_HD_NAME",                                   "Fisher Song"),

    ("LOC_PROMOTION_GLEEMAN_HD_NAME",                                           "Gleeman"),
    ("LOC_PROMOTION_URBAN_OPERA_HD_NAME",                                       "Urban Opera"),
    ("LOC_PROMOTION_PAN_POLITICALIZATION_HD_NAME",                              "Pan Politicalization"),
    ("LOC_PROMOTION_WELL_KNOWN_HD_NAME",                                        "Well Known"),
    ("LOC_PROMOTION_MYSTICISM_HD_DESCRIPTION",                                  "Siu"),
    ("LOC_PROMOTION_CLASSICISM_HD_DESCRIPTION",                                 "Siu"),
    ("LOC_PROMOTION_ROMANTICISM_HD_DESCRIPTION",                                "oral scholar"),
--    ("LOC_PROMOTION_HEDONISM_HD_DESCRIPTION",                                   "oral scholar"),
    ("LOC_PROMOTION_REALISM_HD_DESCRIPTION",                                    "oral scholar"),
    ("LOC_PROMOTION_ACADEMISM_HD_DESCRIPTION",                                  "oral scholar"),
    ("LOC_PROMOTION_POPULARISM_HD_DESCRIPTION",                                 "oral scholar"),
    ("LOC_PROMOTION_PLURALISM_HD_DESCRIPTION",                                  "oral scholar"),
    ("LOC_PROMOTION_FISHER_SONG_HD_DESCRIPTION",                                "oral scholar"),
    ("LOC_PROMOTION_GLEEMAN_HD_DESCRIPTION",                                    "oral scholar"),
    ("LOC_PROMOTION_URBAN_OPERA_HD_DESCRIPTION",                                "oral scholar"),
    ("LOC_PROMOTION_PAN_POLITICALIZATION_HD_DESCRIPTION",                       "oral scholar"),
    ("LOC_PROMOTION_WELL_KNOWN_HD_DESCRIPTION",                                 "oral scholar"),
    ("LOC_RESULT_LEGENDS_OF_ROCK_DESCRIPTION",                                  "All the words that I utter，And all the words that I write, Must spread out their wings untiring, And never rest in their flight. (Your unit grants promotion)"),
    ("LOC_RESULT_HEADLINERS_DESCRIPTION",                                       "I wander on, and wave my hands, And sing, and shake my heavy locks.(Your unit grants promotion)"),
    ("LOC_RESULT_RISING_STARS_DESCRIPTION",                                     "The Almighty has three gifts to give: poetry, dance, and truth."),
    ("LOC_RESULT_OPENING_ACT_DESCRIPTION",                                      "We make out of the quarrel with others, rhetoric, but of the quarrel with ourselves, poetry."),
    ("LOC_RESULT_CREATIVE_DIFFERENCES_DESCRIPTION",                             "Cast a cold eye, On life, on death. Horseman, pass by!"),
    ("LOC_RESULT_AGING_ROCKERS_DESCRIPTION",                                    "Though the great song return no more There's keen delight in what we have: The rattle of pebbles on the shore Under the receding wave. (Your unit has dissolved)"),
    ("LOC_RESULT_LEGENDS_NEVER_DIE_DESCRIPTION",                                "Hearts are not had as a gift but hearts are earned. (Your unit has dissolved)"),
    ("LOC_NOTIFICATION_ROCK_BANDS_PROHIBITED_SUMMARY",                          "{LOC_GRAMMAR_LEADER_UPPER &lt;&lt; {1_leader}} {1_leader: plural 1?is; other?are;} now prohibiting foreign culture. Your Cultural Communicators inside their empire have been displaced to a tile just outside their lands.");

-- Language: zh_Hans_CN
insert or replace into LocalizedText
    (Language,      Tag,                                                                        Text)
values
    ("zh_Hans_CN",  "LOC_UNIT_ORAL_SCHOLAR_NAME",                                               "口述学者"),
    ("zh_Hans_CN",  "LOC_UNIT_TRAVEL_THEATRE_NAME",                                             "旅行剧团"),
    ("zh_Hans_CN",  "LOC_UNIT_ORAL_SCHOLAR_DESCRIPTION",                                        "古典时期文化传播单位"),
    ("zh_Hans_CN",  "LOC_UNIT_TRAVEL_THEATRE_DESCRIPTION",                                      "文艺复兴时期文化传播单位"),
    ("zh_Hans_CN",  "LOC_PROMOTION_MYSTICISM_HD_NAME",                                          "神秘主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_CLASSICISM_HD_NAME",                                         "古典主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_ROMANTICISM_HD_NAME",                                        "浪漫主义"),
--    ("zh_Hans_CN",  "LOC_PROMOTION_HEDONISM_HD_NAME",                                           "享乐主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_REALISM_HD_NAME",                                            "现实主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_ACADEMISM_HD_NAME",                                          "学院主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_POPULARISM_HD_NAME",                                         "通俗主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_PLURALISM_HD_NAME",                                          "普罗主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_FISHER_SONG_HD_NAME",                                        "渔歌船号"),

    ("zh_Hans_CN",  "LOC_PROMOTION_MYSTICISM_PRE_HD_NAME",                                      "神秘主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_CLASSICISM_PRE_HD_NAME",                                     "古典主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_ROMANTICISM_PRE_HD_NAME",                                    "浪漫主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_REALISM_PRE_HD_NAME",                                        "现实主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_ACADEMISM_PRE_HD_NAME",                                      "学院主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_POPULARISM_PRE_HD_NAME",                                     "通俗主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_PLURALISM_PRE_HD_NAME",                                      "普罗主义"),
    ("zh_Hans_CN",  "LOC_PROMOTION_FISHER_SONG_PRE_HD_NAME",                                    "渔歌船号"),

    ("zh_Hans_CN",  "LOC_PROMOTION_GLEEMAN_HD_NAME",                                            "流浪诗人"),
    ("zh_Hans_CN",  "LOC_PROMOTION_URBAN_OPERA_HD_NAME",                                        "瓦市勾栏"),
    ("zh_Hans_CN",  "LOC_PROMOTION_PAN_POLITICALIZATION_HD_NAME",                               "泛政治化"),
    ("zh_Hans_CN",  "LOC_PROMOTION_WELL_KNOWN_HD_NAME",                                         "闻名遐迩"),
    ("zh_Hans_CN",  "LOC_PROMOTION_MYSTICISM_HD_DESCRIPTION",                                   "在奇观、自然奇观和国家公园中的表演提升一个等级,在圣地中的表演提升一个等级"),
    ("zh_Hans_CN",  "LOC_PROMOTION_CLASSICISM_HD_DESCRIPTION",                                  "在剧院中的表演提升两个等级"),
    ("zh_Hans_CN",  "LOC_PROMOTION_ROMANTICISM_HD_DESCRIPTION",                                 "在娱乐区、水上乐园和海滨度假区中的表演提升两个等级"),
--    ("zh_Hans_CN",  "LOC_PROMOTION_HEDONISM_HD_DESCRIPTION",                                    "在水上乐园和海滨度假区的表演提升两个等级"),
    ("zh_Hans_CN",  "LOC_PROMOTION_REALISM_HD_DESCRIPTION",                                     "在社区中的表演提升两个等级"),
    ("zh_Hans_CN",  "LOC_PROMOTION_ACADEMISM_HD_DESCRIPTION",                                   "在学院中的表演提升两个等级"),
    ("zh_Hans_CN",  "LOC_PROMOTION_POPULARISM_HD_DESCRIPTION",                                  "在商业中心中的表演提升两个等级"),
    ("zh_Hans_CN",  "LOC_PROMOTION_PLURALISM_HD_DESCRIPTION",                                   "在工业区中的表演提升两个等级"),
    ("zh_Hans_CN",  "LOC_PROMOTION_FISHER_SONG_HD_DESCRIPTION",                                 "在港口中的表演提升两个等级"),

	("zh_Hans_CN",  "LOC_PROMOTION_MYSTICISM_PRE_HD_DESCRIPTION",                               "允许在自然奇观、国家公园和无建筑的圣地中表演"),
    ("zh_Hans_CN",  "LOC_PROMOTION_CLASSICISM_PRE_HD_DESCRIPTION",                              "允许在无建筑的剧院中表演"),
    ("zh_Hans_CN",  "LOC_PROMOTION_ROMANTICISM_PRE_HD_DESCRIPTION",                             "允许在无建筑的娱乐区、水上乐园和海滨度假区中表演"),
    ("zh_Hans_CN",  "LOC_PROMOTION_REALISM_PRE_HD_DESCRIPTION",                                 "允许在农田、营地和无建筑社区中表演"),
    ("zh_Hans_CN",  "LOC_PROMOTION_ACADEMISM_PRE_HD_DESCRIPTION",                               "允许在无建筑的学院中表演"),
    ("zh_Hans_CN",  "LOC_PROMOTION_POPULARISM_PRE_HD_DESCRIPTION",                              "允许在无建筑的商业中心中表演"),
    ("zh_Hans_CN",  "LOC_PROMOTION_PLURALISM_PRE_HD_DESCRIPTION",                               "允许在无建筑的工业区中表演"),
    ("zh_Hans_CN",  "LOC_PROMOTION_FISHER_SONG_PRE_HD_DESCRIPTION",                             "允许在无建筑的港口中表演"),

    ("zh_Hans_CN",  "LOC_PROMOTION_GLEEMAN_HD_DESCRIPTION",                                     "+4移动力，无视河流及地形"),
    ("zh_Hans_CN",  "LOC_PROMOTION_URBAN_OPERA_HD_DESCRIPTION",                                 "演出后获得等同于产出旅游业绩60%的金币"),
    ("zh_Hans_CN",  "LOC_PROMOTION_PAN_POLITICALIZATION_HD_DESCRIPTION",                        "演出将使所在城市失去50忠诚度"),
    ("zh_Hans_CN",  "LOC_PROMOTION_WELL_KNOWN_HD_DESCRIPTION",                                  "十二个单元格内的其他文明将获得50%的业绩"),
    ("zh_Hans_CN",  "LOC_RESULT_LEGENDS_OF_ROCK_DESCRIPTION",                                   "昆山玉碎凤凰叫，芙蓉泣露香兰笑。十二门前融冷光，二十三丝动紫皇。（您的单位获得了晋升）"),
    ("zh_Hans_CN",  "LOC_RESULT_HEADLINERS_DESCRIPTION",                                        "髣髴兮若轻云之蔽月，飘飖兮若流风之回雪。（您的单位获得了晋升）"),
    ("zh_Hans_CN",  "LOC_RESULT_RISING_STARS_DESCRIPTION",                                      "此曲只应天上有，人间能得几回闻。"),
    ("zh_Hans_CN",  "LOC_RESULT_OPENING_ACT_DESCRIPTION",                                       "空山百鸟散还合，万里浮云阴且晴。"),
    ("zh_Hans_CN",  "LOC_RESULT_CREATIVE_DIFFERENCES_DESCRIPTION",                              "舞低杨柳楼心月，歌尽桃花扇底风。"),
    ("zh_Hans_CN",  "LOC_RESULT_AGING_ROCKERS_DESCRIPTION",                                     "泪眼问花花不语，乱红飞过秋千去。（您的单位已解散）"),
    ("zh_Hans_CN",  "LOC_RESULT_LEGENDS_NEVER_DIE_DESCRIPTION",                                 "商女不知亡国恨，隔江犹唱后庭花。（您的单位已解散）"),
    ("zh_Hans_CN",  "LOC_ABILITY_ORAL_SCHOLAR_BOMB_ALL_HD_DESCRIPTION",                         "相邻文化传播单位在处于和平状态的文明中旅游业绩产出提高4%"),
    ("zh_Hans_CN",  "LOC_ABILITY_TRAVEL_THEATRE_BOMB_ALL_HD_DESCRIPTION",                       "相邻文化传播单位在处于和平状态的文明中旅游业绩产出提高8%"),
    ("zh_Hans_CN",  "LOC_ABILITY_ROCK_BAND_BOMB_ALL_HD_DESCRIPTION",                            "相邻文化传播单位在处于和平状态的文明中旅游业绩产出提高20%"),
    ("zh_Hans_CN",  "LOC_ABILITY_ROCK_BASIC_YIELD_HD_DESCRIPTION",                              "文化传播单位表演获得1% [ICON_GOLD] 和1% [ICON_CULTURE]"),
    ("zh_Hans_CN",  "LOC_ABILITY_ALL_LAND_UNITS_GREAT_PEOPLE_POINTS_HD_DESCRIPTION",            "陆地单位击杀主要和小型文明的单位时，将获得量等同于对方单位战斗力25%的 [ICON_GREATGENERAL] 大将军点数"),
    ("zh_Hans_CN",  "LOC_ABILITY_ALL_NAVAL_UNITS_GREAT_PEOPLE_POINTS_HD_DESCRIPTION",           "海军单位击杀主要和小型文明的单位时，将获得量等同于对方单位战斗力25%的 [ICON_GREATADMIRAL] 海军统帅点数"),
    ("zh_Hans_CN",  "LOC_RESULT_LEGENDS_OF_ROCK_NAME",                                          "天籁之音"),
    ("zh_Hans_CN",  "LOC_RESULT_HEADLINERS_NAME",                                               "家喻户晓"),
    ("zh_Hans_CN",  "LOC_RESULT_RISING_STARS_NAME",                                             "万众瞩目"),
    ("zh_Hans_CN",  "LOC_RESULT_OPENING_ACT_NAME",                                              "观者如市"),
    ("zh_Hans_CN",  "LOC_RESULT_CREATIVE_DIFFERENCES_NAME",                                     "小有所成"),
    ("zh_Hans_CN",  "LOC_RESULT_AGING_ROCKERS_NAME",                                            "门可罗雀"),
    ("zh_Hans_CN",  "LOC_RESULT_LEGENDS_NEVER_DIE_NAME",                                        "声名扫地"),
    ("zh_Hans_CN",  "LOC_RESULT_LEGENDS_OF_ROCK_TIER",                                          "七星表演"),
    ("zh_Hans_CN",  "LOC_RESULT_HEADLINERS_TIER",                                               "六星表演"),
    ("zh_Hans_CN",  "LOC_RESULT_RISING_STARS_TIER",                                             "五星表演"),
    ("zh_Hans_CN",  "LOC_RESULT_OPENING_ACT_TIER",                                              "四星表演"),
    ("zh_Hans_CN",  "LOC_RESULT_CREATIVE_DIFFERENCES_TIER",                                     "三星表演"),
    ("zh_Hans_CN",  "LOC_RESULT_AGING_ROCKERS_TIER",                                            "二星表演"),
    ("zh_Hans_CN",  "LOC_RESULT_LEGENDS_NEVER_DIE_TIER",                                        "一星表演"),
    ("zh_Hans_CN",  "LOC_ROCK_CONCERT_RESULT_ALBUMS",                                           "作品数量"),
    ("zh_Hans_CN",  "LOC_HUD_UNIT_PANEL_ROCK_BAND_ALBUM_SALES",                                 "作品数量"),
    ("zh_Hans_CN",  "LOC_UNIT_MALI_GRIOTS_NAME",                                                "杰利"),
    ("zh_Hans_CN",  "LOC_UNIT_MALI_GRIOTS_DESCRIPTION",                                         "马里古典时代特色单位，取代口述学者。表演拥有25额外基础业绩并获得3% [ICON_GOLD] "),
    ("zh_Hans_CN",  "LOC_ABILITY_MALI_GRIOTS_BASIC_YIELD_HD_DESCRIPTION",                       "表演拥有25额外基础业绩并获得3% [ICON_GOLD] "),
    ("zh_Hans_CN",  "LOC_POLICY_MUSIC_CENSORSHIP_DESCRIPTION",                                  "来自其他文明的文化传播单位无法进入您的领土。"),
    ("zh_Hans_CN",  "LOC_POLICY_MUSIC_CENSORSHIP_NAME",                                         "非乐"),
    ("zh_Hans_CN",  "LOC_NOTIFICATION_ROCK_BANDS_PROHIBITED_SUMMARY",                           "{1_leader}正封杀外来文化。您在其帝国中的文化传播单位已被迁至其领土外的单元格。");

UPDATE LocalizedText SET Text=REPLACE(Text, 'Rock Band','Cultural Communicator') WHERE Tag in (
    'LOC_POLICY_FUTURE_VICTORY_CULTURE_DESCRIPTION',
    'LOC_POLICY_MUSIC_CENSORSHIP_DESCRIPTION',
    'LOC_POLICY_FLOWER_POWER_DESCRIPTION',
    'LOC_HUD_UNIT_PANEL_ROCK_BAND_LEVEL',
    'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_LIT_FIRST_PLACE_ROCK_BAND_BUFF_DESCRIPTION',
    'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_LIT_FIRST_PLACE_ROCK_BAND_CHEAPER_DESCRIPTION',
    'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_LIT_TOP_TIER_ROCK_BAND_BUFF_DESCRIPTION',
    'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_LIT_BOTTOM_TIER_ROCK_BAND_BUFF_DESCRIPTION',
    'LOC_UNIT_ROCK_BAND_DESCRIPTION',
    'LOC_PROMOTION_CLASS_ROCK_BAND_NAME'
);
UPDATE LocalizedText SET Text=REPLACE(Text, '摇滚乐队','文化传播单位') WHERE Tag in (
    'LOC_POLICY_FUTURE_VICTORY_CULTURE_DESCRIPTION',
    'LOC_POLICY_MUSIC_CENSORSHIP_DESCRIPTION',
    'LOC_POLICY_FLOWER_POWER_DESCRIPTION',
    'LOC_HUD_UNIT_PANEL_ROCK_BAND_LEVEL',
    'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_LIT_FIRST_PLACE_ROCK_BAND_BUFF_DESCRIPTION',
    'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_LIT_FIRST_PLACE_ROCK_BAND_CHEAPER_DESCRIPTION',
    'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_LIT_TOP_TIER_ROCK_BAND_BUFF_DESCRIPTION',
    'LOC_EMERGENCY_REWARD_NOBEL_PRIZE_LIT_BOTTOM_TIER_ROCK_BAND_BUFF_DESCRIPTION',
    'LOC_UNIT_ROCK_BAND_DESCRIPTION',
    'LOC_PROMOTION_CLASS_ROCK_BAND_NAME'
);