insert or replace into EnglishText (Tag, Text) values
  ("LOC_HD_ALL_MOUNTAINS_SCIENCE_TEXT",         											"+{1_num} [ICON_SCIENCE] Science from adjacent {1_Num : plural 1?Mountain; other?Mountains;}"),
  ("LOC_HD_ALL_MOUNTAINS_FAITH_TEXT",           											"+{1_num} [ICON_FAITH] Faith from adjacent {1_Num : plural 1?Mountain; other?Mountains;}"),
  ("LOC_HD_TRANSPORTATION_FACILITIES_DISTRICTS_PRODUCTION_TEXT",     	"+{1_num} [ICON_Production] Production from adjacent Transportation Facilities {1_Num : plural 1?District; other?Districts;}"),
  ("LOC_HD_WATER_CONSERVANCY_FACILITIES_DISTRICTS_PRODUCTION_TEXT",  	"+{1_num} [ICON_Production] Production from adjacent Water Conservancy Facilities {1_Num : plural 1?District; other?Districts;}"),
	("LOC_HD_TRANSPORTATION_FACILITIES_DISTRICTS_GOLD_TEXT",     				"+{1_num} [ICON_Gold] Gold from adjacent Transportation Facilities {1_Num : plural 1?District; other?Districts;}"),
	("LOC_HD_TOURISM_FACILITIES_DISTRICTS_CULTURE_TEXT",     						"+{1_num} [ICON_Culture] Culture from adjacent Tourism Facilities {1_Num : plural 1?District; other?Districts;}"),
	("LOC_HD_INDUSTRIAL_PRODUCTION_IMPROVEMENTS_PRODUCTION_TEXT",     	"+{1_num} [ICON_Production] Production from adjacent Industrial Production {1_Num : plural 1?Improvement; other?Improvements;}"),
	("LOC_HD_URBAN_FACILITIES_IMPROVEMENTS_PRODUCTION_TEXT",     				"+{1_num} [ICON_Production] Production from adjacent Urban Facilities {1_Num : plural 1?Improvement; other?Improvements;}"),
  ("LOC_HD_TRANSPORTATION_FACILITIES_IMPROVEMENTS_GOLD_TEXT",     		"+{1_num} [ICON_Gold] Gold from adjacent Transportation Facilities {1_Num : plural 1?Improvement; other?Improvements;}"),
	("LOC_HD_COMMERCIAL_FACILITIES_IMPROVEMENTS_GOLD_TEXT",     				"+{1_num} [ICON_Gold] Gold from adjacent Commercial Facilities {1_Num : plural 1?Improvement; other?Improvements;}"),
	("LOC_HD_MILITARY_FACILITIES_IMPROVEMENTS_PRODUCTION_TEXT",     		"+{1_num} [ICON_Production] Production from adjacent Military Facilities {1_Num : plural 1?Improvement; other?Improvements;}"),
	("LOC_HD_TRANSPORTATION_FACILITIES_IMPROVEMENTS_PRODUCTION_TEXT",   "+{1_num} [ICON_Production] Production from adjacent Transportation Facilities {1_Num : plural 1?Improvement; other?Improvements;}"),
  ("LOC_HD_TOURISM_FACILITIES_IMPROVEMENTS_CULTURE_TEXT",   					"+{1_num} [ICON_Culture] Culture from adjacent Tourism Facilities {1_Num : plural 1?Improvement; other?Improvements;}"),

  ("LOC_DISTRICT_NUSANTARA_FAITH",              "+{1_num} [ICON_FAITH] Faith from adjacent Shallow Sea and Lake {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_NUSANTARA_SCIENCE",            "+{1_num} [ICON_SCIENCE] Science from adjacent Shallow Sea and Lake {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_NUSANTARA_PRODUCTION",         "+{1_num} [ICON_Production] Production from adjacent Shallow Sea and Lake {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_NUSANTARA_CULTURE",            "+{1_num} [ICON_CULTURE] Culture from adjacent Shallow Sea and Lake {1_Num : plural 1?tile; other?tiles;}"),  
	("LOC_GENGHIS_KHAN_PASTURE_HOLY_SITE",        "+{1_num} [ICON_FAITH] Faith from the adjacent Pasture {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_GENGHIS_KHAN_PASTURE_COMMERCIAL_HUB",   "+{1_num} [ICON_GOLD] Gold from the adjacent Pasture {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_JUNGLE_2_PRODUCTION",          "+{1_num} [ICON_PRODUCTION] Production from the adjacent Rainforest {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_QUARRY_1_SCIENCE",             "+{1_num} [ICON_Science] Science from the adjacent Quarry {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_QUARRY_1_GOLD",                "+{1_num} [ICON_Gold] Gold from the adjacent Quarry {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_QUARRY_1_PRODUCTION",          "+{1_num} [ICON_Production] Production from the adjacent Quarry {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_QUARRY_1_FAITH",               "+{1_num} [ICON_Faith] Faith from the adjacent Quarry {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_QUARRY_1_CULTURE",             "+{1_num} [ICON_Culture] Culture from the adjacent Quarry {1_Num : plural 1?tile; other?tiles;}"),
  ("LOC_HD_WAT_ARUN_YIELD_SCIENCE",		          "+{1_num} [ICON_Science] Science from the adjacent {1_num : plural 1?Floodplain; other?Floodplains;}"),
  ("LOC_HD_WAT_ARUN_YIELD_CULTURE",		          "+{1_num} [ICON_CULTURE] Culture from the adjacent {1_num : plural 1?Floodplain; other?Floodplains;}"),
  ("LOC_HD_WAT_ARUN_YIELD_FOOD",					      "+{1_num} [ICON_FOOD] Food from the adjacent {1_num : plural 1?Floodplain; other?Floodplains;}"),
  ("LOC_HD_WAT_ARUN_YIELD_PRODUCTION",	        "+{1_num} [ICON_PRODUCTION] Production from the adjacent {1_num : plural 1?Floodplain; other?Floodplains;}"),
  ("LOC_HD_WAT_ARUN_YIELD_FAITH",				        "+{1_num} [ICON_FAITH] Faith from the adjacent {1_num : plural 1?Floodplain; other?Floodplains;}"),
  ("LOC_HD_WAT_ARUN_YIELD_GOLD",					      "+{1_num} [ICON_GOLD] Gold from the adjacent {1_num : plural 1?Floodplain; other?Floodplains;}"),
		-- Adjacent to district
	("LOC_DISTRICT_INDUSTRIAL_ZONE_GOLD",				"+{1_num} [ICON_GOLD] Gold from the adjacent Industrial Zone {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_HANSA_GOLD",							"+{1_num} [ICON_GOLD] Gold from the adjacent Hansa {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_CANAL_GOLD",							"+{1_num} [ICON_GOLD] Gold from the adjacent Canal {1_Num : plural 3?district; other?districts;}"),
	("LOC_DISTRICT_CITY_CENTER_CULTURE",				"+{1_num} [ICON_CULTURE] Culture from the adjacent City Center {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_CITY_CENTER_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] Production from the adjacent City Center {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_CITY_CENTER_SCIENCE",				"+{1_num} [ICON_SCIENCE] Science from the adjacent City Center {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_AERODROME_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] Production from the adjacent Aerodrome {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_NEIGHBORHOOD_FAITH",					"+{1_num} [ICON_FAITH] Faith from the adjacent Neighborhood {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_MBANZA_FAITH",						"+{1_num} [ICON_FAITH] Faith from the adjacent Mbanza {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_PRESERVE_FAITH",						"+{1_num} [ICON_FAITH] Faith from the adjacent Preserve {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_HARBOR_INDUSTRIAL_PRODUCTION",		"+{1_num} [ICON_PRODUCTION] Production from the adjacent Harbor {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_ROYALDOCK_INDUSTRIAL_PRODUCTION",	"+{1_num} [ICON_PRODUCTION] Production from the adjacent RoyalDock {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_COTHON_INDUSTRIAL_PRODUCTION",		"+{1_num} [ICON_PRODUCTION] Production from the adjacent Cothon {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_HARBOR_HANSA_PRODUCTION",			"+{1_num} [ICON_PRODUCTION] Production from the adjacent Harbor {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_ROYALDOCK_HANSA_PRODUCTION",			"+{1_num} [ICON_PRODUCTION] Production from the adjacent RoyalDock {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_INDUSTRIAL_PRODUCTION",	"+{1_num} [ICON_PRODUCTION] Production from the adjacent Royal Navy Dockyard {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_HANSA_PRODUCTION",		"+{1_num} [ICON_PRODUCTION] Production from the adjacent Royal Navy Dockyard {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_COTHON_HANSA_PRODUCTION",			"+{1_num} [ICON_PRODUCTION] Production from the adjacent Cothon {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_SUGUBA_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] Production from the adjacent Suguba {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_ENCAMPMENT_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] Production from the adjacent Encampment {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_THANH_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] Production from the adjacent Thành {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_IKANDA_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] Production from the adjacent Ikanda {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_HOLY_SITE_FAITH",					"+{1_num} [ICON_CULTURE] Culture from the adjacent Holy Site {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_LAVRA_FAITH",						"+{1_num} [ICON_CULTURE] Culture from the adjacent Lavra {1_Num : plural 2?district; other?districts;}"),
	("LOC_DISTRICT_DIPLOMATIC_QUATER_GOLD",				"+{1_num} [ICON_GOLD] Gold from the adjacent Diplomatic Quater {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_DIPLOMATIC_QUATER_FAITH",			"+{1_num} [ICON_FAITH] Faith from the adjacent Diplomatic Quater {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_DIPLOMATIC_QUATER_SCIENCE",			"+{1_num} [ICON_SCIENCE] Science from the adjacent Diplomatic Quater {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_DIPLOMATIC_QUATER_CULTURE",			"+{1_num} [ICON_CULTURE] Culture from the adjacent Diplomatic Quater {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_DIPLOMATIC_QUATER_PRODUCTION",		"+{1_num} [ICON_PRODUCTION] Production from the adjacent Diplomatic Quater {1_Num : plural 1?district; other?districts;}"),
	("LOC_DISTRICT_DISTRICT_FOOD",		"+{1_num} [ICON_FOOD] Food from the adjacent {1_Num : plural 1?district; other?districts;}"),
	-- Adjacent to resource
	("LOC_DISTRICT_SEARESOURCE_GOLD",					"+{1_num} [ICON_GOLD] Gold from the adjacent coastal {1_Num : plural 2?resource; other?resources;}"),
	("LOC_DISTRICT_HD_STRATEGIC_PRODUCTION",			"+{1_num} [ICON_PRODUCTION] Production from the adjacent Strategic {1_Num : plural 2?resource; other?resources;}"),
	("LOC_DISTRICT_BONUS_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] Production from the adjacent Bonus {1_Num : plural 1?resource; other?resources;}"),
	("LOC_DISTRICT_STRATEGIC_SCIENCE",					"+{1_num} [ICON_SCIENCE] Science from the adjacent Strategic {1_Num : plural 1?resource; other?resources;}"),
	-- Misc
	("LOC_DISTRICT_SELF_FOOD",							"+{1_num} [ICON_FOOD] Food"),
	("LOC_DISTRICT_SELF_GOLD",							"+{1_num} [ICON_GOLD] Gold"),
	("LOC_DISTRICT_RIVER_HANSA_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] Production from the adjacent river"),
	("LOC_DISTRICT_MARSH_SCIENCE",						"+{1_num} [ICON_SCIENCE] Science from the adjacent Marsh {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_SWAMP_FAITH",									"+{1_num} [ICON_FAITH] Faith from the adjacent Swamp {1_Num : plural 1?tile; other?tiles;}"),
    ("LOC_KELP_FAITH",									"+{1_num} [ICON_FAITH] Faith from the adjacent Kelp Forest {1_Num : plural 1?tile; other?tiles;}"),
	-- plural replacement
	("LOC_DISTRICT_CANAL_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] Production from the adjacent Canal {1_Num : plural 3?district; other?districts;}"),
	("LOC_DISTRICT_LUXURY_GOLD",						"+{1_num} [ICON_GOLD] Gold from the adjacent Luxury {1_Num : plural 2?resource; other?resources;}"),
	("LOC_DISTRICT_BONUS_GOLD",						"+{1_num} [ICON_GOLD] Gold from the adjacent Bonus {1_Num : plural 2?resource; other?resources;}"),
	("LOC_DISTRICT_FOREST_FAITH",						"+{1_num} [ICON_FAITH] Faith from the adjacent Woods {1_Num : plural 1?tile; other?tiles;}"),
	("LOC_DISTRICT_RESOURCE_CULTURE",					"+{1_num} [ICON_CULTURE] Culture from the adjacent {1_Num : plural 1?resource; other?resources;}");

insert or replace into LocalizedText (Language, Tag, Text) values
	-- 基于分类的相邻加成
  ("zh_Hans_CN",  "LOC_HD_ALL_MOUNTAINS_SCIENCE_TEXT",          										"+{1_num} [ICON_SCIENCE] 科技值来自相邻山脉"),
  ("zh_Hans_CN",  "LOC_HD_ALL_MOUNTAINS_FAITH_TEXT",            										"+{1_num} [ICON_FAITH] 信仰值来自相邻山脉"),
  ("zh_Hans_CN",  "LOC_HD_TRANSPORTATION_FACILITIES_DISTRICTS_PRODUCTION_TEXT",     "+{1_num} [ICON_Production] 生产力来自相邻交通设施区域"),
  ("zh_Hans_CN",  "LOC_HD_WATER_CONSERVANCY_FACILITIES_DISTRICTS_PRODUCTION_TEXT",  "+{1_num} [ICON_Production] 生产力来自相邻水利设施区域"),
  ("zh_Hans_CN",  "LOC_HD_TRANSPORTATION_FACILITIES_DISTRICTS_GOLD_TEXT",     			"+{1_num} [ICON_Gold] 金币来自相邻交通设施区域"),
  ("zh_Hans_CN",  "LOC_HD_TOURISM_FACILITIES_DISTRICTS_CULTURE_TEXT",     					"+{1_num} [ICON_CULTURE] 文化值来自相邻旅游设施区域"),
  ("zh_Hans_CN",  "LOC_HD_INDUSTRIAL_PRODUCTION_IMPROVEMENTS_PRODUCTION_TEXT",     	"+{1_num} [ICON_Production] 生产力来自相邻工业生产改良"),
  ("zh_Hans_CN",  "LOC_HD_URBAN_FACILITIES_IMPROVEMENTS_PRODUCTION_TEXT",     			"+{1_num} [ICON_Production] 生产力来自相邻城市设施改良"),
  ("zh_Hans_CN",  "LOC_HD_TRANSPORTATION_FACILITIES_IMPROVEMENTS_GOLD_TEXT",     		"+{1_num} [ICON_Gold] 金币来自相邻交通设施改良"),
  ("zh_Hans_CN",  "LOC_HD_COMMERCIAL_FACILITIES_IMPROVEMENTS_GOLD_TEXT",     				"+{1_num} [ICON_Gold] 金币来自相邻商业设施改良"),
  ("zh_Hans_CN",  "LOC_HD_MILITARY_FACILITIES_IMPROVEMENTS_PRODUCTION_TEXT",     		"+{1_num} [ICON_Production] 生产力来自相邻军事设施改良"),
  ("zh_Hans_CN",  "LOC_HD_TRANSPORTATION_FACILITIES_IMPROVEMENTS_PRODUCTION_TEXT",  "+{1_num} [ICON_Production] 生产力来自相邻交通设施改良"),
  ("zh_Hans_CN",  "LOC_HD_TOURISM_FACILITIES_IMPROVEMENTS_CULTURE_TEXT",  					"+{1_num} [ICON_CULTURE] 文化值来自相邻旅游设施改良"),
	
  ("zh_Hans_CN",  "LOC_DISTRICT_NUSANTARA_FAITH",               "+{1_num} [ICON_FAITH] 信仰值来自相邻浅海与湖泊"),
	("zh_Hans_CN",  "LOC_DISTRICT_NUSANTARA_SCIENCE",             "+{1_num} [ICON_SCIENCE] 科技值来自相邻浅海与湖泊"),
	("zh_Hans_CN",  "LOC_DISTRICT_NUSANTARA_PRODUCTION",          "+{1_num} [ICON_Production] 生产力来自相邻浅海与湖泊"),
	("zh_Hans_CN",  "LOC_DISTRICT_NUSANTARA_CULTURE",             "+{1_num} [ICON_CULTURE] 文化值来自相邻浅海与湖泊"),
  ("zh_Hans_CN",  "LOC_GENGHIS_KHAN_PASTURE_HOLY_SITE",         "+{1_num} [ICON_FAITH] 信仰来自相邻牧场"),
	("zh_Hans_CN",  "LOC_GENGHIS_KHAN_PASTURE_COMMERCIAL_HUB",    "+{1_num} [ICON_GOLD] 金币来自相邻牧场"),
	("zh_Hans_CN",  "LOC_DISTRICT_JUNGLE_2_PRODUCTION",           "+{1_num} [ICON_PRODUCTION] 生产力来自相邻雨林"),
	("zh_Hans_CN",  "LOC_DISTRICT_QUARRY_1_SCIENCE",              "+{1_num} [ICON_SCIENCE] 科技值来自相邻采石场"),
	("zh_Hans_CN",  "LOC_DISTRICT_QUARRY_1_GOLD",                 "+{1_num} [ICON_GOLD] 金币来自相邻采石场"),
	("zh_Hans_CN",  "LOC_DISTRICT_QUARRY_1_PRODUCTION",           "+{1_num} [ICON_PRODUCTION] 生产力来自相邻采石场"),
	("zh_Hans_CN",  "LOC_DISTRICT_QUARRY_1_FAITH",                "+{1_num} [ICON_FAITH] 信仰值来自相邻采石场"),
	("zh_Hans_CN",  "LOC_DISTRICT_QUARRY_1_CULTURE",              "+{1_num} [ICON_CULTURE] 文化值来自相邻采石场"),
  ("zh_Hans_CN",  "LOC_HD_WAT_ARUN_YIELD_SCIENCE",				      "+{1_num} [ICON_SCIENCE] 科技值来自相邻泛滥平原"),
  ("zh_Hans_CN",  "LOC_HD_WAT_ARUN_YIELD_CULTURE",				      "+{1_num} [ICON_CULTURE] 文化值来自相邻泛滥平原"),
  ("zh_Hans_CN",  "LOC_HD_WAT_ARUN_YIELD_FOOD",						      "+{1_num} [ICON_FOOD] 食物来自相邻泛滥平原"),
  ("zh_Hans_CN",  "LOC_HD_WAT_ARUN_YIELD_PRODUCTION",			      "+{1_num} [ICON_PRODUCTION] 生产力来自相邻泛滥平原"),
  ("zh_Hans_CN",  "LOC_HD_WAT_ARUN_YIELD_FAITH",					      "+{1_num} [ICON_FAITH] 信仰值来自相邻泛滥平原"),
  ("zh_Hans_CN",  "LOC_HD_WAT_ARUN_YIELD_GOLD",					        "+{1_num} [ICON_GOLD] 金币来自相邻泛滥平原"),
		-- Adjacent to district
	("zh_Hans_CN",	"LOC_DISTRICT_INDUSTRIAL_GOLD",						"+{1_num} [ICON_GOLD] 金币来自相邻工业区"),
	("zh_Hans_CN",	"LOC_DISTRICT_HANSA_GOLD",							"+{1_num} [ICON_GOLD] 金币来自相邻商业同业工会"),
	("zh_Hans_CN",	"LOC_DISTRICT_CANAL_GOLD",							"+{1_num} [ICON_GOLD] 金币来自相邻运河"),
	("zh_Hans_CN",	"LOC_DISTRICT_CITY_CENTER_CULTURE",					"+{1_num} [ICON_CULTURE] 文化值来自相邻市中心"),
	("zh_Hans_CN",	"LOC_DISTRICT_CITY_CENTER_SCIENCE",					"+{1_num} [ICON_SCIENCE] 科技值来自相邻市中心"),
	("zh_Hans_CN",	"LOC_DISTRICT_CITY_CENTER_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] 生产力来自相邻市中心"),
	("zh_Hans_CN",	"LOC_DISTRICT_AERODROME_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] 生产力来自相邻航空港"),
	("zh_Hans_CN",	"LOC_DISTRICT_NEIGHBORHOOD_FAITH",					"+{1_num} [ICON_FAITH] 信仰值来自相邻社区"),
	("zh_Hans_CN",	"LOC_DISTRICT_MBANZA_FAITH",						"+{1_num} [ICON_FAITH] 信仰值来自相邻姆班赞"),
	("zh_Hans_CN",	"LOC_DISTRICT_PRESERVE_FAITH",						"+{1_num} [ICON_FAITH] 信仰值来自相邻保护区"),
	("zh_Hans_CN",	"LOC_DISTRICT_HARBOR_INDUSTRIAL_PRODUCTION",		"+{1_num} [ICON_PRODUCTION] 生产力来自相邻港口"),
	("zh_Hans_CN",	"LOC_DISTRICT_ROYALDOCK_INDUSTRIAL_PRODUCTION",		"+{1_num} [ICON_PRODUCTION] 生产力来自相邻皇家海军船坞"),
	("zh_Hans_CN",	"LOC_DISTRICT_COTHON_INDUSTRIAL_PRODUCTION",		"+{1_num} [ICON_PRODUCTION] 生产力来自相邻U型港"),
	("zh_Hans_CN",	"LOC_DISTRICT_HARBOR_HANSA_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] 生产力来自相邻港口"),
	("zh_Hans_CN",	"LOC_DISTRICT_ROYALDOCK_HANSA_PRODUCTION",			"+{1_num} [ICON_PRODUCTION] 生产力来自相邻皇家海军船坞"),
	("zh_Hans_CN",	"LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_INDUSTRIAL_PRODUCTION",	"+{1_num} [ICON_PRODUCTION] 生产力来自相邻皇家海军船坞"),
	("zh_Hans_CN",	"LOC_DISTRICT_ROYAL_NAVY_DOCKYARD_HANSA_PRODUCTION",		"+{1_num} [ICON_PRODUCTION] 生产力来自相邻皇家海军船坞"),
	("zh_Hans_CN",	"LOC_DISTRICT_INDUSTRIAL_ZONE_GOLD",				"+{1_num} [ICON_GOLD] 金币来自相邻工业区"),
	("zh_Hans_CN",	"LOC_DISTRICT_COTHON_HANSA_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] 生产力来自相邻U型港"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUGUBA_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] 生产力来自相邻曼丁哥市场"),
	("zh_Hans_CN",	"LOC_DISTRICT_ENCAMPMENT_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] 生产力来自相邻军营"),
	("zh_Hans_CN",	"LOC_DISTRICT_THANH_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] 生产力来自相邻城池"),
	("zh_Hans_CN",	"LOC_DISTRICT_IKANDA_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] 生产力来自相邻伊坎达"),
	("zh_Hans_CN",	"LOC_DISTRICT_HOLY_SITE_FAITH",						"+{1_num} [ICON_CULTURE] 文化值来自相邻圣地"),
	("zh_Hans_CN",	"LOC_DISTRICT_LAVRA_FAITH",							"+{1_num} [ICON_CULTURE] 文化值来自相邻拉夫拉修道院"),
	("zh_Hans_CN",	"LOC_DISTRICT_DIPLOMATIC_QUATER_GOLD",				"+{1_num} [ICON_GOLD] 金币来自相邻外交区"),
	("zh_Hans_CN",	"LOC_DISTRICT_DIPLOMATIC_QUATER_FAITH",				"+{1_num} [ICON_FAITH] 信仰值来自相邻外交区"),
	("zh_Hans_CN",	"LOC_DISTRICT_DIPLOMATIC_QUATER_SCIENCE",			"+{1_num} [ICON_SCIENCE] 科技值来自相邻外交区"),
	("zh_Hans_CN",	"LOC_DISTRICT_DIPLOMATIC_QUATER_CULTURE",			"+{1_num} [ICON_CULTURE] 文化值自相邻外交区"),
	("zh_Hans_CN",	"LOC_DISTRICT_DIPLOMATIC_QUATER_PRODUCTION",		"+{1_num} [ICON_PRODUCTION] 生产力来自相邻外交区"),
	("zh_Hans_CN",	"LOC_DISTRICT_DISTRICT_FOOD",		"+{1_num} [ICON_FOOD] 食物来自相邻区域"),
	-- Adjacent to resource
	("zh_Hans_CN",	"LOC_DISTRICT_LUXURY_GOLD",							"+{1_num} [ICON_GOLD] 金币来自相邻奢侈品资源"),
	("zh_Hans_CN",	"LOC_DISTRICT_BONUS_GOLD",							"+{1_num} [ICON_GOLD] 金币来自相邻加成资源"),
	("zh_Hans_CN",	"LOC_DISTRICT_HD_STRATEGIC_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] 生产力来自相邻战略资源"),
	("zh_Hans_CN",	"LOC_DISTRICT_BONUS_PRODUCTION",					"+{1_num} [ICON_PRODUCTION] 生产力来自相邻加成资源"),
	("zh_Hans_CN",	"LOC_DISTRICT_STRATEGIC_SCIENCE",					"+{1_num} [ICON_SCIENCE] 科技值来自相邻战略资源"),
	-- Misc
	("zh_Hans_CN",	"LOC_DISTRICT_SELF_FOOD",							"+{1_num} [ICON_FOOD] 食物"),
	("zh_Hans_CN",	"LOC_DISTRICT_SELF_GOLD",							"+{1_num} [ICON_GOLD] 金币"),
	("zh_Hans_CN",	"LOC_DISTRICT_RIVER_HANSA_PRODUCTION",				"+{1_num} [ICON_PRODUCTION] 生产力来自相邻河流"),
	("zh_Hans_CN",	"LOC_DISTRICT_MARSH_SCIENCE",						"+{1_num} [ICON_SCIENCE] 科技值来自相邻{LOC_FEATURE_MARSH_NAME}"),
	("zh_Hans_CN",	"LOC_SWAMP_FAITH",									"+{1_num} [ICON_FAITH] 信仰值来自相邻木本沼泽"),
	("zh_Hans_CN",	"LOC_KELP_FAITH",									"+{1_num} [ICON_FAITH] 信仰值来自相邻海藻森林"),
	("zh_Hans_CN",	"LOC_DISTRICT_RESOURCE_CULTURE",					"+{1_num} [ICON_CULTURE] 文化值来自相邻{1_Num : plural 1?资源; other?资源;}");