-- 经济政策
update IconDefinitions set 'Index' = 0 where Name in (
  'ICON_POLICY_MERCHANT_CONFEDERATION'
);

update IconAliases set 'OtherName' = 'ICON_POLICY_ECONOMIC' where Name in (
  'ICON_POLICY_WISSELBANKEN',
  'ICON_POLICY_COLONIAL_TAXES'
);

-- 军事政策
update IconDefinitions set 'Index' = 1 where Name in (
  'ICON_POLICY_NAVAL_INFRASTRUCTURE',
  'ICON_POLICY_RELIGIOUS_ORDERS',
  'ICON_POLICY_INTERNATIONAL_SPACE_AGENCY',
  'ICON_POLICY_GUNBOAT_DIPLOMACY',
  'ICON_POLICY_RAJ'
);

update IconAliases set 'OtherName' = 'ICON_POLICY_MILITARY' where Name in (
  'ICON_POLICY_COLONIAL_OFFICES',
  'ICON_POLICY_DEFENSE_OF_MOTHERLAND',
  'ICON_POLICY_FINEST_HOUR',
  'ICON_POLICY_MARTIAL_LAW'
);

-- 文化政策
update IconDefinitions set 'Index' = 2 where Name in (
  'ICON_POLICY_AESTHETICS',
  'ICON_POLICY_NATURAL_PHILOSOPHY',
  'ICON_POLICY_SCRIPTURE',
  'ICON_POLICY_SIMULTANEUM',
  'ICON_POLICY_FIVE_YEAR_PLAN',
  'ICON_POLICY_SPORTS_MEDIA',
	'ICON_POLICY_GRAND_OPERA',
	'ICON_POLICY_RATIONALISM',
	'ICON_POLICY_SATELLITE_BROADCASTS',
	'ICON_POLICY_HERITAGE_TOURISM',
	'ICON_POLICY_ONLINE_COMMUNITIES'
);