-- Warning: do not use replace 
insert or ignore into IconTextureAtlases
    (Name,                      IconSize,   IconsPerRow,    IconsPerColumn,     Filename)
values
    ('ICON_ATLAS_CIVICS_HD',    38,         4,              2,                  'HDCivicIcons_38.dds'),
    ('ICON_ATLAS_CIVICS_HD',    42,         4,              2,                  'HDCivicIcons_42.dds'),
    ('ICON_ATLAS_CIVICS_HD',    128,        4,              2,                  'HDCivicIcons_128.dds'),
    ('ICON_ATLAS_CIVICS_HD',    160,        4,              2,                  'HDCivicIcons_160.dds'),
    ('ICON_ATLAS_CIVICS_HD_FOW',42,         4,              2,                  'HDCivicIcons_FOW_42.dds'),

    ('ICON_ATLAS_TECHS_HD',     30,         2,              1,                  'HDTechIcons_30.dds'),
    ('ICON_ATLAS_TECHS_HD',     38,         2,              1,                  'HDTechIcons_38.dds'),
    ('ICON_ATLAS_TECHS_HD',     42,         2,              1,                  'HDTechIcons_42.dds'),
    ('ICON_ATLAS_TECHS_HD',     128,        2,              1,                  'HDTechIcons_128.dds'),
    ('ICON_ATLAS_TECHS_HD',     160,        2,              1,                  'HDTechIcons_160.dds'),
    ('ICON_ATLAS_TECHS_HD_FOW', 42,         2,              1,                  'HDTechIcons_FOW_42.dds'),

    ('ICON_ATLAS_TECH_CIVIC_2_HD',     30,         2,              3,                  'HDTechCivic_2_30.dds'),
    ('ICON_ATLAS_TECH_CIVIC_2_HD',     38,         2,              3,                  'HDTechCivic_2_38.dds'),
    ('ICON_ATLAS_TECH_CIVIC_2_HD',     42,         2,              3,                  'HDTechCivic_2_42.dds'),
    ('ICON_ATLAS_TECH_CIVIC_2_HD',     128,        2,              3,                  'HDTechCivic_2_128.dds'),
    ('ICON_ATLAS_TECH_CIVIC_2_HD',     160,        2,              3,                  'HDTechCivic_2_160.dds'),
    ('ICON_ATLAS_TECH_CIVIC_2_HD_FOW', 42,         2,              3,                  'HDTechCivic_2_42.dds'),

    ('ICON_ATLAS_TECH_CIVIC_3_HD',     30,         7,              7,                  'New_Tech_Civic_30.dds'),
    ('ICON_ATLAS_TECH_CIVIC_3_HD',     38,         7,              7,                  'New_Tech_Civic_38.dds'),
    ('ICON_ATLAS_TECH_CIVIC_3_HD',     42,         7,              7,                  'New_Tech_Civic_42.dds'),
    ('ICON_ATLAS_TECH_CIVIC_3_HD',     128,        7,              7,                  'New_Tech_Civic_128.dds'),
    ('ICON_ATLAS_TECH_CIVIC_3_HD',     160,        7,              7,                  'New_Tech_Civic_160.dds'),
    ('ICON_ATLAS_TECH_CIVIC_3_HD_FOW', 42,         7,              7,                  'New_Tech_Civic_FOW_42.dds');

insert or replace into IconDefinitions
    (Name,                                              Atlas,                  'Index')
values
    -- Techs
    ('ICON_TECH_CALENDAR_HD',                           'ICON_ATLAS_TECHS_HD',              1),
    ('ICON_TECH_PAPER_MAKING_HD',                       'ICON_ATLAS_TECH_CIVIC_2_HD',       0),
    ('ICON_TECH_COMPASS_HD',                            'ICON_ATLAS_TECH_CIVIC_3_HD',       43),
    ('ICON_TECH_PHYSICS_HD',                            'ICON_ATLAS_TECHS_HD',              0),
    ('ICON_TECH_CIVIL_ENGINEERING_HD',                  'ICON_ATLAS_TECH_CIVIC_3_HD',       42),
    -- FOW
    ('ICON_TECH_CALENDAR_HD_FOW',                       'ICON_ATLAS_TECHS_HD_FOW',          1),
    ('ICON_TECH_PAPER_MAKING_HD_FOW',                   'ICON_ATLAS_TECH_CIVIC_2_HD_FOW',   1),
    ('ICON_TECH_COMPASS_HD_FOW',                        'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   43),
    ('ICON_TECH_PHYSICS_HD_FOW',                        'ICON_ATLAS_TECHS_HD_FOW',          0),
    ('ICON_TECH_CIVIL_ENGINEERING_HD_FOW',              'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   42),
    -- Civics
    ('ICON_CIVIC_EXPLORATION',                          'ICON_ATLAS_TECH_CIVIC_2_HD',       4),
    ('ICON_CIVIC_DEFENSIVE_TACTICS',                    'ICON_ATLAS_CIVICS_HD',             1),
    ('ICON_CIVIC_LITERARY_TRADITION_HD',                'ICON_ATLAS_CIVICS_HD',             4),
    ('ICON_CIVIC_IMPERIAL_EXAMINATION_SYSTEM_HD',       'ICON_ATLAS_CIVICS_HD',             2),
    ('ICON_CIVIC_EVOLUTION_THEORY_HD',                  'ICON_ATLAS_TECH_CIVIC_2_HD',       2),
    ('ICON_CIVIC_HISTORICAL_PHILOSOPHY_HD',             'ICON_ATLAS_CIVICS_HD',             7),
    ('ICON_CIVIC_ETHICS_HD',                            'ICON_ATLAS_CIVICS_HD',             5),
    ('ICON_CIVIC_SOCIAL_SCIENCE_HD',                    'ICON_ATLAS_CIVICS_HD',             6),
    ('ICON_CIVIC_NATURAL_HISTORY',                      'ICON_ATLAS_CIVICS_HD',             3),
    -- FOW
    ('ICON_CIVIC_EXPLORATION_FOW',                      'ICON_ATLAS_TECH_CIVIC_2_HD_FOW',   5),
    ('ICON_CIVIC_DEFENSIVE_TACTICS_FOW',                'ICON_ATLAS_CIVICS_HD_FOW',         1),
    ('ICON_CIVIC_LITERARY_TRADITION_HD_FOW',            'ICON_ATLAS_CIVICS_HD_FOW',         4),
    ('ICON_CIVIC_IMPERIAL_EXAMINATION_SYSTEM_HD_FOW',   'ICON_ATLAS_CIVICS_HD_FOW',         2),
    ('ICON_CIVIC_EVOLUTION_THEORY_HD_FOW',              'ICON_ATLAS_TECH_CIVIC_2_HD_FOW',   3),
    ('ICON_CIVIC_HISTORICAL_PHILOSOPHY_HD_FOW',         'ICON_ATLAS_CIVICS_HD_FOW',         7),
    ('ICON_CIVIC_ETHICS_HD_FOW',                        'ICON_ATLAS_CIVICS_HD_FOW',         5),
    ('ICON_CIVIC_SOCIAL_SCIENCE_HD_FOW',                'ICON_ATLAS_CIVICS_HD_FOW',         6),
    ('ICON_CIVIC_NATURAL_HISTORY_FOW',                  'ICON_ATLAS_CIVICS_HD_FOW',         3),
    -- 新科技
    ('ICON_TECH_ALCHEMY_HD',                            'ICON_ATLAS_TECH_CIVIC_3_HD',       0),
    ('ICON_TECH_TEXTILE_HD',                            'ICON_ATLAS_TECH_CIVIC_3_HD',       1),
    ('ICON_TECH_SADDLE_HD',                             'ICON_ATLAS_TECH_CIVIC_3_HD',       2),
    ('ICON_TECH_FUEL_HD',                               'ICON_ATLAS_TECH_CIVIC_3_HD',       3),
    ('ICON_TECH_GEOMATICS_HD',                          'ICON_ATLAS_TECH_CIVIC_3_HD',       4),
    ('ICON_TECH_OCEANOGRAPHY_HD',                       'ICON_ATLAS_TECH_CIVIC_3_HD',       5),
    ('ICON_TECH_SCIENTIFIC_THEORY',                     'ICON_ATLAS_TECH_CIVIC_3_HD',       6),
    ('ICON_TECH_GEOLOGY_HD',                            'ICON_ATLAS_TECH_CIVIC_3_HD',       7),
    ('ICON_TECH_REFRIGERATION_HD',                      'ICON_ATLAS_TECH_CIVIC_3_HD',       8),
    ('ICON_TECH_BIOLOGY_HD',                            'ICON_ATLAS_TECH_CIVIC_3_HD',       9),
    ('ICON_TECH_MEDICAL_SCIENCE_HD',                    'ICON_ATLAS_TECH_CIVIC_3_HD',       10),
    ('ICON_TECH_MODERN_AGRICULTURE_HD',                 'ICON_ATLAS_TECH_CIVIC_3_HD',       11),
    ('ICON_TECH_MODERN_TRAFFIC_HD',                     'ICON_ATLAS_TECH_CIVIC_3_HD',       12),
    ('ICON_TECH_CATERPILLAR_TRACK_HD',                  'ICON_ATLAS_TECH_CIVIC_3_HD',       13),
    ('ICON_TECH_GENETIC_ENGINEERING_HD',                'ICON_ATLAS_TECH_CIVIC_3_HD',       14),
    ('ICON_TECH_INDUSTRIAL_AUTOMATION_HD',              'ICON_ATLAS_TECH_CIVIC_3_HD',       15),
    ('ICON_TECH_INTERNET_HD',                           'ICON_ATLAS_TECH_CIVIC_3_HD',       16),
    ('ICON_TECH_INTEGRATED_CIRCUIT_HD',                 'ICON_ATLAS_TECH_CIVIC_3_HD',       17),
    ('ICON_TECH_TELECOMMUNICATIONS',                    'ICON_ATLAS_TECH_CIVIC_3_HD',       18),
    ('ICON_TECH_VIRTUAL_REALITY_HD',                    'ICON_ATLAS_TECH_CIVIC_3_HD',       19),
    ('ICON_TECH_BIG_DATA_HD',                           'ICON_ATLAS_TECH_CIVIC_3_HD',       20),
    ('ICON_TECH_ARCH_HD',                               'ICON_ATLAS_TECH_CIVIC_3_HD',       44),
    ('ICON_TECH_CELESTIAL_NAVIGATION',                  'ICON_ATLAS_TECH_CIVIC_3_HD',       45),
    ('ICON_TECH_SQUARE_SAIL_HD',                        'ICON_ATLAS_TECH',                  31),
    ('ICON_TECH_SQUARE_RIGGING',                        'ICON_ATLAS_TECH',                  11),

    ('ICON_TECH_ALCHEMY_HD_FOW',                        'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   0),
    ('ICON_TECH_TEXTILE_HD_FOW',                        'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   1),
    ('ICON_TECH_SADDLE_HD_FOW',                         'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   2),
    ('ICON_TECH_FUEL_HD_FOW',                           'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   3),
    ('ICON_TECH_GEOMATICS_HD_FOW',                      'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   4),
    ('ICON_TECH_OCEANOGRAPHY_HD_FOW',                   'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   5),
    ('ICON_TECH_SCIENTIFIC_THEORY_FOW',                 'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   6),
    ('ICON_TECH_GEOLOGY_HD_FOW',                        'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   7),
    ('ICON_TECH_REFRIGERATION_HD_FOW',                  'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   8),
    ('ICON_TECH_BIOLOGY_HD_FOW',                        'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   9),
    ('ICON_TECH_MEDICAL_SCIENCE_HD_FOW',                'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   10),
    ('ICON_TECH_MODERN_AGRICULTURE_HD_FOW',             'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   11),
    ('ICON_TECH_MODERN_TRAFFIC_HD_FOW',                 'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   12),
    ('ICON_TECH_CATERPILLAR_TRACK_HD_FOW',              'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   13),
    ('ICON_TECH_GENETIC_ENGINEERING_HD_FOW',            'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   14),
    ('ICON_TECH_INDUSTRIAL_AUTOMATION_HD_FOW',          'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   15),
    ('ICON_TECH_INTERNET_HD_FOW',                       'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   16),
    ('ICON_TECH_INTEGRATED_CIRCUIT_HD_FOW',             'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   17),
    ('ICON_TECH_TELECOMMUNICATIONS_FOW',                'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   18),
    ('ICON_TECH_VIRTUAL_REALITY_HD_FOW',                'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   19),
    ('ICON_TECH_BIG_DATA_HD_FOW',                       'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   20),
    ('ICON_TECH_ARCH_HD_FOW',                           'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   44),
    ('ICON_TECH_CELESTIAL_NAVIGATION_FOW',              'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   45),
    ('ICON_TECH_SQUARE_SAIL_HD_FOW',                    'ICON_ATLAS_TECH_FOW',              31),
    ('ICON_TECH_SQUARE_RIGGING_FOW',                    'ICON_ATLAS_TECH_FOW',              11),
    -- 新市政
    ('ICON_CIVIC_EARLY_WARFARE_HD',                     'ICON_ATLAS_TECH_CIVIC_3_HD',       21),
    ('ICON_CIVIC_FUNERAL_HD',                           'ICON_ATLAS_TECH_CIVIC_3_HD',       22),
    ('ICON_CIVIC_HERALDRY_HD',                          'ICON_ATLAS_TECH_CIVIC_3_HD',       23),
    ('ICON_CIVIC_COMMERCIAL_CAPITALISM_HD',             'ICON_ATLAS_TECH_CIVIC_3_HD',       24),
    ('ICON_CIVIC_LAW_HD',                               'ICON_ATLAS_TECH_CIVIC_3_HD',       25),
    ('ICON_CIVIC_HUMAN_RIGHTS_HD',                      'ICON_ATLAS_TECH_CIVIC_3_HD',       26),
    ('ICON_CIVIC_POLICE_SYSTEM_HD',                     'ICON_ATLAS_TECH_CIVIC_3_HD',       27),
    ('ICON_CIVIC_JOURNALISM_STUDIES_HD',                'ICON_ATLAS_TECH_CIVIC_3_HD',       28),
    ('ICON_CIVIC_SCORCHED_EARTH',                       'ICON_ATLAS_TECH_CIVIC_3_HD',       29),
    ('ICON_CIVIC_MUSEOLOGY_HD',                         'ICON_ATLAS_TECH_CIVIC_3_HD',       30),
    ('ICON_CIVIC_SOCIAL_SECURITY_SYSTEM_HD',            'ICON_ATLAS_TECH_CIVIC_3_HD',       31),
    ('ICON_CIVIC_PALEOBIOLOGY_HD',                      'ICON_ATLAS_CIVICS',                31),
    ('ICON_CIVIC_ANTHROPOLOGY_HD',                      'ICON_ATLAS_TECH_CIVIC_3_HD',       32),
    ('ICON_CIVIC_LEAGUE_OF_NATIONS_HD',                 'ICON_ATLAS_TECH_CIVIC_3_HD',       33),
    ('ICON_CIVIC_FINANCE_HD',                           'ICON_ATLAS_TECH_CIVIC_3_HD',       34),
    ('ICON_CIVIC_HIGHER_EDUCATION_HD',                  'ICON_ATLAS_TECH_CIVIC_3_HD',       35),
    ('ICON_CIVIC_NEOCOLONIALISM_HD',                    'ICON_ATLAS_TECH_CIVIC_3_HD',       36),
    ('ICON_CIVIC_MODERNISM_HD',                         'ICON_ATLAS_TECH_CIVIC_3_HD',       37),
    ('ICON_CIVIC_INTERNATIONALISM_HD',                  'ICON_ATLAS_TECH_CIVIC_3_HD',       38),
    ('ICON_CIVIC_HOUSEHOLD_REGISTRATION_HD',            'ICON_ATLAS_TECH_CIVIC_3_HD',       39),
    ('ICON_CIVIC_URBAN_DESIGN_HD',                      'ICON_ATLAS_TECH_CIVIC_3_HD',       40),

    ('ICON_CIVIC_EARLY_WARFARE_HD_FOW',                 'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   21),
    ('ICON_CIVIC_FUNERAL_HD_FOW',                       'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   22),
    ('ICON_CIVIC_HERALDRY_HD_FOW',                      'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   23),
    ('ICON_CIVIC_COMMERCIAL_CAPITALISM_HD_FOW',         'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   24),
    ('ICON_CIVIC_LAW_HD_FOW',                           'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   25),
    ('ICON_CIVIC_HUMAN_RIGHTS_HD_FOW',                  'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   26),
    ('ICON_CIVIC_POLICE_SYSTEM_HD_FOW',                 'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   27),
    ('ICON_CIVIC_JOURNALISM_STUDIES_HD_FOW',            'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   28),
    ('ICON_CIVIC_SCORCHED_EARTH_FOW',                   'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   29),
    ('ICON_CIVIC_MUSEOLOGY_HD_FOW',                     'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   30),
    ('ICON_CIVIC_SOCIAL_SECURITY_SYSTEM_HD_FOW',        'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   31),
    ('ICON_CIVIC_PALEOBIOLOGY_HD_FOW',                  'ICON_ATLAS_CIVICS_FOW',            31),
    ('ICON_CIVIC_ANTHROPOLOGY_HD_FOW',                  'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   32),
    ('ICON_CIVIC_LEAGUE_OF_NATIONS_HD_FOW',             'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   33),
    ('ICON_CIVIC_FINANCE_HD_FOW',                       'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   34),
    ('ICON_CIVIC_HIGHER_EDUCATION_HD_FOW',              'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   35),
    ('ICON_CIVIC_NEOCOLONIALISM_HD_FOW',                'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   36),
    ('ICON_CIVIC_MODERNISM_HD_FOW',                     'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   37),
    ('ICON_CIVIC_INTERNATIONALISM_HD_FOW',              'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   38),
    ('ICON_CIVIC_HOUSEHOLD_REGISTRATION_HD_FOW',        'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   39),
    ('ICON_CIVIC_URBAN_DESIGN_HD_FOW',                  'ICON_ATLAS_TECH_CIVIC_3_HD_FOW',   40);

