insert or ignore into IconTextureAtlases (Name, IconSize, IconsPerRow, IconsPerColumn, Filename) values
	('ICON_ATLAS_RESOURCES_MONOPOLY_HD',		  32,   8,  8,  'HD_Resources_Monopoly_32.dds'),
	('ICON_ATLAS_RESOURCES_MONOPOLY_HD',		  38,   8,  8,  'HD_Resources_Monopoly_38.dds'),
	('ICON_ATLAS_RESOURCES_MONOPOLY_HD',		  50,   8,  8,  'HD_Resources_Monopoly_50.dds'),
	('ICON_ATLAS_RESOURCES_MONOPOLY_HD',		  64,   8,  8,  'HD_Resources_Monopoly_64.dds'),
	('ICON_ATLAS_RESOURCES_MONOPOLY_HD',		  256,  8,  8,  'HD_Resources_Monopoly_256.dds'),
	('ICON_ATLAS_RESOURCES_MONOPOLY_HD_FOW',	256,  8,  8,  'HD_Resources_Monopoly_FOW_256.dds');

insert or ignore into IconTextureAtlases (Name, Baseline, IconSize, IconsPerRow, IconsPerColumn, Filename) values
	('ICON_ATLAS_RESOURCES_MONOPOLY_HD',  6,  22,   8,  8,  'HD_Resources_Monopoly_22.dds');

insert or replace into IconDefinitions (Name, Atlas, "Index") values
	('ICON_MONOPOLIES_AND_CORPS_RESOURCE_C_HEAVENLY_HORSE',				'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		0),
	('ICON_PROJECT_CREATE_CORPORATION_PRODUCT_C_HEAVENLY_HORSE',			'ICON_ATLAS_RESOURCES_MONOPOLY_HD',	0),
	('ICON_MONOPOLIES_AND_CORPS_RESOURCE_C_HEAVENLY_HORSE_FOW',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD_FOW',		0),
	('MONOPOLIES_AND_CORPS_RESOURCE_C_HEAVENLY_HORSE',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		0),

	('ICON_MONOPOLIES_AND_CORPS_RESOURCE_C_ZEBU',				'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		1),
	('ICON_PROJECT_CREATE_CORPORATION_PRODUCT_C_ZEBU',			'ICON_ATLAS_RESOURCES_MONOPOLY_HD',	1),
	('ICON_MONOPOLIES_AND_CORPS_RESOURCE_C_ZEBU_FOW',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD_FOW',		1),
	('MONOPOLIES_AND_CORPS_RESOURCE_C_ZEBU',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		1),

	('ICON_MONOPOLIES_AND_CORPS_RESOURCE_SUK_RAYS',				'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		2),
	('ICON_PROJECT_CREATE_CORPORATION_PRODUCT_SUK_RAYS',			'ICON_ATLAS_RESOURCES_MONOPOLY_HD',	2),
	('ICON_MONOPOLIES_AND_CORPS_RESOURCE_SUK_RAYS_FOW',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD_FOW',		2),
	('MONOPOLIES_AND_CORPS_RESOURCE_SUK_RAYS',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		2),

	('ICON_MONOPOLIES_AND_CORPS_RESOURCESUK_ABALONE_',				'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		3),
	('ICON_PROJECT_CREATE_CORPORATION_PRODUCT_SUK_ABALONE',			'ICON_ATLAS_RESOURCES_MONOPOLY_HD',	3),
	('ICON_MONOPOLIES_AND_CORPS_RESOURCE_SUK_ABALONE_FOW',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD_FOW',		3),
	('MONOPOLIES_AND_CORPS_RESOURCE_SUK_ABALONE',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		3),

	('ICON_MONOPOLIES_AND_CORPS_RESOURCE_SUK_CORAL',				'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		4),
	('ICON_PROJECT_CREATE_CORPORATION_PRODUCT_SUK_CORAL',			'ICON_ATLAS_RESOURCES_MONOPOLY_HD',	4),
	('ICON_MONOPOLIES_AND_CORPS_RESOURCE_SUK_CORAL_FOW',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD_FOW',		4),
	('MONOPOLIES_AND_CORPS_RESOURCE_SUK_CORAL',					'ICON_ATLAS_RESOURCES_MONOPOLY_HD',		4);