insert or ignore into IconTextureAtlases (Name, IconSize, IconsPerRow, IconsPerColumn, Filename) values
	('ICON_ATLAS_RESOURCES_HD',		  32,   8,  3,  'HD_Resources_32.dds'),
	('ICON_ATLAS_RESOURCES_HD',		  38,   8,  3,  'HD_Resources_38.dds'),
	('ICON_ATLAS_RESOURCES_HD',		  50,   8,  3,  'HD_Resources_50.dds'),
	('ICON_ATLAS_RESOURCES_HD',		  64,   8,  3,  'HD_Resources_64.dds'),
	('ICON_ATLAS_RESOURCES_HD',		  256,  8,  3,  'HD_Resources_256.dds'),
	('ICON_ATLAS_RESOURCES_HD_FOW',	256,  8,  3,  'HD_Resources_FOW_256.dds');

insert or ignore into IconTextureAtlases (Name, Baseline, IconSize, IconsPerRow, IconsPerColumn, Filename) values
	('ICON_ATLAS_RESOURCES_HD',  6,  22,   8,  3,  'HD_Resources_22.dds');

insert or replace into IconDefinitions (Name, Atlas, "Index") values
	('ICON_RESOURCE_ALOE',				'ICON_ATLAS_RESOURCES_HD',		0),
	('ICON_RESOURCE_ALOE_FOW',			'ICON_ATLAS_RESOURCES_HD_FOW',	0),
	('RESOURCE_ALOE',					'ICON_ATLAS_RESOURCES_HD',		0),

	('ICON_RESOURCE_MEDIHERBS',			'ICON_ATLAS_RESOURCES_HD',		1),
	('ICON_RESOURCE_MEDIHERBS_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	1),
	('RESOURCE_MEDIHERBS',				'ICON_ATLAS_RESOURCES_HD',		1),

	('ICON_RESOURCE_COD',				'ICON_ATLAS_RESOURCES_HD',		2),
	('ICON_RESOURCE_COD_FOW',			'ICON_ATLAS_RESOURCES_HD_FOW',	2),
	('RESOURCE_COD',					'ICON_ATLAS_RESOURCES_HD',		2),

	('ICON_RESOURCE_QUARTZ',			'ICON_ATLAS_RESOURCES_HD',		3),
	('ICON_RESOURCE_QUARTZ_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	3),
	('RESOURCE_QUARTZ',					'ICON_ATLAS_RESOURCES_HD',		3),

	('ICON_RESOURCE_SALMON',			'ICON_ATLAS_RESOURCES_HD',		4),
	('ICON_RESOURCE_SALMON_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	4),
	('RESOURCE_SALMON',					'ICON_ATLAS_RESOURCES_HD',		4),

	('ICON_RESOURCE_LIMESTONE',			'ICON_ATLAS_RESOURCES_HD',		5),
	('ICON_RESOURCE_LIMESTONE_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	5),
	('RESOURCE_LIMESTONE',				'ICON_ATLAS_RESOURCES_HD',		5),

	('ICON_RESOURCE_BARLEY',			'ICON_ATLAS_RESOURCES_HD',		6),
	('ICON_RESOURCE_BARLEY_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	6),
	('RESOURCE_BARLEY',					'ICON_ATLAS_RESOURCES_HD',		6),

	('ICON_RESOURCE_SEASHELLS',			'ICON_ATLAS_RESOURCES_HD',		8),
	('ICON_RESOURCE_SEASHELLS_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	8),
	('RESOURCE_SEASHELLS',				'ICON_ATLAS_RESOURCES_HD',		8),
	
	('ICON_RESOURCE_SORGHUM',			'ICON_ATLAS_RESOURCES_HD',		9),
	('ICON_RESOURCE_SORGHUM_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	9),
	('RESOURCE_SORGHUM',				'ICON_ATLAS_RESOURCES_HD',		9),
	
	('ICON_RESOURCE_HAM',			'ICON_ATLAS_RESOURCES_HD',		10),
	('ICON_RESOURCE_HAM_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	10),
	('RESOURCE_HAM',				'ICON_ATLAS_RESOURCES_HD',		10),

	('ICON_RESOURCE_OXEN',			'ICON_ATLAS_RESOURCES_HD',		11),
	('ICON_RESOURCE_OXEN_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	11),
	('RESOURCE_OXEN',				'ICON_ATLAS_RESOURCES_HD',		11),

	('ICON_RESOURCE_MAPLE',			'ICON_ATLAS_RESOURCES_HD',		12),
	('ICON_RESOURCE_MAPLE_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	12),
	('RESOURCE_MAPLE',				'ICON_ATLAS_RESOURCES_HD',		12),

	('ICON_RESOURCE_GOLD2',			'ICON_ATLAS_RESOURCES_HD',		13),
	('ICON_RESOURCE_GOLD2_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	13),
	('RESOURCE_GOLD2',				'ICON_ATLAS_RESOURCES_HD',		13),

	('ICON_RESOURCE_CAVIAR',			'ICON_ATLAS_RESOURCES_HD',		14),
	('ICON_RESOURCE_CAVIAR_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	14),
	('RESOURCE_CAVIAR',				'ICON_ATLAS_RESOURCES_HD',		14),

	('ICON_RESOURCE_MACKEREL',			'ICON_ATLAS_RESOURCES_HD',		15),
	('ICON_RESOURCE_MACKEREL_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	15),
	('RESOURCE_MACKEREL',				'ICON_ATLAS_RESOURCES_HD',		15),

	('ICON_RESOURCE_ALGAE',			'ICON_ATLAS_RESOURCES_HD',		16),
	('ICON_RESOURCE_ALGAE_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	16),
	('RESOURCE_ALGAE',				'ICON_ATLAS_RESOURCES_HD',		16),

	('ICON_RESOURCE_CORAL',			'ICON_ATLAS_RESOURCES_HD',		17),
	('ICON_RESOURCE_CORAL_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	17),
	('RESOURCE_CORAL',				'ICON_ATLAS_RESOURCES_HD',		17),

	('ICON_RESOURCE_POTATO',			'ICON_ATLAS_RESOURCES_HD',		18),
	('ICON_RESOURCE_POTATO_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	18),
	('RESOURCE_POTATO',				'ICON_ATLAS_RESOURCES_HD',		18),

	('ICON_RESOURCE_MUSHROOMS',			'ICON_ATLAS_RESOURCES_HD',		19),
	('ICON_RESOURCE_MUSHROOMS_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	19),
	('RESOURCE_MUSHROOMS',				'ICON_ATLAS_RESOURCES_HD',		19),

	('ICON_RESOURCE_SUK_CORAL',			'ICON_ATLAS_RESOURCES_HD',		20),
	('ICON_RESOURCE_SUK_CORAL_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	20),
	('RESOURCE_SUK_CORAL',				'ICON_ATLAS_RESOURCES_HD',		20),

	('ICON_RESOURCE_C_HEAVENLY_HORSE',			'ICON_ATLAS_RESOURCES_HD',		21),
	('ICON_RESOURCE_C_HEAVENLY_HORSE_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	21),
	('RESOURCE_C_HEAVENLY_HORSE',				'ICON_ATLAS_RESOURCES_HD',		21),

	('ICON_RESOURCE_C_ZEBU',			'ICON_ATLAS_RESOURCES_HD',		22),
	('ICON_RESOURCE_C_ZEBU_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	22),
	('RESOURCE_C_ZEBU',				'ICON_ATLAS_RESOURCES_HD',		22),

	('ICON_RESOURCE_JNR_PEAT',			'ICON_ATLAS_RESOURCES_HD',		23),
	('ICON_RESOURCE_JNR_PEAT_FOW',		'ICON_ATLAS_RESOURCES_HD_FOW',	23),
	('RESOURCE_JNR_PEAT',				'ICON_ATLAS_RESOURCES_HD',		23),
	
	('ICON_RESOURCE_HONEY',			'ICON_ATLAS_AMATHERIA',		41),
	('ICON_RESOURCE_HONEY_FOW',		'ICON_ATLAS_AMATHERIA_FOW',	41),
	('RESOURCE_HONEY',				'ICON_ATLAS_AMATHERIA',		41);