-- Custom rows are registered before map-specific configuration is applied.
INSERT OR IGNORE INTO Types (Type, Kind) VALUES
('MAPSIZE_ZYL_RVC_4', 'KIND_MAPSIZE'),
('MAPSIZE_ZYL_RVC_16', 'KIND_MAPSIZE'),
('MAPSIZE_ZYL_RVC_18', 'KIND_MAPSIZE');

INSERT OR IGNORE INTO Maps
(MapSizeType, Name, Description, DefaultPlayers, NumNaturalWonders, GridWidth, GridHeight, PlateValue, Continents)
VALUES
('MAPSIZE_ZYL_RVC_4', 'LOC_ZYL_RVC_MAPSIZE_4_NAME', 'LOC_ZYL_RVC_MAPSIZE_4_DESCRIPTION', 4, 3, 60, 48, 3, 2),
('MAPSIZE_ZYL_RVC_16', 'LOC_ZYL_RVC_MAPSIZE_16_NAME', 'LOC_ZYL_RVC_MAPSIZE_16_DESCRIPTION', 16, 8, 72, 106, 7, 6),
('MAPSIZE_ZYL_RVC_18', 'LOC_ZYL_RVC_MAPSIZE_18_NAME', 'LOC_ZYL_RVC_MAPSIZE_18_DESCRIPTION', 18, 8, 72, 112, 7, 6);

INSERT OR REPLACE INTO Map_GreatPersonClasses
(MapSizeType, GreatPersonClassType, MaxWorldInstances)
VALUES
('MAPSIZE_ZYL_RVC_4', 'GREAT_PERSON_CLASS_PROPHET', 7),
('MAPSIZE_ZYL_RVC_16', 'GREAT_PERSON_CLASS_PROPHET', 7),
('MAPSIZE_ZYL_RVC_18', 'GREAT_PERSON_CLASS_PROPHET', 7);
