-- 新着力点
insert or replace into Types (Type, Kind) values
  -- 翻译运动
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',			    'KIND_MOMENT_OUTCOME'),
  -- 繁荣之路
	('COMMEMORATION_HD_FLOURSHING_ROAD',					    'KIND_MOMENT_OUTCOME'),
  -- 筚路蓝缕
	('COMMEMORATION_HD_DOMESTIC_ASSART',					    'KIND_MOMENT_OUTCOME'),
  -- 信仰之战
	('COMMEMORATION_HD_RELIGIOUS_WAR',				        'KIND_MOMENT_OUTCOME'),
  -- 开明专制
	('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',		    'KIND_MOMENT_OUTCOME'),
  -- 宗教改革
	('COMMEMORATION_HD_RELIGIOUS_REFORM',		          'KIND_MOMENT_OUTCOME'),
  -- 浪漫主义
	('COMMEMORATION_HD_ROMANTICISM',		              'KIND_MOMENT_OUTCOME'),
  -- 科学革命
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',		    'KIND_MOMENT_OUTCOME'),
  -- 国际体系
	('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',		      'KIND_MOMENT_OUTCOME'),
  -- 灯火通明
	('COMMEMORATION_HD_ILLUMINATED_CITY',		          'KIND_MOMENT_OUTCOME'),
  -- 资本输出
	('COMMEMORATION_HD_CAPITAL_EXPORT',		            'KIND_MOMENT_OUTCOME'),
  -- 世界大战
	('COMMEMORATION_HD_WORLD_WAR',		                'KIND_MOMENT_OUTCOME'),
  -- 星球大战
	('COMMEMORATION_HD_STAR_WAR',		                  'KIND_MOMENT_OUTCOME'),
  -- 思想风暴
	('COMMEMORATION_HD_IDEOLOGY_STORM',		            'KIND_MOMENT_OUTCOME'),
  -- 巨型企业
	('COMMEMORATION_HD_MEGA_CORPORATION',		          'KIND_MOMENT_OUTCOME'),
  -- 数字革命
	('COMMEMORATION_HD_DIGITAL_REVOLUTION',		        'KIND_MOMENT_OUTCOME'),
  -- 全球市场
	('COMMEMORATION_HD_WORLD_MARKET',		              'KIND_MOMENT_OUTCOME'),
  -- 网络文化
	('COMMEMORATION_HD_CYBERCULTURE',		              'KIND_MOMENT_OUTCOME'),
  -- 军工复合
	('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX',	'KIND_MOMENT_OUTCOME'),
  -- 宇宙开发
	('COMMEMORATION_HD_COSMIC_EXPLOITATION',		      'KIND_MOMENT_OUTCOME');

insert or replace into CommemorationTypes
	(CommemorationType, CategoryDescription, GoldenAgeBonusDescription, NormalAgeBonusDescription, DarkAgeBonusDescription, MinimumGameEra, MaximumGameEra)
values
	-- 翻译运动
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT',
  'LOC_MOMENT_CATEGORY_TRANSLATION_MOVEMENT',
  'LOC_MOMENT_CATEGORY_TRANSLATION_MOVEMENT_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_TRANSLATION_MOVEMENT_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_TRANSLATION_MOVEMENT_BONUS_DARK_AGE',
  'ERA_MEDIEVAL',
  'ERA_MEDIEVAL'),
	-- 繁荣之路
  ('COMMEMORATION_HD_FLOURSHING_ROAD',
  'LOC_MOMENT_CATEGORY_FLOURSHING_ROAD',
  'LOC_MOMENT_CATEGORY_FLOURSHING_ROAD_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_FLOURSHING_ROAD_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_FLOURSHING_ROAD_BONUS_DARK_AGE',
  'ERA_MEDIEVAL',
  'ERA_MEDIEVAL'),
	-- 筚路蓝缕
  ('COMMEMORATION_HD_DOMESTIC_ASSART',
  'LOC_MOMENT_CATEGORY_DOMESTIC_ASSART',
  'LOC_MOMENT_CATEGORY_DOMESTIC_ASSART_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_DOMESTIC_ASSART_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_DOMESTIC_ASSART_BONUS_DARK_AGE',
  'ERA_MEDIEVAL',
  'ERA_MEDIEVAL'),
	-- 信仰之战
  ('COMMEMORATION_HD_RELIGIOUS_WAR',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_WAR',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_WAR_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_WAR_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_WAR_BONUS_DARK_AGE',
  'ERA_MEDIEVAL',
  'ERA_MEDIEVAL'),
	-- 开明专制
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',
  'LOC_MOMENT_CATEGORY_ENLIGHTENED_DESPOTISM',
  'LOC_MOMENT_CATEGORY_ENLIGHTENED_DESPOTISM_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_ENLIGHTENED_DESPOTISM_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_ENLIGHTENED_DESPOTISM_BONUS_DARK_AGE',
  'ERA_RENAISSANCE',
  'ERA_RENAISSANCE'),
	-- 宗教改革
  ('COMMEMORATION_HD_RELIGIOUS_REFORM',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_REFORM',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_REFORM_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_REFORM_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_RELIGIOUS_REFORM_BONUS_DARK_AGE',
  'ERA_RENAISSANCE',
  'ERA_RENAISSANCE'),
	-- 浪漫主义
  ('COMMEMORATION_HD_ROMANTICISM',
  'LOC_MOMENT_CATEGORY_ROMANTICISM',
  'LOC_MOMENT_CATEGORY_ROMANTICISM_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_ROMANTICISM_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_ROMANTICISM_BONUS_DARK_AGE',
  'ERA_INDUSTRIAL',
  'ERA_INDUSTRIAL'),
	-- 科学革命
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',
  'LOC_MOMENT_CATEGORY_SCIENTIFIC_REVOLUTION',
  'LOC_MOMENT_CATEGORY_SCIENTIFIC_REVOLUTION_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_SCIENTIFIC_REVOLUTION_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_SCIENTIFIC_REVOLUTION_BONUS_DARK_AGE',
  'ERA_INDUSTRIAL',
  'ERA_INDUSTRIAL'),
	-- 国际体系
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',
  'LOC_MOMENT_CATEGORY_INTERNATIONAL_SYSTEM',
  'LOC_MOMENT_CATEGORY_INTERNATIONAL_SYSTEM_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_INTERNATIONAL_SYSTEM_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_INTERNATIONAL_SYSTEM_BONUS_DARK_AGE',
  'ERA_INDUSTRIAL',
  'ERA_INDUSTRIAL'),
	-- 灯火通明
  ('COMMEMORATION_HD_ILLUMINATED_CITY',
  'LOC_MOMENT_CATEGORY_ILLUMINATED_CITY',
  'LOC_MOMENT_CATEGORY_ILLUMINATED_CITY_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_ILLUMINATED_CITY_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_ILLUMINATED_CITY_BONUS_DARK_AGE',
  'ERA_MODERN',
  'ERA_MODERN'),
	-- 资本输出
  ('COMMEMORATION_HD_CAPITAL_EXPORT',
  'LOC_MOMENT_CATEGORY_CAPITAL_EXPORT',
  'LOC_MOMENT_CATEGORY_CAPITAL_EXPORT_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_CAPITAL_EXPORT_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_CAPITAL_EXPORT_BONUS_DARK_AGE',
  'ERA_MODERN',
  'ERA_MODERN'),
	-- 世界大战
  ('COMMEMORATION_HD_WORLD_WAR',
  'LOC_MOMENT_CATEGORY_WORLD_WAR',
  'LOC_MOMENT_CATEGORY_WORLD_WAR_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_WORLD_WAR_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_WORLD_WAR_BONUS_DARK_AGE',
  'ERA_MODERN',
  'ERA_MODERN'),
	-- 星球大战
  ('COMMEMORATION_HD_STAR_WAR',
  'LOC_MOMENT_CATEGORY_STAR_WAR',
  'LOC_MOMENT_CATEGORY_STAR_WAR_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_STAR_WAR_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_STAR_WAR_BONUS_DARK_AGE',
  'ERA_ATOMIC',
  'ERA_ATOMIC'),
	-- 思想风暴
  ('COMMEMORATION_HD_IDEOLOGY_STORM',
  'LOC_MOMENT_CATEGORY_IDEOLOGY_STORM',
  'LOC_MOMENT_CATEGORY_IDEOLOGY_STORM_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_IDEOLOGY_STORM_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_IDEOLOGY_STORM_BONUS_DARK_AGE',
  'ERA_ATOMIC',
  'ERA_ATOMIC'),
	-- 巨型企业
  ('COMMEMORATION_HD_MEGA_CORPORATION',
  'LOC_MOMENT_CATEGORY_MEGA_CORPORATION',
  'LOC_MOMENT_CATEGORY_MEGA_CORPORATION_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_MEGA_CORPORATION_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_MEGA_CORPORATION_BONUS_DARK_AGE',
  'ERA_ATOMIC',
  'ERA_ATOMIC'),
	-- 数字革命
  ('COMMEMORATION_HD_DIGITAL_REVOLUTION',
  'LOC_MOMENT_CATEGORY_DIGITAL_REVOLUTION',
  'LOC_MOMENT_CATEGORY_DIGITAL_REVOLUTION_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_DIGITAL_REVOLUTION_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_DIGITAL_REVOLUTION_BONUS_DARK_AGE',
  'ERA_INFORMATION',
  'ERA_INFORMATION'),
	-- 全球市场
  ('COMMEMORATION_HD_WORLD_MARKET',
  'LOC_MOMENT_CATEGORY_WORLD_MARKET',
  'LOC_MOMENT_CATEGORY_WORLD_MARKET_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_WORLD_MARKET_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_WORLD_MARKET_BONUS_DARK_AGE',
  'ERA_INFORMATION',
  'ERA_INFORMATION'),
	-- 网络文化
  ('COMMEMORATION_HD_CYBERCULTURE',
  'LOC_MOMENT_CATEGORY_CYBERCULTURE',
  'LOC_MOMENT_CATEGORY_CYBERCULTURE_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_CYBERCULTURE_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_CYBERCULTURE_BONUS_DARK_AGE',
  'ERA_INFORMATION',
  'ERA_INFORMATION'),
	-- 军工复合
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX',
  'LOC_MOMENT_CATEGORY_MILITARY_INDUSTRIAL_COMPLEX',
  'LOC_MOMENT_CATEGORY_MILITARY_INDUSTRIAL_COMPLEX_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_MILITARY_INDUSTRIAL_COMPLEX_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_MILITARY_INDUSTRIAL_COMPLEX_BONUS_DARK_AGE',
  'ERA_INFORMATION',
  'ERA_INFORMATION'),
	-- 宇宙开发
  ('COMMEMORATION_HD_COSMIC_EXPLOITATION',
  'LOC_MOMENT_CATEGORY_COSMIC_EXPLOITATION',
  'LOC_MOMENT_CATEGORY_COSMIC_EXPLOITATION_BONUS_GOLDEN_AGE',
  'LOC_MOMENT_CATEGORY_COSMIC_EXPLOITATION_BONUS_NORMAL_AGE',
  'LOC_MOMENT_CATEGORY_COSMIC_EXPLOITATION_BONUS_DARK_AGE',
  'ERA_FUTURE',
  null);

update CommemorationTypes set
  GoldenAgeBonusDescription = 'LOC_MOMENT_CATEGORY_MEGA_CORPORATION_BONUS_GOLDEN_AGE_CORP',
  NormalAgeBonusDescription = 'LOC_MOMENT_CATEGORY_MEGA_CORPORATION_BONUS_NORMAL_AGE_CORP',
  DarkAgeBonusDescription = 'LOC_MOMENT_CATEGORY_MEGA_CORPORATION_BONUS_DARK_AGE_CORP'
where CommemorationType = 'COMMEMORATION_HD_MEGA_CORPORATION' and exists (select ImprovementType from Improvements where ImprovementType = 'IMPROVEMENT_CORPORATION');

update CommemorationTypes set
  GoldenAgeBonusDescription = 'LOC_MOMENT_CATEGORY_CYBERCULTURE_BONUS_GOLDEN_AGE_CORP',
  NormalAgeBonusDescription = 'LOC_MOMENT_CATEGORY_CYBERCULTURE_BONUS_NORMAL_AGE_CORP',
  DarkAgeBonusDescription = 'LOC_MOMENT_CATEGORY_CYBERCULTURE_BONUS_DARK_AGE_CORP'
where CommemorationType = 'COMMEMORATION_HD_CYBERCULTURE' and exists (select ImprovementType from Improvements where ImprovementType = 'IMPROVEMENT_CORPORATION');

-- 着力点时代改动
  -- 自然哲学 轴心时代 雄伟壮丽 光荣胜利
update CommemorationTypes set MinimumGameEra = 'ERA_CLASSICAL', MaximumGameEra = 'ERA_CLASSICAL'
  where CommemorationType in ('COMMEMORATION_SCIENTIFIC', 'COMMEMORATION_CULTURAL', 'COMMEMORATION_INFRASTRUCTURE', 'COMMEMORATION_RELIGIOUS');
  -- 原始积累 此处有龙
update CommemorationTypes set MinimumGameEra = 'ERA_RENAISSANCE', MaximumGameEra = 'ERA_RENAISSANCE'
  where CommemorationType in ('COMMEMORATION_ECONOMIC', 'COMMEMORATION_EXPLORATION');
  -- 滚滚蒸汽
update CommemorationTypes set MinimumGameEra = 'ERA_INDUSTRIAL', MaximumGameEra = 'ERA_INDUSTRIAL'
  where CommemorationType in ('COMMEMORATION_INDUSTRIAL');
  -- 兵不厌诈
update CommemorationTypes set MinimumGameEra = 'ERA_MODERN', MaximumGameEra = 'ERA_MODERN'
  where CommemorationType in ('COMMEMORATION_ESPIONAGE');
  -- 全民皆兵
update CommemorationTypes set MinimumGameEra = 'ERA_ATOMIC', MaximumGameEra = 'ERA_ATOMIC'
  where CommemorationType in ('COMMEMORATION_MILITARY');
  -- 空间旅行 人工智能 机甲战争
update CommemorationTypes set MinimumGameEra = 'ERA_FUTURE', MaximumGameEra = null
  where CommemorationType in ('COMMEMORATION_TOURISM', 'COMMEMORATION_AERONAUTICAL', 'COMMEMORATION_AUTOMATON');

-- 着力点效果
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_SCIENTIFIC' and ModifierId not in ('COMMEMORATION_SCIENTIFIC_QUEST', 'COMMEMORATION_SCIENTIFIC_BUILDING_QUEST');
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_CULTURAL' and ModifierId not in ('COMMEMORATION_CULTURAL_QUEST', 'COMMEMORATION_CULTURAL_BUILDING_QUEST');
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_INFRASTRUCTURE' and ModifierId not in ('COMMEMORATION_INFRASTRUCTURE_QUEST');
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_RELIGIOUS';
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_ECONOMIC';
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_EXPLORATION' and ModifierId = 'COMMEMORATION_EXPLORATION_GA_FOREIGNIDENTITY';
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_INDUSTRIAL' and ModifierId = 'COMMEMORATION_INUDSTRIAL_GA_CAMPUS';
delete from CommemorationModifiers where CommemorationType = 'COMMEMORATION_AERONAUTICAL' and ModifierId in (
  'COMMEMORATION_AERONAUTICAL_GREAT_PERSON_QUEST',
  'COMMEMORATION_AERONAUTICAL_GA_SATELLITES',
  'COMMEMORATION_AERONAUTICAL_GA_NUCLEAR_FUSION',
  'COMMEMORATION_AERONAUTICAL_GA_NANOTECHNOLOGY',
  'COMMEMORATION_AERONAUTICAL_GA_SMART_MATERIALS',
  'COMMEMORATION_AERONAUTICAL_GA_PREDICTIVE_SYSTEMS',
  'COMMEMORATION_AERONAUTICAL_GA_OFFWORLD_MISSION',
  'COMMEMORATION_AERONAUTICAL_GA_AIR',
  'COMMEMORATION_AERONAUTICAL_GA_ALUMINUM'
);

-- ==================================================================================================================================================================
-- CommemorationModifiers
-- ==================================================================================================================================================================
insert or replace into CommemorationModifiers (CommemorationType, ModifierId) values
  -- 自然哲学
  ('COMMEMORATION_SCIENTIFIC',                  'COMMEMORATION_SCIENTIFIC_DISTRICT_SCIENCE'),
  ('COMMEMORATION_SCIENTIFIC',                  'COMMEMORATION_SCIENTIFIC_DISTRICT_CULTURE'),
  -- 轴心时代
  ('COMMEMORATION_CULTURAL',                    'COMMEMORATION_CULTURAL_DISTRICT_FAITH'),
  ('COMMEMORATION_CULTURAL',                    'COMMEMORATION_CULTURAL_DISTRICT_CULTURE'),
  ('COMMEMORATION_CULTURAL',                    'COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS'),
  -- 雄伟壮丽
	('COMMEMORATION_INFRASTRUCTURE',	            'COMMEMORATION_INFRASTRUCTURE_EXTRA_DISTRICT'),
	('COMMEMORATION_INFRASTRUCTURE',	            'COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION'),
	('COMMEMORATION_INFRASTRUCTURE',	            'COMMEMORATION_INFRASTRUCTURE_YIELD_BONUS'),
  -- 光荣胜利
	('COMMEMORATION_RELIGIOUS',     	            'COMMEMORATION_RELIGIOUS_UNIT_SPEED_SIGHT'),
	('COMMEMORATION_RELIGIOUS',     	            'COMMEMORATION_RELIGIOUS_UNIT_STRENGTH'),
	('COMMEMORATION_RELIGIOUS',     	            'COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_GOLD'),
  -- 翻译运动
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_DISTRICT_PRODUCTION'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_BUILDING_PRODUCTION'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_DISTRICT_PRODUCTION'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_BUILDING_PRODUCTION'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS_RECORD'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS'),
	('COMMEMORATION_HD_TRANSLATION_MOVEMENT',     'COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS_RECORD'),
  -- 繁荣之路
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_INDUSTRIAL_BONUS'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_COMMERCIAL_BONUS'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_HARBOR_BONUS'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_SCIENCE'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_CULTURE'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_GOLD'),
	('COMMEMORATION_HD_FLOURSHING_ROAD',          'COMMEMORATION_ECONOMIC_QUEST'),
  -- 筚路蓝缕
	('COMMEMORATION_HD_DOMESTIC_ASSART',          'COMMEMORATION_HD_DOMESTIC_ASSART_CIVILIAN_SPEED'),
	('COMMEMORATION_HD_DOMESTIC_ASSART',          'COMMEMORATION_HD_DOMESTIC_ASSART_GRANT_BUILDER'),
	('COMMEMORATION_HD_DOMESTIC_ASSART',          'COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_FOOD'),
	('COMMEMORATION_HD_DOMESTIC_ASSART',          'COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_PRODUCTION'),
  -- 信仰之战
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_MILITARY_SPEED'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_IMPROVEMENT'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_DISTRICT'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_SPEED'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_CHARGE'),
	('COMMEMORATION_HD_RELIGIOUS_WAR',            'COMMEMORATION_RELIGIOUS_QUEST'),
  -- 开明专制
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',		'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_ADD_SLOT'),
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',		'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_EXTRA_DISTRICT'),
  -- 原始积累
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_EXTRA_GREAT_MERCHANT_POINTS'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_EXTRA_GREAT_ENGINEER_POINTS'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_TRADE_GOLD'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_TRADE_PRODUCTION'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_GOLD_PURCHASE_BUILDING'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_GOLD_PURCHASE_DISTRICT'),
  ('COMMEMORATION_ECONOMIC',		                'COMMEMORATION_ECONOMIC_GOLD_PURCHASE_UNIT'),
  -- 宗教改革
  ('COMMEMORATION_HD_RELIGIOUS_REFORM',         'COMMEMORATION_HD_RELIGIOUS_REFORM_SCIENCE_CULTURE_FAITH'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM',         'COMMEMORATION_HD_RELIGIOUS_REFORM_HOLY_SITE_BONUS'),
  -- 此处有龙
  ('COMMEMORATION_EXPLORATION',		              'COMMEMORATION_EXPLORATION_CIVILIAN_SPEED'),
	('COMMEMORATION_EXPLORATION',		              'COMMEMORATION_EXPLORATION_DISTRICT_PRODUCTION'),
  -- 国际体系
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',     'COMMEMORATION_HD_INTERNATIONAL_SYSTEM_INFLUENCE_BONUS'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',     'COMMEMORATION_HD_INTERNATIONAL_SYSTEM_FAVOR_BONUS'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',     'COMMEMORATION_HD_INTERNATIONAL_SYSTEM_SCIENCE_FROM_ALLY'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',     'COMMEMORATION_HD_INTERNATIONAL_SYSTEM_CULTURE_FROM_ALLY'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',     'COMMEMORATION_HD_INTERNATIONAL_SYSTEM_GOLD_FROM_ALLY'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',     'COMMEMORATION_HD_INTERNATIONAL_SYSTEM_SCIENCE_FROM_CITYSTATE'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',     'COMMEMORATION_HD_INTERNATIONAL_SYSTEM_CULTURE_FROM_CITYSTATE'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM',     'COMMEMORATION_HD_INTERNATIONAL_SYSTEM_GOLD_FROM_CITYSTATE'),
  -- 浪漫主义
	('COMMEMORATION_HD_ROMANTICISM',              'COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_WRITER_POINTS'),
	('COMMEMORATION_HD_ROMANTICISM',              'COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_ARTIST_POINTS'),
	('COMMEMORATION_HD_ROMANTICISM',              'COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_MUSICIAN_POINTS'),
  -- 科学革命
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',    'COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_EXTRA_GREAT_SCIENTIST_POINTS'),
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',    'COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS'),
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION',    'COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS_RECORD'),
  -- 灯火通明
  ('COMMEMORATION_HD_ILLUMINATED_CITY',         'COMMEMORATION_HD_ILLUMINATED_CITY_POWER_REGIONAL_RANGE'),
  -- 资本输出
  ('COMMEMORATION_HD_CAPITAL_EXPORT',           'COMMEMORATION_HD_CAPITAL_EXPORT_SEND_ENVOY'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT',           'COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_PRODUCTION_1'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT',           'COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_SCIENCE_1'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT',           'COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_CULTURE_1'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT',           'COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_GOLD_1'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT',           'COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_PRODUCTION_2'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT',           'COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_SCIENCE_2'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT',           'COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_CULTURE_2'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT',           'COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_GOLD_2'),
  -- 世界大战
  ('COMMEMORATION_HD_WORLD_WAR',                'COMMEMORATION_HD_WORLD_WAR_GRANT_GENERAL'),
  ('COMMEMORATION_HD_WORLD_WAR',                'COMMEMORATION_HD_WORLD_WAR_GENERAL_POINTS'),
  ('COMMEMORATION_HD_WORLD_WAR',                'COMMEMORATION_HD_WORLD_WAR_CORP_STRENGTH'),
  ('COMMEMORATION_HD_WORLD_WAR',                'COMMEMORATION_HD_WORLD_WAR_ARMY_STRENGTH'),
  ('COMMEMORATION_HD_WORLD_WAR',                'COMMEMORATION_HD_WORLD_WAR_PRODUCTION'),
  -- 兵不厌诈
  ('COMMEMORATION_ESPIONAGE',                   'COMMEMORATION_ESPIONAGE_SPY_CAPACITY'),
  ('COMMEMORATION_ESPIONAGE',                   'COMMEMORATION_ESPIONAGE_GRANT_SPY'),
  -- 星球大战
  ('COMMEMORATION_HD_STAR_WAR',                 'COMMEMORATION_HD_STAR_WAR_SPACEPORT_PRODUCTION'),
  ('COMMEMORATION_HD_STAR_WAR',                 'COMMEMORATION_HD_STAR_WAR_SPACE_RACE_PRODUCTION'),
  ('COMMEMORATION_HD_STAR_WAR',                 'COMMEMORATION_HD_STAR_WAR_SCIENTIST_POINTS_ATTACH'),
  ('COMMEMORATION_HD_STAR_WAR',                 'COMMEMORATION_HD_STAR_WAR_ENGINEER_POINTS_ATTACH'),
  -- 思想风暴
  ('COMMEMORATION_HD_IDEOLOGY_STORM',           'COMMEMORATION_HD_IDEOLOGY_STORM_FREE_CIVIC'),
  ('COMMEMORATION_HD_IDEOLOGY_STORM',           'COMMEMORATION_HD_IDEOLOGY_STORM_CIVIC_BOOST'),
  ('COMMEMORATION_HD_IDEOLOGY_STORM',           'COMMEMORATION_HD_IDEOLOGY_STORM_CIVIC_BOOST_RECORD'),
  ('COMMEMORATION_HD_IDEOLOGY_STORM',           'COMMEMORATION_AERONAUTICAL_GREAT_PERSON_QUEST'),
  -- 巨型企业
  ('COMMEMORATION_HD_MEGA_CORPORATION',         'COMMEMORATION_HD_MEGA_CORPORATION_GRANT_MERCHANT'),
  ('COMMEMORATION_HD_MEGA_CORPORATION',         'COMMEMORATION_HD_MEGA_CORPORATION_EXTRA_DISTRICT_ATTACH'),
  ('COMMEMORATION_HD_MEGA_CORPORATION',         'COMMEMORATION_HD_MEGA_CORPORATION_PRODUCTION_ATTACH'),
  ('COMMEMORATION_HD_MEGA_CORPORATION',         'COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_BUILDING_ATTACH'),
  ('COMMEMORATION_HD_MEGA_CORPORATION',         'COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_DISTRICT_ATTACH'),
  ('COMMEMORATION_HD_MEGA_CORPORATION',         'COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_UNIT_ATTACH'),
  -- 全民皆兵
	('COMMEMORATION_MILITARY',                    'COMMEMORATION_MILITARY_STRENGTH'),
  -- 数字革命
  ('COMMEMORATION_HD_DIGITAL_REVOLUTION',       'COMMEMORATION_HD_DIGITAL_REVOLUTION_GRANT_SCIENTIST'),
  ('COMMEMORATION_HD_DIGITAL_REVOLUTION',       'COMMEMORATION_HD_DIGITAL_REVOLUTION_SCIENCE'),
  -- 全球市场
  ('COMMEMORATION_HD_WORLD_MARKET',             'COMMEMORATION_HD_WORLD_MARKET_TRADE_YIELD'),
  ('COMMEMORATION_HD_WORLD_MARKET',             'COMMEMORATION_HD_WORLD_MARKET_TRADE_TOURISM'),
  -- 网络文化
  ('COMMEMORATION_HD_CYBERCULTURE',             'COMMEMORATION_HD_CYBERCULTURE_INTERNET_COMPANY_PURCHASE'),
  ('COMMEMORATION_HD_CYBERCULTURE',             'COMMEMORATION_HD_CYBERCULTURE_ROCK_BAND_PURCHASE'),
  ('COMMEMORATION_HD_CYBERCULTURE',             'COMMEMORATION_HD_CYBERCULTURE_CULTURE'),
  ('COMMEMORATION_HD_CYBERCULTURE',             'COMMEMORATION_HD_CYBERCULTURE_GOLD'),
  -- 军工复合
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX',  'COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_ABILITY'),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX',  'COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_PROPERTY_ATTACH'),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX',  'COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_INFLUENCE_ATTACH'),
  -- 空间旅行
	('COMMEMORATION_TOURISM',                     'COMMEMORATION_TOURISM_IMPROVEMENT'),
	('COMMEMORATION_TOURISM',                     'COMMEMORATION_TOURISM_MOVEMENT'),
  -- 宇宙开发
	('COMMEMORATION_HD_COSMIC_EXPLOITATION',      'COMMEMORATION_HD_COSMIC_EXPLOITATION_RESOURCE_SCIENCE'),
  -- 人工智能
	('COMMEMORATION_AERONAUTICAL',                'COMMEMORATION_AERONAUTICAL_ALL_TECH_BOOST'),
	('COMMEMORATION_AERONAUTICAL',                'COMMEMORATION_AERONAUTICAL_FREE_TECH'),
	('COMMEMORATION_AERONAUTICAL',                'COMMEMORATION_AERONAUTICAL_PRODUCTION');

  
  -- 信仰之战
insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
  'COMMEMORATION_HD_RELIGIOUS_WAR',             'COMMEMORATION_HD_RELIGIOUS_WAR_PILLAGE_' || ImprovementType || '_SCIENCE'
from Improvements where PlunderType != 'NO_PLUNDER';

insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
  'COMMEMORATION_HD_RELIGIOUS_WAR',             'COMMEMORATION_HD_RELIGIOUS_WAR_PILLAGE_' || ImprovementType || '_CULTURE'
from Improvements where PlunderType != 'NO_PLUNDER';

  -- 开明专制
insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
  'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM',     'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_BONUS'
from DistrictCorrespondingYieldType_HD a, Districts b
	where a.HasAdjacency = 1 and b.DistrictType in ('DISTRICT_GOVERNMENT', 'DISTRICT_DIPLOMATIC_QUARTER');

  -- 浪漫主义
insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
	'COMMEMORATION_HD_ROMANTICISM',			          'COMMEMORATION_HD_ROMANTICISM_' || GreatWorkObjectType || '_TOURISM_MODIFIER'
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

  -- 滚滚蒸汽
insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
  'COMMEMORATION_INDUSTRIAL', 'COMMEMORATION_INDUSTRIAL_BUILDING_' || YieldType || '_BONUS'
from Yields;

insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
  'COMMEMORATION_INDUSTRIAL', 'COMMEMORATION_INDUSTRIAL_REGIONAL_' || YieldType || '_BONUS'
from Yields;

  -- 灯火通明
insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
  'COMMEMORATION_HD_ILLUMINATED_CITY', 'COMMEMORATION_HD_ILLUMINATED_CITY_' || BuildingType || '_PURCHASE'
from Buildings where BuildingType in ('BUILDING_COAL_POWER_PLANT', 'BUILDING_FOSSIL_FUEL_POWER_PLANT', 'BUILDING_POWER_PLANT', 'BUILDING_HYDROELECTRIC_DAM');

insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
  'COMMEMORATION_HD_ILLUMINATED_CITY', 'COMMEMORATION_HD_ILLUMINATED_CITY_' || DistrictType || '_REGIONAL_RANGE'
from DistrictCorrespondingYieldType_HD;

-- 思想风暴
insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
  'COMMEMORATION_HD_IDEOLOGY_STORM', 'COMMEMORATION_HD_IDEOLOGY_STORM_' || BuildingType || '_TOURISM'
from Buildings where PrereqDistrict = 'DISTRICT_GOVERNMENT' and GovernmentTierRequirement = 'Tier3';

-- 网络文化
insert or replace into CommemorationModifiers (CommemorationType, ModifierId) select
  'COMMEMORATION_HD_CYBERCULTURE', 'COMMEMORATION_HD_CYBERCULTURE_' || GreatWorkObjectType || '_ATTACH'
from GreatWorkObjectTypes;

-- ==================================================================================================================================================================
-- Modifiers
-- ==================================================================================================================================================================
insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) values
  -- 自然哲学
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_SCIENCE',                           'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',                    'PLAYER_HAS_GOLDEN_AGE',    'HD_COMMEMORATION_SCIENTIFIC_DISTRICT_REQUIREMENTS'),
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_CULTURE',                           'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',                    'PLAYER_HAS_GOLDEN_AGE',    'HD_COMMEMORATION_SCIENTIFIC_DISTRICT_REQUIREMENTS'),
  -- 轴心时代
  ('COMMEMORATION_CULTURAL_DISTRICT_FAITH',                               'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',                    'PLAYER_HAS_GOLDEN_AGE',    'HD_DISTRICTS_IS_NOT_WONDERS_REQUIREMENTS'),
  ('COMMEMORATION_CULTURAL_DISTRICT_CULTURE',                             'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',                    'PLAYER_HAS_GOLDEN_AGE',    'HD_DISTRICTS_IS_NOT_WONDERS_REQUIREMENTS'),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS',                 'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',                        'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_SPECIALTY_DISTRICT_REQUIREMENTS'),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS_MODIFIER',        'MODIFIER_PLAYER_DISTRICT_ADJUST_GREAT_PERSON_POINTS',              Null,                       Null),
  -- 雄伟壮丽
  ('COMMEMORATION_INFRASTRUCTURE_EXTRA_DISTRICT',                         'MODIFIER_PLAYER_CITIES_EXTRA_DISTRICT',                            'PLAYER_HAS_GOLDEN_AGE',    'BUILDING_IS_PALACE'),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'MODIFIER_PLAYER_CITIES_ADJUST_WONDER_ERA_PRODUCTION',              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_INFRASTRUCTURE_YIELD_BONUS',                            'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',                'PLAYER_HAS_GOLDEN_AGE',    'DL_CITY_HAS_WONDER_REQUIREMENTS'),
  -- 光荣胜利
  ('COMMEMORATION_RELIGIOUS_UNIT_SPEED_SIGHT',                            'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_RELIGIOUS_UNIT_STRENGTH',                               'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_GOLD',                         'MODIFIER_PLAYER_ADJUST_GOLD_DISPERSAL',                            'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 翻译运动
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_DISTRICT_PRODUCTION',    'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION',                'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_BUILDING_PRODUCTION',    'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION',                'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_DISTRICT_PRODUCTION',   'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION',                'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_BUILDING_PRODUCTION',   'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PRODUCTION',                'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS',              'MODIFIER_PLAYER_ADJUST_TECHNOLOGY_BOOST',                          'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS_RECORD',       'MODIFIER_PLAYER_ADJUST_PROPERTY',                                  'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS',             'MODIFIER_PLAYER_ADJUST_CIVIC_BOOST',                               'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS_RECORD',      'MODIFIER_PLAYER_ADJUST_PROPERTY',                                  'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 繁荣之路
  ('COMMEMORATION_HD_FLOURSHING_ROAD_INDUSTRIAL_BONUS',                   'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',                  'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_INDUSTRIAL_ZONE'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_COMMERCIAL_BONUS',                   'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',                  'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_COMMERCIAL_HUB'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_HARBOR_BONUS',                       'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',                  'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_HARBOR'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_SCIENCE',                      'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_CULTURE',                      'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_GOLD',                         'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 筚路蓝缕
  ('COMMEMORATION_HD_DOMESTIC_ASSART_CIVILIAN_SPEED',                     'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_GRANT_BUILDER',                      'MODIFIER_PLAYER_BUILT_CITIES_GRANT_FREE_UNIT',                     'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_FOOD',                     'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_BY_NUMBER_RESOURCES',          'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_PRODUCTION',               'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_BY_NUMBER_RESOURCES',          'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 信仰之战
  ('COMMEMORATION_HD_RELIGIOUS_WAR_MILITARY_SPEED',                       'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_IMPROVEMENT',           'MODIFIER_PLAYER_ADJUST_IMPROVEMENT_PILLAGE',                       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_DISTRICT',              'MODIFIER_PLAYER_ADJUST_DISTRICT_PILLAGE',                          'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_SPEED',                      'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_CHARGE',                     'MODIFIER_PLAYER_UNITS_RELIGIOUS_SPREADS',                          'PLAYER_HAS_GOLDEN_AGE',    'UNIT_IS_RELIGIOUS'),
  -- 开明专制
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_ADD_SLOT',		                  'MODIFIER_PLAYER_CULTURE_ADJUST_GOVERNMENT_SLOTS_MODIFIER',		      'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_EXTRA_DISTRICT',		            'MODIFIER_PLAYER_CITIES_EXTRA_DISTRICT',		                        'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 原始积累
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_MERCHANT_POINTS',		              'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',		            'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_ENGINEER_POINTS',		              'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',		            'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_TRADE_GOLD',		                                'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD',                         'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_TRADE_PRODUCTION',		                          'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD',                         'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_BUILDING',		                    'MODIFIER_PLAYER_CITIES_ADJUST_ALL_BUILDINGS_PURCHASE_COST',	      'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_DISTRICT',		                    'MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PURCHASE_COST',	      'PLAYER_HAS_GOLDEN_AGE',	  Null),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_UNIT',		                        'MODIFIER_PLAYER_CITIES_ADJUST_UNITS_PURCHASE_COST',		            'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 宗教改革
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_SCIENCE_CULTURE_FAITH',		          'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',		            'PLAYER_HAS_GOLDEN_AGE',	  'HD_CITY_HAS_RELIGIOUS_TIER_3_BUILDING_REQUIREMENTS'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_HOLY_SITE_BONUS',		                'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',		              'PLAYER_HAS_GOLDEN_AGE',	  'DISTRICT_IS_HOLY_SITE'),
  -- 此处有龙
  ('COMMEMORATION_EXPLORATION_CIVILIAN_SPEED',		                        'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',						                  'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_EXPLORATION_DISTRICT_PRODUCTION',	                      'MODIFIER_PLAYER_CITIES_ADJUST_ALL_DISTRICTS_PRODUCTION',	          'PLAYER_HAS_GOLDEN_AGE',	  'CITY_HAS_0_SPECIALTY_DISTRICTS_REQUIREMENTS'),
  -- 国际体系
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_INFLUENCE_BONUS',               'MODIFIER_PLAYER_GOVERNMENT_FLAT_BONUS',                            'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_FAVOR_BONUS',                   'MODIFIER_PLAYER_ADJUST_SUZERAIN_FAVOR_MULTIPLIER',                 'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_SCIENCE_FROM_ALLY',             'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_ALLY_ROUTE',   'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_CULTURE_FROM_ALLY',             'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_ALLY_ROUTE',   'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_GOLD_FROM_ALLY',                'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_ALLY_ROUTE',   'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_SCIENCE_FROM_CITYSTATE',        'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_SUZERAIN_ROUTE',  'PLAYER_HAS_GOLDEN_AGE', Null),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_CULTURE_FROM_CITYSTATE',        'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_SUZERAIN_ROUTE',  'PLAYER_HAS_GOLDEN_AGE', Null),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_GOLD_FROM_CITYSTATE',           'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_ORIGIN_YIELD_FOR_SUZERAIN_ROUTE',  'PLAYER_HAS_GOLDEN_AGE', Null),
  -- 浪漫主义
  ('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_WRITER_POINTS',		          'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',	              'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_ARTIST_POINTS',	            'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',               'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_MUSICIAN_POINTS',	          'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',               'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 科学革命
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_EXTRA_GREAT_SCIENTIST_POINTS',	'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',               'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS',	            'MODIFIER_PLAYER_ADJUST_TECHNOLOGY_BOOST',                          'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS_RECORD',	    'MODIFIER_PLAYER_ADJUST_PROPERTY',                                  'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 灯火通明
  ('COMMEMORATION_HD_ILLUMINATED_CITY_POWER_REGIONAL_RANGE',              'MODIFIER_PLAYER_DISTRICTS_ADJUST_EXTRA_REGIONAL_RANGE',            'PLAYER_HAS_GOLDEN_AGE',    'REQUIRES_DISTRICT_IS_DISTRICT_INDUSTRIAL_ZONE_UDMET'),
  -- 资本输出
  ('COMMEMORATION_HD_CAPITAL_EXPORT_SEND_ENVOY',                          'MODIFIER_PLAYER_ADJUST_TOKEN_ON_TRADE_ROUTE_STARTED',              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_PRODUCTION_1',                  'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_SCIENCE_1',                     'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_CULTURE_1',                     'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_GOLD_1',                        'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_PRODUCTION_2',                  'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_SCIENCE_2',                     'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_CULTURE_2',                     'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_GOLD_2',                        'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL',       'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 世界大战
  ('COMMEMORATION_HD_WORLD_WAR_GRANT_GENERAL',                            'MODIFIER_CAPITAL_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY',           'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_WORLD_WAR_GENERAL_POINTS',                           'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',               'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_WORLD_WAR_CORP_STRENGTH',                            'MODIFIER_PLAYER_CORPS_ARMY_MODIFIED_STRENGTH',                     'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_WORLD_WAR_ARMY_STRENGTH',                            'MODIFIER_PLAYER_CORPS_ARMY_MODIFIED_STRENGTH',                     'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_WORLD_WAR_PRODUCTION',                               'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',                'PLAYER_HAS_GOLDEN_AGE',    'REQUIRES_CITY_HAS_DISTRICT_ENCAMPMENT_UDMET'),
  -- 兵不厌诈
  ('COMMEMORATION_ESPIONAGE_SPY_CAPACITY',                                'MODIFIER_PLAYER_GRANT_SPY',                                        'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_ESPIONAGE_GRANT_SPY',                                   'MODIFIER_PLAYER_GRANT_UNIT_IN_CAPITAL',                            'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 宇宙大战
  ('COMMEMORATION_HD_STAR_WAR_SPACEPORT_PRODUCTION',                      'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION',                'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_STAR_WAR_SPACE_RACE_PRODUCTION',                     'MODIFIER_PLAYER_CITIES_ADJUST_SPACE_RACE_PROJECTS_PRODUCTION',     'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_STAR_WAR_SCIENTIST_POINTS_ATTACH',                   'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',                        'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_DISTRICT_SPACEPORT_REQUIREMENTS'),
  ('COMMEMORATION_HD_STAR_WAR_ENGINEER_POINTS_ATTACH',                    'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',                        'PLAYER_HAS_GOLDEN_AGE',    'DISTRICT_IS_DISTRICT_SPACEPORT_REQUIREMENTS'),
  ('COMMEMORATION_HD_STAR_WAR_SCIENTIST_POINTS',                          'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',               Null,                       Null),
  ('COMMEMORATION_HD_STAR_WAR_ENGINEER_POINTS',                           'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_POINTS_PERCENT',               Null,                       Null),
  -- 思想风暴
  ('COMMEMORATION_HD_IDEOLOGY_STORM_FREE_CIVIC',                          'MODIFIER_PLAYER_ADJUST_PROPERTY',                                  'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_IDEOLOGY_STORM_CIVIC_BOOST',                         'MODIFIER_PLAYER_ADJUST_CIVIC_BOOST',                               'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_IDEOLOGY_STORM_CIVIC_BOOST_RECORD',                  'MODIFIER_PLAYER_ADJUST_PROPERTY',                                  'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 巨型企业
  ('COMMEMORATION_HD_MEGA_CORPORATION_GRANT_MERCHANT',                    'MODIFIER_CAPITAL_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY',           'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_MEGA_CORPORATION_EXTRA_DISTRICT_ATTACH',             'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                           'PLAYER_HAS_GOLDEN_AGE',    'CITY_HAS_DISTRICT_COMMERCIAL_HUB_TIER_4_BUILDING_REQUIREMENTS'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PRODUCTION_ATTACH',                 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                           'PLAYER_HAS_GOLDEN_AGE',    'CITY_HAS_DISTRICT_COMMERCIAL_HUB_TIER_4_BUILDING_REQUIREMENTS'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_BUILDING_ATTACH',          'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                           'PLAYER_HAS_GOLDEN_AGE',    'CITY_HAS_DISTRICT_COMMERCIAL_HUB_TIER_4_BUILDING_REQUIREMENTS'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_DISTRICT_ATTACH',          'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                           'PLAYER_HAS_GOLDEN_AGE',    'CITY_HAS_DISTRICT_COMMERCIAL_HUB_TIER_4_BUILDING_REQUIREMENTS'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_UNIT_ATTACH',              'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                           'PLAYER_HAS_GOLDEN_AGE',    'CITY_HAS_DISTRICT_COMMERCIAL_HUB_TIER_4_BUILDING_REQUIREMENTS'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_EXTRA_DISTRICT',                    'MODIFIER_SINGLE_CITY_EXTRA_DISTRICT',                              Null,                       Null),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PRODUCTION',                        'MODIFIER_SINGLE_CITY_ADJUST_CITY_YIELD_MODIFIER',                  Null,                       Null),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_BUILDING',                 'MODIFIER_SINGLE_CITY_ADJUST_ALL_BUILDINGS_PURCHASE_COST',          Null,                       Null),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_DISTRICT',                 'MODIFIER_SINGLE_CITY_ADJUST_ALL_DISTRICTS_PURCHASE_COST',          Null,                       Null),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_UNIT',                     'MODIFIER_SINGLE_CITY_ADJUST_ALL_UNITS_PURCHASE_COST',              Null,                       Null),
  -- 全民皆兵
	('COMMEMORATION_MILITARY_STRENGTH',	                                    'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 数字革命
  ('COMMEMORATION_HD_DIGITAL_REVOLUTION_GRANT_SCIENTIST',                 'MODIFIER_CAPITAL_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY',           'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_DIGITAL_REVOLUTION_SCIENCE',                         'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',                'PLAYER_HAS_GOLDEN_AGE',    'CITY_HAS_DISTRICT_CAMPUS_TIER_4_BUILDING_REQUIREMENTS'),
  -- 全球市场
  ('COMMEMORATION_HD_WORLD_MARKET_TRADE_YIELD',                           'MODIFIER_PLAYER_ADJUST_INTERNATIONAL_TRADE_ROUTE_YIELD_MODIFIER',  'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_WORLD_MARKET_TRADE_TOURISM',                         'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_TOURISM_MODIFIER',              'PLAYER_HAS_GOLDEN_AGE',    Null),
  -- 网络文化
  ('COMMEMORATION_HD_CYBERCULTURE_INTERNET_COMPANY_PURCHASE',             'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PURCHASE_COST',             'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CYBERCULTURE_ROCK_BAND_PURCHASE',                    'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST',                 'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_CYBERCULTURE_CULTURE',                               'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',                'PLAYER_HAS_GOLDEN_AGE',    'CITY_HAS_BUILDING_HD_INTERNET_COMPANY_REQUIREMENTS'),
  ('COMMEMORATION_HD_CYBERCULTURE_GOLD',                                  'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',                'PLAYER_HAS_GOLDEN_AGE',    'CITY_HAS_BUILDING_HD_INTERNET_COMPANY_REQUIREMENTS'),
  -- 军工复合
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_ABILITY',                'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',                              'PLAYER_HAS_GOLDEN_AGE',    Null),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_PROPERTY_ATTACH',        'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                           'PLAYER_HAS_GOLDEN_AGE',    'HD_CITY_HAS_DISTRICT_ENCAMPMENT_AND_INDUSTRIAL_ZONE_REQUIREMENTS'),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_PROPERTY',               'MODIFIER_PLAYER_UNITS_ADJUST_PROPERTY',                            Null,                       'HD_UNIT_IS_MILITARY_REQUIREMENTS'),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_INFLUENCE_ATTACH',       'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',                           'PLAYER_HAS_GOLDEN_AGE',    'HD_CITY_HAS_DISTRICT_ENCAMPMENT_AND_INDUSTRIAL_ZONE_REQUIREMENTS'),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_INFLUENCE',              'MODIFIER_PLAYER_ADJUST_INFLUENCE_POINTS_PER_TURN',                 Null,                       Null),
  -- 空间旅行
	('COMMEMORATION_TOURISM_IMPROVEMENT',	                                  'MODIFIER_PLAYER_CITIES_ADJUST_IMPROVEMENT_TOURISM',                'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_TOURISM_MOVEMENT',	                                    'MODIFIER_PLAYER_UNITS_ADJUST_FRIENDLY_TERRITORY_START_MOVEMENT',   'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 宇宙开发
	('COMMEMORATION_HD_COSMIC_EXPLOITATION_ALL_YIELDS',	                    'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',                Null,	                      Null),
	('COMMEMORATION_HD_COSMIC_EXPLOITATION_RESOURCE_SCIENCE',	              'MODIFIER_PLAYER_CITIES_ADJUST_RESOURCE_YIELD_BY_COUNT',            'PLAYER_HAS_GOLDEN_AGE',	  Null),
  -- 人工智能
	('COMMEMORATION_AERONAUTICAL_ALL_TECH_BOOST',	                          'MODIFIER_PLAYER_GRANT_ALL_TECHNOLOGY_BOOST_BY_ERA',                'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_AERONAUTICAL_FREE_TECH',	                              'MODIFIER_PLAYER_ADJUST_PROPERTY',                                  'PLAYER_HAS_GOLDEN_AGE',	  Null),
	('COMMEMORATION_AERONAUTICAL_PRODUCTION',	                              'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER',                'PLAYER_HAS_GOLDEN_AGE',	  Null);

update Modifiers set ModifierType = 'MODIFIER_PLAYER_CITIES_ADD_POPULATION', NewOnly = 1, Permanent = 1 where ModifierId = 'COMMEMORATION_EXPLORATION_GA_NEW_CITY_POPULATION';
update Modifiers set OwnerRequirementSetId = 'PLAYER_HAS_GOLDEN_AGE', SubjectRequirementSetId = Null where ModifierId = 'COMMEMORATION_TOURISM_GA_WONDERS';
update Modifiers set Permanent = 1 where ModifierId in ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_ADD_SLOT', 'COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_CHARGE');
update Modifiers set ModifierType = 'MODIFIER_PLAYER_IMPROVEMENTS_ATTACH_MODIFIER', SubjectRequirementSetId = 'PLOT_HAS_IMPROVEMENT_CORPORATION_REQUIREMENTS' where
  ModifierId in (
    'COMMEMORATION_HD_MEGA_CORPORATION_EXTRA_DISTRICT_ATTACH',
    'COMMEMORATION_HD_MEGA_CORPORATION_PRODUCTION_ATTACH',
    'COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_BUILDING_ATTACH',
    'COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_DISTRICT_ATTACH',
    'COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_UNIT_ATTACH'
  ) and exists (select ImprovementType from Improvements where ImprovementType = 'IMPROVEMENT_CORPORATION');

  -- 信仰之战
insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) select
  'COMMEMORATION_HD_RELIGIOUS_WAR_PILLAGE_' || ImprovementType || '_SCIENCE', 'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING', 'PLAYER_HAS_GOLDEN_AGE'
from Improvements where PlunderType != 'NO_PLUNDER';

insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) select
  'COMMEMORATION_HD_RELIGIOUS_WAR_PILLAGE_' || ImprovementType || '_CULTURE', 'MODIFIER_PLAYER_ADJUST_ADDITIONAL_PILLAGING', 'PLAYER_HAS_GOLDEN_AGE'
from Improvements where PlunderType != 'NO_PLUNDER';

  -- 开明专制
insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
  'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_BONUS',
  'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_MODIFIER',
  'PLAYER_HAS_GOLDEN_AGE',
  'HD_IS_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_REQUIREMENTS'
from DistrictCorrespondingYieldType_HD a, Districts b
	where a.HasAdjacency = 1 and b.DistrictType in ('DISTRICT_GOVERNMENT', 'DISTRICT_DIPLOMATIC_QUARTER');

  -- 浪漫主义
insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) select
	'COMMEMORATION_HD_ROMANTICISM_' || GreatWorkObjectType || '_TOURISM_MODIFIER',		'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM',  'PLAYER_HAS_GOLDEN_AGE'
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

  -- 蒸汽滚滚
insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) select
  'COMMEMORATION_INDUSTRIAL_BUILDING_' || YieldType || '_BONUS', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_MODIFIERS_FOR_DISTRICT', 'PLAYER_HAS_GOLDEN_AGE'
from Yields;

insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) select
  'COMMEMORATION_INDUSTRIAL_REGIONAL_' || YieldType || '_BONUS', 'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY', 'PLAYER_HAS_GOLDEN_AGE'
from Yields;

  -- 灯火通明
insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId) select
  'COMMEMORATION_HD_ILLUMINATED_CITY_' || BuildingType || '_PURCHASE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PURCHASE_COST', 'PLAYER_HAS_GOLDEN_AGE'
from Buildings where BuildingType in ('BUILDING_COAL_POWER_PLANT', 'BUILDING_FOSSIL_FUEL_POWER_PLANT', 'BUILDING_POWER_PLANT', 'BUILDING_HYDROELECTRIC_DAM');

insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
  'COMMEMORATION_HD_ILLUMINATED_CITY_' || DistrictType || '_REGIONAL_RANGE', 'MODIFIER_PLAYER_CITIES_ADJUST_PROPERTY', 'PLAYER_HAS_GOLDEN_AGE', 'CITY_IS_POWERED'
from DistrictCorrespondingYieldType_HD;

-- 思想风暴
insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
  'COMMEMORATION_HD_IDEOLOGY_STORM_' || BuildingType || '_TOURISM', 'MODIFIER_PLAYER_ADJUST_TOURISM', 'PLAYER_HAS_GOLDEN_AGE', 'PLAYER_HAS_' || BuildingType || '_REQUIREMENTS'
from Buildings where PrereqDistrict = 'DISTRICT_GOVERNMENT' and GovernmentTierRequirement = 'Tier3';

-- 网络文化
insert or replace into Modifiers (ModifierId, ModifierType, OwnerRequirementSetId, SubjectRequirementSetId) select
  'COMMEMORATION_HD_CYBERCULTURE_' || GreatWorkObjectType || '_ATTACH', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', 'PLAYER_HAS_GOLDEN_AGE', 'CITY_HAS_BUILDING_HD_INTERNET_COMPANY_REQUIREMENTS'
from GreatWorkObjectTypes;

insert or replace into Modifiers (ModifierId, ModifierType) select
  'COMMEMORATION_HD_CYBERCULTURE_' || GreatWorkObjectType, 'MODIFIER_PLAYER_CITIES_ADJUST_TOURISM'
from GreatWorkObjectTypes;

-- ==================================================================================================================================================================
-- ModifierArguments
-- ==================================================================================================================================================================
insert or replace into ModifierArguments (ModifierId, Name, Value) values
  -- 自然哲学
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_SCIENCE',                           'YieldType',              'YIELD_SCIENCE'),
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_SCIENCE',                           'Amount',                 1),
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_CULTURE',                           'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_SCIENTIFIC_DISTRICT_CULTURE',                           'Amount',                 1),
  -- 轴心时代
  ('COMMEMORATION_CULTURAL_DISTRICT_FAITH',                               'YieldType',              'YIELD_FAITH'),
  ('COMMEMORATION_CULTURAL_DISTRICT_FAITH',                               'Amount',                 1),
  ('COMMEMORATION_CULTURAL_DISTRICT_CULTURE',                             'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_CULTURAL_DISTRICT_CULTURE',                             'Amount',                 1),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS',                 'ModifierId',             'COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS_MODIFIER'),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS_MODIFIER',        'GreatPersonClassType',   'GREAT_PERSON_CLASS_WRITER'),
  ('COMMEMORATION_CULTURAL_DISTRICT_GREAT_WRITER_POINTS_MODIFIER',        'Amount',                 3),
  -- 雄伟壮丽
  ('COMMEMORATION_INFRASTRUCTURE_EXTRA_DISTRICT',                         'Amount',                 1),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'Amount',                 10),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'IsWonder',               1),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'StartEra',               'ERA_ANCIENT'),
  ('COMMEMORATION_INFRASTRUCTURE_WONDER_PRODUCTION',                      'EndEra',                 'ERA_MEDIEVAL'),
  ('COMMEMORATION_INFRASTRUCTURE_YIELD_BONUS',                            'YieldType',              'YIELD_FOOD,YIELD_PRODUCTION'),
  ('COMMEMORATION_INFRASTRUCTURE_YIELD_BONUS',                            'Amount',                 '10,10'),
  -- 光荣胜利
  ('COMMEMORATION_RELIGIOUS_UNIT_SPEED_SIGHT',                            'AbilityType',            'ABILITY_COMMEMORATION_RELIGIOUS_UNIT_SPEED_SIGHT'),
  ('COMMEMORATION_RELIGIOUS_UNIT_STRENGTH',                               'AbilityType',            'ABILITY_COMMEMORATION_RELIGIOUS_UNIT_STRENGTH'),
  ('COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_GOLD',                         'Amount',                 50),
  ('COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_GOLD',                         'Improvement',            'IMPROVEMENT_BARBARIAN_CAMP'),
  -- 翻译运动
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_DISTRICT_PRODUCTION',    'DistrictType',           'DISTRICT_CAMPUS'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_DISTRICT_PRODUCTION',    'Amount',                 30),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_BUILDING_PRODUCTION',    'DistrictType',           'DISTRICT_CAMPUS'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CAMPUS_BUILDING_PRODUCTION',    'Amount',                 30),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_DISTRICT_PRODUCTION',   'DistrictType',           'DISTRICT_THEATER'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_DISTRICT_PRODUCTION',   'Amount',                 30),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_BUILDING_PRODUCTION',   'DistrictType',           'DISTRICT_THEATER'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_THEATER_BUILDING_PRODUCTION',   'Amount',                 30),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS',              'Amount',                 3),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS_RECORD',       'Key',                    'HD_Player_Extra_Tech_Boost'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_TECH_BOOST_BONUS_RECORD',       'Amount',                 3),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS',             'Amount',                 3),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS_RECORD',      'Key',                    'HD_Player_Extra_Civic_Boost'),
  ('COMMEMORATION_HD_TRANSLATION_MOVEMENT_CIVIC_BOOST_BONUS_RECORD',      'Amount',                 3),
  -- 繁荣之路
  ('COMMEMORATION_HD_FLOURSHING_ROAD_INDUSTRIAL_BONUS',                   'YieldType',              'YIELD_PRODUCTION'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_INDUSTRIAL_BONUS',                   'Amount',                 50),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_COMMERCIAL_BONUS',                   'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_COMMERCIAL_BONUS',                   'Amount',                 50),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_HARBOR_BONUS',                       'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_HARBOR_BONUS',                       'Amount',                 50),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_SCIENCE',                      'YieldType',              'YIELD_SCIENCE'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_SCIENCE',                      'Amount',                 1),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_CULTURE',                      'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_CULTURE',                      'Amount',                 1),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_GOLD',                         'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_FLOURSHING_ROAD_TRADE_GOLD',                         'Amount',                 6),
  -- 筚路蓝缕
  ('COMMEMORATION_HD_DOMESTIC_ASSART_CIVILIAN_SPEED',                     'AbilityType',            'ABILITY_COMMEMORATION_HD_DOMESTIC_ASSART_CIVILIAN_SPEED'),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_GRANT_BUILDER',                      'UnitType',               'UNIT_BUILDER'),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_GRANT_BUILDER',                      'Amount',                 1),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_FOOD',                     'YieldType',              'YIELD_FOOD'),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_FOOD',                     'Amount',                 1),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_PRODUCTION',               'YieldType',              'YIELD_PRODUCTION'),
  ('COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_PRODUCTION',               'Amount',                 1),
  -- 信仰之战
  ('COMMEMORATION_HD_RELIGIOUS_WAR_MILITARY_SPEED',                       'AbilityType',            'ABILITY_COMMEMORATION_HD_RELIGIOUS_WAR_MILITARY_SPEED'),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_IMPROVEMENT',           'Amount',                 50),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_DOUBLE_PILLAGE_DISTRICT',              'Amount',                 50),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_SPEED',                      'AbilityType',            'ABILITY_COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_SPEED'),
  ('COMMEMORATION_HD_RELIGIOUS_WAR_RELIGIOUS_CHARGE',                     'Amount',                 2),
  -- 开明专制
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_ADD_SLOT',		                  'GovernmentSlotType',	    'SLOT_WILDCARD'),
  ('COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_EXTRA_DISTRICT',		            'Amount',	                1),
  -- 原始积累
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_MERCHANT_POINTS',		              'GreatPersonClassType',	  'GREAT_PERSON_CLASS_MERCHANT'),
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_MERCHANT_POINTS',		              'Amount',	                50),
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_ENGINEER_POINTS',		              'GreatPersonClassType',	  'GREAT_PERSON_CLASS_ENGINEER'),
  ('COMMEMORATION_ECONOMIC_EXTRA_GREAT_ENGINEER_POINTS',		              'Amount',	                50),
  ('COMMEMORATION_ECONOMIC_TRADE_GOLD',		                                'YieldType',	            'YIELD_GOLD'),
  ('COMMEMORATION_ECONOMIC_TRADE_GOLD',		                                'Amount',	                6),
  ('COMMEMORATION_ECONOMIC_TRADE_PRODUCTION',		                          'YieldType',	            'YIELD_PRODUCTION'),
  ('COMMEMORATION_ECONOMIC_TRADE_PRODUCTION',		                          'Amount',	                2),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_BUILDING',		                    'Amount',	                10),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_DISTRICT',		                    'Amount',	                10),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_UNIT',		                        'Amount',	                10),
  ('COMMEMORATION_ECONOMIC_GOLD_PURCHASE_UNIT',		                        'IncludeCivilian',	      1),
  -- 宗教改革
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_SCIENCE_CULTURE_FAITH',             'YieldType',              'YIELD_SCIENCE,YIELD_CULTURE,YIELD_FAITH'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_SCIENCE_CULTURE_FAITH',             'Amount',                 '10,10,10'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_HOLY_SITE_BONUS',                   'YieldType',	            'YIELD_FAITH'),
  ('COMMEMORATION_HD_RELIGIOUS_REFORM_HOLY_SITE_BONUS',                   'Amount',	                100),
  -- 此处有龙
  ('COMMEMORATION_EXPLORATION_CIVILIAN_SPEED',			                      'AbilityType',		        'ABILITY_COMMEMORATION_EXPLORATION_CIVILIAN_SPEED'),
	('COMMEMORATION_EXPLORATION_DISTRICT_PRODUCTION',		                    'Amount',		              100),
  -- 国际体系
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_INFLUENCE_BONUS',               'BonusType',              'GOVERNMENTBONUS_ENVOYS'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_INFLUENCE_BONUS',               'Amount',                 100),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_FAVOR_BONUS',                   'Amount',                 100),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_SCIENCE_FROM_ALLY',             'YieldType',              'YIELD_SCIENCE'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_SCIENCE_FROM_ALLY',             'Amount',                 4),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_CULTURE_FROM_ALLY',             'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_CULTURE_FROM_ALLY',             'Amount',                 4),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_GOLD_FROM_ALLY',                'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_GOLD_FROM_ALLY',                'Amount',                 4),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_SCIENCE_FROM_CITYSTATE',        'YieldType',              'YIELD_SCIENCE'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_SCIENCE_FROM_CITYSTATE',        'Amount',                 4),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_CULTURE_FROM_CITYSTATE',        'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_CULTURE_FROM_CITYSTATE',        'Amount',                 4),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_GOLD_FROM_CITYSTATE',           'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_INTERNATIONAL_SYSTEM_GOLD_FROM_CITYSTATE',           'Amount',                 4),
  -- 浪漫主义
  ('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_WRITER_POINTS',		          'GreatPersonClassType',	  'GREAT_PERSON_CLASS_WRITER'),
  ('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_WRITER_POINTS',		          'Amount',	                50),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_ARTIST_POINTS',	            'GreatPersonClassType',	  'GREAT_PERSON_CLASS_ARTIST'),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_ARTIST_POINTS',	            'Amount',	                50),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_MUSICIAN_POINTS',	          'GreatPersonClassType',	  'GREAT_PERSON_CLASS_MUSICIAN'),
	('COMMEMORATION_HD_ROMANTICISM_EXTRA_GREAT_MUSICIAN_POINTS',	          'Amount',	                50),
  -- 科学革命
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_EXTRA_GREAT_SCIENTIST_POINTS',	'GreatPersonClassType',	  'GREAT_PERSON_CLASS_SCIENTIST'),
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_EXTRA_GREAT_SCIENTIST_POINTS',	'Amount',	                30),
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS',		          'Amount',	                5),
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS_RECORD',      'Key',	                  'HD_Player_Extra_Tech_Boost'),
  ('COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_BOOST_BONUS_RECORD',      'Amount',	                5),
  -- 灯火通明
  ('COMMEMORATION_HD_ILLUMINATED_CITY_POWER_REGIONAL_RANGE',              'Amount',                 3),
  -- 资本输出
  ('COMMEMORATION_HD_CAPITAL_EXPORT_SEND_ENVOY',                          'Amount',                 2),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_PRODUCTION_1',                  'YieldType',              'YIELD_PRODUCTION'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_PRODUCTION_1',                  'Amount',                 3),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_SCIENCE_1',                     'YieldType',              'YIELD_SCIENCE'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_SCIENCE_1',                     'Amount',                 3),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_CULTURE_1',                     'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_CULTURE_1',                     'Amount',                 3),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_GOLD_1',                        'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_GOLD_1',                        'Amount',                 3),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_PRODUCTION_2',                  'YieldType',              'YIELD_PRODUCTION'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_PRODUCTION_2',                  'Amount',                 3),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_PRODUCTION_2',                  'Intercontinental',       1),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_SCIENCE_2',                     'YieldType',              'YIELD_SCIENCE'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_SCIENCE_2',                     'Amount',                 3),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_SCIENCE_2',                     'Intercontinental',       1),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_CULTURE_2',                     'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_CULTURE_2',                     'Amount',                 3),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_CULTURE_2',                     'Intercontinental',       1),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_GOLD_2',                        'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_GOLD_2',                        'Amount',                 3),
  ('COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_GOLD_2',                        'Intercontinental',       1),
  -- 世界大战
  ('COMMEMORATION_HD_WORLD_WAR_GRANT_GENERAL',                            'GreatPersonClassType',   'GREAT_PERSON_CLASS_GENERAL'),
  ('COMMEMORATION_HD_WORLD_WAR_GRANT_GENERAL',                            'Amount',                 1),
  ('COMMEMORATION_HD_WORLD_WAR_GENERAL_POINTS',                           'GreatPersonClassType',   'GREAT_PERSON_CLASS_GENERAL'),
  ('COMMEMORATION_HD_WORLD_WAR_GENERAL_POINTS',                           'Amount',                 100),
  ('COMMEMORATION_HD_WORLD_WAR_CORP_STRENGTH',                            'Corps',                  1),
  ('COMMEMORATION_HD_WORLD_WAR_CORP_STRENGTH',                            'Domain',                 'DOMAIN_LAND'),
  ('COMMEMORATION_HD_WORLD_WAR_CORP_STRENGTH',                            'Amount',                 7),
  ('COMMEMORATION_HD_WORLD_WAR_ARMY_STRENGTH',                            'Corps',                  0),
  ('COMMEMORATION_HD_WORLD_WAR_ARMY_STRENGTH',                            'Domain',                 'DOMAIN_LAND'),
  ('COMMEMORATION_HD_WORLD_WAR_ARMY_STRENGTH',                            'Amount',                 7),
  ('COMMEMORATION_HD_WORLD_WAR_PRODUCTION',                               'YieldType',              'YIELD_PRODUCTION'),
  ('COMMEMORATION_HD_WORLD_WAR_PRODUCTION',                               'Amount',                 10),
  -- 兵不厌诈
  ('COMMEMORATION_ESPIONAGE_SPY_CAPACITY',                                'Amount',                 3),
  ('COMMEMORATION_ESPIONAGE_GRANT_SPY',                                   'UnitType',               'UNIT_SPY'),
  ('COMMEMORATION_ESPIONAGE_GRANT_SPY',                                   'Amount',                 3),
  ('COMMEMORATION_ESPIONAGE_GRANT_SPY',                                   'AllowUniqueOverride',    0),
  -- 星球大战
  ('COMMEMORATION_HD_STAR_WAR_SPACEPORT_PRODUCTION',                      'DistrictType',           'DISTRICT_SPACEPORT'),
  ('COMMEMORATION_HD_STAR_WAR_SPACEPORT_PRODUCTION',                      'Amount',                 30),
  ('COMMEMORATION_HD_STAR_WAR_SPACE_RACE_PRODUCTION',                     'Amount',                 30),
  ('COMMEMORATION_HD_STAR_WAR_SCIENTIST_POINTS_ATTACH',                   'ModifierId',             'COMMEMORATION_HD_STAR_WAR_SCIENTIST_POINTS'),
  ('COMMEMORATION_HD_STAR_WAR_SCIENTIST_POINTS',                          'GreatPersonClassType',   'GREAT_PERSON_CLASS_SCIENTIST'),
  ('COMMEMORATION_HD_STAR_WAR_SCIENTIST_POINTS',                          'Amount',                 10),
  ('COMMEMORATION_HD_STAR_WAR_ENGINEER_POINTS_ATTACH',                    'ModifierId',             'COMMEMORATION_HD_STAR_WAR_ENGINEER_POINTS'),
  ('COMMEMORATION_HD_STAR_WAR_ENGINEER_POINTS',                           'GreatPersonClassType',   'GREAT_PERSON_CLASS_ENGINEER'),
  ('COMMEMORATION_HD_STAR_WAR_ENGINEER_POINTS',                           'Amount',                 10),
  -- 思想风暴
  ('COMMEMORATION_HD_IDEOLOGY_STORM_FREE_CIVIC',                          'Key',                    'HD_FREE_CIVIC'),
  ('COMMEMORATION_HD_IDEOLOGY_STORM_FREE_CIVIC',                          'Amount',                 1),
  ('COMMEMORATION_HD_IDEOLOGY_STORM_CIVIC_BOOST',                         'Amount',                 10),
  ('COMMEMORATION_HD_IDEOLOGY_STORM_CIVIC_BOOST_RECORD',                  'Key',                    'HD_Player_Extra_Civic_Boost'),
  ('COMMEMORATION_HD_IDEOLOGY_STORM_CIVIC_BOOST_RECORD',                  'Amount',                 10),
  -- 巨型企业
  ('COMMEMORATION_HD_MEGA_CORPORATION_GRANT_MERCHANT',                    'GreatPersonClassType',   'GREAT_PERSON_CLASS_MERCHANT'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_GRANT_MERCHANT',                    'Amount',                 2),
  ('COMMEMORATION_HD_MEGA_CORPORATION_EXTRA_DISTRICT_ATTACH',             'ModifierId',             'COMMEMORATION_HD_MEGA_CORPORATION_EXTRA_DISTRICT'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PRODUCTION_ATTACH',                 'ModifierId',             'COMMEMORATION_HD_MEGA_CORPORATION_PRODUCTION'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_BUILDING_ATTACH',          'ModifierId',             'COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_BUILDING'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_DISTRICT_ATTACH',          'ModifierId',             'COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_DISTRICT'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_UNIT_ATTACH',              'ModifierId',             'COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_UNIT'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_EXTRA_DISTRICT',                    'Amount',                 1),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PRODUCTION',                        'YieldType',              'YIELD_PRODUCTION'),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PRODUCTION',                        'Amount',                 20),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_BUILDING',                 'Amount',                 20),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_DISTRICT',                 'Amount',                 20),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_UNIT',                     'Amount',                 20),
  ('COMMEMORATION_HD_MEGA_CORPORATION_PURCHASE_UNIT',                     'IncludeCivilian',        1),
  -- 全民皆兵
  ('COMMEMORATION_MILITARY_STRENGTH',		                                  'AbilityType',	          'ABILITY_COMMEMORATION_MILITARY_STRENGTH'),
  -- 数字革命
  ('COMMEMORATION_HD_DIGITAL_REVOLUTION_GRANT_SCIENTIST',                 'GreatPersonClassType',   'GREAT_PERSON_CLASS_SCIENTIST'),
  ('COMMEMORATION_HD_DIGITAL_REVOLUTION_GRANT_SCIENTIST',                 'Amount',                 1),
  ('COMMEMORATION_HD_DIGITAL_REVOLUTION_SCIENCE',                         'YieldType',              'YIELD_SCIENCE'),
  ('COMMEMORATION_HD_DIGITAL_REVOLUTION_SCIENCE',                         'Amount',                 20),
  -- 全球市场
  ('COMMEMORATION_HD_WORLD_MARKET_TRADE_YIELD',                           'YieldType',              'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH'),
  ('COMMEMORATION_HD_WORLD_MARKET_TRADE_YIELD',                           'Amount',                 '50, 50, 50, 50, 50, 50'),
  ('COMMEMORATION_HD_WORLD_MARKET_TRADE_TOURISM',                         'Amount',                 15),
  -- 网络文化
  ('COMMEMORATION_HD_CYBERCULTURE_INTERNET_COMPANY_PURCHASE',             'BuildingType',           'BUILDING_HD_INTERNET_COMPANY'),
  ('COMMEMORATION_HD_CYBERCULTURE_INTERNET_COMPANY_PURCHASE',             'Amount',                 50),
  ('COMMEMORATION_HD_CYBERCULTURE_ROCK_BAND_PURCHASE',                    'UnitType',               'UNIT_ROCK_BAND'),
  ('COMMEMORATION_HD_CYBERCULTURE_ROCK_BAND_PURCHASE',                    'Amount',                 50),
  ('COMMEMORATION_HD_CYBERCULTURE_CULTURE',                               'YieldType',              'YIELD_CULTURE'),
  ('COMMEMORATION_HD_CYBERCULTURE_CULTURE',                               'Amount',                 20),
  ('COMMEMORATION_HD_CYBERCULTURE_GOLD',                                  'YieldType',              'YIELD_GOLD'),
  ('COMMEMORATION_HD_CYBERCULTURE_GOLD',                                  'Amount',                 20),
  -- 军工复合
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_ABILITY',                'AbilityType',            'ABILITY_COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX'),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_PROPERTY_ATTACH',        'ModifierId',             'COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_PROPERTY'),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_PROPERTY',               'Key',                    'HD_COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_TAG'),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_PROPERTY',               'Amount',                 3),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_INFLUENCE_ATTACH',       'ModifierId',             'COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_INFLUENCE'),
  ('COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_INFLUENCE',              'Amount',                 10),
  -- 空间旅行
  ('COMMEMORATION_TOURISM_IMPROVEMENT',		                                'Amount',	                500),
  ('COMMEMORATION_TOURISM_MOVEMENT',		                                  'Amount',	                5),
  -- 宇宙开发
  ('COMMEMORATION_HD_COSMIC_EXPLOITATION_ALL_YIELDS',                     'YieldType',              'YIELD_PRODUCTION, YIELD_FOOD, YIELD_SCIENCE, YIELD_CULTURE, YIELD_GOLD, YIELD_FAITH'),
  ('COMMEMORATION_HD_COSMIC_EXPLOITATION_ALL_YIELDS',                     'Amount',                 '10, 10, 10, 10, 10, 10'),
  ('COMMEMORATION_HD_COSMIC_EXPLOITATION_RESOURCE_SCIENCE',               'YieldType',              'YIELD_SCIENCE'),
  ('COMMEMORATION_HD_COSMIC_EXPLOITATION_RESOURCE_SCIENCE',               'Amount',                 10),
  -- 人工智能
  ('COMMEMORATION_AERONAUTICAL_ALL_TECH_BOOST',		                        'StartEraType',	          'ERA_ANCIENT'),
  ('COMMEMORATION_AERONAUTICAL_ALL_TECH_BOOST',		                        'EndEraType',	            'ERA_FUTURE'),
  ('COMMEMORATION_AERONAUTICAL_FREE_TECH',		                            'Key',	                  'HD_FREE_TECH'),
  ('COMMEMORATION_AERONAUTICAL_FREE_TECH',		                            'Amount',	                1),
  ('COMMEMORATION_AERONAUTICAL_PRODUCTION',		                            'YieldType',	            'YIELD_PRODUCTION'),
  ('COMMEMORATION_AERONAUTICAL_PRODUCTION',		                            'Amount',	                50);

update ModifierArguments set Value = 25 where ModifierId = 'COMMEMORATION_INDUSTRIAL_GA_INDUSTRIALINFORMATION' and Name = 'Amount';
update ModifierArguments set Value = 100 where ModifierId = 'COMMEMORATION_MILITARY_GA_PRODUCTION' and Name = 'Amount';
update ModifierArguments set Value = 600 where ModifierId = 'COMMEMORATION_TOURISM_GA_WONDERS' and Name = 'ScalingFactor';
update ModifierArguments set Value = 500 where ModifierId = 'COMMEMORATION_TOURISM_GA_NATIONAL_PARKS' and Name = 'Amount';

  -- 开明专制
insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_BONUS',
  'YieldType', a.YieldType
from DistrictCorrespondingYieldType_HD a, Districts b
	where a.HasAdjacency = 1 and b.DistrictType in ('DISTRICT_GOVERNMENT', 'DISTRICT_DIPLOMATIC_QUARTER');

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_' || a.DistrictType || '_ADJACENT_TO_' || b.DistrictType || '_BONUS',
  'Amount', 50
from DistrictCorrespondingYieldType_HD a, Districts b
	where a.HasAdjacency = 1 and b.DistrictType in ('DISTRICT_GOVERNMENT', 'DISTRICT_DIPLOMATIC_QUARTER');

  -- 浪漫主义
insert or replace into ModifierArguments (ModifierId, Name, Value) select
	'COMMEMORATION_HD_ROMANTICISM_' || GreatWorkObjectType || '_TOURISM_MODIFIER',		'ScalingFactor',				400
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

insert or replace into ModifierArguments (ModifierId, Name, Value) select
	'COMMEMORATION_HD_ROMANTICISM_' || GreatWorkObjectType || '_TOURISM_MODIFIER',		'GreatWorkObjectType',	GreatWorkObjectType
from GreatWorkObjectTypes where GreatWorkObjectType != 'GREATWORKOBJECT_PRODUCT';

  -- 蒸汽滚滚
insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_INDUSTRIAL_BUILDING_' || YieldType || '_BONUS', 'DistrictType', 'DISTRICT_INDUSTRIAL_ZONE'
from Yields;

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_INDUSTRIAL_BUILDING_' || YieldType || '_BONUS', 'YieldType', YieldType
from Yields;

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_INDUSTRIAL_BUILDING_' || YieldType || '_BONUS', 'Amount', 50
from Yields;

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_INDUSTRIAL_REGIONAL_' || YieldType || '_BONUS', 'Key', 'HD_SINGLE_DISTRICT_PROVIDE_REGIONAL_YIELD_SCALING_FACTOR_DISTRICT_INDUSTRIAL_ZONE_' || YieldType
from Yields;

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_INDUSTRIAL_REGIONAL_' || YieldType || '_BONUS', 'Amount', 50
from Yields;

  -- 灯火通明
insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_ILLUMINATED_CITY_' || BuildingType || '_PURCHASE', 'BuildingType', BuildingType
from Buildings where BuildingType in ('BUILDING_COAL_POWER_PLANT', 'BUILDING_FOSSIL_FUEL_POWER_PLANT', 'BUILDING_POWER_PLANT', 'BUILDING_HYDROELECTRIC_DAM');

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_ILLUMINATED_CITY_' || BuildingType || '_PURCHASE', 'Amount', 50
from Buildings where BuildingType in ('BUILDING_COAL_POWER_PLANT', 'BUILDING_FOSSIL_FUEL_POWER_PLANT', 'BUILDING_POWER_PLANT', 'BUILDING_HYDROELECTRIC_DAM');

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_ILLUMINATED_CITY_' || DistrictType || '_REGIONAL_RANGE', 'Key', 'HD_SINGLE_DISTRICT_EXTRA_REGIONAL_RANGE_' || DistrictType
from DistrictCorrespondingYieldType_HD;

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_ILLUMINATED_CITY_' || DistrictType || '_REGIONAL_RANGE', 'Amount', 3
from DistrictCorrespondingYieldType_HD;

-- 思想风暴
insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_IDEOLOGY_STORM_' || BuildingType || '_TOURISM', 'Amount', 20
from Buildings where PrereqDistrict = 'DISTRICT_GOVERNMENT' and GovernmentTierRequirement = 'Tier3';

-- 网络文化
insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_CYBERCULTURE_' || GreatWorkObjectType || '_ATTACH', 'ModifierId', 'COMMEMORATION_HD_CYBERCULTURE_' || GreatWorkObjectType
from GreatWorkObjectTypes;

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_CYBERCULTURE_' || GreatWorkObjectType, 'GreatWorkObjectType', GreatWorkObjectType
from GreatWorkObjectTypes;

insert or replace into ModifierArguments (ModifierId, Name, Value) select
  'COMMEMORATION_HD_CYBERCULTURE_' || GreatWorkObjectType, 'ScalingFactor', 200
from GreatWorkObjectTypes;

-- ==================================================================================================================================================================
-- GlobalParameters
-- ==================================================================================================================================================================
-- 全局参数 用于Lua
insert or replace into GlobalParameters (Name, Value) values
  -- 自然哲学
  ('HD_COMMEMORATION_SCIENTIFIC_SCIENTIST_POINTS',                 10),
  -- 光荣胜利
  ('HD_COMMEMORATION_RELIGIOUS_CONQUER_CITY_GOODY_HUT',            1),
  ('HD_COMMEMORATION_RELIGIOUS_BARBARIAN_CAMP_ERA_SCORE',          1),
  ('HD_COMMEMORATION_RELIGIOUS_CONQUER_CITY_ERA_SCORE',            3),
  -- 翻译运动
  ('HD_COMMEMORATION_HD_TRANSLATION_MOVEMENT_GP_ERA_SCORE',        1),
  -- 筚路蓝缕
  ('HD_COMMEMORATION_HD_DOMESTIC_ASSART_RESOURCES_ERA_SCORE',      1),
  -- 开明专制
  ('HD_COMMEMORATION_HD_ENLIGHTENED_DESPOTISM_DISTRICT_ERA_SCORE', 2),
  -- 原始积累
  ('HD_COMMEMORATION_ECONOMIC_GP_ERA_SCORE',                       2),
  -- 宗教改革
  ('HD_COMMEMORATION_HD_RELIGIOUS_REFORM_DISTRICT_ERA_SCORE',      2),
  -- 国际体系
  ('HD_COMMEMORATION_HD_INTERNATIONAL_SYSTEM_TRADE_ERA_SCORE',     3),
  -- 浪漫主义
  ('HD_COMMEMORATION_HD_ROMANTICISM_GW_ERA_SCORE',                 1),
  -- 科技革命
  ('HD_COMMEMORATION_HD_SCIENTIFIC_REVOLUTION_TECH_ERA_SCORE',     1),
  -- 灯火通明
  ('HD_COMMEMORATION_HD_ILLUMINATED_CITY_BUILDING_ERA_SCORE',      2),
  -- 资本输出
  ('HD_COMMEMORATION_HD_CAPITAL_EXPORT_TRADE_ERA_SCORE',           3),
  -- 世界大战
  ('HD_COMMEMORATION_HD_WORLD_WAR_KILL_ERA_SCORE',                 1),
  -- 星球大战
  ('HD_COMMEMORATION_HD_STAR_WAR_SPACEPORT_ERA_SCORE',             3),
  -- 巨型企业
  ('HD_COMMEMORATION_HD_MEGA_CORPORATION_BUILDING_ERA_SCORE',      1),
  ('HD_COMMEMORATION_HD_MEGA_CORPORATION_IMPROVEMENT_ERA_SCORE',   3),
  -- 数字革命
  ('HD_COMMEMORATION_HD_DIGITAL_REVOLUTION_TECH_ERA_SCORE',        3),
  -- 世界市场
  ('HD_COMMEMORATION_HD_WORLD_MARKET_TRADE_ERA_SCORE',             3),
  -- 网络文化
  ('HD_COMMEMORATION_HD_CYBERCULTURE_GW_ERA_SCORE',                2),
  -- 军工复合
  ('HD_COMMEMORATION_HD_MILITARY_INDUSTRIAL_COMPLEX_ERA_SCORE',    2),
  -- 宇宙开发
  ('HD_COMMEMORATION_HD_COSMIC_EXPLOITATION_ERA_SCORE',            5),
  -- AI保底时代分
  ('HD_AI_TURN_END_ERA_SCORE',                                     1),
  ('HD_AI_DISTRICT_ERA_SCORE',                                     1);

delete from GlobalParameters where Name = 'HD_COMMEMORATION_HD_MEGA_CORPORATION_BUILDING_ERA_SCORE'
  and exists (select ImprovementType from Improvements where ImprovementType = 'IMPROVEMENT_CORPORATION');
delete from GlobalParameters where Name = 'HD_COMMEMORATION_HD_MEGA_CORPORATION_IMPROVEMENT_ERA_SCORE'
  and not exists (select ImprovementType from Improvements where ImprovementType = 'IMPROVEMENT_CORPORATION');

-- ==================================================================================================================================================================
-- Moments
-- ==================================================================================================================================================================
-- 历史时刻
update Moments set MinimumGameEra = Null, MaximumGameEra = Null where MomentType in (
  'MOMENT_BARBARIAN_CAMP_DESTROYED',
  'MOMENT_BARBARIAN_CAMP_DESTROYED_NEAR_YOUR_CITY',
  'MOMENT_GOODY_HUT_TRIGGERED'
);
update Moments set EraScore = 4 where MomentType in (
  'MOMENT_NATIONAL_PARK_CREATED',
  'MOMENT_GREAT_PERSON_CREATED_PATRONAGE_FAITH_OVER_HALF',
  'MOMENT_GREAT_PERSON_CREATED_PATRONAGE_GOLD_OVER_HALF',
  'MOMENT_IMPROVEMENT_CONSTRUCTED_RENEWABLE_ENERGY_FIRST_IN_WORLD',
  'MOMENT_IMPROVEMENT_CONSTRUCTED_MOUNTAIN_TUNNEL_FIRST_IN_WORLD',
  'MOMENT_IMPROVEMENT_CONSTRUCTED_SEASIDE_RESORT_FIRST_IN_WORLD',
  'MOMENT_FIRST_CORPORATION_IN_WORLD',
  'MOMENT_FIND_NATURAL_WONDER_FIRST_IN_WORLD',
  'MOMENT_ARTIFACT_EXTRACTED_SHIPWRECK_FIRST_IN_WORLD',
  'MOMENT_ROUTE_CREATED_RAILROAD_CONNECTS_TWO_CITIES_FIRST_IN_WORLD'
);
update Moments set EraScore = 3 where MomentType in (
  'MOMENT_FIND_NATURAL_WONDER'
);

-- ==================================================================================================================================================================
-- CommemorationIcons
-- ==================================================================================================================================================================
-- 图标
insert or ignore into CommemorationIcons(CommemorationType, Icon) select
  CommemorationType, 'ICON_' || CommemorationType
from CommemorationTypes;

update CommemorationIcons set Icon = 'ICON_COMMEMORATION_AUTOMATON_HD' where CommemorationType = 'COMMEMORATION_AUTOMATON';