insert or ignore into Types (Type, Kind) values
  -- 中心医院
  ('NOTIFICATION_JNR_HOSPITAL_PREVENT_POP_LOST', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_JNR_HOSPITAL_EXTRA_POP_BOOST', 'KIND_NOTIFICATION'),
  -- 布达拉宫
  ('NOTIFICATION_POTALA_EXTRA_BELIEF', 'KIND_NOTIFICATION'),
  -- 中国远古着力点
  ('NOTIFICATION_CHINA_CHOOSE_FIRST_TURN_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_ANCIENT_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_CLASSICAL_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_MEDIEVAL_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_RENAISSANCE_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_INDUSTRIAL_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_MODERN_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_ATOMIC_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_INFORMATION_COMMEMORATION', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_FUTURE_COMMEMORATION', 'KIND_NOTIFICATION'),
  -- 永乐大典
  ('NOTIFICATION_YONGLE_REWARD', 'KIND_NOTIFICATION'),
  -- 七下西洋
  ('NOTIFICATION_QIXIA_XIYANG', 'KIND_NOTIFICATION'),
  -- 梅花内卫
  ('NOTIFICATION_PLUM_INTERNAL_SECURITY_GPP', 'KIND_NOTIFICATION'),
  -- 苏美尔
  ('NOTIFICATION_SUMERIA_FREE_TECH', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_SUMERIA_FREE_CIVIC', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_SUMERIA_SPECIAL_QUEST', 'KIND_NOTIFICATION'),
  ('NOTIFICATION_SUMERIA_SPECIAL_QUEST_REWORD', 'KIND_NOTIFICATION'),
  -- 金法国
  ('NOTIFICATION_LEADER_MAGNIFICENCES_WONDER', 'KIND_NOTIFICATION'),
  -- 阿拉伯
  ('NOTIFICATION_ARABIA_TRANSFORM_GPP', 'KIND_NOTIFICATION'),
  -- 波兰
  ('NOTIFICATION_POLAND_ALLIANCE_COPY_GPP', 'KIND_NOTIFICATION'),
  -- 花蛇
  ('NOTIFICATION_MEDITERRANEAN_REWARD', 'KIND_NOTIFICATION'),
  -- 光荣胜利
  ('NOTIFICATION_GLORIOUS_VICTORY_REWARD', 'KIND_NOTIFICATION');

insert or ignore into Notifications (NotificationType, SeverityType, ExpiresEndOfTurn, AutoNotify, AutoActivate) values
  -- 中心医院
  ('NOTIFICATION_JNR_HOSPITAL_PREVENT_POP_LOST',	            'MID',			  1,					      0,			    0),
  ('NOTIFICATION_JNR_HOSPITAL_EXTRA_POP_BOOST',	              'MID',			  1,					      0,			    0),
  -- 布达拉宫
  ('NOTIFICATION_POTALA_EXTRA_BELIEF',	                      'MID',			  0,					      0,			    0),
  -- 中国远古着力点
  ('NOTIFICATION_CHINA_CHOOSE_FIRST_TURN_COMMEMORATION',	    'MID',			  0,					      0,			    1),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_ANCIENT_COMMEMORATION',	    'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_CLASSICAL_COMMEMORATION',	  'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_MEDIEVAL_COMMEMORATION',	  'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_RENAISSANCE_COMMEMORATION',	'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_INDUSTRIAL_COMMEMORATION',	'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_MODERN_COMMEMORATION',	    'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_ATOMIC_COMMEMORATION',	    'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_INFORMATION_COMMEMORATION',	'MID',			  0,					      0,			    0),
  ('NOTIFICATION_CHINA_CHOOSE_ERA_FUTURE_COMMEMORATION',	    'MID',			  0,					      0,			    0),
  -- 永乐大典
  ('NOTIFICATION_YONGLE_REWARD',                              'MID',			  1,					      0,			    0),
  -- 七下西洋
  ('NOTIFICATION_QIXIA_XIYANG',                               'MID',			  1,					      0,			    0),
  -- 梅花内卫
  ('NOTIFICATION_PLUM_INTERNAL_SECURITY_GPP',	                'MID',			  1,					      0,			    0),
  -- 苏美尔
  ('NOTIFICATION_SUMERIA_FREE_TECH',	                        'MID',			  1,					      0,			    0),
  ('NOTIFICATION_SUMERIA_FREE_CIVIC',	                        'MID',			  1,					      0,			    0),
  ('NOTIFICATION_SUMERIA_SPECIAL_QUEST',	                    'MID',			  1,					      0,			    0),
  ('NOTIFICATION_SUMERIA_SPECIAL_QUEST_REWORD',	              'MID',			  1,					      0,			    0),
  -- 金法国
  ('NOTIFICATION_LEADER_MAGNIFICENCES_WONDER',	              'MID',			  1,					      0,			    0),
  -- 阿拉伯
  ('NOTIFICATION_ARABIA_TRANSFORM_GPP',	                      'MID',			  1,					      0,			    0),
  -- 波兰
  ('NOTIFICATION_POLAND_ALLIANCE_COPY_GPP',	                  'MID',			  1,					      0,			    0),
  -- 花蛇
  ('NOTIFICATION_MEDITERRANEAN_REWARD',	                      'MID',			  1,					      0,			    0),
  -- 光荣胜利
  ('NOTIFICATION_GLORIOUS_VICTORY_REWARD',	                  'MID',			  1,					      0,			    0);